- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/private/FTSGraph.py
- DataManagementSystem/private/FTSStrategy.py
- Resources/Storage/StorageElement.py
- TransformationSystem/Agent/TransformationAgent.py
- TransformationSystem/Client/TransformationClient.py
Include quite some changes for fixing memory and scalability issues in the TS for very large transformations. These have been tested on the stripping merging productions.
The default behavior is very similar to the former release. However Operations CS parameters can be defined for each plugin:
MaxFiles : max number of files to consider in an iteration
SortedBy: sort files by a parameter (e.g. RunNumber)
NoUnusedDelay: overwrite the default agent delay after which to reconsider files if no new unused files were found
> [V6r11] fix trans150105

- TransformationSystem/Agent/TransformationAgent.py
- WorkloadManagementSystem/Client/InputDataByProtocol.py
- WorkloadManagementSystem/Client/InputDataResolution.py
There was a bug in the merging of the branches yesterday: a member was not defined, nor was it used properly (my fault). I also reduced the number of times we write out the cache file, as it has a very poor performance. I also added a @gSynchro on writeCache to see if it improves not to write 2 files at the same time...
In addition, I took the opportunity to define RemoteProtocol for IDR by protocol as otherwise we cannot use CNAF as federating SE in Gaudi (file: protocol cannot be used remotely)
> V6r12 fix trans and idr 150114

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Client/FTSJob.py
- RequestManagementSystem/Agent/RequestExecutingAgent.py
- Resources/Storage/SRM2Storage.py
Main change: return all FileCatalog errors
VOs using more than one catalog should treat this correctly. In LHCb we return S_OK() for actions on files starting with /lhcb/user
> [v6r12] fix fts150114

- DataManagementSystem/Agent/RequestOperations/DMSRequestOperationsBase.py
- RequestManagementSystem/Client/Request.py
- ResourceStatusSystem/Client/ResourceStatus.py
Delay execution or cancel request based on SE statuses from RSS/CS
> [v6r13] Uses RSS in RMS 

- Core/Utilities/CFG.py
- Resources/Computing/SSHTorqueComputingElement.py
FIX: CFG - bug fixed in loadFromBuffer() resulting in a loss of comments
FIX: SSHTorqueComputingElement - check the status of ssh call for qstat
> [v6r11] CFG comment fix

- Core/DISET/private/FileHelper.py
- Core/Utilities/ProcessPool.py
- DataManagementSystem/Client/FileCatalogClientCLI.py
- DataManagementSystem/Service/IRODSStorageElementHandler.py
- Resources/Catalog/FileCatalog.py
- Resources/Computing/SSHTorqueComputingElement.py
NEW: IRODSStorageElementHandler class
FIX: FileHelper - count transfered bytes in DataSourceToNetwork
BUGFIX: FileCatalogCLI - changed interface in changePathXXX() methods
FIX: SSHTorqueComputingElement - check the status of the ssh call for qstat
> [v6r12] IRODSStorageElementHandler

- DataManagementSystem/Client/DataManager.py
- Resources/Storage/StorageElement.py
> [v6r13] fix put and register

- DataManagementSystem/ConfigTemplate.cfg
- DataManagementSystem/DB/FileCatalogDB.py
- DataManagementSystem/Service/FileCatalogHandler.py
- DataManagementSystem/Service/IRODSStorageElementHandler.py
- Interfaces/API/Dirac.py
- Resources/Catalog/FileCatalog.py
FIX: IRODSStorageElement more complete implementation
FIX: FileCatalogHandler(DB) - make removeMetadata bulk method
FIX: FileCatalog - make a special option CatalogList (Operations) to specify catalogs used by a given VO
> [v6r12] Several fixes

- DataManagementSystem/private/FTSStrategy.py
- RequestManagementSystem/Client/Operation.py
- RequestManagementSystem/Client/ReqClient.py
- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Client/InputDataByProtocol.py
A few fixes gathered in the last days...
Apologies for the few "beautifyings" ;-)
> [v6r12] PhC fixes 150122

- DataManagementSystem/Client/DataManager.py
FIX: DataManager - remove dirac_directory in __cleanDirectory() just in case
> [v6r12] DataManager minor fix

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Client/FTSClient.py
- DataManagementSystem/Client/FTSFile.py
- DataManagementSystem/Client/FTSJob.py
- DataManagementSystem/Client/FTSRequest.py
- DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/FileManagerPs.py
- RequestManagementSystem/Agent/RequestExecutingAgent.py
- RequestManagementSystem/private/RequestTask.py
I found only one bad merging so far
> [v6r13] Fix the merging of FTSAgent

- Resources/Storage/GFAL2_SRM2Storage.py
- Resources/Storage/GFAL2_StorageBase.py
- Resources/Storage/GFAL2_XROOTStorage.py
> [v6r13] fixing issues noted by pylint

- DataManagementSystem/Service/StorageElementProxyHandler.py
- FrameworkSystem/Client/SystemAdministratorClientCLI.py
FIX: StorageElementProxyHandler - do not remove the cache directory
FIX: SystemAdministratorClient - increase the timeout to 300 for the software update
> [v6r12] StorageProxy fix

- DataManagementSystem/Client/DataManager.py
- RequestManagementSystem/Client/Operation.py
- RequestManagementSystem/Client/ReqClient.py
- RequestManagementSystem/Client/Request.py
- RequestManagementSystem/DB/RequestDB.py
- RequestManagementSystem/Service/ReqManagerHandler.py
- Resources/Catalog/LcgFileCatalogClient.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/TransformationAgent.py
- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Client/InputDataResolution.py
* Group ReplicateAndRegister operations together for failover requests: it allows to launch all FTS jobs at once
* Minor fixes in DataManager
* Set Operation Scheduled if one file is Scheduled
* Fix longstanding problem in LFC when several files were not available (only one was returned)
* Fix exception in RequestTaskAgent
* Remove useless printouts
> [v6r12] PhC fixes 150203

- ConfigurationSystem/Client/CSAPI.py
- ConfigurationSystem/scripts/dirac-admin-add-resources.py
- ConfigurationSystem/scripts/dirac-admin-add-shifter.py
- ConfigurationSystem/scripts/dirac-admin-add-site.py
As this is very common. 
If merged, I think this deserves an entry in the installation instructions.
> [v6r13] Function, and script, for adding or modifying a shifter in the CS

- DataManagementSystem/Agent/RequestOperations/PutAndRegister.py
- DataManagementSystem/Agent/RequestOperations/RegisterFile.py
- DataManagementSystem/Client/FTSJob.py
- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-wms-job-get-jdl.py
- Resources/Catalog/FileCatalog.py
- WorkloadManagementSystem/Client/JobState/JobManifest.py
- WorkloadManagementSystem/Service/JobMonitoringHandler.py
Changes from #2274 acceptable for an urgent patch
FIX: RegisterFile, PutAndRegister - pass a list of catalogs to the DataManager instead of a comma separated string
CHANGE: Dirac, JobMonitoringHandler,dirac-wms-job-get-jdl - possibility to retrieve original JDL
CHANGE: JobManifest - make MaxInputData a configurable option
FIX: FTSJob - log when a job is not found in FTS
> [v6r12] Several urgent fixes

- DataManagementSystem/Client/DataManager.py
As soon as possible to avoid InputData optimizer failures
> Retry RSS call as we know it may give bad answer

- DataManagementSystem/Agent/RequestOperations/PutAndRegister.py
- DataManagementSystem/Agent/RequestOperations/RegisterFile.py
- DataManagementSystem/Agent/RequestOperations/RegisterReplica.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
We are running on a hot fix
The RMS helpers had to be fixed
> !!![v6r12] Fix the catalog split

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Agent/RequestOperations/RegisterFile.py
- DataManagementSystem/Agent/RequestOperations/RegisterReplica.py
- RequestManagementSystem/Client/Operation.py
- Resources/Catalog/FileCatalog.py
This was causing a lot of failures in LHCb DMS agents :((((
> !!![v6r12] getDirectoryMetadata was wrongly set in ro_meta_methods

- Core/Utilities/InstallTools.py
Creation of a t file in $DIRACROOT/runit/System/Agent/control to allow the clean way of stopping the agent via the command runsvctrl t.
> [v6r12] Add the t file for stop_agent

- ConfigurationSystem/Client/CSCLI.py
- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- Interfaces/scripts/dirac-wms-job-submit.py
This adds history to various sysadmin-cli commands and allows writing job IDs to a file in dirac-wms-job-submit.
> [v6r12] Minor CLI imrpovements

- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
- Resources/Storage/SRM2Storage.py
* longer param for a stored procedure of the DFC
* properly fetch the checksum type value from the CS used for the SRM transfers
> [v6r12] Few bug fixes

- Core/Utilities/MySQL.py
- FrameworkSystem/DB/NotificationDB.py
- FrameworkSystem/DB/ProxyDB.py
Fixes the security hole due to a possibility of the SQL injection
FIX: NotificationDB - escape fields for sorting in getNotifications()
FIX: MySQL.py - treat in detailed way datetime functions in __escapeString()
> [v6r13] Fix security hole

- DataManagementSystem/DB/FileCatalogComponents/Utilities.py
- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
avoid propagating empty path, which normally ends up in max depth recursion
> [v6r12] Fix for max depth recursion in DFC

- RequestManagementSystem/Service/ReqManagerHandler.py
Oups, the fix was in my local branch and as hot fix, but not pushed... Apologies
> !!![v6r12] Set None as type for getRequest

- Core/Security/VOMSService.py
Since the retirement of VOMRS, we need to use some new methods to get the nickname. certificates and identity.
> [v6r12] Add method admListCertificates

- Core/Utilities/DictCache.py
- DataManagementSystem/Client/FTSRequest.py
- DataManagementSystem/Client/FailoverTransfer.py
- DataManagementSystem/DB/FileCatalogComponents/DirectorySimpleTree.py
- DataManagementSystem/DB/FileCatalogComponents/FileManager.py
- DataManagementSystem/Service/IRODSStorageElementHandler.py
- FrameworkSystem/Agent/MyProxyRenewalAgent.py
- FrameworkSystem/Client/MonitoringClient.py
- FrameworkSystem/Client/ProxyManagerClient.py
- FrameworkSystem/DB/ProxyDB.py
- FrameworkSystem/Service/PlotCache.py
- FrameworkSystem/Service/PlottingHandler.py
- FrameworkSystem/private/monitoring/MonitoringCatalog.py
- FrameworkSystem/private/monitoring/PlotCache.py
- FrameworkSystem/private/monitoring/RRDManager.py
- FrameworkSystem/private/monitoring/ServiceInterface.py
- FrameworkSystem/test/testLogger.py
- Interfaces/API/Job.py
- Interfaces/scripts/dirac-utils-file-adler.py
- RequestManagementSystem/DB/RequestDB.py
- RequestManagementSystem/Service/ReqManagerHandler.py
- ResourceStatusSystem/Policy/SpaceTokenOccupancyPolicy.py
- Resources/Computing/BOINCComputingElement.py
- Resources/Storage/StorageElement.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/TransformationAgentsUtilities.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/test/test_Client.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Client/CPUNormalization.py
Please check the change in FTSRequest.py (is this the method, or the FTS3 one to be used?)
> [v6r13] Pylint and fixes

- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
- DataManagementSystem/DB/test/TestFileCatalogDB.py
Bug in calculating the DirectoryUsage table.
Add more tests
> [v6r12] fix storage usage calculation

- ConfigurationSystem/Client/Utilities.py
- Core/Base/DB.py
- FrameworkSystem/DB/InstalledComponentsDB.py
- RequestManagementSystem/DB/RequestDB.py
> [v6r13] Several bug fixes

- DataManagementSystem/Agent/RequestOperations/RemoveFile.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
Use regexp to test the error code of a non existing file, which is compatible with the LFC and the DFC
> [v6r12] Change regex for "no such file"

- WorkloadManagementSystem/Service/WMSUtilities.py
I hope this is correct usage. I have not been able to test this minor patch as the test system is under flux right now.
> [v6r13] Fix to use cfgPath

- FrameworkSystem/scripts/dirac-populate-component-db.py
This script is to be run only once to populate the DB with the currently installed components.
> [v6r13] Script for initial filling of the component monitoring DB

- Resources/Storage/GFAL2_SRM2Storage.py
- Resources/Storage/GFAL2_StorageBase.py
Hopefully they are better now.
> [v6r13] added comments for gfal2 parameters

- AccountingSystem/private/DataCache.py
- DataManagementSystem/Client/MetaQuery.py
- FrameworkSystem/Client/ProxyManagerClient.py
- FrameworkSystem/Service/PlotCache.py
- WorkloadManagementSystem/private/DIRACPilotDirector.py
- WorkloadManagementSystem/private/GridPilotDirector.py
FIX: DictCache.get() returns now None instead of False if no or expired value
CHANGE: MetaQuery - uses isinstance() to compare types
> [v6r13] Several fixes

- ConfigurationSystem/Client/Utilities.py
- ConfigurationSystem/ConfigTemplate.cfg
Correction in ConfigTemplate and fix for variable referenced before assingment
> [v6r12] Bugfixes for Bdii2CS Agent

- FrameworkSystem/Client/SystemAdministratorClientCLI.py
Added new commands to the CLI to query the ComponentMonitoring service about the history of installations and hosts available
> [v6r13] CLI integration with component monitoring

- Core/Utilities/InstallTools.py
Closes #2342 
Reverts #2146 partially
> [v6r12] FIX: Replace --no-defaults for --default-file (fix #2342 + revert #2146 partially)

- DataManagementSystem/Client/DataManager.py
- RequestManagementSystem/Client/ReqClient.py
- RequestManagementSystem/Client/Request.py
- RequestManagementSystem/test/RequestTests.py
- Resources/Storage/StorageFactory.py
- StorageManagementSystem/Agent/RequestPreparationAgent.py
This PR makes an important fix:
* Requests optimization was buggy in case the failover operations sequence was not first in the request: it was putting the merged operations upfront. This was making requests fail...
* In addition, request made for checking the presence of a file not only in the destination SE but also in aliases (DataManager)
> !!! [v6r12] FixRequest optimization + DM for aliases

- Core/Utilities/InstallTools.py
It is now possible to add the 'BashVariables' section to any component's section in the configuration template in order to have the variables (options) in that section set automatically by the run script.
As requested in #1984
> [v6r13] Setting of bash variables in run script

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Client/FTSJob.py
> [v6r13] certif fts3

- Core/LCG/GOCDBClient.py
- ResourceStatusSystem/Command/DowntimeCommand.py
There are 2 issues that I've spotted in DTCommand and needed a fix:
- The GOCDBclient raised an exception due to a string encoding issue
- In DTCommand, the doNew function is used to initialize the ResourceManagementDB by adding the DTs for a list of sites and resources. I revised the code to guarantee that doNew is able to deal with list of sites/resources.
> [v6r13] Av150504

- DataManagementSystem/Client/DataManager.py
- Resources/Storage/SRM2Storage.py
* Infinite loop in listing directory on SRM2 storage
* Incompatible return between LFC/DFC for listDirectory
> [v6r13] Certification fixes

- RequestManagementSystem/Service/ReqManagerHandler.py
- RequestManagementSystem/Service/ReqProxyHandler.py
Adapt to JSON. And remove the old trick from Philippe to fix requests
> [v6r13] Adapt the ReqProxy to the new request style

- Core/Base/ExecutorModule.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/TaskManagerPlugin.py
- TransformationSystem/Client/test/test_Client.py
- WorkloadManagementSystem/Executor/InputData.py
Feel free to merge, but this is not the last commit I have for v6r13
> [v6r13] Various fixes

- DataManagementSystem/Client/FileCatalogClientCLI.py
- DataManagementSystem/DB/FileCatalogComponents/FileMetadata.py
- DataManagementSystem/scripts/dirac-dms-find-lfns.py
CHANGE: FileMetadata - allow single character wild cards, close #1793
NEW: dirac-dms-find-lfns command
> [v6r13] Metaquery enhancement and command

- Interfaces/scripts/dirac-wms-job-submit.py
The default is False, i.e. the same a before.
Follows discussion...
> Allow enabling job repository by cmd line switch

- Core/Utilities/SiteSEMapping.py
- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Utilities/DMSHelpers.py
- Resources/Storage/StorageFactory.py
The module Core.Utilities.SiteSEMapping was updated to make use of the DMSHelpers module. This should ease the porting of all components to using this single source of information.
DataManager was updated to use directly DMSHelpers
> [v6r13] Fixes to DMSHelpers

- Resources/Computing/GlobusComputingElement.py
Implemented and tested functions:
jobSubmit
getJobOutput
Implemented functions:
getCEStatus (empty implementation)
killJob (not sure where this is called from)
> [v6r11] Add first implementation for GlobusComputingElement

- DataManagementSystem/Client/FTSClient.py
- Resources/Storage/StorageBase.py
- Resources/Storage/StorageFactory.py
This is preventing staging from FTS. We should get rid of this method anyway.
> [v6r13] fix get current url

- Core/Utilities/Version.py
- Core/scripts/dirac-configure.py
- RequestManagementSystem/private/RequestTask.py
- RequestManagementSystem/private/test/RequestTaskTests.py
- StorageManagementSystem/Client/StorageManagerClient.py
- StorageManagementSystem/Client/test/test_Client.py
- WorkloadManagementSystem/Executor/JobScheduling.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py
- __init__.py
This removes a "None" hack discovered yesterday to allow to get input data everywhere (and the pilot log will be cleaner).
Also added more tests and some easy fixes.
> [v6r13] Add LocalSE list in pilots only if strictly necessary, don't fail if it is not defined

- WorkloadManagementSystem/Client/DownloadInputData.py
- WorkloadManagementSystem/Client/test/Test_Client.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
Fixes for downloading input data (see Line 269 of DownloadInputData) and for interpreting json files (now we really use json: simple eval was not interpreting "null" as None as it should be)
> [v6r13] JobWrapper fixes

- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Utilities/DMSHelpers.py
- RequestManagementSystem/Client/ReqClient.py
- TransformationSystem/Client/Transformation.py
After a change to be able to define an SEGroup as accessible to a site, it was no longer possible to define it as a site (which is the main use case)
Sites should be excluded and then added
> [v6r13] Fix one use case in DMSHelpers

- Core/Utilities/InstallTools.py
Added controlDir initialization
> Fix stop agent

- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Utilities/DMSHelpers.py
- DataManagementSystem/scripts/dirac-dms-user-lfns.py
- RequestManagementSystem/Client/Request.py
This PR fixes he following:
* dirac-dms-get-file: broken as local site usually has no SE (this is an important fix)
* dirac-dms-user-lfns: sort result
> [v6r13] DMS fixes 

- RequestManagementSystem/Client/Operation.py
Some argument could be None, so split wouldn't work
> [v6r13] FIX exception in the RMS with some RegisterFile Operation

- RequestManagementSystem/Client/Request.py
> [v6r13] fix a typo sourceSE instead of SourceSE

- FrameworkSystem/scripts/dirac-populate-component-db.py
The script now checks the setup of the hosts to register into the DB only installations from the same setup.
Also, the script now checks whether there is a MySQL installation in the hosts before trying to retrieve their DB installations ( before, trying to do so when MySQL is not present would bause the host to be ignored, not registering the rest of its components ).
> [v6r13] Another fix for populating script

- DataManagementSystem/Client/DataManager.py
Forgot to specify the protocol, so we were asking for a turl, which srm is not always able to give right away after transferring. 
We need a quick patch with this please
> [v6r13] URGENT fspecify the registration protocol when doing dm.putAndRegister

- Resources/Storage/SRM2Storage.py
test was done as for the RSS method!
> [v6r13] Fix bad test on se.getStatus() 

- RequestManagementSystem/Client/Request.py
Pylint error: Error is the member variable _Error does not exist
Disabled error for two false positives.
~~None of this seems to have an impact, but it is weird and probably was not done on purpose.~~
Edit: Removed "_Status is the member variable, Status is the member function"
"_LastUpdate is the member variable, LastUpdate is the member function"
> [v6r13]: Minor Fixes for Request

- Resources/Computing/BatchSystems/SLURM.py
At least I am guessing that this should have %% in these places...
PS: no more from me today
> [v6r13] SLURM script: to get % with format, need to put %%

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- RequestManagementSystem/Client/ReqClient.py
- TransformationSystem/Agent/TransformationAgentsUtilities.py
- TransformationSystem/Client/TransformationClient.py
- TransformationSystem/DB/TransformationDB.py
This PR includes PR #2440 that was reviewed and has been closed.
Additional fixes in the TS are for making derived productions work
> [v6r13] DMS changes (checksum) and derived transformations

- RequestManagementSystem/Client/File.py
- RequestManagementSystem/Client/Operation.py
- RequestManagementSystem/Client/Request.py
- RequestManagementSystem/DB/RequestDB.py
The hybrid properties were not in use anyway
> [v6r13] Remove sqlalchemy from client side

- Resources/Computing/SSHComputingElement.py
BUGFIX: SSHComputingElement - return full job references from getJobStatus()
> [v6r13] Bug fix in SSHComputingElement

- Resources/Computing/ARCComputingElement.py
- WorkloadManagementSystem/Service/WMSUtilities.py
This code stack has not been tested on lbtestvobox, as we do not yet have the arc api properly installed on it - the "import arc" command does not work in python.
Once it starts working, I hope to make the needed tests and fix whatever issues I find. Until then, this is the baseline of what the code needs to do.
> [v6r14] Now we use the ARC api to communicate with the ARC CEs

- TransformationSystem/Agent/TransformationPlugin.py
- TransformationSystem/Agent/test/Test_Agent.py
- TransformationSystem/Agent/test/Test_Plugins.py
- TransformationSystem/Client/Utilities.py
- TransformationSystem/Client/test/Test_Client.py
- TransformationSystem/Client/test/test_Client.py
This PR supersedes https://github.com/DIRACGrid/DIRAC/pull/2268 that I am going to close.
Mostly ported plugins from LHCb, added unit tests.
> [v6r14] Plugins additions

- DataManagementSystem/Utilities/lfc_dfc_db_copy.py
Share and document the script used by LHCb to migrate from the LFC to the DFC with FK and SP
> [v6r14] Migration script from LFC DB to DFC DB

- Resources/Computing/BatchSystems/Torque.py
- Resources/Storage/StorageBase.py
- WorkloadManagementSystem/Executor/InputData.py
- WorkloadManagementSystem/Executor/JobScheduling.py
BUGFIX: Torque - getCEStatus() must return integer job numbers
FIX: InputData, JobScheduling - StorageElement needs to know its VO
FIX: StorageBase -  removed checking the VO name inside the LFN
> [v6r13] Torque batch system bug, executors, StorageBase fix

- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Utilities/DMSHelpers.py
- TransformationSystem/Client/TransformationClient.py
- TransformationSystem/DB/TransformationDB.py
* Take into account Alias and BaseSE in site-SE relation
* Remove unnecessary access to RSS from DataManager and use SE.getStatus()
* Add checksumType to RMS files when adding checksum value
> [v6r13] Few DMS fixes for Alias and BaseSE

- Resources/Computing/ARCComputingElement.py
This update has the additional configurable XRSLExtra string as requested by Belle. There is a function added "__getXRSLExtraString" which also contains some documentation on what the function is supposed to do. This code "should just
> Implemented XRSLExtraString

- FrameworkSystem/DB/InstalledComponentsDB.py
- Resources/Computing/ARCComputingElement.py
- TransformationSystem/Agent/TransformationCleaningAgent.py
- TransformationSystem/Agent/TransformationPlugin.py
- TransformationSystem/Agent/ValidateOutputDataAgent.py
- TransformationSystem/Client/PluginBase.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/TaskManagerPlugin.py
- TransformationSystem/Client/Transformation.py
- TransformationSystem/Client/TransformationClient.py
- TransformationSystem/Client/Utilities.py
- TransformationSystem/DB/TransformationDB.py
- TransformationSystem/Service/TransformationManagerHandler.py
- WorkloadManagementSystem/Client/JobDescription.py
- WorkloadManagementSystem/Service/WMSUtilities.py
Adding nothing, just pure bug fixes
> [v6r14] Fixes from pylint

- DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py
_findFiles can return S_ERROR, need to check.
> [v6r12] FileManagerBase fix in addReplicas

- Resources/Computing/BatchSystems/GE.py
- Resources/Computing/BatchSystems/Torque.py
BUGFIX: Torque, GE - methods must return Message field in case of non-zero return status
> [v6r13] Fixes in BatchSystems to return Message in case of errors

- DataManagementSystem/Agent/RequestOperations/RemoveFile.py
Currently, when a site/SE is in downtime, the RMS keep trying again and again. Now, not anymore
> [v6r13] Check the SE status when doing remove file

- Core/Security/X509CRL.py
It is used by the new portal...
> [v6r13] New class to handle the revoked certificates 

- Resources/Storage/SRM2Storage.py
When used internaly, listDirectory should return urls and not lfns. This is to be put in relation with this PR https://github.com/DIRACGrid/DIRAC/pull/2375 and this commit in particular https://github.com/chaen/DIRAC/commit/367ac2a5ddec8da932a5a93c2ee8670571757135
> [v6r13] FIX removeDirectory

- RequestManagementSystem/DB/RequestDB.py
These little fixes allow to have at least a minimum set of functionality in the portal for the RMS, until we have time to do a proper page
> [v6r13] Fix the RequestDB to have minimal web portal functionality

- DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/FileManagerPs.py
- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
The method _getFileLFNs needed to be implemented  in the FileManagerPs for the web interface to work
> [v6r14] FIX : fix the web interface for the PS DFC managers

- Resources/Storage/SRM2Storage.py
I've finally moved to v6r12 in production and ran into the problem fixed by this.
> [v6r12] Backported fix for SRM2Storage prestageFile

- FrameworkSystem/Utilities/MonitoringUtilities.py
> [v6r13] Fix to MonitoringUtilities bug

- Resources/Utilities.py
- TransformationSystem/Client/TransformationClient.py
- TransformationSystem/DB/TransformationDB.py
- TransformationSystem/Service/TransformationManagerHandler.py
Replaces https://github.com/DIRACGrid/DIRAC/pull/2464 with proper fixes
> [v6r13] Code clean up in TS

- DataManagementSystem/DB/FileCatalogComponents/SecurityPolicies/VOMSPolicy.py
Do the same thing, but in a different way to make pylint happy
> [v6r14] Pylint happy

- WorkloadManagementSystem/Agent/PilotStatusAgent.py
Hi,
We like to propose to modify PilotStatusAgent to consider pilot's payload job activity.
In the current code, even if pilot has running payload job, PilotStatusAgent force
the pilot deleted when the time limitation is exceeded. So, our modified code
to check the pilot's payload job activity before to make pilot deleted.
In addition, since PilotStatusAgent does not kill pilots actually,
"ghost" (or deleted) pilot makes its payload job execute later.  This makes some confusion.
So, we like to propose to introduce the code to kill pilots actually, whose status becomes deleted.
> [v6r12] Proposal to modify PilotStatusAgent to consider pilot's payload job

- Resources/Storage/XROOTStorage.py
> [v6r12] Add metadata entries for compatibility with SRM Storage

- DataManagementSystem/Agent/RequestOperations/DMSRequestOperationsBase.py
- DataManagementSystem/Agent/RequestOperations/RemoveFile.py
- RequestManagementSystem/Client/Operation.py
- RequestManagementSystem/Client/ReqClient.py
The ReqClient fixes is to avoid the dirac-rms-show-request to crash in some cases
The two others are stupid mistakes...
> [v6r13] URGENT stupid bugs that surprisingly were not found during tests

- Resources/Storage/GFAL2_StorageBase.py
> [v6r13] Add metadata for compatibility with srm storage

- WorkloadManagementSystem/Client/InputDataByProtocol.py
Useless as now done in StorageElement itself
> [v6r13] Remove StorageElement caching

- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- FrameworkSystem/DB/InstalledComponentsDB.py
- FrameworkSystem/Utilities/MonitoringUtilities.py
- FrameworkSystem/scripts/dirac-populate-component-db.py
InstalledComponents DB will now store information about the user who did the installation/uninstallation of components.
> [v6r14] Extended InstalledComponents DB

- DataManagementSystem/Client/DataManager.py
> [v6r13] SEActive: Add mandatory vo parameter

- Core/Utilities/TimeLeft/LSFTimeLeft.py
- Core/Utilities/TimeLeft/TimeLeft.py
- DataManagementSystem/Agent/RequestOperations/RegisterFile.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/scripts/dirac-dms-replicate-and-register-request.py
- RequestManagementSystem/private/OperationHandlerBase.py
- Resources/Catalog/FileCatalogClient.py
- Resources/Storage/StorageElement.py
- WorkloadManagementSystem/Executor/JobScheduling.py
* Improve dirac-dms-replicate-and-replister-request script to allow large number of files
* Fix a very old bug in DFC (was returning OwmerDGroup instead of OwnerGroup)
* Pass directory name to getDirectoryMetadata and not file name (which was working in LFC plugin)
* LSF is setting shell variables, not envioronment variables, therefore added an "export" command to get the relevant variable and extract then the correct normalisation
* Review / beautify code in TimeLeft and LSFTimeLEFT
> [v6r13] Various fixes to TimeLeft, DFC, RMS

- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
As requested in #1013, a new command has been added to get information about services and agents' documentation.
> [v6r14] Added show doc command

- Core/Utilities/Proxy.py
- Resources/Computing/ARCComputingElement.py
- Resources/Computing/CREAMComputingElement.py
- Resources/Computing/ComputingElement.py
- WorkloadManagementSystem/Service/WMSAdministratorHandler.py
- WorkloadManagementSystem/Service/WMSUtilities.py
Several updates to remove obsoleted stuff and to use ARC/CREAM ComputingElements consistently with any other CEs.
> [v6r14] Updates for ARC/CREAM CE code

- Core/Utilities/InstallTools.py
Get default options of the component module if given in installComponent()
> [v6r14] InstallTools fix

- DataManagementSystem/Client/FileCatalogClientCLI.py
> [v6r12] FileCatalogCLI: removeMetadata needs a dict

- DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
- DataManagementSystem/scripts/dirac-dms-user-lfns.py
- RequestManagementSystem/private/OperationHandlerBase.py
This fixes a bug that was there forever when using the file owner's proxy for removing a file or a replica.
It also increases the timeout for listing a directory of user as some uses have 10,000's directories in their top directory...
> [v6r13] Fix to RMS

- Core/Workflow/Parameter.py
- Interfaces/API/Dirac.py
- Interfaces/API/Job.py
- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Client/WMSClient.py
- WorkloadManagementSystem/Service/WMSUtilities.py
- WorkloadManagementSystem/scripts/dirac-jobexec.py
Plus other fixes, i.e. bug fix in WMSUtilities.py
> [v6r14] Fixes for running jobs locally, using StringIO

- Interfaces/API/Dirac.py
BUGFIX: Dirac- missing jobDescriptionObject initialization
> [v6r14] Missing jobDescriptionObject initialization

- ConfigurationSystem/private/ConfigurationClient.py
Function returns a subsections in the configuration starting from given root. Returns a list of strings. Allows additional filtering.
> [v6r14] Added function getSectionTree() in ConfigurationClient

- Resources/Computing/GlobusComputingElement.py
- WorkloadManagementSystem/Agent/PilotStatusAgent.py
- WorkloadManagementSystem/Service/WMSAdministratorHandler.py
Because the PilotStatusAgent is now trying to kill pilots I could debug the killJob function in the GlobusCE.
> [v6r12] Fixes for GlobusCE killJobs, fix typos in PilotStatusAgent

- Core/scripts/dirac-install-client.py
- Core/scripts/dirac-install.py
NEW: dirac-install - makes us of the DIRAC tar files in CVMFS if available
NEW: dirac-install-client - a guiding script to install the DIRAC client from A to Z
>  [v6r15] Updated dirac installation tools

- FrameworkSystem/private/monitoring/ServiceInterface.py
- WorkloadManagementSystem/DB/TaskQueueDB.py
This PR adds a possibility to present requirements in a form of tags from the site( pilot ) to the jobs to select ones with required properties.
> [v6r15] Required tags for jobs matching

- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- Resources/Storage/StorageFactory.py
- WorkloadManagementSystem/Client/CPUNormalization.py
- WorkloadManagementSystem/scripts/dirac-wms-cpu-normalization.py
* Fixes a problem when a file is set Problematic in the FC but indeed doesn't exist at all
* Adds reading CPU power from MJF for comparison with our script
> [v6r13] Fix in DM and add MJF as test

- Resources/Storage/FileStorage.py
- Resources/Storage/test/TestFilePlugin.py
Implement a plugin to use directly the file protocol. Tests included
> [v6r14] Plugin for file protocol

- DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/DirectoryClosure.py
- Resources/Catalog/FileCatalogClient.py
Implements all the methods of the FileCatalog on the client side, with doc and default args
> [v6r15] new dfc client rebase

- Core/Utilities/DEncode.py
- Core/Utilities/DErrno.py
- Core/Utilities/DIRACError.py
- DataManagementSystem/Client/DataManager.py
- Resources/Storage/SRM2Storage.py
- Resources/Storage/StorageElement.py
- Resources/Utilities.py
- __init__.py
Proper merge of https://github.com/DIRACGrid/DIRAC/pull/2466 
Should hopefully be good
> [v6r15] new error handling merge

- RequestManagementSystem/Client/Request.py
- RequestManagementSystem/DB/RequestDB.py
Fix itt from RequestDB, and slightly modify the informaion returned by Request.getDigest
> [v6r14] Fix in the getDigest

- TransformationSystem/Client/PluginBase.py
- TransformationSystem/Client/Utilities.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Client/CPUNormalization.py
* Fix CPU normalisation from MJF
* Fix type conversion in plugin utilities
> [v6r14] Fixes to MJF and WMS (minor)

- FrameworkSystem/Service/SystemAdministratorHandler.py
Show executors in log overview,
> [v6r12] SystemAdmin: show executors in log overview

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Client/DataManager.py
- StorageManagementSystem/Client/StorageManagerClient.py
- WorkloadManagementSystem/Client/CPUNormalization.py
- WorkloadManagementSystem/Executor/JobScheduling.py
* Don't fail getting metadata for staging if at least one staged replica found
* Allow to not get URLs in DM
* Fix printout in optimizer that was saying "single site" and "multiple sites" in two consecutive lines ;-)
* Add recovery of FTS files (in FTSAgent) that can be left in weird statuses when the agent dies
* Protect MJF from 0 logical cores
> [v6r14] Fixes in Staging, DM, MJF

- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- WorkloadManagementSystem/PilotAgent/pilotTools.py
This is mainly for specifying option --CEType=Pool in case it's wanted.
> [v6r14] Added new CEType option for pilots

- Core/DISET/private/BaseClient.py
- Core/Utilities/DictCache.py
- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- FrameworkSystem/Client/SystemAdministratorIntegrator.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
Speed up evaluation of a list of accessible hosts. BaseClient will print a warning message about a temporary banned URL only if it is really banned 
JobWrapper decoding OptimizerParameters fix, closes #2421 
DictCache destructor is throwing exception without purging the contents due to some called object in threading which is None already
> [v6r15] SysAdmin integrator speedup and others

- Core/Security/X509Certificate.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/PilotAgent/dirac-pilot_1.py
- WorkloadManagementSystem/PilotAgent/pilotTools.py
The use of 0o22 form of integer is not understood by 2.6 python interpreters causing pilots failure on some sites.
A logical bug was introduced when the Matcher client class was created resulting in that only the first job was assigned to the pilot which ran multiple jobs
And yes, the VOMS is the evil - need extra protection against endecodabe attributes
> [v6r14] WMS bug fixes

- WorkloadManagementSystem/JobWrapper/JobWrapper.py
> [v6r15] fix JobWrapper import

- WorkloadManagementSystem/Agent/TaskQueueDirector.py
`from DIRAC import Time, List` failed
> [v6r15] fix TaskQueueDirector utilities import

- Core/scripts/dirac-install.py
Fix for #2627
Replaces #2630 
Cleaned up the branch the other PR was based on, better use a feature branch...
> [v6r12] fix dirac-install for python 2.5 and younger

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Agent/RequestOperations/DMSRequestOperationsBase.py
- DataManagementSystem/private/FTS3/FTS3Placement.py
- RequestManagementSystem/Client/ReqClient.py
- ResourceStatusSystem/Client/ResourceStatus.py
* check whether the always banned policy is applied to a given access type
* make printing the full request prettier
* make the amount of scheduled requests fetched by the FTSAgent a parameter in the CS
> [v6r14] Fix always banned check

- RequestManagementSystem/Client/ReqClient.py
- RequestManagementSystem/DB/RequestDB.py
- RequestManagementSystem/Service/ReqManagerHandler.py
Lock the lines when selecting the requests to be assigned, update the LastUpdate time, and expose the assigned flag to the client
> [v6r14] fix bulk requests

- Core/Utilities/TimeLeft/BQSTimeLeft.py
- Core/Utilities/TimeLeft/LSFTimeLeft.py
- Core/Utilities/TimeLeft/PBSTimeLeft.py
- Core/Utilities/TimeLeft/SGETimeLeft.py
- Core/Utilities/TimeLeft/TimeLeft.py
- WorkloadManagementSystem/Agent/JobAgent.py
I reviewed the TimeLeft utilities included the plugins:
* Make them consistent in terms of what is returned: all return real seconds
* Checked with concrete examples -> fix LSFTimeLeft not taking correctly normalization
* Use consistently always the same CPU power (not yet changed the names, i.e. normFactor and scaleFactor)
* Review JobAgent as well for what concerns time left
> [v6r14] Time Left utility revisited

- Resources/Computing/ComputingElement.py
Get rid of the legacy getResourcesDict()
> [v6r14]  Bug fix in ComputingElement

- Core/Utilities/ReturnValues.py
- Interfaces/API/Job.py
Just some things I stumbled across while compiling my own (ILCDIRAC) documentation
This should go to whatever release the documentation is compiled from, please let me know if it is another branch...
Fixes for this:
http://diracgrid.org/files/docs/CodeDocumentation/Core/Utilities/ReturnValues.html
And this
http://diracgrid.org/files/docs/CodeDocumentation/Interfaces/API/Job.html#DIRAC.Interfaces.API.Job.Job.setExecutable
> [v6r14] Documentation fixes

- TransformationSystem/Client/TransformationCLI.py
Added a function returning the input data query for a given transformation
when using the transformation CLI.
> [v6r12] Function returning inputDataQuery on Trans. CLI

- ResourceStatusSystem/Policy/Configurations.py
Which can be useful for doing, for example (CS conf):
```
[OpsCS]/ResourceStatus/Policies/...
.../DTScheduled1/matchParams/element = Resource
status = Active,Degraded
.../DTOngoing/matchParams/element = Resource
status = Banned
```
> [v6r14] Just added a new possible conf for Downtime Policies

- FrameworkSystem/scripts/dirac-install-component.py
- FrameworkSystem/scripts/dirac-uninstall-component.py
Solving problem when importing InstallTools. This was originally pushed into integration, instead of v6r14.
> [v6r14] Patch with bugfix

- Core/DISET/private/MessageBroker.py
- Core/DISET/private/TransportPool.py
- Interfaces/API/Job.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
> [v6r14] MessageBroker fixes

- DataManagementSystem/Client/FileCatalogClientCLI.py
- TransformationSystem/Client/TransformationCLI.py
Current implementation cover the transformation input
quite well, but lacks of methods to check out easily the
transformation output.
Sometimes you want to list the output lfns in a
running production: you can easily do that in the dirac
file catalog but it's sensible to include such operation
also here.
> [v6r12] Function returning trans. output lfns

- Resources/Computing/GlobusComputingElement.py
Greatly simplify the creation of the pilotStamp, copied from some other CE code
Also note: If anyone ever used this class: the temporary files that were created were never removed
so one should clean the SiteDirector working directory...
> [v6r12] GlobusCE: Simplify creating of pilotStamp

- TransformationSystem/Client/Transformation.py
- TransformationSystem/Client/TransformationCLI.py
Added functions:
[1] do_getallByUser
(DIRAC/TransformationSystem/Client/TransformationCLI.py)
[2] getAuthorDNfromProxy
[3] getTransformationsByUser
(DIRAC/TransformationSystem/Client/Transformation.py)
Monitoring ilcdirac productions from the terminal presents a difficulty:
users do not own their productions: all productions own to the leader
of this project. This cause that users can not list their productions using
their username as a filter
To overcome this problem a dedicated function has being introduced in the
transformation CLI: getallByUser
This function allow list productions filtering by AuthorDN. Then, getTransformationsByUser
is called.
Because AuthorDN is hard to remember, getallByUser also
accept the dirac username. When username is provided instead of the AuthorDN,
another …
> !!! [v6r12] List transformations by UserName/AuthorDN

- Core/Utilities/TimeLeft/PBSTimeLeft.py
- Core/Utilities/TimeLeft/SGETimeLeft.py
- DataManagementSystem/Agent/FTSAgent.py
- FrameworkSystem/private/logging/Logger.py
- TransformationSystem/Agent/TransformationAgent.py
- TransformationSystem/Agent/TransformationPlugin.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/Utilities.py
* TimeLeft: set limit to CPU lower than wall clock if unknown
* FTS system: wait some time between 2 monitorings of each job
* Clean getNextSite() and normalizeShares()  in TS
* Fix exception printing in gLogger.exception()
> [v6r14] Miscellaneous small fixes

- Core/Utilities/InstallTools.py
We are missing important information about DIRAC processes. I have added the CPU,MEM, VSZ,RSS to the system administrator. We can get the process status from the system administrator.
> [v6r14] add more information about the processes

- DataManagementSystem/Utilities/DMSHelpers.py
Add check for CS entry so that one can define an SE to belong to more than one ComputingElement, as was possible before. This fixes my issues with the InputData Executor.
> [v6r13] Allow for more than one Site per SE

- TransformationSystem/Agent/TransformationPlugin.py
- TransformationSystem/Agent/test/Test_Plugins.py
As far as I can see the parameters for PluginUtilities are never set.
Without setting the params things like GroupSize are otherwise only taken from the default or the CS and not from individual transformations.
> [v6r14] TransformationPlugin: Need to pass parameters to utils

- ConfigurationSystem/Agent/GOCDB2CSAgent.py
- ConfigurationSystem/private/ConfigurationClient.py
- Core/Utilities/SitesDIRACGOCDBmapping.py
An agent that retrieve data from GOCDB is ready. Currently only perfSONAR related data are supported, but other types of service endpoints can be added later. The agent requires working instance of CS to run properly. I've made some tests on my computer, but no unit/integration tests are included at the moments.
Additionally, I changed the function getSectionTree() submitted previously with getConfigurationTree(), as it is a bit more powerful since it also returns options with their values.
Some small changes have also been introduced automatically by the code formatter - I hope they didn't break anything.
> [v6r15] Added GOCDB2CSAgent to Configuration System.

- FrameworkSystem/DB/InstalledComponentsDB.py
Fixed a bug with HostLogging where the name of a field was not generated correctly.
> [v6r15] Fixed bug

- TransformationSystem/Agent/TransformationPlugin.py
Fix TargetSE that was not correctly set.
> [v6r13] Fix TargetSE in TransformationPlugin

- FrameworkSystem/Client/ComponentInstaller.py
> [v6r15] Fix on ComponentInstaller

- TransformationSystem/scripts/dirac-production-runjoblocal.py
line 163
__configurePilot(_path) -> __configurePilot(_path, _vo)
> [v6r15] dirac-production-runjoblocal.py fix

- ConfigurationSystem/Agent/UsersAndGroups.py
- ConfigurationSystem/Agent/VOMS2CSAgent.py
- ConfigurationSystem/Client/CSAPI.py
- Core/Utilities/Time.py
- Core/scripts/dirac-info.py
- __init__.py
VOMS2CSAgent - do not send mail if no changes performed
CSAPI.modifyUser() returns True or False if there were or not changes done
dirac-info - few more items to print out
> [v6r15] Several minor fixes

- ConfigurationSystem/Client/Utilities.py
- Core/Security/VOMS.py
1. Validate some Bdii values
2. Make RFC VOMS extended proxy if the original one is RFC
> [v6r14] Bdii2CS and VOMS fixes

- Resources/Storage/SRM2Storage.py
Since this PR https://github.com/DIRACGrid/DIRAC/pull/2668 is not going to be merged in v6r15, I backported this important fix.
You can't add to DError. Also, the accounting is done in the StorageElement, no need to do it in the plugins
> [v6r15] Do not return anything in DError, contrary to S_ERROR in SRM plugin

- Core/Security/VOMS.py
This bug generates proxies which are a mix between legacy and rfc proxies. Impossible to talk to any outside world service like this, it is not a valid delegation chain
> [v6r14][URGENT] Test properly if a proxy is RFC or not

- Core/Utilities/Proxy.py
- DataManagementSystem/Client/DataManager.py
- Interfaces/API/Dirac.py
- StorageManagementSystem/Client/StorageManagerClient.py
- TransformationSystem/Agent/TransformationAgent.py
- WorkloadManagementSystem/Executor/InputData.py
* Allow selecting disk replicas in getActiveReplicas() and getReplicas()
* Better check that files are staged in stager, + protect against bad metadata structure
* Minor fix in decorator for executing method with user proxy when processing exceptions (return the actual exception information)
* Use the preferDisk option in the InputData optimizer, the TransformationAgent and in the Interface splitter
> [v6r14] DataManagement small improvements

- Resources/Computing/ARCComputingElement.py
Chose a round figure of 10K seconds for the renewal.
> [v6r14] Update to automatically renew proxies of jobs when needed

- Core/Security/BaseSecurity.py
- Core/Security/ProxyFile.py
- Core/Security/ProxyInfo.py
- Core/Security/VOMS.py
- Core/Security/VOMSService.py
- Core/Security/X509CRL.py
- Core/Security/X509Certificate.py
- Core/Security/X509Chain.py
- Core/Security/X509Request.py
- Core/Utilities/DEncode.py
- Core/Utilities/DErrno.py
- Core/Utilities/MySQL.py
- Core/Utilities/ReturnValues.py
- Core/Utilities/__init__.py
- DataManagementSystem/Client/DataManager.py
- FrameworkSystem/private/logging/Logger.py
- Resources/Catalog/FileCatalog.py
- Resources/Catalog/Utilities.py
- Resources/Storage/SRM2Storage.py
- Resources/Storage/StorageElement.py
- Resources/Storage/Utilities.py
- TransformationSystem/scripts/dirac-production-runjoblocal.py
Replace DError class by the enhanced S_ERROR structure.
> [v6r15] Replace DError by enhanced S_ERROR

- Core/scripts/dirac-configure.py
- Core/scripts/dirac-fix-mysql-script.py
- Core/scripts/dirac-install-db.py
- Core/scripts/dirac-install-mysql.py
- Core/scripts/dirac-install-web-portal.py
- Core/scripts/dirac-restart-component.py
- Core/scripts/dirac-restart-mysql.py
- Core/scripts/dirac-setup-site.py
- Core/scripts/dirac-start-component.py
- Core/scripts/dirac-start-mysql.py
- Core/scripts/dirac-status-component.py
- Core/scripts/dirac-stop-component.py
- Core/scripts/dirac-stop-mysql.py
- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
- FrameworkSystem/scripts/dirac-install-component.py
- FrameworkSystem/scripts/dirac-uninstall-component.py
Replaced references to InstallTools with the appropriate calls to ComponentInstaller.
InstallTools has not been deleted yet, just in case.
> [v6r15] Adaptation to ComponentInstaller

- Core/scripts/dirac-deploy-scripts.py
I don't know how it could work before :-)
> [V6r14] Install dirac scripts first so that they can be overwritten

- FrameworkSystem/Client/ComponentInstaller.py
Modified ComponentInstaller to add entries to the InstalledComponents DB for services, agents and executors installed during the setup process.
> [v6r15] Store in DB on setup

- FrameworkSystem/Client/SystemAdministratorClientCLI.py
Added new CLI command, retire <host>, that removes a host and all of its installations (if any) from the DB
> [v6r15] Retire hosts

- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
Added new getPorts command to the CLI (#1174) that returns which ports are currently in use by which services in a given host.
> [v6r15] Get ports

- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
Bad accounting when removing several files from the same directory, and when removing replicas in a non existing SE
> [v6r14] Bug in DirectoryUsage table

- FrameworkSystem/Client/ComponentInstaller.py
- Resources/Computing/SSHComputingElement.py
- WorkloadManagementSystem/Client/Matcher.py
- mysql startup script is in the new location with the new MySQL version
- restored RequiredTag logic in the Matcher
> [v6r15] Several bug fixes

- .gitignore
- .pylintrc
- Core/scripts/dirac-create-distribution-tarball.py
e.g.:
```
ABCDIRAC/
WMS
DMS
```
or
```
ABCDIRAC/
WMS
DMS
tests
docs
```
or
```
ABCDIRAC/
ABCDIRAC/
WMS
DMS
```
or 
```
ABCDIRAC/
ABCDIRAC/
WMS
DMS
tests
docs
```
> [v6r14] Consider different structures of repository

- Core/scripts/dirac-create-distribution-tarball.py
Bug fixed in __generateTarball
> [v6r14] Bug fixed

- WorkloadManagementSystem/DB/SandboxMetadataDB.py
Problems with people having apostrophe in their name
> [v6r14] Escape the values in SandboxMetadataDB

- DataManagementSystem/scripts/dirac-admin-allow-se.py
- DataManagementSystem/scripts/dirac-admin-ban-se.py
- TransformationSystem/Agent/TransformationAgent.py
* Allow SE group is dirac-admin-allow-se
* Fix reduction of number of files in TransformationAgent
> [v6r14] Few minor fixes

- Core/Utilities/MySQL.py
- FrameworkSystem/private/logging/Logger.py
- WorkloadManagementSystem/DB/PilotAgentsDB.py
- WorkloadManagementSystem/DB/TaskQueueDB.py
- WorkloadManagementSystem/JobWrapper/JobWrapperTemplate.py
- WorkloadManagementSystem/Utilities/Utils.py
Main fix here comes from @chaen : escaping DNs ("special" characters may cause nasty effects)
I also added a better exception logging for JobWrapper.
> [v6r14] Escape DNs

- RequestManagementSystem/Service/ReqProxyHandler.py
Add a bit of monitoring to know how many requests are being handled by the proxy
> [v6r15] Add monitoring in the ReqProxy

- ResourceStatusSystem/Client/ResourceManagementClient.py
- tests/Integration/ResourceStatusSystem/Test_ResourceManagement.py
- tests/Integration/ResourceStatusSystem/Test_ResourceStatus.py
> [v6r15] Integration tests for ResourceStatus and ResourceManagement

- WorkloadManagementSystem/JobWrapper/JobWrapperTemplate.py
And this PR corrects a bug introduced with v6r14p21 (that should be probably removed)
> [v6r14] Being sure that unicode is interpreted correctly

- Core/Utilities/DErrno.py
- RequestManagementSystem/Service/ReqProxyHandler.py
> [v6r15] Allow listing and showing the request in a ReqProxy

- ResourceStatusSystem/Utilities/InfoGetter.py
- tests/Integration/ResourceStatusSystem/Test_ResourceManagement.py
- tests/Integration/ResourceStatusSystem/Test_fullChain.py
added an extra check to __filterPolicies and fixed a typo
>  [v6r15] added an extra check to __filterPolicies and fixed a typo

- DataManagementSystem/Client/DataManager.py
- Resources/Storage/StorageFactory.py
* SE inheritance was not working well when some parameters were modified
* Fix DataManager for getActiveReplicas (first check Active before selecting disk SEs)
> [v6r14] Minor DMS fixes

- WorkloadManagementSystem/Agent/SiteDirector.py
Using PilotRunDirectory as WorkingDirectory, if available at the CE level in the CS. 
Requested at the issue #2746
> [v6r15] Pilot run dir

- ConfigurationSystem/Client/Helpers/Resources.py
- Core/Utilities/Graphs/GraphUtilities.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/Service/WMSAdministratorHandler.py
- WorkloadManagementSystem/Service/WMSUtilities.py
- requirements.txt
Only change: added funcsigs in "requirements.txt" (used by mock)
> [v6r15] Almost purely pylint

- Core/Utilities/List.py
I have improved uniqueElements, it is **much** faster now.
Here are some data from the performance benchmarking that I made using a list of 20 thousand numbers (unique and non-unique):
```
1) Old uniqueElements time:  0.752 seconds
2) New uniqueElements time:  0.002 seconds
```
> [v6r15] Improved uniqueElements

- DataManagementSystem/scripts/dirac-admin-allow-se.py
- WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py
1. dirac-admin-allow-se can accept several status types to update in one go. Status Unknown becomes a valid status.
2. Use NumberOfProcessors CS option name everywhere
> [v6r15] dirac-admin-allow-se more convenient

- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-framework-ping-service.py
All in the title. 
FYI, this will allow better monitoring for containers
> [v6r14] Allow to ping a specific URL

- Core/LCG/test/Test_LCG.py
- Core/Utilities/File.py
- Core/Utilities/TimeLeft/test/Test_TimeLeft.py
- Core/Utilities/test/Test_File.py
- ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py
- ResourceStatusSystem/Command/test/Test_RSS_Command_VOBOXAvailabilityCommand.py
- TransformationSystem/Client/test/Test_Client_TransformationSystem.py
As per https://travis-ci.org/DIRACGrid/DIRAC/builds/122505590
> [v6r14] Fixing the tests

- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/Utilities/JobMemory.py
- WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py
The jobs will be failed if the request is inValid.
Plus other very minor fixes.
> [v6r14] Setting minor status if failover request fails to be sent

- TransformationSystem/DB/TransformationDB.py
This may explain why we have tasks assigned to the same request...
> [v6r14] forward errors in TS

- DataManagementSystem/DB/FileCatalogComponents/SecurityPolicies/VOMSPolicy.py
- DataManagementSystem/DB/FileCatalogComponents/SecurityPolicies/test/Test_VOMSPolicy.py
Following the replacement of setFileXXX with changePathXXX
> [v6r15] Remove the setFileXXX method from VOMSPolicy 

- tests/Integration/RequestManagementSystem/Test_Client_Req.py
> [v6r15] Add sleep in a test, lost during migration from TestDIRAC

- AccountingSystem/Client/DataStoreClient.py
- Core/Utilities/Time.py
- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Client/DataManager.py
1. In getFile(), select preferentially local disk replicas, if none disk replicas, if none tape replicas
2. Avoid changing argument of public method checkActiveReplicas() as it could be dangerous
Change name of __SEActive() as it is used to know the SE type as well... rename to  __checkSEStatus()
Minor additional changes:
* wait 3 times longer for monitoring FTS jobs if Staging
* suppress printout of timeThis() if interactive
> [v6r14] DataManager improvements

- AccountingSystem/private/DBUtils.py
- AccountingSystem/private/Plotters/PilotPlotter.py
- Core/Utilities/Graphs/QualityMapGraph.py
> [v6r14] use better (2D) plot for number of jobs running per pilot

- FrameworkSystem/Service/MonitoringHandler.py
> [v6r14] MonitoringHandler: Fix KeyError in deleteActivities

- docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/index.rst
I added some more packages for Fedora/CentOS
I also added an indication that the user must include his own github username while cloning.
> [v6r15] Updated Developer Guide Documentation

- docs/source/AdministratorGuide/Systems/RequestManagement/rms.rst
This adds some information about the RMS, and remove deprecated one. Some details are not true anymore, but would require regenerating image, which I won't do right now
> [v6r15] Documentation updated for the RMS 

- .landscape.yml
We should actually add some pep8 configuration file into the branch, but for now only this.
> [v6r14] Disable indentation a multiple of four from pep8

- RequestManagementSystem/Client/ReqClient.py
There was a bug in the ReqClient preventing to have multiple instance of the ReqManager.
Basically the client would talk to ```url1:9140/RequestManagement/ReqManager``` asking for ```url2:9140/RequestManagement/ReqManager```, resulting in the error message ```RequestManagement/ReqManager is not up in this server```
> [v6r14] Fix the ReqClient to allow it to talk to multiple ReqManager

- ConfigurationSystem/Client/Helpers/Resources.py
As discussed during the workshop
> [v6r15] Remove dips from the list of ThirdPartyProtocols

- WorkloadManagementSystem/Client/CPUNormalization.py
gLogger.Exception -> gLogger.exception
> [v6r14] Fixed typo in CPUNormalization

- WorkloadManagementSystem/PilotAgent/pilotCommands.py
Protecting the parsing of pilot commands output.
See #2928
> [v6r15] Protecting the parsing of pilot commands output.

- Core/Utilities/PrettyPrint.py
- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/DB/TaskQueueDB.py
Fixed a bug resulting in ignoring multiProcessor job requirement for sites presenting an empty Tag list.
Better and prettier logging of the matching parameters
> [v6r15] Bug fixes and better logging in the Matcher

- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Sites/index.rst
- docs/source/AdministratorGuide/Systems/WorkloadManagement/Jobs/index.rst
added terminology and resources configuration options.
> [v6r15] Document multi-processor jobs feature

- docs/source/AdministratorGuide/Systems/ResourceStatus/install.rst
> [v6r15] Updated documentation

- ConfigurationSystem/Agent/Bdii2CSAgent.py
- Resources/Computing/InProcessComputingElement.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/JobWrapper/JobWrapperTemplate.py
> [v6r14] Bdii2CSAgent bad infromation caching problem fix

- Resources/Computing/BatchSystems/SLURM.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
Some changes for SSHSLURM CE
1. Modified SLURM.py as queue in the slurm is partition, not cluster.
2. Modified pilotCommands.py to identify SSHSLURM 
We confirmed these modifications are working in the Belle II DIRAC environment.
> [v6r14] Modifications to use SSHSLURM CE

- DataManagementSystem/scripts/dirac-dms-show-se-status.py
Added switches to the  dirac-dms-show-se-status command to show SEs for a given VO, all VOs and also those SEs with no VO assignment
> [v6r15] dirac-dms-show-se-status new flags

- AccountingSystem/Client/DataStoreClient.py
Fix for https://github.com/DIRACGrid/DIRAC/issues/2416
> [v6r15] Never throw an exception when sending failover accounting request

- Resources/Storage/ProxyStorage.py
> [v6r14] make DMS client work with multiple StorageElementProxy urls

- Core/Utilities/Mail.py
> [v6r14] Fix sending mail to multiple recipients

- Resources/Storage/GFAL2_SRM2Storage.py
- Resources/Storage/GFAL2_StorageBase.py
* rename self.gfal2 into self.ctx 
* There is a bug in globus. I added a magic line that circumvent it until fixed (if you want the full story: https://its.cern.ch/jira/browse/DMC-853)
> [v6r15] Circumvent globus bug in gfal2

- ConfigurationSystem/Agent/Bdii2CSAgent.py
> [v6r14] Find all CEs in a new site supporting our VO

- RequestManagementSystem/Service/ReqManagerHandler.py
Instead of incrementing the delay at each attempt, there might be (there is !) a wish to have a constant delay.
> [v6r14] RMS: Add possibility of constant delay

- Core/Utilities/Mail.py
> [v6r15] enable attachments in the mail

- ConfigurationSystem/Agent/Bdii2CSAgent.py
- ConfigurationSystem/Agent/GOCDB2CSAgent.py
- ConfigurationSystem/Agent/VOMS2CSAgent.py
- Core/DISET/private/Service.py
- DataManagementSystem/Client/ConsistencyInspector.py
- DataManagementSystem/Client/DataIntegrityClient.py
- DataManagementSystem/DB/DataIntegrityDB.py
- DataManagementSystem/Service/DataIntegrityHandler.py
- Interfaces/API/Dirac.py
- Interfaces/API/Job.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- tests/Integration/DataManagementSystem/Test_DataIntegrityDB.py
> [v6r15] FIX CS agents init

- ConfigurationSystem/Agent/VOMS2CSAgent.py
> [v6r15] VOMS2CSAgent bug fix

- ConfigurationSystem/Agent/Bdii2CSAgent.py
- ConfigurationSystem/test/Test_Bdii2CS.py
As discussed here: https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/KdZ9pg_Dj18
The information from the alternates will only be used for sites that don't exist in the primary one.
> [v6r15] Get information from alternative bdiis for sites not existing in central one.

- FrameworkSystem/scripts/dirac-proxy-destroy.py
One for the admins (and anyone who is a member of multiple VOs):
Deletes proxies (local and/or uploaded) from the command line.
Selective deletions by VO also supported.
> [v6r15] Delete proxies from the command line

- Core/Base/API.py
> [v6r15] Fix group space

- Resources/Storage/StorageElement.py
> [v6r15] SE: error in the accounting for putFile

- ConfigurationSystem/Client/Helpers/Resources.py
- DataManagementSystem/Utilities/DMSHelpers.py
- DataManagementSystem/scripts/dirac-dms-find-lfns.py
- TransformationSystem/Agent/TransformationAgent.py
* Remove temporary fix in TransformationAgent (that had been there for 2 years ;-)
* Cache list of SEs in DMSHelpers
* Fix helper getStorageElementOptions() for handling BaseSE and Alias. Note: this is redundant with (part of) the StorageFactory and was causing troubles when introducing BaseSE earlier. It is only used by RSS
> [v6r15] Miscellaneous small fixes

- AccountingSystem/DB/AccountingDB.py
now the delete query condition is:
startTime < _UNIX_TIMESTAMP() - 14months - maxBucketLength
> [v6r15] Changes to using index in accounting to speed-up removal query

- DataManagementSystem/Agent/RequestOperations/MoveReplica.py
- DataManagementSystem/Agent/RequestOperations/test/Test_RequestOperations.py
- DataManagementSystem/scripts/dirac-dms-move-replica-request.py
This handler moves replicas from source SEs to target SEs. Replicas are first replicated to target SEs and then removed from the source SEs.
> [v6r16] New MoveReplica operation handler

- ConfigurationSystem/Agent/VOMS2CSAgent.py
- ConfigurationSystem/Client/CSAPI.py
- ConfigurationSystem/Client/Helpers/Registry.py
- ConfigurationSystem/ConfigTemplate.cfg
- Core/Utilities/Grid.py
- Resources/Catalog/FileCatalogClient.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Agents/VOMS2CSAgent/index.rst
Added more options for the VOMS2CSAgent:
- Possibility to automatically delete users who are no longer in the VOMS ( AutoDeleteUsers CS flag )
- Possibility to create user home directories in DFC ( MakeHomeDirectory CS flag )
- Possibility to generate more detailed report for the admins ( DetailedReport CS flag )
Plus several fixes in the logic of the agent.
> [v6r15] More options for the VOMS2CSAgent

- Core/Utilities/DErrno.py
- Core/Utilities/Profiler.py
- requirements.txt
Added profiling utility used to retrieve dynamic information about a process. This is used by the dynamic monitoring system to get the information that will be stored into ElasticSearch.
> [v6r16] DynamicMonitoring Profiler

- Core/Utilities/ElasticSearchDB.py
- FrameworkSystem/Client/SystemAdministratorClientCLI.py
- MonitoringSystem/Client/MonitoringClient.py
- MonitoringSystem/DB/MonitoringDB.py
- MonitoringSystem/Service/MonitoringHandler.py
- MonitoringSystem/private/Plotters/ComponentMonitoringPlotter.py
- docs/source/AdministratorGuide/Systems/Framework/index.rst
- docs/source/DeveloperGuide/Systems/Framework/index.rst
- tests/Integration/Monitoring/Test_MonitoringReporter.py
- tests/Integration/Monitoring/Test_MonitoringSystem.py
Added a new CLI command to read and display logging information stored in ElasticSearch.
Requires PR #2968 to be merged before.
> [v6r16] DynamicMonitoring info from CLI

- Core/LCG/GOCDBClient.py
- ResourceStatusSystem/PolicySystem/Actions/FTSStorageBanAction.py
- ResourceStatusSystem/PolicySystem/Actions/FTSStorageUnbanAction.py
For more info: https://ggus.eu/index.php?mode=ticket_info&ticket_id=123971
> [v6r15] GOCDBClient.py to catch all downtimes, independently of their scope

- AccountingSystem/Service/DataStoreHandler.py
- AccountingSystem/Service/ReportGeneratorHandler.py
- Core/scripts/dirac-setup-site.py
- FrameworkSystem/Client/ComponentInstaller.py
Refresh database configuration even if the database exists in the server
Refresh global configuration when adding options to the local dirac.cfg
> [v6r16]  Fix setupSite

- ConfigurationSystem/Client/Utilities.py
> [cherry-pick in v6r15] Take into account WallTime during MaxCPUTime definition

- Resources/Storage/StorageBase.py
For https://github.com/DIRACGrid/DIRAC/pull/3099
> [v6r15] StorageBase: add baseURL in the list of parameters returned

- StorageManagementSystem/Client/StorageManagerClient.py
- WorkloadManagementSystem/Client/CPUNormalization.py
- WorkloadManagementSystem/DB/JobDB.py
If there are no active replicas, avoid an exception
Dummy change in CPUNormalisation
> [v6r15] Fix StorageManagementClient

- DataManagementSystem/Agent/RequestOperations/RemoveFile.py
- TransformationSystem/Client/FileReport.py
* When updating input files status, if OK, clear the dictionary
- This was forcing to do it twice
* In RemoveFile: remove all files that are not at a banned SE
> [v6r15] Minor fixes

- Core/LCG/GOCDBClient.py
I replaced `urllib2` with `requests` in GOCDBClient.
> [v6r16] Replaced urllib2 with requests

- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- RequestManagementSystem/scripts/dirac-rms-show-request.py
- TransformationSystem/Client/Utilities.py
* Remove @timeThis in TS utilities
* Reject bad checksums in RMS
* Small fix in show-request script
> [v6r15] Small fixes

- Resources/Computing/HTCondorCEComputingElement.py
- Resources/Computing/test/Test_HTCondorCEComputingElement.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst
This includes  #3170 , so if this PR needs more review, please merge the other one and I will rebase this one.
Option strings as used by LHCb, from @VladimirRomanovsky 
Added tests, updated doc.
> [v6r15] HTCondorCE: Add option to use remote schedd

- ConfigurationSystem/Agent/VOMS2CSAgent.py
Remove user DNs which are no more in VOMS. Fixes #3130
> [v6r16] Remove obsoleted DNs

- DataManagementSystem/Client/DataManager.py
- DataManagementSystem/Client/FailoverTransfer.py
Workflow: properly pass the checksum when uploading output.
DMS: handle properly checksum calculation in the DataManager
This avoids having "False" checksum in the DFC, resulting in problems in RMS/FTS/etc
> [v6r16] Fix with checksum propagation and handling

- DataManagementSystem/Client/FileCatalogClientCLI.py
- DataManagementSystem/DB/FileCatalogComponents/DatasetManager.py
Dataset client commands were totally broken starting from v6r15. Here the various commands have been fixed. For details, see #3100.
> [v6r16] Bug fixes in dataset management

- Core/Utilities/Adler.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- FrameworkSystem/private/logging/Logger.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/TransformationAgentsUtilities.py
- TransformationSystem/Client/TaskManager.py
* Review the code of TaskManager (in TS) and TaskManagerAgentBase:
- Standardize the logging information
- Remove unnecessary code (e.g. take into account the fact that only one transformation is dealt with at a time)
- Use iterators wherever possible
* Although the checksum was fixed when "False" in the FC, it was overwritten later by _addMetatadataToFiles()
* Check explicitly for "False" in Adler utility and return error (no exception)
* gLogger: test level before processing string (i.e. mostly converting objects to strings)
> [v6r17] Revisit TaskManager, further fix checksum in ReplicateAndRegister, improve gLogger

- Resources/Computing/HTCondorCEComputingElement.py
https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/k90bZIU6YXc
> [v6r15] HTCondorCEComputingElement: 'cast' useLocalSchedd to bool

- Core/scripts/dirac-install.py
- Core/scripts/install_site.sh
- docs/source/AdministratorGuide/CommandReference/install_site.sh.rst
- docs/source/AdministratorGuide/InstallingDIRACService/index.rst
- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
- tests/Jenkins/dirac_ci.sh
For issue https://github.com/DIRACGrid/DIRAC/issues/3171
Also mod documentation and Jenkins invocation.
> [v6r17] Adding version switch to install_site.sh

- AccountingSystem/Client/DataStoreClient.py
- AccountingSystem/Service/DataStoreHandler.py
- Core/Utilities/ElasticSearchDB.py
- FrameworkSystem/Client/ComponentInstaller.py
- ResourceStatusSystem/Command/Command.py
- ResourceStatusSystem/Command/FreeDiskSpaceCommand.py
- TransformationSystem/Agent/TransformationAgentsUtilities.py
- TransformationSystem/Client/TaskManager.py
- docs/source/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.rst
- requirements.txt
- tests/Integration/Framework/Test_ComponentInstallUninstall.py
- tests/Integration/Monitoring/Test_MonitoringReporter.py
- tests/Integration/Monitoring/Test_MonitoringSystem.py
- tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/Jenkins/dirac-cfg-update.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/install.cfg
> [v6r17] SetupSite to include NoSQL parameters

- FrameworkSystem/Client/ProxyGeneration.py
- FrameworkSystem/Client/ProxyUpload.py
- FrameworkSystem/DB/ProxyDB.py
- FrameworkSystem/Service/ProxyManagerHandler.py
- FrameworkSystem/scripts/dirac-admin-proxy-upload.py
- FrameworkSystem/scripts/dirac-proxy-init.py
- docs/source/AdministratorGuide/CommandReference/dirac-proxy-init.rst
- docs/source/AdministratorGuide/Configuration/ConfReference/Registry/Groups/index.rst
- docs/source/AdministratorGuide/InstallingDIRACService/index.rst
- docs/source/UserGuide/CommandReference/Others/dirac-proxy-init.rst
- docs/source/UserGuide/Tutorials/ManagingUserCredentials/index.rst
- tests/Jenkins/utilities.sh
> [v6r17] pylint, doc and test for rfc proxies. Always re-uploading proxy

- Core/scripts/dirac-install.py
- DataManagementSystem/Client/DataManager.py
- FrameworkSystem/private/logging/SubSystemLogger.py
- Resources/Storage/GFAL2_StorageBase.py
Fix for https://github.com/DIRACGrid/DIRAC/issues/3196 that can be closed when merged
> [v6r17] Fix for logger and optimization of multi-protocol

- Resources/Storage/StorageElement.py
Was throwing an exception when RSS was not knowing the SE
> [v6r17] Fix SE crash when not valid in RSS

- ResourceStatusSystem/Agent/EmailAgent.py
- ResourceStatusSystem/PolicySystem/Actions/EmailAction.py
> [v6r17] Prevent database locks

- Core/Utilities/ElasticSearchDB.py
- MonitoringSystem/Client/MonitoringReporter.py
- MonitoringSystem/DB/MonitoringDB.py
- Resources/MessageQueue/StompMQConnector.py
- Resources/MessageQueue/Utilities.py
Next time we can not just change the Elasticsearch-dsl version! It needs proper testing!
> [v6r17] update to elasticsearch-dsl 5.0.1 and use host cert

- ResourceStatusSystem/Utilities/Synchronizer.py
From now on, the `sync` method will be removing the resources that are no longer in the CS from the `DowntimeCache` table.
> [v6r17] Remove resources that no longer exist in the CS

- Core/Utilities/SiteCEMapping.py
- DataManagementSystem/scripts/dirac-dms-find-lfns.py
- Interfaces/API/Job.py
- Interfaces/API/test/Test_JobAPI.py
- Resources/Storage/GFAL2_SRM2Storage.py
- Resources/Storage/SRM2Storage.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/TransformationAgentsUtilities.py
- TransformationSystem/Client/TaskManager.py
The TaskManager was taking close to 50 seconds to prepare each job!! This was mainly caused by the check done one each and every site, fetching the Site-CE mapping for every job and every site.
Other optimization done taking into account the fact that the agent processed only tasks from a single transformation in each thread, hence a template job can be created once for the whole list of jobs. Also instances of plugins can be kept.
It still takes more than 2 seconds to set the output LFNs in the JDL, which is not obvious for me that it is useful at all... However the current optimisation is already sufficient for submitting faster enough.
> [v6r17] Fix the TaskManager

- WorkloadManagementSystem/ConfigTemplate.cfg
Missing section was preventing smooth installation of MultiProcessorSiteDirector agent
> add MultiProcessorSiteDirector configuration section

- DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
- FrameworkSystem/private/logging/Logger.py
* Fix Logger such that subLogger works fine
* Don't set file Done in RemoveReplicas if there is an error
> [v6r17] Various fixes

- ConfigurationSystem/Client/Utilities.py
WallTime should not be 4444 or 9999 
MaxCPUTime should be integer
> fix small bug in BDII

- Resources/Computing/BatchSystems/Torque.py
Some sites put advertising in command answer which we can not parse. Redirect err to /dev/null
> [v6r17] Torque fix

- ConfigurationSystem/Client/Helpers/ResourcesDefaults.py
- ConfigurationSystem/Client/Utilities.py
- ConfigurationSystem/private/ConfigurationClient.py
- Core/Utilities/Grid.py
- Core/Workflow/Module.py
- Core/Workflow/Step.py
- Core/scripts/dirac-externals-requirements.py
- FrameworkSystem/Client/ComponentInstaller.py
- FrameworkSystem/ConfigTemplate.cfg
- Workflow/Modules/UploadOutputs.py
- tests/Integration/WorkloadManagementSystem/pilot.cfg
- tests/Integration/WorkloadManagementSystem/sb.cfg
- tests/Jenkins/dirac-cfg-update-dbs.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/install.cfg
- tests/Jenkins/utilities.sh
And several other things for certification tests
> [v6r18] Fixes when getting elasticDB parameters

- Resources/Storage/test/Test_StorageFactory.py
Fixed test `getStorageElementStatus` has been replaced with `getElementStatus`
> StorageFactory test fix

- ResourceStatusSystem/DB/ResourceManagementDB.py
- ResourceStatusSystem/DB/ResourceStatusDB.py
- tests/Integration/ResourceStatusSystem/Test_ResourceStatus.py
- Added an extra check for `meta` parameter in `ResourceStatusDB`
- Fixed RSS test
**EDIT**: I also fixed a bug in RMS, I added it to this PR
> Fixed RSS test

- Core/Security/X509Chain.py
- Core/Utilities/DErrno.py
- FrameworkSystem/DB/ProxyDB.py
- docs/source/UserGuide/GettingStarted/InstallingClient/index.rst
With the new error return object the message comparison in completeDelegation() was invalid
> [v6r17] Minor fix ProxyDB

- WorkloadManagementSystem/DB/TaskQueueDB.py
When an empty TaskQueue is marked for deletion, it can still get matches which result in no selected jobs that produced unnecessary error messages polluting SystemLogging.
> [v6r17]  Fix in the matching logic

- docs/source/DeveloperGuide/Systems/WorloadManagementSystem/index.rst
Add @phicharp 's finding about the watchdog in a temporary doc. It needs to be refined before making it to the admin section
> [v6r17] JobWrapper documentation

- Core/Utilities/Proxy.py
- DataManagementSystem/Client/test/mock_DM.py
- StorageManagementSystem/Client/StorageManagerClient.py
- StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
- TransformationSystem/Client/FileReport.py
- WorkloadManagementSystem/Executor/InputData.py
- WorkloadManagementSystem/Executor/JobScheduling.py
Contains #3244 plus a minor bug fix
> [v6r17] Minor fixes to #3244

- Core/Utilities/Proxy.py
- DataManagementSystem/Client/test/mock_DM.py
- StorageManagementSystem/Client/StorageManagerClient.py
- StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
- TransformationSystem/Client/FileReport.py
- WorkloadManagementSystem/Executor/InputData.py
- WorkloadManagementSystem/Executor/JobScheduling.py
* JobScheduling is calling getFilesToStage that toggles UseServerCertificate. As the optimizer is multithreaded this must be protected with a lock.
* getProxy has a bad indentation preventing looping on the DNs
* Minor other fixes
> !!! [v6r17] Fix JobScheduling optimizer

- ResourceStatusSystem/DB/ResourceManagementDB.py
- ResourceStatusSystem/DB/ResourceStatusDB.py
`columns` may not be in the `meta` dictionary, I added an extra check for this occasion
> [v6r18] Fixed a bug in meta parameter check

- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Utilities/RSSCacheNoThread.py
- Fixed the problematic generation of RSS cache
> [v6r18] Fixed RSS cache generation

- StorageManagementSystem/Client/StorageManagerClient.py
- WorkloadManagementSystem/Executor/JobScheduling.py
Avoid using proxy if no files to check on tape SE
> [v6r17] Another fix to getFilesToStage

- Core/Utilities/ProcessMonitor.py
- DataManagementSystem/Client/FTSJob.py
- FrameworkSystem/private/monitoring/MonitoringCatalog.py
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Service/ResourceStatusHandler.py
- TransformationSystem/Agent/TransformationCleaningAgent.py
- WorkloadManagementSystem/Client/SandboxStoreClient.py
- WorkloadManagementSystem/Client/WMSClient.py
- WorkloadManagementSystem/Executor/JobScheduling.py
- tests/Integration/DataManagementSystem/Test_FileCatalogDB.py
- tests/Integration/ResourceStatusSystem/Test_Publisher.py
- tests/Integration/ResourceStatusSystem/Test_ResourceManagement.py
- tests/Integration/ResourceStatusSystem/Test_ResourceStatus.py
- tests/Integration/ResourceStatusSystem/Test_ResourceStatusClient.py
- tests/Integration/ResourceStatusSystem/Test_SiteStatus.py
- tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
Plus various pylints/test fixes
> [v6r18] Fixes to RSS (for when RSS is inActive)

- DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
- DataManagementSystem/Client/ConsistencyInspector.py
- DataManagementSystem/Client/DataIntegrityClient.py
- DataManagementSystem/Client/FTSRequest.py
- DataManagementSystem/scripts/dirac-dms-replica-metadata.py
- StorageManagementSystem/Agent/StageMonitorAgent.py
- StorageManagementSystem/Agent/StageRequestAgent.py
- StorageManagementSystem/Client/StorageManagerClient.py
- StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
- WorkloadManagementSystem/Client/DownloadInputData.py
- WorkloadManagementSystem/Client/InputDataByProtocol.py
* RemoveReplica: If an error was set it was never reset 
* Fixes for solving issue https://github.com/DIRACGrid/DIRAC/issues/2502 on SE metadata keys
> [v6r17] Fix RemoveReplica handler and SE metadata keys

- Resources/Storage/GFAL2_GSIFTPStorage.py
- Resources/Storage/GFAL2_HTTPSStorage.py
- Resources/Storage/GFAL2_StorageBase.py
- Resources/Storage/StorageBase.py
- docs/source/AdministratorGuide/Systems/DataManagement/index.rst
- tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
Add GSIFTP and HTTPS plugin. Correct GFAL2 integration tests.
The HTTPS plugin is not tested properly yet because of the lack of endpoint to try
> [v6r17] New GSIFTP and HTTPS protocol

- WorkloadManagementSystem/Client/SandboxStoreClient.py
Do not make destination directory if inMemory result
> [v6r17] SandboxStoreClient fix

- Core/Utilities/Proxy.py
> [v6r17] Add executeWithoutServerCertificate function

- Core/Utilities/PrettyPrint.py
- Interfaces/API/Dirac.py
DiracLHCb API needed to use the checkFileArgument method, remove one "_" in the name
> [v6r17] Make methods visible to derived class

- DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
- RequestManagementSystem/scripts/dirac-rms-list-req-cache.py
> [v6r17] Add a script to list the requests in the ReqProxies

- RequestManagementSystem/Agent/RequestExecutingAgent.py
- RequestManagementSystem/Client/ReqClient.py
- StorageManagementSystem/Client/StorageManagerClient.py
- StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/test/Test_Agent_TransformationSystem.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/TransformationClient.py
- WorkloadManagementSystem/Executor/JobScheduling.py
Replaces https://github.com/DIRACGrid/DIRAC/pull/3294
* getFilesToStage was only returning online files
* JobScheduling was assuming all non-online files required staging
* Improvements include:
return explicitly offline files and only stage those if at TpeSE
return also absent files (i.e. not at SE): in this case make the job Failed
* Improvements in TaskManager: process tasks in chunks of 100 in order to update faster the TS (tasks and files)
> [v6r17] Improvement in getFilesToStage, JobScheduling snd TS 

- Core/scripts/dirac-install.py
- DataManagementSystem/private/FTSHistoryView.py
For the FTSHistoryView.
And a small fx for dirac-install to allow local md5 files
For task #3293
> [v6r18] Fixes for MySQL 5.7

- .pylintrc
- WorkloadManagementSystem/DB/JobDB.py
> [v6r18] more fixes for MySQL 5.7

- DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
> [v6r17] Removing the replica of a non exisiting file is successful

- docs/source/DeveloperGuide/AddingNewComponents/CheckYourInstallation/index.rst
> [v6r18] correct return doc

- Core/Utilities/Os.py
- Core/Utilities/__init__.py
- Resources/Computing/ComputingElement.py
- Resources/Computing/InProcessComputingElement.py
- Resources/Computing/PoolComputingElement.py
- Resources/Computing/SudoComputingElement.py
- Resources/Computing/test/Test_PoolComputingElement.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/JobWrapper/Watchdog.py
- WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py
This PR contains changes needed to run several possibly multiprocessor jobs in one JobAgent using the PoolComputingElement with optionally changing user identity with "sudo".
Replaces #3299 to resolve conflicts with the target branch. All the comments to #3299 are taken into account.
> [v6r18] Support for multi-processor job execution

- ConfigurationSystem/Agent/VOMS2CSAgent.py
Yet another weird VOMS DN case
> [v6r17] VOMS2CSAgent fix

- DataManagementSystem/Client/FileCatalogClientCLI.py
- DataManagementSystem/DB/FileCatalogComponents/FileManager.py
1. Fix for the doc strings usage in file catalog CLI, fixes #3306 
2. Modified recursive file parameter setting as suggested by André in #3282 to enable usage of the index
> [v6r17] File Catalog fixes

- WorkloadManagementSystem/Agent/SiteDirector.py
Sometimes this protection is necessary.
> [v6r17] ceStatus = oldStatus when pRef not found

- Core/Security/X509Chain.py
- FrameworkSystem/Client/ProxyUpload.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- ResourceStatusSystem/scripts/dirac-rss-sync.py
1. Bug fixes in the dirac-rss-sync command
2. Fixes to allow robot proxies with embedded DIRAC group extension
> [v6r18] Several fixes 

- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/StorageElements/index.rst
Replace ProtocolName with PluginName
> [v6r18] Correct documentation for PluginName

- Resources/Computing/ComputingElement.py
fixing pylint issues in ComputingElement
> [v6r18] ComputingElement: pylint fixes

- WorkloadManagementSystem/Service/WMSAdministratorHandler.py
Fixing ~25 pylint warnings during the workshop
> [v6r18] WMSAdministratorHandler: linting the code

- WorkloadManagementSystem/Agent/JobAgent.py
Ran pylint on JobAgent.py and was able to improve the score. Testing a pull request.
> [v6r18] improved code quality via variable name change

- Resources/Computing/HTCondorCEComputingElement.py
Minor change for HTCondor job output when it uses remote scheduler.
> [v6r17] HTCondor: get job output for remote sheduler

- WorkloadManagementSystem/Agent/SiteDirector.py
- docs/source/AdministratorGuide/index.rst
1. Connect VMDIRAC docs to the Admin guide ToC
2. SiteDirector - log the target VO.
> [v6r18] Connect VMDIRAC docs

- Core/Utilities/ElasticSearchDB.py
- Core/scripts/dirac-distribution.py
- FrameworkSystem/test/testLogging/tests/Test_DisplayOptions.py
- FrameworkSystem/test/testLogging/tests/Test_Levels.py
- FrameworkSystem/test/testLogging/tests/Test_LogRecordCreation.py
- FrameworkSystem/test/testLogging/tests/Test_Logging.py
- FrameworkSystem/test/testLogging/tests/Test_SubLogger.py
- Interfaces/API/Dirac.py
- Interfaces/API/Job.py
- ResourceStatusSystem/Client/SiteStatus.py
- Resources/Computing/test/Test_PoolComputingElement.py
- WorkloadManagementSystem/Client/Matcher.py
- docs/source/AdministratorGuide/index.rst
- docs/source/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.rst
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/Jenkins/dirac-test-job.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/utilities.sh
*Core
FIX: dirac-distribution will by default compile for python 2.7
*Interfaces
FIX: correctly setting local PATHs for local job execution
*tests
NEW: added submitAndMatch test for Jenkins style jobs
> [v6r18] fixes to dirac-distribution and style/docs fixes

- FrameworkSystem/private/standardLogging/Logging.py
- FrameworkSystem/private/standardLogging/LoggingRoot.py
- FrameworkSystem/test/testLogging/tests/Test_DisplayOptions.py
- FrameworkSystem/test/testLogging/tests/Test_Logging.py
Here is an update of the new logging system including thread-safety.
> [v6r18] Make the new logging system thread-safe

- AccountingSystem/DB/test/Test_AccountingDB.py
- Resources/Computing/PoolComputingElement.py
- Resources/Computing/test/Test_PoolComputingElement.py
- WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py
- tests/Jenkins/utilities.sh
- tests/Workflow/Regression/exe-script.py
*Tests
FIX: getting proxy also for pilot installations
> [v6r19] Just fixing tests

- AccountingSystem/DB/test/Test_AccountingDB.py
*Accounting
FIX: Use the calculateBuckets method to have the correct start end end time of the query
> [v6r19] fix accounting unit test

- Core/Base/API.py
- FrameworkSystem/Client/Logger.py
- FrameworkSystem/private/standardLogging/Logging.py
- FrameworkSystem/test/testLogging/tests/Test_Logging.py
- Interfaces/API/Job.py
This pull request just replaces the logging system *gLogger* by the new one and fix some issues due to the changes.
> [v6r19] Replace gLogger and fix some issues due to the changes

- DataManagementSystem/scripts/dirac-admin-allow-se.py
FIX: dirac-admin-allow-se  first call of gLogger after its import
> [v6r17] gLogger first call after its import

- FrameworkSystem/private/standardLogging/Handler/MessageQueueHandler.py
- FrameworkSystem/private/standardLogging/Handler/ServerHandler.py
- Resources/LogBackends/MessageQueueBackend.py
- Resources/MessageQueue/StompMQConnector.py
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/Backends/index.rst
The pull request contains a new Backend and its documentation, used to send logs to a MessageQueue.
> [v6r19] New logging backend: MessageQueueBackend

- Core/Security/Locations.py
- Core/Security/Utilities.py
- Core/Utilities/CertificateMgmt.py
- Core/Utilities/ElasticSearchDB.py
- Core/scripts/genAllCAs.sh
- Core/scripts/genRevokedCerts.sh
- FrameworkSystem/Client/BundleDeliveryClient.py
- FrameworkSystem/Service/BundleDeliveryHandler.py
*Core
NEW: New module implemented, which can be used to create CAs and revoked certificates files, if they are not provided. ElsticsearchDB is updated to use this new module.
> [v6r19] create an utility module, which can be used to create the CAs

- Core/Utilities/TimeLeft/TimeLeft.py
- Core/Utilities/TimeLeft/test/Test_TimeLeft.py
*WMS
CHANGE: split time left margins in cpuMargin and wallClockMargin. 
> [v6r17] Split CPU and wallclock margin

- TransformationSystem/scripts/dirac-transformation-add-file.py
- TransformationSystem/scripts/dirac-transformation-get-files.py
- tests/System/dirac-test-production.py
- tests/System/transformationSystem.sh
Added a system test for transformations with meta-filters.
*tests
FIX: Minor fixes in the TS system test
CHANGE: Add to the TS system test, the test for transformations with meta-filters
> [v6r19] System test ts

- tests/Jenkins/dirac-cfg-update-dbs.py
*Test
FIX: correctly update the DFC DB configuration in jenkins' tests
> [v6r19] Jenkins: correctly update the DFC config

- DataManagementSystem/Client/FTSJob.py
FIX: fix the serialization of 0 values for FTSJob
> [v6r19]Fix serialization of FTSJob

- Core/scripts/dirac-create-distribution-tarball.py
- MonitoringSystem/Client/MonitoringReporter.py
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Service/ResourceStatusHandler.py
- ResourceStatusSystem/scripts/dirac-rss-query-db.py
- ResourceStatusSystem/scripts/dirac-rss-query-dtcache.py
- Resources/MessageQueue/MQCommunication.py
- Resources/MessageQueue/Utilities.py
- TransformationSystem/scripts/dirac-transformation-add-files.py
- TransformationSystem/scripts/dirac-transformation-get-files.py
- tests/System/dirac-test-production.py
- tests/System/rss-scripts.sh
- tests/System/transformationSystem.sh
*tests
NEW: RSS system test
*Core
FIX: removing docs and tests directories when creating release tarballs.
> [v6r19] Fixes for RSS scripts and transformation system tests

- WorkloadManagementSystem/Agent/SiteDirector.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Operations/Pilots/index.rst
*WMS
NEW: Added option to force lcgBundle version from SiteDirector
> [v6r19] Added option to force lcgBundle version from SiteDirector

- Resources/Computing/HTCondorCEComputingElement.py
Transfer output files(only log and err) for remote scheduler
> [v6r17] HTCondor transfer files

- Resources/Storage/StorageFactory.py
- Resources/Storage/test/Test_FilePlugin.py
- Resources/Storage/test/Test_StorageFactory.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/StorageElements/index.rst
- docs/source/AdministratorGuide/Systems/DataManagement/index.rst
This pull request:
+ fixes different weird behaviours in Storage Element, as the inheritance of the protocol sections
+ creates a new Resources section named *StorageElementBases* containing only Base SEs
+ updates the documentation
> [v6r19] Fix StorageElement inheritance and add a new Resources section

- DataManagementSystem/Client/FTSFile.py
- DataManagementSystem/Client/FTSJob.py
FIX: Fix sql statement generation for stricter versions of MySQL
> [v6r19] FTS: fixes for ToSQL method (which would not happen with SQLAlchemy :-) )

- Core/Utilities/List.py
- TransformationSystem/Agent/InputDataAgent.py
- TransformationSystem/Agent/TransformationPlugin.py
- TransformationSystem/Client/Transformation.py
- TransformationSystem/Client/TransformationClient.py
- TransformationSystem/Client/test/Test_Client_TransformationSystem.py
- TransformationSystem/DB/TransformationDB.py
- TransformationSystem/Service/TransformationManagerHandler.py
- tests/Integration/TransformationSystem/Test_Client_Transformation.py
* TransformationSystem
FIX: fix issue https://github.com/DIRACGrid/DIRAC/issues/3446 for wrong file error counting in TS
FIX: there was a bug in the TS files state machine (comparing old status.lower() with new status). Fixed tests accordingly
CHANGE: cosmetic change in List.py
FIX: set ExternalID _before_ ExternalStatus in tasks
> [v6r19] Fix ErrorCount in TS files

- DataManagementSystem/Utilities/DMSHelpers.py
- RequestManagementSystem/Client/ReqClient.py
- TransformationSystem/Client/Utilities.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
* RequestManagementSystem
FIX: avoid INFO message in client 
* WMS
CHANGE: Allow SE-USER to be defined as another SE group (e.g. Tier1-USER)
* DMS
CHANGE: make resolveSEGroup recursive in order to be able to define SE groups in terms of SE groups
> [v6r17] Minor fixes

- Resources/Storage/GFAL2_SRM2Storage.py
- Resources/Storage/GFAL2_StorageBase.py
This will be for when we get the new LcgBundle with gfal 2.13.3 in it
> [v6r19] Update to gfal 2.13.3 API

- Core/scripts/genAllCAs.sh
- Core/scripts/genRevokedCerts.sh
*Framework
CHANGE: add the possibility to specify the Input and/or output directory from sh files used for generating CAs and CRLs
> [v6r19] add the possibility to specify the Input and/or output directory

- FrameworkSystem/private/standardLogging/LoggingRoot.py
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/Changes/index.rst
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst
As requested by @atsareg, I modified the name of the Backends configuration section
> [v6r19] Change BackendsConfig section to LogBackendsConfig

- Core/Utilities/Mail.py
- FrameworkSystem/Service/NotificationHandler.py
- docs/source/AdministratorGuide/Systems/Framework/Notification/index.rst
- docs/source/AdministratorGuide/Systems/Framework/index.rst
*Framework
NEW: Mail.py - added smtp parameters
NEW: NotificationHandler.py - added read smtp parameters from configuration
> [v6r19] Added new parameters of notification service

- WorkloadManagementSystem/PilotAgent/dirac-pilot.py
- WorkloadManagementSystem/PilotAgent/pilotTools.py
*WMS
CHANGE: Add option to clear PYTHONPATH on pilot start
backporting from https://github.com/DIRACGrid/DIRAC/pull/3352
> [v6r17] Clearing the python path

- Core/Utilities/Mail.py
- FrameworkSystem/Agent/ErrorMessageMonitor.py
- FrameworkSystem/Client/NotificationClient.py
*Framework
CHANGE: can now send mails to multiple recipients using the NotificationClient
FIX: Adapting query to MySLQ 5.7 "GROUP BY" clause
> [v6r19] Fixes to messages reporting and notifications

- Core/Utilities/SitesDIRACGOCDBmapping.py
- FrameworkSystem/Client/NotificationClient.py
- ResourceStatusSystem/Agent/SummarizeLogsAgent.py
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Client/ResourceStatusClient.py
- ResourceStatusSystem/Client/SiteStatus.py
- ResourceStatusSystem/Command/DowntimeCommand.py
- ResourceStatusSystem/DB/ResourceManagementDB.py
- ResourceStatusSystem/DB/ResourceStatusDB.py
- ResourceStatusSystem/PolicySystem/Actions/EmailAction.py
- tests/Integration/ResourceStatusSystem/Test_ResourceStatus.py
*RSS
FIX: Just better check for key
FIX: handling all meta conditions in DB requests
> [v6r19] v6r19 RSS fixes

- Resources/Computing/ARCComputingElement.py
*Resources
FIX: ARCComputingElement: fix job submission issue due to timeout for newer lcg-bundles
See also: https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/u_5gO56Y3Co
> [v6r17] ARCCE: ensure the timeout for server connections is set

- ResourceStatusSystem/Agent/TokenAgent.py
- ResourceStatusSystem/Client/SiteStatus.py
- ResourceStatusSystem/DB/ResourceStatusDB.py
- ResourceStatusSystem/Service/ResourceManagementHandler.py
- ResourceStatusSystem/Service/ResourceStatusHandler.py
- WorkloadManagementSystem/Service/JobPolicy.py
*RSS
FIX: fix backward compatibility
> [v6r19] bug fixes

- Interfaces/API/Dirac.py
Just a simple bug fix in runLocal
> [v6r19] Reading IS from job dir in runLocal

- Interfaces/API/Dirac.py
- requirements.txt
> [v6r19] fixes to IS resolution

- Resources/Computing/SudoComputingElement.py
Pass the application error transparently through SudoCE (unless a shellCall error).
FIX: SudoComputingElement message overwriting application errors
> [v6r19] Fix regression in SudoComputingElement.py

- Core/Base/ElasticDB.py
- Core/Utilities/ElasticSearchDB.py
*Monitoring
FIX: certifi package was miscalled
FIX: added debug messages for DB connection
> [v6r19] Just debug messages for ElasticSearch

- FrameworkSystem/Client/ComponentInstaller.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/Jenkins/dirac-cfg-update-server.py
- tests/Jenkins/utilities.sh
*Framework
FIX: Handling correctly extensions of DBs found in sql files
> [v6r19] Handling correctly extensions of DBs found in sql files

- .github/CODEOWNERS
- .pylintrc
- AccountingSystem/ConfigTemplate.cfg
- ConfigurationSystem/Client/Helpers/CSGlobals.py
- Core/DISET/private/MessageBroker.py
- Core/Utilities/Graphs/GraphData.py
- Core/Utilities/test/test.cfg
- DataManagementSystem/ConfigTemplate.cfg
- DataManagementSystem/private/FTS3Utilities.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
- FrameworkSystem/private/monitoring/monitoringSchema.sql
- RequestManagementSystem/ConfigTemplate.cfg
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Utilities/RSSCacheNoThread.py
- TransformationSystem/DB/TransformationDB.sql
- TransformationSystem/Service/TransformationManagerHandler.py
- Workflow/Modules/Script.py
- requirements.txt
FIX: fixed pylint version to 1.6.5 (latest is broken)
NEW: added CODEOWNERS file
> [v6r20] Mostly pylint fixes

- ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py
- ResourceStatusSystem/Command/test/Test_RSS_Command_VOBOXAvailabilityCommand.py
- ResourceStatusSystem/DB/ResourceStatusDB.py
- ResourceStatusSystem/Policy/JobDoneRatioPolicy.py
- ResourceStatusSystem/Policy/JobRunningMatchedRatioPolicy.py
- ResourceStatusSystem/Policy/JobRunningWaitingRatioPolicy.py
- ResourceStatusSystem/Policy/PilotEfficiencyPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_AlwaysActivePolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_CEAvailabilityPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_Configurations.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_DTPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_JobDoneRatioPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_JobEfficiencyPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_JobRunningMatchedRatioPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_JobRunningWaitingRatioPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_PilotEfficiencyPolicy.py
- ResourceStatusSystem/Policy/test/Test_RSS_Policy_SpaceTokenOccupancyPolicy.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/utilities.sh
> [v6r19] RSS DB fix: microseconds should always be 0

- AccountingSystem/Client/Types/BaseAccountingType.py
- AccountingSystem/Service/ReportGeneratorHandler.py
- AccountingSystem/private/DBUtils.py
- AccountingSystem/private/MainReporter.py
- Core/DISET/private/FileHelper.py
- Core/DISET/private/Transports/SSL/SocketInfoFactory.py
- Core/Utilities/Graphs/Palette.py
- Core/Utilities/ObjectLoader.py
- Core/Utilities/ThreadScheduler.py
- Core/scripts/dirac-distribution.py
- DataManagementSystem/DB/FileCatalogComponents/DatasetManager.py
- FrameworkSystem/DB/UserProfileDB.py
- Interfaces/API/DiracAdmin.py
- Workflow/Modules/ModuleBase.py
- Workflow/Modules/Script.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
- docs/source/DeveloperGuide/AddingNewComponents/DevelopingExecutors/PingPongMindHandler.py
*WMS
FIX: pilot commands will add /DIRAC/Extensions=extensions if requested
*Workflow
FIX: application log name can also come from step_commons.get['logFile']
and some pylints as usual
> [v6r19] Saving extension in pilots

- Core/scripts/dirac-configure.py
- Core/scripts/dirac-install.py
*Core
CHANGE: Removed deprecated option "ExtraModules" (dirac-configure, dirac-install scripts)
> [v6r20] Removed deprecated option

- Resources/Storage/StorageFactory.py
- WorkloadManagementSystem/Service/JobMonitoringHandler.py
autopep8 applied...
*DMS
FIX: avoid complaining if Access option is not in SE section
*WMS
FIX: web table was not considering correctly Failed jobs because stalled for setting the LastSignOfLife
> [v6r19] Fix LastSignOfLife in web monitor

- ResourceStatusSystem/Agent/CacheFeederAgent.py
- ResourceStatusSystem/Command/DowntimeCommand.py
*ResourceStatusSystem
FIX: CacheFeederAgent resiliant to command exceptions
> [v6r19] RSS fixes

- tests/Utilities/testJobDefinitions.py
*tests
FIX: use rootPath instead of environment variable
> [v6r19] test fixes

- .travis.yml
- Resources/Computing/HTCondorCEComputingElement.py
This adds a job to the CI that will check that any changed lines or new files are formatted according to the agreed style.
The check only does something meaningful for PRs because it is impossible to figure out with what to diff the code otherwise.
> [v6r20] CI: add formatting job

- TransformationSystem/Service/TransformationManagerHandler.py
FIX:  wrong method called by the Manager 
Of course autopep8 for free
> [v6r19] fix typo in TSManager

- WorkloadManagementSystem/Agent/SiteDirector.py
*WMS
CHANGE: Added logging format and UTC timestamp to pilot wrapper
> [v9r19] Added logging format to pilot wrapper

- AccountingSystem/Agent/NetworkAgent.py
*Accounting
CHANGE: NetworkAgent - remove support of perfSONAR summaries and add support of raw metrics.
> [v6r19] Change of the perfSONAR input feed in NetworkAgent

- AccountingSystem/ConfigTemplate.cfg
- Core/Utilities/test/test.cfg
- DataManagementSystem/ConfigTemplate.cfg
- RequestManagementSystem/ConfigTemplate.cfg
- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst
- docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Agents/inputdataagent.rst
- docs/source/AdministratorGuide/InstallingVMDIRAC/index.rst
- docs/source/AdministratorGuide/Systems/Accounting/index.rst
- docs/source/AdministratorGuide/Systems/DataManagement/data_logging_system.rst
- docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst
- docs/source/AdministratorGuide/Systems/ResourceStatus/install.rst
- docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/downloadCAs.sh
- docs/source/DeveloperGuide/DevelopmentEnvironment/Eclipse/index.rst
- docs/source/UserGuide/CommandReference/DataManagement/dirac-dls-method-call.rst
- docs/source/UserGuide/CommandReference/DataManagement/dirac-dls-sequence.rst
- docs/source/UserGuide/GettingStarted/InstallingClient/index.rst
- docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst
- docs/source/UserGuide/WebPortalReference/PilotMonitor/index.rst
- tests/Integration/WorkloadManagementSystem/Test_TimeLeft.sh
- tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh
- tests/System/random_files_creator.sh
- tests/System/transformationSystem.sh
.sh, .cfg, .rst files (no tab found in .py)
> [v6r19] Simply replacing tabs with spaces

- WorkloadManagementSystem/Service/JobMonitoringHandler.py
*WMS
FIX: the fix... for showing correct sign of life for stalled jobs
> [v6r19] Fix typo and add stalling case

- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py
*WMS
FIX: added some printouts to dirac-wms-get-wn-parameters
> [v6r19] just added some monitoring messages for pilot

- TransformationSystem/Client/TaskManager.py
*TS
FIX: bad merge when porting
> [v6r20] Bad merge

- README.rst
*Documentation
CHANGE: point README to master and add badges for integration
> [v6r19] DOC: point README to master and add badges for integration

- Core/Utilities/Decorators.py
Hi,
Here is my suggestion for adding a simple deprecated decorator (for issue #3518)... I was initially going to do something more complicated but I ran into quite a few minor implementation details of decorators, so kept it simpler in the end.
Regards,
Simon
*Core
NEW: Add deprecated decorator
> [v6r19] Add deprecated decorator

- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/StorageElementsGroups/index.rst
- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
- docs/source/AdministratorGuide/SetupStructure/index.rst
- docs/source/AdministratorGuide/index.rst
- docs/source/DeveloperGuide/AddingNewComponents/DevelopingServices/index.rst
- docs/source/DeveloperGuide/CodeTesting/index.rst
- docs/source/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.rst
*Doc
CHANGE: update of release procedure, certification procedure
CHANGE: Added developer doc on how to use the dip protocol
CHANGE: Added Tier1-Failover option in Resources CS section
> [v6r19 Various documentation updates

- Interfaces/API/DiracAdmin.py
- Interfaces/scripts/dirac-admin-get-banned-sites.py
- Interfaces/scripts/dirac-admin-get-site-mask.py
- Interfaces/scripts/dirac-admin-site-mask-logging.py
- ResourceStatusSystem/Agent/ElementInspectorAgent.py
- ResourceStatusSystem/Utilities/CSHelpers.py
- ResourceStatusSystem/Utilities/Publisher.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Client/Matcher.py
- WorkloadManagementSystem/DB/PilotAgentsDB.py
*RSS
FIX: CSHelper: getting FTS from the correct location
CHANGE: use the SiteStatus object wherever possible
> [v6r19] Various RSS fixes

- Core/Utilities/test/Test_Encode.py
- requirements.txt
This contains extensive unit tests for encoding and decoding. It is based on a framework that I highly encourage you to use for unit tests: Hypothesis. The two issues mentioned here https://github.com/DIRACGrid/DIRAC/issues/3551 are directly from it.
*Core
NEW: encode/decode unit tests
> [v6r20] Add extensive unit tests for encoding/decoding

- DataManagementSystem/Utilities/DMSHelpers.py
- RequestManagementSystem/scripts/dirac-rms-request.py
- WorkloadManagementSystem/Client/DownloadInputData.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
* WMS
CHANGE: DownloadInputData was instantiating all local SEs which is not necessary... Only instantiate those that are needed
CHANGE: In JobWrapper, use resolveSEGroup in order to allow defining SE groups including other SE groups
* DMS
FIX: in DMSHelpers don't complain if an SE is at 0 sites
> [v6r19] Fix handling of SEs in jobs

- ConfigurationSystem/Client/Helpers/Resources.py
- ResourceStatusSystem/Agent/CacheFeederAgent.py
- ResourceStatusSystem/Command/DowntimeCommand.py
- ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py
- ResourceStatusSystem/Policy/SpaceTokenOccupancyPolicy.py
- ResourceStatusSystem/Utilities/CSHelpers.py
- WorkloadManagementSystem/Executor/JobScheduling.py
*RSS
CHANGE: getting storage options by instantiating storage element objects
*Resources
FIX: removed a useless/broken method in Resources helper
FIX: marked as obsoletes two methods in Resources helper (FTS2)
> [v6r19] in RSS, getting storage options by instantiating storage element objects

- Interfaces/API/Job.py
- ResourceStatusSystem/PolicySystem/Actions/EmailAction.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- Workflow/Modules/ModuleBase.py
- Workflow/Modules/UploadOutputs.py
- WorkloadManagementSystem/Service/JobMonitoringHandler.py
*RSS
FIX: EmailAction considers also CEs, not only SEs
> [v6r19] Just doc, an RSS fix, and style/pylint

- DataManagementSystem/Agent/FTSAgent.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- DataManagementSystem/Utilities/DMSHelpers.py
- RequestManagementSystem/Client/ReqClient.py
- RequestManagementSystem/scripts/dirac-rms-request.py
- TransformationSystem/Service/TransformationManagerHandler.py
* TransformationSystem
CHANGE: add possibility to get extension-specific tasks and files statuses in TransformationMonitor web application
* RMS
NEW: add option --ListJobs to dirac-rms-request to list the jobs for a set of requests
* DMS
FIX: in DMSHelpers, fix case when no site is found for an SE
FIX: in ReplicateAndRegister, don't try and get SE metadata is replica is inactive
> [v6r19] Add new fields in TransformationMonitor, fix ReplicateAndRegister

- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
At the last merge or v6r19 to integration, the merging (difficult!) was not good. This fixes it.
@andresailer : in order to do that, I started from Integration branch, checked out the buggy file as it was before the merge of rel-v619, cherry-picked every commit from Phillipe and resolved them by hand, and finally created a patch between my result and the integration branch. From this patch, I generated a single new commit on top of the integration branch. Is there any better way of doing so ? 
*DMS
FIX: correct bad merge of ReplicateAndRegister
> [v6r20] DMS: fix bad merge of ReplicateAndRegister

- WorkloadManagementSystem/JobWrapper/JobWrapperTemplate.py
*WMS
FIX: Fix exception handling on JobWrapperTemplate
> [v6r19] Fix exception handling on JobWrapperTemplate

- RequestManagementSystem/DB/RequestDB.py
There was a join missing in the query resulting in a huuuuuge cartesian product. 
*RMS
FIX: add missing JOIN in the web summary query
> [v6r19] RMS: add missing JOIN in the web summary query

- DataManagementSystem/Agent/FTSAgent.py
- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-wms-select-jobs.py
- RequestManagementSystem/Client/ReqClient.py
- RequestManagementSystem/scripts/dirac-rms-request.py
* DMS
FIX: FTSAgent, change data member names from uppercase to lower case
* RMS
NEW: add option to dirac-rms-request to allow resetting the NotBefore member even for non-failed requests
* Interfaces
CHANGE: autopep8 on the API/Dirac module
* WMS
CHANGE: new option to limit the number of selected jobs in dirac-wms-select-jobs
> [v6r19] Minor fixes

- FrameworkSystem/DB/InstalledComponentsDB.py
- WorkloadManagementSystem/Agent/JobCleaningAgent.py
- WorkloadManagementSystem/DB/SandboxMetadataDB.py
- WorkloadManagementSystem/Service/SandboxStoreHandler.py
- docs/source/DeveloperGuide/Internals/Core/componentsAuthNandAuthZ.rst
- docs/source/DeveloperGuide/Internals/index.rst
*Framework:
CHANGE: moved column "Instance" of InstalledComponentsDB.InstalledComponent table from 64 to 32 characters
*WMS:
CHANGE: returning an error when sandboxes can't be unassigned from jobs (JobCleaningAgent)
*docs:
NEW: added some doc about shifterProxy
> [v6r19] Always removing the sandboxes of deleted jobs

- Core/Utilities/ElasticSearchDB.py
- DataManagementSystem/Agent/FTSAgent.py
- Interfaces/scripts/dirac-wms-select-jobs.py
- ResourceStatusSystem/Agent/SummarizeLogsAgent.py
- docs/source/UserGuide/CommandReference/WorkloadManagement/dirac-wms-select-jobs.rst
- tests/System/client_test.sh
- tests/System/rss-scripts.sh
@phicharp this PR is (an "emergency") bugfix of FTSAgent which is mostly restoring the previous version. Please re-apply your fixes once back.
*RSS
FIX: fixed bug in creation of history of status (avoid repetition of entries)
*DMS
FIX: fixed bug in FTSAgent initialization
*WMS
FIX: fix bug in dirac-wms-job-select: treating the case of jobGroup(s) not requested
> [v6r19] Bug fix in FTSAgent (DMS) and in SummarizeLogsAgent (RSS)

- AccountingSystem/DB/test/Test_AccountingDB.py
- Core/LCG/GOCDBClient.py
The only real change is at line 338
*RSS
NEW/CHANGE/FIX: encode in utf-8, update goc db web api URL
> [v6r19] Fixes to encoding in GOCDBClient

- Core/Utilities/Graphs/QualityMapGraph.py
- MonitoringSystem/Client/Types/BaseType.py
- MonitoringSystem/Client/Types/ComponentMonitoring.py
- MonitoringSystem/Client/Types/WMSHistory.py
*Core:
CHANGE: Change the colour map of the Quality plots
CHANGE: Elasticsearch 6 does not support multiple types, only one type is created instead.
> [v6r19] EL mapping change and change the colour map of the quality plots

- WorkloadManagementSystem/private/correctors/BaseHistoryCorrector.py
- WorkloadManagementSystem/private/correctors/MonitoringHistoryCorrector.py
- WorkloadManagementSystem/private/correctors/WMSHistoryCorrector.py
With the introduction of the ElasticSearch based monitoring we have two equivalent sources of resources consumption data. Two new classes for user priority corrections are introduced in this PR corresponding to each source of history data.
*WMS
NEW: WMSHistoryCorrector and MonitoringHistoryCorrector classes inheriting from a common BaseHistoryCorrector class
> [v6r20] MonitoringHistoryCorrector of user priorities using ElasticSearch data

- Core/Base/Client.py
- Core/Utilities/ExecutorDispatcher.py
- Core/Utilities/Graphs/GraphUtilities.py
- Core/Utilities/OracleDB.py
- Core/Utilities/test/Test_ExecutorDispatcher.py
- Core/scripts/dirac-info.py
- DataManagementSystem/Utilities/lfc_dfc_db_copy.py
- Interfaces/API/DiracAdmin.py
- RequestManagementSystem/Client/Request.py
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Utilities/CSHelpers.py
- ResourceStatusSystem/Utilities/RSSCacheNoThread.py
- Resources/Computing/ARCComputingElement.py
- Resources/Storage/SRM2Storage.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Agent/test/Test_Agent_WorkloadManagementSystem.py
- WorkloadManagementSystem/Client/MatcherClient.py
- requirements.txt
This PR does not change the SiteDirector: what I have done is simply split the method `submitJobs` in several sub-methods, with the purpose of being easier to extend (and to partly replace some of its internal logic). I also added more tests, and better code documentation. Minor fixes applied here and there.
*WMS
CHANGE: Refactored Site Director for better extensibility
> [v6r20] Refactored Site Director for better extensibility

- Core/Security/Utilities.py
- FrameworkSystem/Client/BundleDeliveryClient.py
- ResourceStatusSystem/Client/SiteStatus.py
- StorageManagementSystem/Client/StorageManagerClient.py
- WorkloadManagementSystem/Client/JobState/JobState.py
- WorkloadManagementSystem/Executor/JobScheduling.py
- WorkloadManagementSystem/Service/JobManagerHandler.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
*WMS
FIX: always initialize gPilotAgentsDB object
*RSS
FIX: Initialize RPC to WMSAdministrator only once
> [v6r20] Small bug fixes in WMS and RSS

- docs/source/DeveloperGuide/Internals/Core/componentsAuthNandAuthZ.rst
Just a very small addition to the doc written by @fstagni
> [v6r20] Docs: add documentation about Auth and AuthZ

- TransformationSystem/Agent/TransformationCleaningAgent.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Agents/transformationcleaningagent.rst
*TS
FIX: Just few simplifications in TranformationCleaningAgent
> [v6r20] Just few simplifications in TranformationCleaningAgent

- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py
- tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh
- tests/Integration/WorkloadManagementSystem/createJobXMLDescriptions.py
And extended one test.
*WMS
FIX: JobWrapper: added a debug message
> [v6r19] Just adding a debug message in JobWrapper

- docs/source/DeveloperGuide/Internals/Core/index.rst
- tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
Just better test for DMS and fix of doc formatting 
*Test
CHANGE: improve Gfal2 integration tests by checking the metadata
> [v6r19] Improve DMS tests

- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
*docs
NEW: describe the web configuration file
> add web related docs

- ConfigurationSystem/Client/Helpers/Resources.py
- DataManagementSystem/Agent/FTS3Agent.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- DataManagementSystem/Client/FTS3File.py
- DataManagementSystem/Client/FTS3Job.py
- DataManagementSystem/Client/FTS3Operation.py
- DataManagementSystem/private/FTS3Utilities.py
- DataManagementSystem/private/test/Test_FTS3Utilities.py
- docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst
Some fixes for the new fts3 system
*DMS
FIX: 
- adding vo name argument for StorageElement
- fixing rss to fetch fts3 server status
> [v6r20] fixing FTS3

- AccountingSystem/Client/Types/DataOperation.py
- AccountingSystem/Client/Types/Job.py
- FrameworkSystem/Client/WebAppCompiler.py
- FrameworkSystem/DB/InstalledComponentsDB.py
- docs/source/DeveloperGuide/CodingConvention/index.rst
- tests/Jenkins/dirac-cfg-update-dbs.py
- tests/Jenkins/install.cfg
*tests
FIX: add MonitoringDB to the configuration
> [v6r20] fix monitoring integration test

- docs/source/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.rst
*docs
CHANGE: WebApp release procedure 
> [v6r20]dirac-distribution documentation

- Interfaces/API/Job.py
*WMS
FIX: fixing finding XML file
> [v6r20] fixing finding XML file in _toJDL (Job API)

- ConfigurationSystem/Service/ConfigurationHandler.py
- Core/DISET/HTTPDISETConnection.py
- WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Services/Server/index.rst
- docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
*Configuration
FIX: fixes for enabling pilotCStoJSONSynchronizer, and doc
> [v6r20] fixed upload of pilot JSON file for pilot 3

- DataManagementSystem/Client/FTSJob.py
*DMS
CHANGE: FailedSize is now BIGINT in FTSJob
CHANGE: increase the bringonline time
> [v6r19] Increase column size for FTS (mysql 5.7)

- ResourceStatusSystem/Agent/SummarizeLogsAgent.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- WorkloadManagementSystem/PilotAgent/pilotTools.py
This is a fix for pilots in v6r19p14
*WMS
FIX: SiteDirector won't set CPUTime of the pilot
FIX: convert MaxRAM inside the pilots to int
*RSS
FIX: SummarizeLogsAgent: comparison bug fix
FIX: Fixed sites synchronizer
> [v6r19] pilot: CPUTime is discovered always at runtime

- FrameworkSystem/DB/ProxyDB.py
Hi,
I think this one is fairly self-explanatory... You must get a lot of bounced e-mails to the default address :-)
Regards,
Simon
*Framework
NEW: Allow from address to be set for proxy expiry e-mails
> [v6r19] Allow setting from address in proxy expiry e-mails

- .gitignore
- Core/Base/ElasticDB.py
- Core/Utilities/ElasticSearchDB.py
- DataManagementSystem/Agent/FTS3Agent.py
- FrameworkSystem/Client/ComponentInstaller.py
- FrameworkSystem/scripts/dirac-restart-component.py
- WorkloadManagementSystem/DB/JobLoggingDB.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
- tests/Jenkins/dirac-cfg-update-server.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/install.cfg
- tests/Jenkins/utilities.sh
*Test
CHANGE: several fixes for running integration tests in Jenkins with errexit flag on
> [v6r20] Several fixes for better tests, and not only

- Core/DISET/RequestHandler.py
- requirements.txt
- tests/Performance/Service/config.cfg
- tests/Performance/Service/test_scripts/service.py
- tests/Performance/webserver/config.cfg
- tests/Performance/webserver/test_scripts/web.py
*tests
NEW: new performance based on multi-mechanize tests are added 
> [v6r20] add performance tests

- AUTHORS.rst
- README.rst
> Added authors and modified README.rst

- Core/Utilities/Time.py
- FrameworkSystem/Client/ComponentInstaller.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
*FramerworkSystem
CHANGE: convert string to number and pylint fixes
> [v6r20] convert string to number

- MonitoringSystem/DB/MonitoringDB.py
- MonitoringSystem/Service/MonitoringHandler.py
- tests/Integration/Monitoring/Test_MonitoringReporter.py
- tests/Integration/Monitoring/Test_MonitoringSystem.py
*Subsystem
FIX: the result of the query must be interpreted correctly
> [v6r20] fix elasticsearch queries

- DataManagementSystem/Service/StorageElementHandler.py
- ResourceStatusSystem/Agent/CacheFeederAgent.py
- ResourceStatusSystem/Command/AccountingCacheCommand.py
- ResourceStatusSystem/Command/CEAvailabilityCommand.py
- ResourceStatusSystem/Command/Command.py
- ResourceStatusSystem/Command/DIRACAccountingCommand.py
- ResourceStatusSystem/Command/FreeDiskSpaceCommand.py
- ResourceStatusSystem/Command/GGUSTicketsCommand.py
- ResourceStatusSystem/Command/GOCDBSyncCommand.py
- ResourceStatusSystem/Command/PilotCommand.py
- ResourceStatusSystem/Command/TransferCommand.py
- ResourceStatusSystem/Command/VOBOXAvailabilityCommand.py
- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Client/Limiter.py
- WorkloadManagementSystem/Client/WMSClient.py
- WorkloadManagementSystem/Service/MatcherHandler.py
- WorkloadManagementSystem/Service/SandboxStoreHandler.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/System/client_dms.sh
- tests/System/unitTestUserJobs.py
- tests/Utilities/testJobDefinitions.py
*RSS
FIX: Using MB as default for the size
FIX: flagged some commands that for the moment are unusable
FIX: fixed documentation of how to develop commands
*Resources
FIX: fix path for DIP SEs
*tests
FIX: fixes for parametric job submission and use SEs used
> [v6r20] Various fixes for tests and RSS

- AccountingSystem/DB/AccountingDB.py
- ConfigurationSystem/Agent/Bdii2CSAgent.py
- ConfigurationSystem/scripts/dirac-admin-add-resources.py
- Core/Utilities/ProcessMonitor.py
new version of pylint spots more "errors"
> [v6r19] pylint fixes

- AccountingSystem/DB/AccountingDB.py
- Core/Utilities/MySQL.py
- Core/Utilities/ProcessMonitor.py
- WorkloadManagementSystem/Agent/SiteDirector.py
for "errors" spotted by new pylint version
> [integration] fix pylint

- .pylintrc
- Core/Security/X509Chain.py
- FrameworkSystem/Service/MonitoringHandler.py
- FrameworkSystem/Service/SystemAdministratorHandler.py
- MonitoringSystem/Client/MonitoringReporter.py
- Resources/Computing/CREAMComputingElement.py
- Resources/Computing/GlobusComputingElement.py
- Resources/Computing/HTCondorCEComputingElement.py
- Resources/Computing/SSHComputingElement.py
- WorkloadManagementSystem/Agent/StatesMonitoringAgent.py
- WorkloadManagementSystem/Service/WMSAdministratorHandler.py
- WorkloadManagementSystem/Service/WMSUtilities.py
- releases.cfg
- tests/Integration/Monitoring/Test_MonitoringSystem.py
- tests/Jenkins/utilities.sh
- tests/System/unitTestUserJobs.py
> [v6r20] Removed last entry of glite-wms commands

- Core/scripts/dirac-install.py
*Core
NEW: install operating system on demand
> [v6r20] allow to install DIRAC OS

- ResourceStatusSystem/Agent/SummarizeLogsAgent.py
*RSS
FIX: SummarizeLogsAgent: fix when no previous history
> [v6r19] Fix for RSS SummarizeLogsAgent

- Core/Security/VOMS.py
- Core/scripts/dirac-install.py
Couple of changes for DIRACOS:
* the new voms commands are now named (voms-proxy-.*2). Don't ask why... So I am trying both
* the dirac-install is updated to keep the old behavior as default
*Core
NEW: new command name for voms proxy
FIX: dirac-install default behaviour preserved even with diracos options
> [v6r20] diracos necessary changes

- Core/Utilities/MJF.py
- WorkloadManagementSystem/JobWrapper/Watchdog.py
Added an additional mechanism, such that when the watchdog asks for wall clock seconds left, the mjf utility will also look for a shutdown time file. This can be set to be created by an acpi script when a vm is told to shutdown by the hypervisor.
*Core
New: Add additional check in MJF utility to look for a shutdown file located at '/var/run/shutdown_time'
> [v6r20] Add additional shutdown mechanism

- Core/DISET/AuthManager.py
*Core
FIX: The hardcoded rule was not taken into account when the query was coming from the web server
> [v6r20] use the correct role when the query coming from the web server

- ConfigurationSystem/Service/ConfigurationHandler.py
- Core/Security/Locations.py
- Core/Utilities/MJF.py
- Core/Workflow/Module.py
- Resources/Computing/ComputingElementFactory.py
- Resources/Storage/GFAL2_SRM2Storage.py
- Workflow/Modules/ModuleBase.py
- Workflow/Modules/Script.py
- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Agent/test/Test_Agent_WorkloadManagementSystem.py
- WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
- WorkloadManagementSystem/Utilities/PilotWrapper.py
- WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py
- WorkloadManagementSystem/private/ConfigHelper.py
- tests/Jenkins/dirac-cfg-update-server.py
*Core
FIX: MJF utility won't theow exceptions when MJF is not fully deployed at a site
*WMS
FIX: Bug fixes for SiteDirector and Pilot Wrapper
*Workflow
CHANGE: Script.py: created _exitWithError method for extension possibilities
> [v6r20] bug fixes for SiteDirector and Pilot Wrapper

- WorkloadManagementSystem/DB/PilotAgentsDB.py
CHANGE: Add Failed column to the Pilot summary 
> add missing status to the pilot summary

- StorageManagementSystem/DB/StorageManagementDB.py
All in the title.
Btw, are we finally using this release not script or not ?
*StorageManagement
FIX: buggy group by with MySQL 5.7
> [v6r19] Stager: fix a buggy group by incompatible with MySQL 5.7

- .pylintrc
- README.rst
- Workflow/Modules/ModuleBase.py
- Workflow/Modules/Script.py
- container/Dockerfile
- requirements.txt
- tests/Jenkins/dirac-cfg-update-server.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/utilities.sh
> [v6r19] Backports from v6r20

- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
*docs
CHANGE: improve the install document of WebAppDIRAC 
> documentation improvement

- Core/DISET/private/BaseClient.py
- Resources/Computing/CREAMComputingElement.py
- Resources/Computing/PoolComputingElement.py
- Resources/Computing/test/Test_PoolComputingElement.py
- WorkloadManagementSystem/private/ConfigHelper.py
> [v6r20] Several minor fixes

- ConfigurationSystem/Service/ConfigurationHandler.py
*Configuration
FIX: ConfigurationHandler - import PilotCStoJSONSynchronizer only in case of the CS master
> [v6r20] Import PilotCStoJSONSynchronizer only in case of the CS master

- DataManagementSystem/DB/FileCatalogComponents/DirectoryLevelTree.py
- ResourceStatusSystem/Utilities/CSHelpers.py
Fixing a bug introduced when escaping input path strings
*DMS
FIX: DirectoryLevelTree - fix bug when escaping input path strings
> [v6r20] FileCatalog - fix quotes after escaping input strings

- Core/DISET/private/BaseClient.py
- RequestManagementSystem/Agent/RequestOperations/ForwardDISET.py
- RequestManagementSystem/Service/ReqManagerHandler.py
- RequestManagementSystem/Service/ReqProxyHandler.py
- RequestManagementSystem/private/RequestValidator.py
- tests/Integration/RequestManagementSystem/Test_Client_Req.py
Work done with @sfayer 
*Core
CHANGE: Fixes the infamous "invalid action proposal" by speeding up the handshake and not looking up the user/group in the baseStub
RMS:
CHANGE: FowardDISET uses the owner/group of Request to execute the stub
CHANGE: owner/group of the Requests are evaluated/authorized on the server side
CHANGE: LimitedDelegation or FullDelegation are required to set requests on behalf of others -> pilot user and hosts should must them (which should already be the case)
> [v6r20] fix stub and rms

- DataManagementSystem/Utilities/DMSHelpers.py
*DMS
FIX: return None as LocalSite if an SE is at no site
> [v6r19] Fix DMSHelpers

- Core/DISET/private/BaseClient.py
- RequestManagementSystem/Agent/RequestOperations/ForwardDISET.py
- RequestManagementSystem/Service/ReqManagerHandler.py
- RequestManagementSystem/Service/ReqProxyHandler.py
- RequestManagementSystem/private/RequestValidator.py
- tests/Integration/RequestManagementSystem/Test_Client_Req.py
Backport to v6r19 of https://github.com/DIRACGrid/DIRAC/pull/3713
*Core
CHANGE: Fixes the infamous "invalid action proposal" by speeding up the handshake and not looking up the user/group in the baseStub
RMS:
CHANGE: FowardDISET uses the owner/group of Request to execute the stub
CHANGE: owner/group of the Requests are evaluated/authorized on the server side
CHANGE: LimitedDelegation or FullDelegation are required to set requests on behalf of others -> pilot user and hosts should must them (which should already be the case)
> [v6r19] Backport of stub fix

- Interfaces/API/Dirac.py
*API
NEW: running jobs locally now also works for parametric jobs. Only the first sequence will be run
FIX: running jobs locally will now properly work with LFNs in the inputSanbdox
> [v6r19] Dirac.runLocal fixes for LFNs and parametricJobs

- tests/Integration/RequestManagementSystem/Test_Client_Req.py
*RMS
FIX: fix integration tests to work with privileged and non privileged proxies
> [v6r20] RMS: fix the integration test to work with several properties

- ResourceStatusSystem/Service/PublisherHandler.py
*RSS
FIX: Fix for downtime publisher: wrong column names. Avoiding dates (not reflected in web app)
> [v6r20] Fix for downtime publisher

- RequestManagementSystem/private/RequestTask.py
- Resources/Storage/StorageElement.py
@atsareg please continue using the release not script, it works super nicely ! :-)
This fixes https://github.com/DIRACGrid/DIRAC/issues/3727
Thanks @andresailer for testing it
*DMS
FIX: use proxy location in the SECache
*RMS
FIX: use downloadVOMSProxyToFile in RequestTask
> [v6r20] Fix SE Cache

- Resources/Storage/XROOTStorage.py
- docs/source/AdministratorGuide/Resources/Storage/index.rst
*Resources
CHANGE: Add the deprecated decorator to native XROOT plugin
> [v6r20] native XROOT storage deprecated

- docs/Tools/MakeDoc.py
- docs/Tools/fakeEnvironment.py
- docs/source/fakeEnv.py
- docs/source/fakeEnvironment.py
*Docs
FIX: Fix fake environments for sqlalchemy.ext import, some code documentation pages were not build, e.g. FTS3Agent
> [v6r20] Some fixes for documentation

- TransformationSystem/Agent/TransformationCleaningAgent.py
FIX: If the result can not be evaluated, it can be converted to list
> [v6r20]handle exception when the result is not a string

- tests/Jenkins/dirac_ci.sh
*Tests
NEW: added a miniInstallDIRAC function in dirac_ci.sh, to be used for tests in Jenkins
> [v6r20] backported miniInstallDIRAC function --- for tests

- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
This solves an optimizer issue of MySQL 5.7
FIX: change the ps_delete_files and ps_delete_replicas_from_file_ids to not lock on MySQL 5.7
> [v6r20] DFC: adapt stored procedure to MySQL 5.7

- Interfaces/API/Dirac.py
*Interfaces
FIX: classmethods should not have self! (Dirac.py)
> [V6r20] Bug Fix API

- WorkloadManagementSystem/Service/JobManagerHandler.py
*WMS
FIX: JobManager - bug fix in __deleteJob resulting in exceptions 
> [v6r20] Bug fixes in JobManager

- docs/source/DeveloperGuide/WebAppDIRAC/InstallWebAppDIRAC/index.rst
*docs
FIX: Better dirac.cfg example configuration for web
> update WebAppDIRAC installation guide

- docs/Tools/GetReleaseNotes.py
*Docs
NEW: add --repo option, e.g. --repo DiracGrid/DiracOS, or just --repo DiracOS, fixes DIRACGrid/DIRACOS#30
```
$ ./GetReleaseNotes.py  -r DIRACGRID/diracos --branches=master --openPRs
[master]
NEW: (#29) requirements.txt copied from DIRAC
CHANGE: (#29) allow to have pipRequirements a URL or a file
```
> [v6r20] GetReleaseNotes: add --repo option

- Core/scripts/dirac-install.py
- tests/Jenkins/dirac_ci.sh
- tests/Jenkins/utilities.sh
*Tests
NEW: allow to install DIRACOS if DIRACOSVER env variable is specified
> [v6r20] CI: allow to install DIRACOS if DIRACOSVER env variable is specified

- Core/Utilities/DErrno.py
- Core/Utilities/Glue2.py
- DataManagementSystem/Client/DataManager.py
- ResourceStatusSystem/Utilities/InfoGetter.py
- ResourceStatusSystem/scripts/dirac-rss-query-db.py
- WorkloadManagementSystem/Service/JobManagerHandler.py
- WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
*RSS
CHANGE: Added a post-processing function in InfoGetter, for handling special case of FreeDisk policies
*WMS
FIX: corrected inconsistent option name for pilotFileServer CS option
> [v6r20] corrected inconsistent option name for pilotFileServer CS option, and other minor fixes

- WorkloadManagementSystem/Agent/StalledJobAgent.py
*WMS
FIX: StalledJobAgent: fix "Proxy not found" error when sending kill command to stalled job, fixes #3783 
> [v6r20] StalledJobAgent: delegate WMSClient to jobOwner, fixes "No proxy found" error

- Core/Utilities/ProcessPool.py
- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- DataManagementSystem/Client/FTS3Client.py
- DataManagementSystem/DB/FTS3DB.py
- DataManagementSystem/Service/FTS3ManagerHandler.py
- RequestManagementSystem/Client/ReqClient.py
*DMS
FIX: add a protection against race condition between RMS and FTS3 
> [v6r20] FTS3: add a protection against race condition between RMS and FTS3

- ConfigurationSystem/Client/CSAPI.py
- ConfigurationSystem/Client/VOMS2CSSynchronizer.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Registry/index.rst
Replaces https://github.com/DIRACGrid/DIRAC/pull/3780
For CS/Registry section: I added the possibility to define an "QuarantineGroup": this option can be used to specify a group name that acts as an alternative default VO group, and to which users would normally be added by hand (maybe as "punishment", like, for LHCb case, the "low priority group"). If a user is added there (and, in theory, removed from the "DefaultGroup"), then it won't be added back to the Default group.
Here I have put the doc for the new CS option in the "old" place, until we finally decide what to do.
*CS
NEW: for CS/Registry section: added possibility to define a QuarantineGroup per VO
> [v6r20] Quarantine vo group

- TransformationSystem/Agent/test/Test_Agent_TransformationSystem.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/test/Test_Client_TransformationClient.py
- TransformationSystem/Client/test/Test_Client_TransformationSystem.py
- TransformationSystem/Client/test/Test_Client_WorkflowTasks.py
- requirements.txt
*TS
FIX: better tests for TS agents
> [v6r20] just better tests for TS agents

- DataManagementSystem/Agent/FTS3Agent.py
- DataManagementSystem/DB/FTS3DB.py
- DataManagementSystem/Service/FTS3ManagerHandler.py
*DMS
CHANGE: reuse of the ThreadPool in the FTS3Agent in order to optimize the Context use
> [v6r20] FTS3: reuse ThreadPools in the FTS3Agent

- Workflow/Modules/test/Test_Modules.py
- WorkloadManagementSystem/Client/test/Test_Client_WorkloadManagementSystem.py
- WorkloadManagementSystem/DB/JobDB.py
- WorkloadManagementSystem/DB/TaskQueueDB.py
- docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst
- tests/Integration/WorkloadManagementSystem/inputsandbox/helloWorld.xml
*WMS
FIX: Removed legacy "SystemConfig" and "LHCbPlatform" checks
> [v6r20] Removed some legacy code

- Core/Utilities/ElasticSearchDB.py
*Subsystem
NEW: Add method which allows for deletion by query in ElasticSearch
> [v6r20] Add method which allows for deletion by query in ElasticSearch

- Core/Workflow/Utility.py
- Interfaces/API/Job.py
- Resources/Computing/CREAMComputingElement.py
- Resources/Computing/ComputingElement.py
- Resources/Computing/HTCondorCEComputingElement.py
- Resources/Computing/SSHBatchComputingElement.py
- Resources/Computing/glexecComputingElement.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Agent/SiteDirector.py
The only real fix is in SiteDirector, the other fixes are only stylistic ones
*WMS
FIX: bug fix: missing loop on pRef in SiteDirector
> [v6r20] Fix pilots accounting report for HTCondor CEs

- Core/Utilities/ElasticSearchDB.py
- RequestManagementSystem/Client/File.py
> [v7r0] bug fix after merge of v6r20 branch

- TransformationSystem/Agent/TaskManagerAgentBase.py
This is really a bug fix
*TS
FIX: checking return value of jobManagerClient.getMaxParametricJobs() call
> [v6r20] Fix for WorkflowTaskAgent and parametric jobs

- Core/Utilities/Proxy.py
- DataManagementSystem/Client/FileCatalogClientCLI.py
*DMS
FIX: FileCatalogCLI: print error message when removeReplica encounters weird return value
> [v6r20] minor fixes

- DataManagementSystem/Agent/FTS3Agent.py
*DMS
CHANGE: FTS3Agent: set pool_size of the FTS3DB
> [v6r20] FTS3Agent: set pool_size of the FTS3DB

- Core/Security/VOMSService.py
- Workflow/Utilities/Utils.py
*Core
FIX: VOMSService.py: better logging and error prevention
> [v6r20] VOMSService.py: better logging and error prevention

- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Client/SiteStatus.py
- ResourceStatusSystem/Utilities/RssConfiguration.py
- docs/source/AdministratorGuide/Systems/ResourceStatus/advanced_configuration.rst
- docs/source/AdministratorGuide/Systems/ResourceStatus/install.rst
- docs/source/AdministratorGuide/Systems/Transformation/index.rst
*RSS
FIX: Documentation update
> [v6r20] Update on RSS documentation

- Core/Utilities/SiteSEMapping.py
- ResourceStatusSystem/Command/AccountingCacheCommand.py
- ResourceStatusSystem/Command/FreeDiskSpaceCommand.py
- ResourceStatusSystem/Command/TransferCommand.py
- ResourceStatusSystem/Service/PublisherHandler.py
- ResourceStatusSystem/Utilities/CSHelpers.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- ResourceStatusSystem/scripts/dirac-rss-sync.py
*RSS
CHANGE: For some info, use DMSHelper instead of CSHelper for better precision
> [v6r20] RSS fixes: using DMSHelper instead of CSHelper

- Interfaces/API/test/Test_JobAPI.py
- Interfaces/API/test/testWF.jdl
- Interfaces/API/test/testWF.xml
- Interfaces/API/test/testWFSIO.jdl
- docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst
*Docs
NEW: Added some info on parametric jobs
> [v6r20] Added some info on parametric jobs (and better test)

- FrameworkSystem/Client/NotificationClient.py
- WorkloadManagementSystem/Client/JobMonitoringClient.py
- WorkloadManagementSystem/Client/PilotsLoggingClient.py
*Framework
FIX: added setServer for NotificationClient
*WMS
FIX: late creation on RPC in JobMonitoringClient and PilotsLoggingClient
> [v6r20] bugfix: setServer for NotificationClient

- Interfaces/API/Dirac.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/scripts/dirac-admin-show-task-queues.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
> [v6r20] using Clients instead of RPCClient

- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/Agent/test/Test_Agent_SiteDirector.py
- WorkloadManagementSystem/DB/JobDB.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst
- docs/source/AdministratorGuide/GettingStarted/Step 1/index.rst
- docs/source/AdministratorGuide/InstallingDIRACService/index.rst
- docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
- docs/source/AdministratorGuide/SystemAdministratorInterface/index.rst
- docs/source/AdministratorGuide/Systems/Accounting/index.rst
- docs/source/AdministratorGuide/Systems/Framework/Monitoring/index.rst
- docs/source/AdministratorGuide/Systems/Transformation/index.rst
- docs/source/AdministratorGuide/Systems/WorkloadManagement/Jobs/index.rst
- docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/index.rst
- docs/source/DeveloperGuide/DevelopmentModel/DIRACProjects/index.rst
- docs/source/DeveloperGuide/Systems/Transformation/index.rst
- docs/source/UserGuide/GettingStarted/InstallingClient/index.rst
- docs/source/UserGuide/Tutorials/ClientInstallation/index.rst
- docs/source/UserGuide/Tutorials/ManagingUserCredentials/index.rst
*WMS
CHANGE: the platform discovery can be VO-specific. 
> [v6r20] Using ObjectLoader for platform discovery

- ResourceStatusSystem/Service/PublisherHandler.py
- ResourceStatusSystem/Utilities/CSHelpers.py
*RSS
FIX:  site may not have any SE
> [v6r20] bug fix: site may not have any SE

- Interfaces/API/Job.py
- TransformationSystem/Client/TaskManager.py
- TransformationSystem/Client/test/Test_Client_WorkflowTasks.py
@andresailer you better check this one
*Interfaces
CHANGE: setParameterSequence always return S_OK/S_ERROR
*TS
FIX: check for return value on Job interface and handle it
> [v6r20] [ALERT] better handling of return values (API and TaskManager)

- Core/scripts/dirac-create-distribution-tarball.py
*Core: Add tests directory to the tar file and fix pylint warnings.
CHANGE: explanation
> [v6r20] add tests directory to the distributed tar and pylint

- ConfigurationSystem/Client/Helpers/Resources.py
- ResourceStatusSystem/Client/ResourceStatus.py
- ResourceStatusSystem/Client/SiteStatus.py
- ResourceStatusSystem/Command/AccountingCacheCommand.py
- ResourceStatusSystem/Command/JobCommand.py
- ResourceStatusSystem/Command/PilotCommand.py
- ResourceStatusSystem/Command/TransferCommand.py
- ResourceStatusSystem/Service/PublisherHandler.py
- ResourceStatusSystem/Utilities/CSHelpers.py
- ResourceStatusSystem/Utilities/RssConfiguration.py
- ResourceStatusSystem/Utilities/Synchronizer.py
- docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Sites/index.rst
- tests/Jenkins/dirac-cfg-add-option.py
- tests/Jenkins/dirac-cfg-update-server.py
- tests/System/rss-scripts.sh
Fixing bug https://github.com/DIRACGrid/DIRAC/issues/3869
*RSS
CHANGE: deprecated CSHelpers.getSites() function
*Test
CHANGE: Enable RSS in Jenkins
> [v6r20] Enabling RSS in Jenkins

- Core/Base/AgentModule.py
- Core/Utilities/Shifter.py
- FrameworkSystem/DB/ProxyDB.py
- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-admin-get-pilot-info.py
- Interfaces/scripts/dirac-dms-lfn-metadata.py
- Interfaces/scripts/dirac-framework-ping-service.py
- Interfaces/scripts/dirac-wms-job-logging-info.py
- Interfaces/scripts/dirac-wms-job-peek.py
- TransformationSystem/Agent/TaskManagerAgentBase.py
- TransformationSystem/Agent/WorkflowTaskAgent.py
- TransformationSystem/ConfigTemplate.cfg
- WorkloadManagementSystem/Service/JobManagerHandler.py
- docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst
- docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst
- tests/Jenkins/dirac-test-job.py
- tests/Performance/DFCPerformance/submitJobs.py
- tests/Utilities/testJobDefinitions.py
- tests/Workflow/Regression/helloWorld.py
*Interfaces
CHANGE: marked deprecated some API functions (perfect replace exists already, as specified)
> [v6r20] Several minor fixes 

- Interfaces/API/Job.py
- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Utilities/ParametricJob.py
*TS
FIX: fixed submission of parametric jobs with InputData from WorkflowTask
FIX: better logging for parametric jobs submission
> [v6r20] fixed submission of parametric jobs with InputData (from WorkflowTaskAgent)

- Core/Base/API.py
- Interfaces/API/Dirac.py
- Interfaces/API/Job.py
- WorkloadManagementSystem/Client/SandboxStoreClient.py
- docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst
- tests/Integration/WorkloadManagementSystem/Test_SandboxStoreClient.py
For https://github.com/DIRACGrid/DIRAC/issues/3866
*Subsystem
CHANGE: Returning file location in output of getOutputSandbox
> [v6r20] Returning file location in output of getOutputSandbox

- ConfigurationSystem/Client/Helpers/Resources.py
- Core/scripts/dirac-create-distribution-tarball.py
This fixes the merge conflict markers left over from the last merge into integration
> [v7] dirac-create-distribution-tarball: fix merge conflict markers

- ConfigurationSystem/Client/LocalConfiguration.py
- Core/Base/Script.py
- ResourceStatusSystem/Agent/ElementInspectorAgent.py
- ResourceStatusSystem/ConfigTemplate.cfg
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/Integration/WorkloadManagementSystem/Test_SandboxStoreClient.py
*Core
CHANGE: Script.parseCommandLine: the called script is not necessarily the first in sys.argv 
> [v6r20] Better argument parsing 

- ConfigurationSystem/Client/Helpers/Registry.py
Added oAuth2 type authontification to web portal
*ConfigurationSystem 
CHANGE: /Client/Helpers/Registry.py: Added search dirac user for ID and CA
> [v6r20] Added oAuth2 type authontification to webapp

- MonitoringSystem/Client/MonitoringReporter.py
FIX: mqProducer field in MonitoringReporter can be set to None, and the comparision was broken. It is fixed. Also some additional checks are added.
> [v6r20] Fix checks of possibly None object and add some error handling messages

- Interfaces/API/Dirac.py
- WorkloadManagementSystem/Agent/JobAgent.py
*WMS
CHANGE: removed confusing Job parameter LocalBatchID
> [v6r20] removed confusing Job parameter LocalBatchID

- DataManagementSystem/Agent/RequestOperations/StagingCallback.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Agent/JobCleaningAgent.py
- WorkloadManagementSystem/Agent/OptimizerModule.py
- WorkloadManagementSystem/Agent/StalledJobAgent.py
- WorkloadManagementSystem/Client/DownloadInputData.py
- WorkloadManagementSystem/Client/InputDataByProtocol.py
- WorkloadManagementSystem/Client/JobReport.py
- WorkloadManagementSystem/Client/JobStateUpdateClient.py
- WorkloadManagementSystem/Executor/test/Test_Executor.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/JobWrapper/Watchdog.py
- tests/Integration/DataManagementSystem/Test_Client_DFC.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
- tests/Integration/WorkloadManagementSystem/Test_TaskQueueDB.py
Also includes some test fixes.
*WMS
CHANGE: Using JobStateUpdateClient instead of RPCClient to it
CHANGE: Using JobManagerClient instead of RPCClient to it
> [v6r20] Using clients instead of RPCClients

- ConfigurationSystem/Client/PathFinder.py
- Core/DISET/private/BaseClient.py
- Core/Utilities/Subprocess.py
- ResourceStatusSystem/scripts/dirac-rss-set-token.py
- WorkloadManagementSystem/PilotAgent/pilotCommands.py
*Core
FIX: more debug messages in BaseClient
*RSS
FIX: fixed bug in dirac-rss-set-token script
> [v6r20] Just a bit more debug messages

- Core/Utilities/DErrno.py
- Core/Utilities/ObjectLoader.py
- Interfaces/API/Job.py
- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- WorkloadManagementSystem/Agent/SiteDirector.py
- WorkloadManagementSystem/DB/JobDB.py
- WorkloadManagementSystem/Executor/JobScheduling.py
- __init__.py
Also the usual autopep8
*Core
FIX: ObjectLoader returns Derrno code
*WMS
FIX: SiteDirector: using checkPlatform flag everwhere needed 
> [v6r20] Some fixes for SiteDirector

- Core/Utilities/ObjectLoader.py
> [v7r0] fix bad merge

- Core/DISET/private/BaseClient.py
- WorkloadManagementSystem/Agent/JobAgent.py
- WorkloadManagementSystem/Agent/JobCleaningAgent.py
- WorkloadManagementSystem/Agent/StalledJobAgent.py
- WorkloadManagementSystem/Client/DownloadInputData.py
- WorkloadManagementSystem/Client/JobReport.py
- WorkloadManagementSystem/JobWrapper/JobWrapper.py
- WorkloadManagementSystem/JobWrapper/Watchdog.py
...just bug fixes, no need to release notes.
> [v6r20] Various fixes

- Core/DISET/ServiceReactor.py
- Core/DISET/private/TransportPool.py
- Core/DISET/private/Transports/BaseTransport.py
- Core/DISET/private/Transports/SSL/SocketInfoFactory.py
- docs/source/AdministratorGuide/scalingAndLimitations.rst
Fixes https://github.com/DIRACGrid/DIRAC/issues/3905 
tested in LHCb prod environment
*Core
FIX:  always close the socket even in case of exception
> [v6r20] Core: always close the socket even in case of exception

- FrameworkSystem/Service/NotificationHandler.py
Fixed SMTPServer to SMTP
*FrameworkSystem/Service/NotificationHandler.py
FIX: Changed SMTPServer to SMTP
> [v6r20] Fixed SMTPServer to SMTP

- DataManagementSystem/Client/FTS3Operation.py
- Resources/Storage/StorageElement.py
- Resources/Storage/test/Test_StorageElement.py
- TransformationSystem/Client/Utilities.py
Part of https://github.com/DIRACGrid/DIRAC/issues/3908
@phicharp can you have a look please ? 
*Resources
NEW: Add isSameSE method to StorageElement which works for all protocols
CHANGE: use SE.isSameSE
> [v6r20] Add isSameSE method to StorageElement 

- docs/source/DeveloperGuide/AddingNewComponents/DevelopingServices/index.rst
Fix example for calling the example service
See: https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/bZTPQD2SPFw
> [v6r20] Docs: DeveloperGuide, fix example for calling service

- .travis.yml
- docs/source/AdministratorGuide/DIRACSites/ComputingElements/index.rst
- docs/source/AdministratorGuide/DIRACSites/StorageElements/index.rst
- docs/source/AdministratorGuide/DIRACSites/index.rst
- docs/source/AdministratorGuide/Systems/WorkloadManagement/architecture.rst
- requirements.txt
*docs
NEW: more doc on WMS and Sites in DIRAC
> [v6r20] doc on WMS and Sites in DIRAC

- WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
*WMS
FIX: MutiProcessorSiteDirector: get platform is checkPLatform flag is true
> [v6r20] Fix for platform check

- AccountingSystem/Client/Types/Job.py
- Resources/MessageQueue/MQCommunication.py
*Accounting
CHANGE: Change the columns size of the FinalMinorStatus
*Resources
CHANGE: When crating a consumer or producer then the error message must be handled by the caller.
> [v6r21] remove error messages and extend column size of FinalMinorStatus

- Core/scripts/dirac-install.py
*CORE
CHANGE: backport dirac-install inorder to support diracps
> [v6r21] backport dirac-install in order to support diracos

- Core/scripts/dirac-install.py
- Resources/MessageQueue/MQCommunication.py
*Core
CHANGE: source diracosrc to set PYTHONPATH and LD_LIBRARYPATH
*Resources
CHANGE: remove error logging from MQCommunication 
> [v7r0] fix wrong merge and remove error logging from MQ

- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-wms-job-parameters.py
- WorkloadManagementSystem/Agent/JobCleaningAgent.py
- WorkloadManagementSystem/Agent/test/Test_Agent_JobCleaningAgent.py
- WorkloadManagementSystem/Client/JobState/CachedJobState.py
- WorkloadManagementSystem/Client/JobState/JobState.py
- WorkloadManagementSystem/DB/JobDB.py
- WorkloadManagementSystem/Executor/Base/OptimizerExecutor.py
- WorkloadManagementSystem/Executor/InputData.py
- WorkloadManagementSystem/Executor/JobSanity.py
- WorkloadManagementSystem/Executor/JobScheduling.py
- WorkloadManagementSystem/Service/JobMonitoringHandler.py
- tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
*WMS
NEW: JobDB: getJobParameters work also with list on job IDs
CHANGE: JobCleaningAgent queries for job parameters in bulk
CHANGE: Optimizers only set optimizers parameters (backported from v7r0)
> [v6r21] Speedup job cleaning and not only

- Resources/Computing/BatchSystems/Condor.py
- Resources/Computing/BatchSystems/GE.py
- Resources/Computing/BatchSystems/LSF.py
- Resources/Computing/BatchSystems/OAR.py
- Resources/Computing/BatchSystems/SLURM.py
- Resources/Computing/BatchSystems/Torque.py
- Resources/Computing/SSHComputingElement.py
There is a case of a rather specific environment setting necessary before submission of a job to the local batch system. This PR solves the issue and is generic enough to accommodate future possible needs of this kind.
*Resources
NEW: SSHComputingElement - added Preamble option to define a command to be executed right before the batch system job submission command
> [v6r21] Preamble option for the SSHComputingElement

- ConfigurationSystem/Client/Helpers/Resources.py
- FrameworkSystem/private/standardLogging/Logging.py
- Resources/LogFilters/ModuleFilter.py
- Resources/LogFilters/PatternFilter.py
- Resources/LogFilters/test/Test_PatternFilter.py
- docs/Tools/MakeDoc.py
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst
*Resources
NEW: Added the possibility to add filters to log backends to refine the output shown/stored
NEW: Resources.LogFilters.ModuleFilter: Filter that allows one to set the LogLevel for individual modules
NEW: Resources.LogFilter.PatternFilter: Filter to select or reject log output based on words
> [v6r21] logging filter

- MonitoringSystem/DB/test/Test_monitoringdb.py
- MonitoringSystem/private/DBUtils.py
CHANGE: Change the bucket size from week to day. 
> [v6r21] change the bucket size

- Core/scripts/dirac-install.py
*Core
FIX: Change DiracOS to DIRACOS
> [v7r0] change DiracOS to DIRACOS

- Resources/Computing/PoolComputingElement.py
*Resources
FIX: PoolComputingElement - bug fix: initialize process pool if not yet done in getCEStatus()
> [v6r21] PoolCE bug fix

- WorkloadManagementSystem/DB/TaskQueueDB.py
- tests/Integration/WorkloadManagementSystem/Test_TaskQueueDB.py
*WMS
FIX:  fixed Banned Sites matching in TaskQueueDB
> [v6r21] fixed Banned Sites matching

- WorkloadManagementSystem/Agent/OptimizerModule.py
- WorkloadManagementSystem/DB/JobDB.py
* WMS
FIX: when an optimiser agent was instantiating JobDB (via the base class) and the machine was overloaded, the connection to the DB failed but this was not noticed and the agent was not working until restarted after max cycles. Now testing JobDB  is valid in OptimizerModule base class and exit if not valid. Eventually this should be using exceptions...
CHANGE: streamlining code in OptimizerModule. Also pep8 formatting (ignore white spaces for reviewing)
> [v6r21] Fix problem when not being able to instantiate JobDB

- DataManagementSystem/private/FTS3Utilities.py
*DMS
FIX: respect the source limitation when picking source for an FTS transfer
> [v6r21] Respect the allowedSources in FTS3 source selection

- DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
- WorkloadManagementSystem/Agent/OptimizerModule.py
- WorkloadManagementSystem/DB/JobDB.py
*DMS
FIX: check missing file with another string
> [v6r21] Small fix in ReplicateAndRegister

- Core/scripts/dirac-install.py
*CORE
NEW: dirac-install if DIRACOS already installed and DIRACOS is not requested, it will force to install it
> [v6r21] force using diracos, if it is already installed

- Interfaces/API/Dirac.py
- Interfaces/scripts/dirac-wms-job-get-output-data.py
*Interfaces
FIX: return value of getJobParameters changed
> [v6r21] fix: return value of getJobParameters changed

- WorkloadManagementSystem/Client/InputDataResolution.py
This is then consistent with the Remote plugins
*WMS
FIX:  Local protocols are retrieved as a list in InputDataResolution
> [v6r21] WMS: Local protocols are retrieved as a list in InputDataResolution

- ConfigurationSystem/Client/Utilities.py
- ConfigurationSystem/scripts/dirac-admin-add-resources.py
- ConfigurationSystem/scripts/dirac-admin-add-shifter.py
- ConfigurationSystem/scripts/dirac-admin-add-site.py
- ConfigurationSystem/scripts/dirac-admin-bdii-info.py
- ConfigurationSystem/scripts/dirac-configuration-cli.py
- ConfigurationSystem/scripts/dirac-configuration-dump-local-cache.py
*Configuration
FIX: BDII2CSAgent: fix for CEs with incomplete BDII info
> [v6r21] BDII2CSAgent: fix for CEs with incomplete BDII info

- WorkloadManagementSystem/Agent/StalledJobAgent.py
- WorkloadManagementSystem/DB/JobDB.py
- WorkloadManagementSystem/Service/JobMonitoringHandler.py
*WMS
FIX: JobMonitoring.getJobParameter cast to int
> [v6r21] Simple fix for JobMonitoring.getJobParameter

- TransformationSystem/Client/TaskManager.py
- WorkloadManagementSystem/Service/PilotsLoggingHandler.py
- WorkloadManagementSystem/scripts/dirac-admin-pilot-logging-info.py
- WorkloadManagementSystem/scripts/dirac-admin-show-task-queues.py
- WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py
*TS
FIX: when a site was requested inside the job workflow description, and BulkSubmission was used, such site was not considered.
> [v6r21] fix for bulk submission

- .travis.yml
- codecov.yml
- requirements.txt
Call codecov at the end pytest and disable comments on PR
> [v6r21]Codecov setup

- requirements.txt
> v6r21 - fixing versions for travis

- Resources/MessageQueue/StompMQConnector.py
- docs/source/AdministratorGuide/InstallingDIRACService/index.rst
Fix inconsistent header use, order of (=-^ etc.) needs to be consistent inside each file
Fix two links with RPM (add second underscore)
bullet lists do not need indentation
use double ticks for emphasis
use note block
Ps: someone needs to fix that elasticsearch error
> [v6r21] Docs: installingDiracServices: fix sphinx warnings, improve syntax

- docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst
*Docs
CHANGE: Add magic runs to setup DIRAC in example scripts, so they work out of the box.
> [v6r21] Add magic runes to make scripts work with DIRAC to the examples

- DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
it so happens that by default, transactions are useless in stored procedure :-)
So fix that by adding handlers. This passes the integration tests and is running in prod for LHCb
*DMS
FIX: add exit handler for stored procedure
> [v6r21] DFC: add exit handler for stored procedure

- ConfigurationSystem/Client/ConfigurationData.py
- ConfigurationSystem/Client/Helpers/CSGlobals.py
- ConfigurationSystem/Client/Helpers/Local.py
- ConfigurationSystem/Client/Helpers/Path.py
- ConfigurationSystem/Client/Helpers/Registry.py
- ConfigurationSystem/Client/Helpers/ResourcesDefaults.py
- ConfigurationSystem/Client/Utilities.py
- ConfigurationSystem/private/ConfigurationData.py
- Core/scripts/dirac-configure.py
The only real change is in dirac-configure, `setServer` function.
*Configuration
CHANGE:  dirac-configure: forcing update (override, in fact) of CS list
> [v6r21] dirac-configure: forcing update (override, in fact) of CS list

- Core/Utilities/SiteCEMapping.py
- ResourceStatusSystem/PolicySystem/Actions/BaseAction.py
- ResourceStatusSystem/PolicySystem/Actions/EmailAction.py
- ResourceStatusSystem/PolicySystem/Actions/LogPolicyResultAction.py
- ResourceStatusSystem/PolicySystem/Actions/LogStatusAction.py
- ResourceStatusSystem/PolicySystem/Actions/SMSAction.py
- ResourceStatusSystem/PolicySystem/Actions/__init__.py
*RSS
FIX: fix reporting from EmailAgent
> [v6r21] RSS FIX: fix reporting from EmailAgent

- MonitoringSystem/Client/MonitoringReporter.py
- Resources/MessageQueue/StompMQConnector.py
- tests/Integration/Resources/MessageQueue/Test_ActiveClose.py
As suggested by Chris this removes the infinite loop due to
disconnect/reconnect sequences.
*Resources/MessageQueue
FIX: Remove infinite loop bug caused by the ReconnectListener.
> [v6r21]Add remove ReconnectListener in disconnect

- docs/source/AdministratorGuide/centralizedLogging.rst
- docs/source/AdministratorGuide/index.rst
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/Backends/index.rst
- docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst
*Docs
NEW:  document centralized logging with ELK stack
> [v6r21] Docs: document centralized logging with ELK stack

- docs/source/AdministratorGuide/index.rst
- docs/source/AdministratorGuide/pitExport.rst
@iueda @hmiyake  once this is merge, maybe you could add a few lines about your setup here too ? 
*Docs
NEW: document methods for pit export
> [v6r21] Document pit export
