DataManagementSystem/Client/FileCatalogClientCLI.py

Just enable the posibility to print only the directories that contain files with matching metaData.
As there is no fileCatalog function to get folders By metadata (right?), I create a set of directories by slicing the filename at the end.

[v6r11] FileCatalogCLI: add new -D flag for find to print only directories

---

DataManagementSystem/Agent/FTSAgent.py
RequestManagementSystem/Agent/RequestExecutingAgent.py
RequestManagementSystem/Client/ReqClient.py
RequestManagementSystem/private/RequestTask.py

This PR adds 2 options to the ReqClient.putRequest:
* useFailoverProxy : by default to True. If set to False, we will not try to send the Request to ReqProxy in case of failure on the RequestHandler. This is useful in the RequestExecutingAgent
* retryMainServer : in case the putRequest on the main RequestHandler fails, we retry that amount of time

[v6r13] Add options to ReqClient.putRequest

---

DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py
DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py

FIX: FileCatalog - exists() method returns the LFN name instead of boolean True if the LFN is already present in the catalog
This PR replaces #2232

[v6r11] DFC exists() return value

---

ConfigurationSystem/private/Refresher.py
DataManagementSystem/DB/FileCatalogComponents/DirectoryLevelTree.py
DataManagementSystem/DB/FileCatalogComponents/FileManager.py
DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py
DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/DirectoryClosure.py
DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/FileManagerPs.py
DataManagementSystem/DB/FileCatalogDB.py
DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
DataManagementSystem/DB/test/TestFileCatalogDB.py
DataManagementSystem/Service/FileCatalogHandler.py
DataManagementSystem/scripts/dirac-dms-resolve-guid.py
Resources/Catalog/FileCatalog.py
Resources/Catalog/LcgFileCatalogClient.py

!!! IMPORTANT !!! The major change here is that the DFC.exists method behaves now like the LFC.exists method : 
if the GUID is given to the exists call together with the LFN, and if UniqueGUID is True, we will check whether the GUID already exists. If yes, we return the LFN to which it is associated. Note that the overall mechanism has a bit strange behavior, but that is what you end up with if you have two unique identifiers for one entity... anyway, it is now the same behavior as the LFC, and this was needed because the DM.putAndRegister does not behave the same depending on whether fc.exists or fc.addFile fails.

[v6r12] certif dfc 2

---

ConfigurationSystem/Client/Helpers/Operations.py
Core/Utilities/SiteSEMapping.py
TransformationSystem/Agent/TaskManagerAgentBase.py
TransformationSystem/Agent/TransformationAgent.py
TransformationSystem/Agent/TransformationPlugin.py
TransformationSystem/Client/Plugins.py
TransformationSystem/Client/TaskManager.py
TransformationSystem/Client/TaskManagerPlugin.py
TransformationSystem/Client/test/test_Client.py

I added a task manager plugins mechanism. I introduced a base plugin class simply named "Plugins" and "TransformationPlugins" inherits from it. Also the new "TaskManagerPlugin" inherits from it. The method "generateTasks" has been renamed simply "run" (this may affect extensions, we need to pay attention to that). 
The plugins for TaskManager are 2, and define how the list of destination sites is created: "BySE" and "ByJobType". By default nothing changes, as for using a plugin that is not "BySE" VOs need to explicitely set a CS entry (/Operations/<Setup>/Transformations/DestinationPlugin) and at the moment the value can only be "ByJobType" other then "BySE". 
If "ByJobType" is selected, the CS section "JobTypeMapping" in Operations have to be present. A list of exclusions and allowance …

[v6r14] Task manager plugins

---

RequestManagementSystem/Client/File.py
RequestManagementSystem/Client/Operation.py
RequestManagementSystem/DB/RequestDB.py

There was a small bug making that the request would always show the current time for LastUpdate. Also, if the Operation was Scheduled, and some files move from Scheduled to Done but not all, the timestamp of the operation would not change. Now it does :-) Same goes from Operation to Request

[v6r12] LastUpdate was not always correct

---

RequestManagementSystem/Client/ReqClient.py
RequestManagementSystem/Client/Request.py

This was a temporary patch for getting failover transfers done.
We forgot to remove it when all requests have been completed...

[v6r12] stop optimizing requests already in the DB

---

DataManagementSystem/Client/FileCatalogClientCLI.py
DataManagementSystem/DB/FileCatalogDB.py
DataManagementSystem/Service/FileCatalogHandler.py
Resources/Catalog/FileCatalog.py
Resources/Catalog/FileCatalogClient.py

CHANGE: FileCatalog - replace getDirectoryMetadata by getDirectoryUserMetadata
NEW: FileCatalog - added new getDirectoryMetadata() interface to get standard directory metadata

[v6r13] Added getDirectoryMetadata to the DFC interface

---

DataManagementSystem/Client/DataManager.py
DataManagementSystem/scripts/dirac-dms-remove-catalog-files.py
DataManagementSystem/scripts/dirac-dms-remove-catalog-replicas.py
RequestManagementSystem/Client/Operation.py
RequestManagementSystem/Client/Request.py

This fix is necessary because LHCb has more than one catalog and some files are only registered in the DFC and not in the LFC (sandboxes).

[v6r12] make successful removeReplica if missing in one catalog

---

Core/DISET/private/BaseClient.py
Core/DISET/private/SSLSocketFactory.py
Core/DISET/private/Transports/SSL/SocketInfo.py

This just enables TLSv1 for outgoing connections via suds (mainly to connect to VOMS admin/whatever servers). DIRAC connections were already TLSv1

[v6r11-onwards]CHANGE: Force use of TLSv1 from the client side

---

Core/LCG/GOCDBClient.py
ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py

Instead of using HOSTNAME, which could lead to ignore downtime elements

[v6r12] GOCDBClient creates unique DowntimeID using the ENDPOINT

---

DataManagementSystem/Client/FileCatalogClientCLI.py
DataManagementSystem/Client/MetaQuery.py
DataManagementSystem/DB/FileCatalogComponents/FileMetadata.py
Resources/Catalog/FileCatalog.py

Possibility to use standarda metadata fields for queries: time stamps, User, Group, Name, Size, Status, GUID, CheckSum. Possibility to use '*' wild card in the string meta values. Example:
dfind . "SE=IN2P3-disk Name='*.bmp' CreationDate>'2015-01-01' Size<1000000"
NEW: FileMetadata, MetaQuery, FileCatalogClientCLI - added possibility to search for files by standard metadata

[v6r13] FileCatalog - finding files by standard metadata

---

WorkloadManagementSystem/PilotAgent/pilotCommands.py

On SLC5 the native python is 2.4 with no json module available
FIX: pilotCommands.py - import json module just in case it is needed

[v6r12] pilotCommands fix 

---

Core/Security/X509Request.py

Required when using Externals v6r3
Same as #2305 but targeting v6r13

[v6r13] FIX: Sign x509 requests before sending them down the wire

---

Resources/Computing/remote_scripts/sshce

Do not grep by user as on some platforms ps truncates the user name (on fedora 20, dirac_user becomes dirac_u+ and that grep fails). Normally, a process name should be unique...
Also the wc returns more than 1 line on some platforms (again fedora 20 returns column headers always).

[v6r12] Try to not remove the pid files to prevent bad scheduling

---

Resources/Computing/ARCComputingElement.py

The 'GridEnv' string may not be defined and hence a call to _reset causes crashes in the WMSAdministrator when trying to get the pilot stdout.

[v6r13] Bug fix to prevent crashes

---

DataManagementSystem/Client/DataManager.py
Resources/Storage/SRM2Storage.py
WorkloadManagementSystem/private/correctors/WMSHistoryCorrector.py

FIX: WMSHistoryCorrector - explicit error if no data returned from the WMSHistory Accounting
FIX: DataManager - when replicate files, the file size should be zero ( indicating file upload ) if replication through a local cache - logic to be reviewed in the next release anyway

[v6r12] Several fixes

---

Resources/Storage/GFAL2_StorageBase.py
Resources/Storage/GFAL2_XROOTStorage.py

* Cleand up \__init__: removed unused member variables
* __putSingleFile checks the origin of the source file whether it's local or from and srm or root storage. 
* Moved unrelated code out of try/except (__getSingleMetadata and __listSingleDirectory)
* __getChecksum needs a checksum set by the SE (set as self.checksumType) otherwise the checksum entry in the metadata will be empty
* Cleaned up \__init__: removed unused member variables
* Added a _getExtendedAttributes method until gfal2-plugin-xrootd version 0.4 is available. Added hard coded list of extended attributes because plugin returns a wrong list

[v6r13] Fixes for the GFAL2StorageBase and GFAL2_XROOTStorage plugin

---

Core/Utilities/InstallTools.py
FrameworkSystem/Client/SystemAdministratorClientCLI.py

The monitoring system now uses UTC times instead of the local ones.
Also, the InstalledComponentsDB no longer attempts to  add an entry to itself by calling the ComponentMonitoring service ( which is always installed AFTER the DB ). Instead, said service will add the entry along with its own upon installation.

[v6r13] Minor fixes to static monitoring

---

FrameworkSystem/ConfigTemplate.cfg

Read-only methods in the ComponentMonitoring service no longer require ServiceAdministrator permissions

[v6r13] Permission fix for ComponentMonitoring

---

Core/Utilities/InstallTools.py
FrameworkSystem/Client/SystemAdministratorClientCLI.py

Now all runnable components use the same code in some of the functions, avoiding repeating identical blocks of code for every different component, therefore making it easier to add new types of components
(for extensions, for instance).

[v6r13] Changes on InstallTools

---

ConfigurationSystem/Client/Helpers/Resources.py

Whitespace is removed from the OSCompatibility list, but not from the
originalPlatforms, this prohibits jobs to be send to CEs with spaces in the OS
version name e.g. "Scientific Linux"

[v6r11] Fix for getCompatiblePlatforms

---

FrameworkSystem/scripts/dirac-populate-component-db.py

The script now allows the -e/--exclude flag followed by a comma-separated list of hosts that will not be taken into consideration by the script. Also, the script will no longer attempt to register components from hosts that are unreachable and will send a notification mail in this case.

[v6r13] Modified DB populating script

---

ConfigurationSystem/Client/Helpers/Registry.py
FrameworkSystem/Client/SystemAdministratorClientCLI.py
FrameworkSystem/Client/SystemAdministratorIntegrator.py

Added a new 'getTrustedHosts' method to Registry so that only host with the 'TrustedHost' property are retrieved by the SystemAdministratorIntegrator, instead of every single host in the installation.

!!! [v6r13] Retrieval of trusted hosts from Registry

---

DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py

FIX: DirectoryTreeBase - unify interface for changePathXXX functions between files and directories, closes #2363

[v6r13] Unify interface for changePathXXX functions

---

DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py

Change table engine to InnoDB when rebuilding DirectoryUsage

[v6r12] DFC: RebuildDirectoryUsage, fix table Engine

---

Core/Utilities/InstallTools.py

Enabling monitoring while setting up new components is failing in several respects:
- Installing the InstalledComponentsDB is failing
- Installing the ComponentMonitoring service itself to an already existing DIRAC installation is failing
- Host where new components are installed through the ServiceAdministrator service must have ServiceAdministrator property, which is not good.
I would suggest that we introduce a new property, e.g. ServiceHost, which is given to all the hosts that are supposed to run DIRAC services and agents. This will be a sign for the host to be monitored. 
On the whole I would like to review the logic of component monitoring in favor of detecting automatically the installed/running components instead of relying on information added/removed while …

[v6r13] Ignore installMonitoring() errors

---

Interfaces/API/Dirac.py

FIX: getFile() allows to pass a list of LFNs

[v6r13] dirac-dms-get-file broken

---

Interfaces/API/JobRepository.py
Interfaces/scripts/dirac-wms-job-submit.py

Use the same switch but use the value as file name. Means it cannot use the default file name ($HOME/.dirac.repo.cfg, will create another fix for that).

Allow setting the repo file name

---

WorkloadManagementSystem/Client/DownloadInputData.py

FIX: could not find cached files (missing [lfn])
CHANGE: remove caching of StorageElements as it is already a cache!
FIX: localFile was not defined properly
It was impossible to download a file if not from a local SE.
In addition if there were no local SEs we were instantiating a weird SE called None
Changed method names as they were totally misleading (PFN don't exist any longer)

[v6r13] Fix to DownloadInputData

---

Core/Utilities/Proxy.py
WorkloadManagementSystem/Executor/InputData.py

executeWithUserProxy decorator - a utility to facilitate a function execution with a temporary proxy of a particular user. It overrides the useServerCertificate flag ( and restores it after the execution ).
The InputData executor is updated to use this decorator for looking up input data replicas. By default ( if checkWithUserProxy flag is not set to True in the CS ), the old "shifter" behavior is preserved.

[v6r13] New decorator to execute function with a user proxy

---

FrameworkSystem/scripts/dirac-populate-component-db.py

Excluded hosts are no longer checked for availability ( it is pointless to do so, since they are not going to be used ). The script now also checks whether the 'ServiceAdministrator' group property is present or not in the proxy, stopping its execution in the latter case.

[v6r13] Fixed DB-populating script

---

RequestManagementSystem/Client/ReqClient.py
RequestManagementSystem/Client/Request.py
RequestManagementSystem/Client/test/OperationTests.py
RequestManagementSystem/Client/test/RequestTests.py
RequestManagementSystem/scripts/dirac-rms-cancel-request.py
RequestManagementSystem/scripts/dirac-rms-reset-request.py
Resources/Storage/SRM2Storage.py

* Adapt the reset and cancel RMS script to also accept request name, providing it is unique
* The error code for SRM_REQUEST_QUEUED changed in a more recent version of srm-ifce, so now we handle both case
* There were some error in the difficult merging when converting the RMS to SQLAlchemy and json, mostly in tests. Corrected that

[v6r13] fix reset/cancel request and SRM2 stage request

---

FrameworkSystem/Client/SystemAdministratorIntegrator.py
FrameworkSystem/scripts/dirac-populate-component-db.py

Modified SystemAdministratorIntegrator so that it can be told to exclude hosts during initialization. This way, the SysAdminIntegrator calls will not take into account these hosts and the populating script is also
relieved from checking if hosts are in the excludedHosts list.

[v6r13] New fix for populating script

---

DataManagementSystem/Agent/FTSAgent.py
DataManagementSystem/Client/FTSFile.py
DataManagementSystem/Client/FTSJob.py
Resources/Storage/SRM2Storage.py
Resources/Storage/StorageElement.py

As now getTransportURL() is not checking the status of the SE, whenever access to a service is required, one should check the read access permission in the plugin.
This is done in SRM2, thus getting an "srm" URL is OK but not a "root" URL:
In [3]: se.getURL('/lhcb/MC/MC11a/ALLSTREAMS.DST/00013911/0000/00013911_00000017_1.allstreams.dst', 'srm')
Out[3]: 
{'OK': True,
'Value': {'Failed': {},
'Successful': {'/lhcb/MC/MC11a/ALLSTREAMS.DST/00013911/0000/00013911_00000017_1.allstreams.dst': 'srm://srm.grid.sara.nl:8443/srm/managerv2?SFN=/pnfs/grid.sara.nl/data/lhcb/archive/lhcb/MC/MC11a/ALLSTREAMS.DST/00013911/0000/00013911_00000017_1.allstreams.dst'}}}
In [4]: se.getURL('/lhcb/MC/MC11a/ALLSTREAMS.DST/00013911/0000/00013911_00000017_1.allstreams.dst', 'root')
Out[4]: 
{'OK': True,
'Value': …

[v6r13] Check read access for getURL only if service is required (SRM2)

---

Resources/Storage/StorageElement.py

This was importing the Module and later trying to call it (line 541), so this needs to import the Class
(also found by pylint).

[v6r13] Minor Fix for StorageElement

---

Workflow/Modules/FailoverRequest.py

These setters are no longer available (they are part of the old RequestManagementSystem), must directly assign to variables.

[v6r13] FailoverRequest: no more setters

---

DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py

Just create the new table like the old table.

[v6r12] DirectoryUsage: avoid defining table in two places

---

WorkloadManagementSystem/Service/WMSAdministratorHandler.py

Minor bug fix to include ARC among the supported CE types. This could probably go in starting v6r12, but I leave it to the experts to determine this.

[v6r14] Minor bug fix to include ARC CEs

---

RequestManagementSystem/Client/Request.py

Since the relationship between entities is now handled by SQLAlchemy, there are "automatic actions" taken on the servers that are not visible on the client side (and hence escaped the tests we had). Basically, when reassigning a File to another Operation, SQLAlchemy removes the link from its old parent to the File, while without it (i.e. on the client side), we must do it by hand. This is done only at one place (Request.optimize), so I corrected it here, and commented.

[v6r13] Fix Request.optimize()

---

Core/Utilities/InstallTools.py
Core/scripts/dirac-install-agent.py
Core/scripts/dirac-install-db.py
Core/scripts/dirac-install-executor.py
Core/scripts/dirac-install-service.py
FrameworkSystem/Client/SystemAdministratorClientCLI.py
FrameworkSystem/DB/InstalledComponentsDB.py
FrameworkSystem/Utilities/MonitoringUtilities.py
FrameworkSystem/scripts/dirac-populate-component-db.py

Due to the fact that the requests to the ComponentMonitoring service are currently made by the server's SysAdmin service ( and not from the original caller of the top level script/CLI command ) the certificate of the server is used instead, meaning that the calls turn out unauthorized.
To avoid this, the InstallTools' monitorInstallation/Uninstallation funcions that make the requests to the ComponentMonitoring service have been moved so that they are callable by the scripts or the CLI.
Also, some minor changes to the InstalledComponentsDB module have been made to avoid sqlAlchemy warnings.
Lastly, I'm PR'ing the DB-populating script again, since I made the last PR for it to integration by mistake.

[v6r14] Several changes on ComponentMonitoring

---

ConfigurationSystem/Agent/CE2CSAgent.py
Resources/Computing/ComputingElement.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Since... ever we've been passing to the JobAgent CPU time variables that are unused. Also the initial default used made little sense.

[v6r13] Fix pilot cpu time - urgent

---

Core/Security/X509Chain.py

CHANGE: X509Chain - use SHA1 signature encryption when generating proxy by Proxy Manager

[v6r13] Use SHA1 signature encryption everywhere

---

WorkloadManagementSystem/Agent/SiteDirector.py

The change in L591 is made basically to include the status "Waiting", whose meaning is the same as "Scheduled" but used for SSH sites. In the current code, when only "Waiting" job exists (no "Running" job) in a SSH site,  accoring to  L251 of Resources/Computing/ComputingElement.py, it is recognized no job exists at this site and SiteDirector submits jobs until running jobs appear. Attached file shows the number of waiting jobs in our site where maximum number of waiting job is set to be several 10. We have tested this modification in r12, which is used at Belle II now.
The change in L508-L509 is already discussed in PR No2456 but we want to include it in r12, too.

[v6r12] Modified SiteDirector.py to change the way to count existing pilot jobs for SSH sites

---

Resources/Storage/SRM2Storage.py

I've had the problem for quite some time, that my FailoverRequests failed because the file already existed on the cern Castor, it had size 0 and I had to remove it by hand.
Now I figured out that the reason is that the SRM2Storage.exists function encountered status 22
(added some debug printout of urldict etc. during investigation)
```
2015-07-02 11:29:52 UTC RequestManagement/RequestExecutingAgent/SRM2Storage   INFO: SRM2Storage.exists: Checking the existance of 1 path(s) 
2015-07-02 11:29:52 UTC RequestManagement/RequestExecutingAgent/SRM2Storage   INFO: SRM2Storage.exists urlDict:  {'status': 0, 'estimated_wait_time': 0, 'stat': [16893, 0L, 0, 1, 2, 2, 0L, 0L, 1435832987L, 1435832987L], 'SRMReqID': None, 'locality': 'ONLINE_AND_NEARLINE', 'explanation': None, 'turl': None, 'surl': …
```

!!! [v6r12] Add dealing with status 22 to SRM2Storag.exists

---

WorkloadManagementSystem/JobWrapper/JobWrapper.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Here first of all for evaluation, this might not be the end of the story @phicharp 
@atsareg : extra options file passed from the JobAgent to the JobWrapper are not loaded. But still, it has to be seen if its configuration is passed correctly to the executable (which, if it is "dirac-jobexec", should have it).

[v6r13] Extra options file loaded within the JobWrapper

---

DataManagementSystem/DB/FileCatalogComponents/SecurityManager.py
DataManagementSystem/DB/FileCatalogComponents/SecurityPolicies/VOMSPolicy.py

make the vomspolicy compatible with the old client by calling in case of need the old SecurityManager

[v6r13] VOMS Policy compatible with old client

---

Core/Security/VOMS.py
Core/Security/X509Certificate.py

In case no VOMS attributes are defined for a given VO, fqan is the only source of the VO information

[v6r14] VOMS: get VO information from the fqan VOMS attribute

---

Core/DISET/private/Transports/SSL/SocketInfo.py

DIRAC allowed to connect users with revoked certificates, because the CRLs was not correctly handled.
Problem:
get_not_after() is a method of the certificate. Revoked certificates do not have this method.
Solution:
I removed the line and each time when we start a DIRAC component or client (skipCACheck == False) the CRLs cache will be recreated.

[v6r14] Check the CRLs

---

ResourceStatusSystem/Utilities/CSHelpers.py
Resources/Computing/BatchSystems/GE.py
Resources/Computing/BatchSystems/Torque.py
WorkloadManagementSystem/Client/SandboxStoreClient.py

FIX: SandboxStoreClient - get the vo info from the delegatedGroup argument to use for the StorageElement instantiation
FIX: BatchSystems - always return Message in case of errors ( cherry-picked from integration )

[v6r13] SandboxStoreClient is vo aware in the web portal context

---

DataManagementSystem/Client/DataManager.py

This bug has always been there....

[v6r13] FIX : Remove the local file when doing two hops transfer in the DataManager

---

ResourceStatusSystem/Agent/CacheFeederAgent.py
ResourceStatusSystem/Agent/ElementInspectorAgent.py
ResourceStatusSystem/PolicySystem/Actions/LogPolicyResultAction.py
ResourceStatusSystem/PolicySystem/PEP.py
ResourceStatusSystem/Service/PublisherHandler.py
ResourceStatusSystem/Service/ResourceManagementHandler.py
ResourceStatusSystem/Utilities/Synchronizer.py
ResourceStatusSystem/scripts/dirac-rss-query-dtcache.py

We like to propose to modify code in RSS to make VO extension easy.
Some codes directly call ResourceManagementDB and ResourceManagemantClient.
But, when VO extension is made, they may be rewritten.
In the current codes, these codes directly calling them should be modified
to import VO-extended  ResourceManagementDB and ResourceManagemantClient.
In my proposal, ResourceManagementDB and ResourceManagemantClient are called
by voimport in DIRAC.ResourceStatusSystem.Utilities.Utils. So some codes do not need
to be modified.

!!! [v6r12] Proposal of modification for codes in ResourceStatus to make VO extension easy. 

---

Resources/Computing/GlobusComputingElement.py

As there is no command for Globus, we just count the pilots in the dirac system
I don't know if anybody else is using this, and if this should also go into v6r11?

[v6r12] GlobusComputingElement: count waiting pilots in the system

---

Core/Utilities/Graphs/GraphData.py
Resources/Storage/SRM2Storage.py

a) I am not sure, but now the Castor-SRM return status 16 for SRM_FILE_BUSY. I don't know if this is a new return code for the same issue as before, or a different Issue.
b) I was trying to plot WMSHistory NumberOfJobs grouped by Status, limited to two groups , limited to the last two days and got an exception for a missing key in the parsed_errors

[v6r12] SRM2Storage, busyfile new return code?; GraphData protect against missing key

---

FrameworkSystem/DB/SystemLoggingDB.py

My SystemLogging Test instance had lots of errors, because the IPaddress of the machine could not be inserted fully.
Apparently one needs 45 characters to account for all cases (see google)
And of course for existing DBs
```
ALTER TABLE ClientIPs MODIFY Column `ClientIPNumberString` varchar(45) NOT NULL DEFAULT '0.0.0.0';
```

[v6r13] SystemLoggingDB.ClientIPs.ClientIPNumberString too short for IPv6

---

Resources/Storage/GFAL2_StorageBase.py

Relative paths didn't work because the 'file:' protocol specifier (that gfal2 needs) was set as such that it interpreted all paths as absolute, resulting in an error for relative paths.
This is the same PR as before but on a clean branch.

[v6r13] fixing relative path issues

---

WorkloadManagementSystem/PilotAgent/pilotCommands.py

Solves   #2462 
With these changes I can run on sites that define OSG_WN_TMP
And with the Job Contact string the connection from Pilot to Job is done now also for jobs running on GlobusCEs 
EDIT: for v6r11 of course this would be somewhere completely different

[v6r12] Fixes for the pilot on osg and globus sites

---

FrameworkSystem/Client/SystemAdministratorClientCLI.py

Fixed a bug that made the CLI crash upon calling the 'show installations' command when there was an entry such that the UninstallationTime was present, but not the person that uninstalled the component. Now it is not assumed that the uninstalled person is always registered, even if the component is uninstalled.

[v6r14] Fix on CLI

---

DataManagementSystem/Client/DataManager.py

This is needed to run replicateAndRegister to SEs where only the XROOT protocol is available

[v6r12] Add XROOT to registration protocols

---

TransformationSystem/Client/TransformationCLI.py

resetFile can have more than one lfn as argument, 
Failed might not exist in res causing a crash; not sure if 'Failed' is ever in res.

[v6r12] TransformationCLI: resetFile change doc string, fix crash

---

Resources/Computing/ARCComputingElement.py

Check if WorkingDirectory is set
Create WorkingDirectory if it does not exist
This also happens now that the PilotStatusAgent is calling killJob

[v6r12] ARCComputingElement: check against missing ceParameters

---

AccountingSystem/DB/AccountingDB.py
AccountingSystem/Service/ReportGeneratorHandler.py
Core/Base/AgentModule.py
Core/DISET/private/Service.py
Core/Utilities/Os.py
DataManagementSystem/Agent/CleanFTSDBAgent.py
DataManagementSystem/Agent/FTSAgent.py
DataManagementSystem/Agent/RequestOperations/PhysicalRemoval.py
DataManagementSystem/Agent/RequestOperations/PutAndRegister.py
DataManagementSystem/Agent/RequestOperations/ReTransfer.py
DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
DataManagementSystem/Service/FileCatalogHandler.py
FrameworkSystem/Service/PlottingHandler.py
FrameworkSystem/scripts/dirac-monitoring-get-components-status.py
RequestManagementSystem/Agent/CleanReqDBAgent.py
RequestManagementSystem/Agent/RequestExecutingAgent.py
RequestManagementSystem/private/RequestTask.py
TransformationSystem/Agent/InputDataAgent.py
TransformationSystem/Agent/TaskManagerAgentBase.py
WorkloadManagementSystem/Client/Matcher.py
__init__.py

Remove instantiation of the global gMonitor object from DIRAC.__init__.py to be less dependent
on DIRAC internal details when instantiating various objects, for example to generate documentation.

[v6r15] Remove gMonitor instantiation from DIRAC.__init__.py

---

Core/Utilities/TimeLeft/MJFTimeLeft.py
Core/Utilities/TimeLeft/TimeLeft.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Hi, 
I've tested these changes to the code with jobs running in VMs. The Job Features CPU and Wallclock limits are used for the TimeLife calculation if the information is not available from a batch system. If the shutdowntime is set in Machine Features then that is used to decrease the wall clock time left. The presence of both $MACHINEFEATURES and $JOBFEATURES is used to enable the MJF plugin. urlopen().read() is used to read the values, which works with both local file (Batch, Vac) and remote HTTP URL (Cloud) scenarios in the MJF specifications.
The patch to pilotCommands.py makes the identification of SGE batch systems consistent with TimeLeft.py in that SGE_TASK_ID is checked too. If only $JOB_ID is set, that is used as a generic job id. The LHCb and GridPP DIRAC VMs set this with the …

[v6r15] Machine/Job Features support

---

WorkloadManagementSystem/Agent/SiteDirector.py

Force executing pilot in the current working directory if not specified otherwise

[v6r13] Forbid pilot to execute in /tmp

---

Resources/Computing/ARCComputingElement.py

Hopefully this actually fixes the problem with keeping the userConfig object alive as the underlying ARC plugins require. Tested in certification for some time and hotfixed in production now and seems to be running fine.
Also a major/minor depending on your point of view fix for jobID.
And this time hopefully to v6r14

[v6r14]Bug fix plus improvement in treatment of userConfig

---

FrameworkSystem/scripts/dirac-populate-component-db.py
Interfaces/API/Dirac.py
WorkloadManagementSystem/JobWrapper/JobWrapper.py
WorkloadManagementSystem/Service/MatcherHandler.py

FIX: JobWrapper - avoid defaulting outputData to ['']
BUGFIX: dirac-populate-component-db - DIRACexit instead of return
FIX: Matcher - use VO specific Operations helper
BUGFIX: Dirac - use open and not os.open
This PR replaces #2584

[v6r14] JobWrapper default for outputData + other fixes

---

Resources/Computing/ARCComputingElement.py

The query should in principle work for all CEs and is probably the best that can be done.
For sites which support ALICE, the query should return correct values as we expect. This is because of a patch which is installed at such sites.
For other sites (which do not have the above patch), the information is for all VOs in the CE. So, we will see a much higher number of running jobs than reality for our VO. This cannot be escaped for now.
We probably need to ask all sites to install the patch mentioned above and push the ARC developers to include the patch in their official release and ask sites to upgrade.

[v6r14] Better implementation of ldap query for getCEStatus

---

Core/Security/VOMS.py

This is the responsible for the zillions of proxies created everywhere.

[v6r14] Remove the temporary file created when issueing getVOMSProxyInfo

---

Core/scripts/dirac-install.py

At least in the client externals v6r2 glibc2.12 python 2.7 the share/terminfo is missing, this breaks for example the reset command, which is in the externals bin/reset.
I.e. the bashrc contains
```
export TERMINFO=[...]/DIRAC/Linux_x86_64_glibc-2.12/share/terminfo
```
So either these things have to be part of the client externals again, or TERMINFO needs to point to the local installation, if it exists, as is done in this PR.

[v6r12] set TERMINFO also to local installations if they exist

---

WorkloadManagementSystem/Agent/PilotStatusAgent.py

PilotStatusAgent log messages were not split between static and dynamic part
Also some cleanup for wrong indendation (off by 1) and variable naming and whitespaces after and before parentheses.

[v6r12]  PilotStatusAgent: split error messages, pylint cleanup

---

DataManagementSystem/Client/FileCatalogClientCLI.py

Some functions receiving a path as argument were not normalizing
this path, which may cause some functions fail.
Normalizing all paths using the member function
getPath makes code more readable.
For instance following function call fail because path ends with '/':
```
meta set /ilc/user/c/calanchac/stdhep/E500/ Energy 500
Error: Server error while serving setMetadata: '/ilc/user/c/calanchac/stdhep/E500/'
```

[v6r12]  Make systematic use of getPath to avoid '//' in path names

---

FrameworkSystem/Client/SystemAdministratorClientCLI.py

This location printout was wrong.
Also in v6r12 and before, but as there were many changes in v6r13 it would cause issues so I just make a PR against v6r14.

[v6r14] Correct location of Pilot version printout

---

Core/Utilities/DictCache.py

The property does not seem very __del__ friendly. 
An exception is *sometimes* thrown, however it is ignored and transformed into warning. No consequences, just printout.
This should fix it

[v6r14] conditional lock in the DictCache for the __del__

---

DataManagementSystem/Client/FTSJob.py

We now don't recreate the FTS3 Context at every submission or monitoring of a job, but keep it as object attribute. This leverages the memory leak of pycurl and nss

[v6r14] Don't recreate systematicaly the FTS3 Context

---

DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/DirectoryClosure.py
DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql

Implement recursive operation in the LHCb managers compatible with generic changes.
Replaces https://github.com/DIRACGrid/DIRAC/pull/2487 
Tests (successful) are in https://github.com/DIRACGrid/TestDIRAC/pull/89

[v6r15] Recursive DFC operation for LHCb managers

---

Core/LCG/GGUSTicketsClient.py
Core/LCG/GOCDBClient.py
ResourceStatusSystem/Command/DowntimeCommand.py
ResourceStatusSystem/Utilities/InfoGetter.py
ResourceStatusSystem/scripts/dirac-rss-policy-manager.py

- dirac-rss-policy-manager.py allows to interactively modify and test only the policy section of Dirac.cfg (the test will be made against the setup selected by InfoGetter)
- the cachecleaning inside the DT can now remove from the cache the DT removed from GocDB, but it requires an additional access to GOCDB at every doNew

[v6r15] RSS: update DowntimeCache with Removed DTs

---

Resources/Storage/GFAL2_StorageBase.py

Fixed Indentation: Updating metadata dict with attributeDict only works if there is an attributeDict

[v6r14] Fixed indentation and a debug log typo

---

DataManagementSystem/Client/FileCatalogClientCLI.py

Set/Remove metadata fields for a large bunch of files/directories
using the dirac file catalog is cumbersome: only one metadata field can be set/remove each time.
This commit allow set/remove unlimited number of metadata fields each time.

!!! [v6r12] Set/Remove >1 metadata field each time

---

Resources/Computing/HTCondorCEComputingElement.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Continuing from #2610 
* pilotRef is now working, the environment value needs to be in quotation marks
* add initialdir: local directory where log/err/out are stored. Set to workingDirectory of Sitedirector, I don't really understand why this should depend on the queue, which can be independent of the site/CE
Still the problem to tell the WMSAdministrator about this folder...
* unlink the submission file right away
* fix bug with missing variable when condor_history would fail
* rewrite the pilotStatus code to reduce calls to condor_q and condor_history

[v6r12] HTCondorCE improvements

---

ConfigurationSystem/Agent/Bdii2CSAgent.py
ConfigurationSystem/Client/Utilities.py
ConfigurationSystem/private/ConfigurationClient.py
ConfigurationSystem/private/Refresher.py
Core/Utilities/Grid.py
Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Agent/JobAgent.py
WorkloadManagementSystem/Agent/TaskQueueDirector.py
WorkloadManagementSystem/private/DIRACPilotDirector.py

This PR fixes four bugs:
- When the application finishes with errors but the agent continues to take jobs, the timeLeft was not evaluated
- The initial timeLeft value was always set to 0.0 because the /Resources/Computing/CEDefaults/MaxCPUTime is not set in the current pilot commands
- The Bdii2CSAgent logic was faulty in some cases because the BDII info was compared to the CS info from any CS server and not from the Master resulting in discrepancies in some rare cases.
- The Bdii2CSAgent logic did not distinguish the CE and the Cluster in the Glue 1.0 schema which can be sometimes different
Also removed legacy getResourceDict() from the ComputingElement.py and moved to DIRACPilotDirector which itself is a legacy, kept just in case somebody still uses it.

[v6r14] JobAgent and other fixes

---

DataManagementSystem/Client/DataManager.py

cleanDirectory (e.g., called from dirac-dms-clean-directory) fails when the directory itself is empty,
```
Failed to clean directory. /ilc/prod/ilc/mc-dbd/ild/dst/250-TDR_ws/higgs_ffh/ILD_o1_v05/v01-16-p10_250/00005972/000 Failed to perform exists from any catalog
```
because the function passes an empty list to removeFile here https://github.com/andresailer/DIRAC/blob/de7cc06e8d86f8ff0787e315faf76824688413ab/DataManagementSystem/Client/DataManager.py#L128
, removeFile then passes an empty list to exists which returns an error.
Now there are three locations to fix that: 
* in cleanDirectory not passing an empty list
* in removeFile returning success for empty input 
* in exists to also return success in case of empty input (I guess, did not actually try that...)
I chose the second option …

[v6r12] fix: cleanDirectory fails for empty directories

---

Core/DISET/private/Transports/SSL/SocketInfoFactory.py

I have a very strange error message using my local PC. I try to connect to certification without any success. I am using the latest LHCbDIRAC version:
/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/bin/python
>>> import socket
>>> osSocket = socket.socket( socket.AF_INET6, socket.SOCK_STREAM )
File "<stdin>", line 1, in <module>
File "/cvmfs/lhcb.cern.ch/lib/lcg/releases/LCG_79/Python/2.7.9.p1/x86_64-slc6-gcc48-opt/lib/python2.7/socket.py", line 187, in __init__
_sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol
>>>
I have a feeling that some library is not up to date.
A real example when I try to ping the Bookkeeping service:
[zmathe@pclhcb63 LHCbDirac_v8r2p7]$ …

[v6r14] - ipv6: Address family not supported by protocol

---

Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Client/Matcher.py

The hosts requesting jobs as GenericPilot must provide a VirtualOrganization parameter in the resource description, then they are allowed to match jobs.
Plus a bug fix in the resource description evaluation where Tags were sometimes overwritten

[v6r14] Matching jobs by hosts in a multi-VO environment

---

WorkloadManagementSystem/Client/CPUNormalization.py

This is more correct than the default low value we had before

[v6r15] Changed default limit of queue time to 9999999 ("Infinite")

---

Resources/Computing/ARCComputingElement.py

This is to add the "queue" field for submission to ARC sites, which was discussed, but seems to have mysteriously vanished at some point. This has been tested in the certification instance by me.
The major assumption of this patch is that none of the batch systems we run on (PBS, GE, Condor, Torque, ... whatever) have a "-" in their name.

[v614] Update to add queue to the XRSL string

---

WorkloadManagementSystem/Agent/JobAgent.py

We found that when a glexec wrapped job failed and rescheduleOnError was True, the rescheduling would trigger an exception. This patch fixes that problem and also returns S_OK() so that the outer layer of the JobAgent doesn't immediately mark the job as failed again.
Regards,
Simon

[v6r12] Fix job rescheduling on (glexec) error

---

DataManagementSystem/Client/FileCatalogClientCLI.py
release.notes

Changed short option to list size i nhuman readable from '-h' to '-H'.
This is necessary in order to use same parameters in dls command
without conflicting with the script help (also '-h').

[v6r12] Improved ls in the dirac filecatalog

---

WorkloadManagementSystem/Service/JobMonitoringHandler.py

I want to propose to extend the JobMonitoring Service with this function, it would allow to retrieve multiple parameters for multiple jobs. Otherwise when going through a list of jobs and retrieving the same parameters for each of them it takes a very long time. This would allow to do it in one shot. 
My concrete example where I can use this is the monitoring of mesh processing, here I will need to retrieve multiple parameters, such as the JobGroup, RunNumber, Status  for a "helper site" to jobs it has done for a given job type in order to further digest which site it was contributing to for each job.

v6r14 : extend the JobMonitoring Service 

---

FrameworkSystem/private/SecurityFileLog.py

fix the buffer size for reading when zipping a file to maximum 2^31-1 bytes. Gzip internally does a crc32 check which will otherwise fail.

v6r14 - fix gzip buffer size

---

TransformationSystem/Client/TransformationCLI.py

Two occurrences of getallByUser still remain.

Completing the change getallByUser to getAllByUser

---

ConfigurationSystem/Client/Utilities.py
Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Client/Matcher.py

The MaxRAM option can be defined both on the CE and Queue level. If defined in both places, Queue option takes precedence.
Also added protection on importing faulty MaxRAM values from BDII
The MaxRAM and other Tags generation is moved to the Matcher.

[v6r14] MaxRAM option defined on the CE level

---

Core/Utilities/DErrno.py

This is a port of fixes that are included in this https://github.com/DIRACGrid/DIRAC/pull/2668, which will probably not be merged in v6r15

[v6r15] DErrno: compatible string for ENOENT and fix in cmpErr

---

Core/Utilities/TimeLeft/MJFTimeLeft.py
Core/Utilities/TimeLeft/PBSTimeLeft.py
Core/Utilities/TimeLeft/SGETimeLeft.py
Core/Utilities/TimeLeft/TimeLeft.py

The batch plugins won't mix CPU and walltime values anymore, missing values are handled by the TimeLeft object.
This is the first part of the replacement of #2629

[v6r15] move missing wc/cpu time workaround fixes from batchPlugins to TimeLeft

---

TransformationSystem/Client/Transformation.py
TransformationSystem/Client/TransformationCLI.py

Monitoring productions using the web interfaz is not as convenient as
in one terminal, where you can operate on regions/rectangles.
The proposed changes introduce a new function in the transformation
CLI summaryTransformations. This new function receives a list of
transformations ID's, and display some files/jobs statistics similarly
as its shown in the web interfaz.

[v6r12] Added func. summaryTransformations in trans. CLI

---

TransformationSystem/scripts/dirac-production-runjoblocal.py

this script gets the VO extension name (e.g. LHCb) in general and uses it to create the job object.
The original script was created to run LHCb jobs, so must of its functions might not be usefull to other VOs,
or might need extra procedures to make it functional for other VOs...
I left the commented cede lines on it to show how it's done on LHCb, it can be helpful for the necessary fixes in order to run multiple VOs
Marcelo Vilaca

[v6r14] Requested script to run jobs locally using job().runlocal() from the API

---

Resources/Storage/XROOTStorage.py
Resources/Storage/test/TestXROOTStorage.py

While GFAL2 not available... see #2495 
Add two functions needed, copies from StorageBase but adding extra "/" for the path.
Fix almost all tests. getProtocolPFN doesn't exist and I don't know if there is an equivalent new function..
Tested also dirac-dms-add-file, get-file, replicate-lfn (from and to xroot), remove-files, remove-replica
Only tested with v6r13, but I hope these things where not re-written also in v6r14?
Need a tag to test this on the grid

[v6r13] XRootStorage: Make it work again.

---

Core/Utilities/TimeLeft/TimeLeft.py
WorkloadManagementSystem/Agent/JobAgent.py
WorkloadManagementSystem/JobWrapper/JobWrapper.py

Allows JobAgent to handle multicore jobs.
Matching is done with "XCores" or "WholeNode" in JDL variable `Tags`.
Multicore information is transmitted to the payload job through JobWrapper with environment variables.
I wonder if cores number and wholenode flag are to be sent to the Accounting database (can be helpful to compute multicore efficiency statistics).
This is the second part of the replacement of #2629

[v6r15] Multicore jobagent

---

Resources/Computing/ARCComputingElement.py

This is not an urgent patch and in principle, should give identical results to what already exists. Hopefully this code will be blind to what version of ldap or which glue schema is actually used to publish information in the future.
Here, we also avoid (unnecessary) knowledge of what VO this is, as that depends on the configuration which can be in a debatable state.
"Tested" in certification and by the Imperial College / GridPP instance.

[v6r14] Move getCEStatus function back to using the ARC API.

---

Core/Utilities/TimeLeft/LSFTimeLeft.py
DataManagementSystem/Agent/FTSAgent.py
TransformationSystem/Client/PluginBase.py
TransformationSystem/Client/Utilities.py
WorkloadManagementSystem/Client/CPUNormalization.py
WorkloadManagementSystem/scripts/dirac-wms-cpu-normalization.py
WorkloadManagementSystem/scripts/dirac-wms-get-queue-cpu-time.py

Change to allow a renormalization of the estimated CPU power, as this is drifting with time... 
The default behavior is the same as before.
getCPUTime() was only looking into the CS to get the time left, but this is incorrect for LSF @ CERN in particular as the queue size in the CS is not in real seconds but must be renormalized which is what TimeLeft() does... Therefore try TimeLeft first and then CS if unsuccessful

[v6r14] Minor fixes

---

Core/scripts/dirac-install.py

hashlib does not exist on SL5 by default (python 2.4) so use md5 instead (as it was before).
Also remove unused imports (pylint)

[v6r14] dirac-install: Make hashlib optional again

---

WorkloadManagementSystem/Client/CPUNormalization.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

- cpuTimeLeft is now always a float in CPUNormalization.py -- @phicharp 
- pilot commands CheckCECapabilities and CheckWNCapabilities were not considering the case of missing proxy (e.g. every VM) -- @CinziaLu

[v6r14] Fixes

---

FrameworkSystem/Client/SystemAdministratorClientCLI.py
FrameworkSystem/Service/SystemAdministratorHandler.py

getHostInfo now resorts to reading the host information with __readHostInfo (i.e., asking the host to read and generate the dictionary), rather than reading from the database, which is faster, when it fails to do so, for whichever reason

[v6r15] Improvements to installations monitoring

---

Resources/Storage/XROOTStorage.py
Resources/Storage/test/TestXROOTStorage.py

These changes allow one to use third party copy between storage elements based on xroot.

[v6r14] Enable ThirdPartyCopy with XROOTStorage

---

Resources/Computing/HTCondorCEComputingElement.py
WorkloadManagementSystem/Service/WMSUtilities.py

Some improvements for the HTCondorCE, still some open issues about the WorkingDirectory...
(Maybe adding a section in Operations for WorkingDirectory and how long the condor out/err/log files are kept?)
The Condor logging can now be obtained in the webinterface (that are the changes in WMSUtilities)
The pilot out and err files and the log files for each job are now placed in random locations.
Using find to find the files (which is fast enough...)
All log/out/err files older than 15 days are removed (using find again).
SIGTERM (instead of SIGKILL) is send to the application in case jobs are killed by the host site.
When pilots are put in held status we kill them in condor and mark them as aborted.
Some OSG sites allow opportunistic resources only 2 hours of uninterrupted running, after …

[v6r14] HTCondorCE tweaks, log output

---

RequestManagementSystem/Client/Request.py
RequestManagementSystem/Service/ReqProxyHandler.py

If one of the request is malformed for a reason or another, the rest of the requests could not be swiped. This PR fixes this behavior.

[v6r15] Don't block the ReqProxy sweeping if one of the request is buggy

---

Resources/Computing/ARCComputingElement.py

This is a PR to presumably be discussed further in this thread.
Aim : Reconcile the usage of getCEStatus for the configuration as used for GridPP (robot certificates for pilot proxy) and LHCb (human certificates).
Attempt : Try to get the VO information. If a valid VO can be obtained, assume that the proxy is not a robot certificate and proceed. Otherwise proceed the other way.
Future of this PR :
1. Depends on the outcome of the infosys-discuss mailing list where a proper implementation of Glue2 on ARC CEs (among others) is being discussed. Once this is implemented by the sites (and ARC), the "robot certificate" method of using just the ARC api will presumably become the formally standard way of doing this.
2. If GridPP (and other instances?) move to using human certificates, the "if" …

[v6r14] Attempt to reconcile getCEStatus for LHCb and others

---

Core/DISET/private/Service.py

After enabling Service configuration to inherit another Service configuration with Module option, the Service name can be different from the name of the class of the service handler. The private self._name variable was still pointing to the class name. This was wrong and caused the StorageElement service to fail in case it was configured with the Module option.
Removed obsoleted _discoverHandlerLocation. This function is performed by the ModuleLoader.

[v6r14] Fix Service class

---

AccountingSystem/Client/DataStoreClient.py

* Synchronizer based decorators have been replaced with a simple lock as they were blocking addRegister() during every commit() (and commits could take several seconds to finish)
* Added delayedCommit() which reduces overheads. Call to this function will in the future be propagated to BaseAccountingType class and similar places
* See comment in the lines 59-60
* Change of the target branch (see pull request #2747)

[v6r15] Performance update in DataStoreClient

---

TransformationSystem/Client/TaskManager.py
TransformationSystem/Client/test/Test_Client.py

reflected in the tests.
In case there is no InputData for a task, the Request created for the previous task was reassigned. This fixes this bug.
However, how can there be no InputData is probably another bug somewhere, still to be found.

[v6r15] avoid to assign the same request to two different tasks

---

Interfaces/API/Dirac.py

* Interfaces/API/Dirac.py (selectJobs):
Include in error message the date used to select the jobs.

[v6r14] Increase verbosity in error message

---

Resources/Computing/ARCComputingElement.py

Before returning it to the calling code. This should prevent file existance exceptions in various log files, especially the Site Directors and WMSAdministrators.

[v6r14] Test for existance of downloaded pilot log

---

Core/Utilities/MySQL.py

Fix in the base MySQL module to execute stored procedure when the attributes are unicode
PS: yes, v6r14 is on purpose.

[v6r14] Unicode in MySQL base

---

FrameworkSystem/scripts/dirac-populate-component-db.py

Updated the populate-component-db script to make use of MonitoringUtilities and, therefore, avoid inserting duplicates of entries (if they were not uninstalled) when running the script a second time

[v6r14] Populate script bugfix

---

Core/Security/VOMSService.py

Seal down the evilish suds.sax.text.Text type into VOMSService. The fix is already running in production in LHCb

[v6r14] VOMSService outputs only string type

---

TransformationSystem/Client/TaskManager.py

The return of putting the Request is used as ExternalID for the Task. if it goes through a proxy, we never get the RequestID

[v6r14] Do not use ReqProxy when submitting Request for Tasks

---

DataManagementSystem/Service/IRODSStorageElementHandler.py
DataManagementSystem/Service/StorageElementHandler.py
Resources/Storage/FileStorage.py
Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/GFAL2_StorageBase.py
Resources/Storage/RFIOStorage.py
Resources/Storage/SRM2Storage.py
Resources/Storage/StorageBase.py
Resources/Storage/XROOTStorage.py

This PR is the first part of https://github.com/DIRACGrid/DIRAC/issues/2502
It defines a standard set of metadata that all the plugins have to return:
Checksum
Directory
File
Mode
Size
Accessible
In v6r16, once the next multi protocol steps will finally be merged (https://github.com/DIRACGrid/DIRAC/pull/2668), we will make use of it by checking the specific metadata (Lost, Cached...) only where it is really relevant, and by specifying getFileMetadata with the proper protocols
I also added the checksum computation in the DIPS storage handler, which was an other part of the bug  https://github.com/DIRACGrid/DIRAC/issues/2413

[v6r15] Add standard metadata to all plugins

---

DataManagementSystem/Agent/FTSAgent.py
DataManagementSystem/Agent/RequestOperations/RegisterFile.py
DataManagementSystem/Agent/RequestOperations/RegisterReplica.py

If a RegisterReplica operation fails on a file that no longer exists and has no replica at that SE, consider the operation as Done.
This is necessary due to potential race conditions between the RMS and e.g. merging jobs in LHCb that remove the file on completion.

[v6r14] RMS fix

---

ConfigurationSystem/Client/Utilities.py

One site with a space before a comma was constantly being "updated" because the CS splits by comma and cleans whitespace afterwards (or something?).
This will cleanup the string around commas to make the "new" description the same as the old one

[v6r14] Silence the constant update of the site description with funny whitespace

---

Interfaces/API/Dirac.py

Retrieved and OutputData are strings '0' in the jobDict when repo file is read, need to cast to int
Replace #2801 for proper target

[v6r14] Fix for Repo retrieve sandbox/outputdata

---

FrameworkSystem/Client/SystemAdministratorClientCLI.py
FrameworkSystem/DB/InstalledComponentsDB.py

Added a new field, 'Extension', to the HostLogging database in order to log the version of the different extensions installed in a given host ( this information will be displayed by both the CLI and the SysAdmin web page: #2785 ).
Updated the CLI 'show host' command to display the new information.

[v6r15] Extensions information

---

DataManagementSystem/Service/FileCatalogHandler.py
DataManagementSystem/scripts/dirac-dms-remove-files.py

the signature in v6r14 used to be (operationName (str), paths (str, list, dict)) while in v6r15 it is (paths (dict), operationName (str)).
If the first argument arriving to the serving is a string, we swap the parameters. This should go away as soon as v6r16

[v6r15] fix backward compatibility has access

---

WorkloadManagementSystem/Client/Matcher.py

Renaming "Cores" to "Processors" was not complete here.

[v6r15] rename cores to processors in resource description

---

StorageManagementSystem/Agent/RequestPreparationAgent.py

A corrupted staging request with an empty LFN made its way to the StorageManagementDB. This was causing the RequestPreparationAgent to crash

[v6r14] Fix a crash in the RequestPreparationAgent 

---

FrameworkSystem/DB/UserProfileDB.py

When we have a desktop name which is belong to two different users we have to use the desktop name (varname) and user id to identify the desktop.

[v6r14] retrive only one userprofile

---

Interfaces/API/Job.py
WorkloadManagementSystem/Service/JobManagerHandler.py

Set both CPUTime and MaxCPUTime in setCPUTime() method. Otherwise only MaxCPUTime was set and in the job checking logic the CPUTime was assigned a default value of 86400. But If CPUTime is defined the MaxCPUTime was ignored ( just kept for backward compatibility ). It is still kept in this patch but in v6r15 will be dropped altogether

[v6r14] Ignored MaxCPUTime restored

---

DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/DirectoryClosure.py
tests/Integration/DataManagementSystem/TestClientDFC.py
tests/Integration/DataManagementSystem/TestFileCatalogDB.py

Correctly return success if setting a directory parameter to the same value it was previously

[v6r15] Bug in setDirectoryParameter of DirectoryClosure

---

AccountingSystem/private/Plots.py
AccountingSystem/private/Plotters/JobPlotter.py

The sorting for cumulative plots where the enddate is not now, for example Q3 and Q4 of 2015
is not correct.
Before:
After:
Plots with enddate == now E.g. Q1 2016 are still correct (anyway the last_value should be the max_value for cumulative plots, I don't know where the logic goes wrong for the different enddate...)

[v6r14] Fix Cumulative plots with enddate != now

---

DataManagementSystem/scripts/dirac-dms-user-lfns.py

When the proxy is expired the username field is not present, and the command fails with an exception.

[v6r14] dirac-dms-user-lfns: Add error message when proxy is expired

---

WorkloadManagementSystem/Agent/SiteDirector.py

voGroups gets very long in time with copies of the same groups.
Not really important but annoying in the logs.

[v6r15] Fix SiteDirector.voGroups unnecesary growth between iterations

---

ConfigurationSystem/private/ConfigurationData.py

Compressing `gConfigurationData.remoteCFG` data each time `sync()` is called takes only a few tens of a second. However, each user command does this a few times while it has no need to do so.
This PR should improve user experience a bit, especially with COMDIRAC cli.

[v6r15] ConfigurationData.sync() performance

---

ResourceStatusSystem/scripts/dirac-rss-query-dtcache.py

Removed some unused imports and moved `ResourceManagementClient` import after `parseSwitches` because `Script.parseCommandLine( ignoreErrors = True )` has to be called first.

[v6r15] Fixed an import error in dirac-rss-dt-query-cache

---

Resources/Computing/CREAMComputingElement.py
Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
WorkloadManagementSystem/Agent/SiteDirector.py

Introduces a a new SiteDirector Agent than can submit multiprocessor pilots for task queues that require it.
On one side, user job JDL may contain one tag of the form `12Processors` (or any integer superior to 1 in place of `12`) or `WholeNode`.
On the other side, MultiProcessorSiteDirector agent will to select CE queues where one of the following CS option is set: `MaxProcessors = <2+>` or `WholeNode = true`. It will then match TaskQueue with CE queue and will submit multiprocessor pilots to the queue.
Thanks to #2694, the running JobAgent will select multiprocessor payload jobs corresponding to the requirements put in the wrapper by MultiProcessorSiteDirector.
Notes:
* the agent will ignore single processor jobs in order not to interfere with existing production. This can be changed in …

[v6r15] MultiProcessorSiteDirector

---

Resources/Storage/StorageElement.py

For a yet unknown reason, the FTSAgent threads started to step on each other when using the StorageElement. One thread would ask for getFileMetadata, the other one for getURL, but the parameters of the two calls would be swapped (leading to exceptions, and to getFileMetadata returning an URL....). 
I tracked this down to the StorageElementCache not being thread safe, which is now fixed in this PR.

[v6r14] Make the StorageElementCache Thread safe

---

Core/scripts/dirac-install.py

scripts created with dirac-deploy-scripts will attempt to determine platform with `DIRAC.Core.Utilities.Platform.getPlatformString()`. This function uses `libc_ver()` which is fairly long. In user commands, it appends a delay about a few tens of seconds.
This PR caches the platform value at installation time for client installations through the DIRACPLAT environment variable.

[v6r15] Cache DIRACPLAT in client installations

---

Core/Base/AgentModule.py
Core/DISET/private/Service.py
Core/Utilities/Os.py
Core/Utilities/Platform.py
Core/scripts/dirac-info.py
__init__.py

Importing DIRAC module in a scripts implied computing of `DIRAC.platform` with `Platform.getPlatformString()` which is a bit long (see #2854).
This PR hides this field in a variable of the`Platform` module accessible through a `getPlatform()` method. All client scripts will be a few tens of seconds faster than before (except those who explicitly need platform string, like dirac-info).

[v6r15] compute DIRAC platform only when requested

---

Resources/Catalog/FileCatalogClient.py
Resources/Catalog/FileCatalogClientBase.py
Resources/Catalog/LcgFileCatalogClient.py
Resources/Catalog/TSCatalogClient.py

Added default methods needed to be implemented by all the catalogs to be used in standard operations:
hasAccess()
exists()
getPathPermissions
In the default implementations the answer is True to all the requests

[v6r15] Added default methods to the FileCatalogClientBase

---

WorkloadManagementSystem/Executor/JobScheduling.py

All in the title. 
If everything went fine, a bool was returned, otherwise, S_ERROR was. The calling code was expecting only a boolean, which turns out to be True in case of problem.

[v6r14] Properly checks if staging is allowed in JobScheduling

---

Core/Utilities/Subprocess.py

While looking for that memory consumption in the JobWrapper or JobAgent I found two possible issues. I can reliably cause a large memory consumption by starting a JobWrapper and after it ran for a minute or so remove the output folder of the jobwrapper (a folder named with the job id of the jobwrapper). I don't know if something like this is also causing the issue on the grid, but that was the best lead I had and I would like to try this out in reality.
So there are two locations where infinite loops can be caused, and in the first case this leads to an ever growing string.
* dataString can grow infinitely if select.select always returns something. 10000000 is an arbitrary number that is maybe large enough for anybody? text output shouldn't ever be that large on purpose, should it?
* …

[v6r14] Subprocess: Fix two possible infinite loops

---

Resources/Storage/StorageElement.py

In v6r15, the parameters is properly called "plugins", and not "protocols"

[v6r15] Fix bad merge of the SE

---

ResourceStatusSystem/scripts/dirac-rss-sync.py
WorkloadManagementSystem/DB/JobDB.py

The sites that reside in `SiteMask` table of `JobDB` database are taken and inserted (with the appropriate format) to the `SiteStatus` table of `ResourceStatusDB` database.
This is invoked when: `dirac-rss-sync --init` is executed.

 [v6r15] dirac-rss-sync is also syncing sites now

---

Resources/Catalog/LcgFileCatalogClient.py

Inside LcgFileCatalogClient, LFC wrapper does not accept unicode but only string.
This patch converts any basestring to string.

[v6r14] Gives string LFN to LFC

---

Core/DISET/private/Transports/PlainTransport.py
Core/DISET/private/Transports/SSL/SocketInfoFactory.py

Hi,
This is a fix for the IPv6 "Address family not supported by protocol" problems mentioned on the diracgrid-forum mailing list. I think the bug exists in all version which support IPv6.
Regards,
Simon

[v6r15] Fall back to IPv4 only if AF_INET6 doesn't work.

---

WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/ConfigTemplate.cfg

This PR is solving the problem of the sites that are not getting pilots, although not having any waiting pilots, if there are already many pilots sent to other sites. In this case empty sites still will get some pilots at a lower than usual pace

[v6r15] SiteDirector enhanced logic for using empty sites

---

WorkloadManagementSystem/Client/CPUNormalization.py

This function is called in the dirac-wms-cpu-normalization run by pilots. 
Not creating a list with 12.5 million entries saves about 400 MB. Creating this list was not intentional, right?
Proper target branch

[v6r14] dirac-wms-cpu-normalization, reduce memory footprint

---

Resources/Storage/XROOTStorage.py

One fix when downloading from, e.g., castor with xroot protocol where the spaceToken is defined.
And one fix when an error happens during upload

[v6r14] Xroot fixes

---

RequestManagementSystem/scripts/dirac-rms-cancel-request.py
TransformationSystem/Client/TransformationCLI.py

RMS Cancel, also recently reported in diracgrid-forum
TransformationCLI: Protection against missing entry in dict

[v6r14]  Fix for dirac-rms-cancel and TransformationCLI

---

ResourceStatusSystem/Agent/EmailAgent.py

Indication of the setup added (e.g. "LHCb-Production" or "LHCb-Certification").
Now we can distinguish if an email is for a resource monitored in one setup or another.

[v6r15] Setup Indication in Emails

---

DataManagementSystem/Agent/FTSAgent.py
Workflow/Modules/FailoverRequest.py

If a file was not Scheduled, the FTSAgent was setting it Done even if it had not been replicated...
Minor fix in Failover module for forcing setting the input file Unused if it was already set Processed

[v6r14] Fix FTSAgent bug

---

ResourceStatusSystem/PolicySystem/Actions/EmailAction.py

The database can be locked due to concurrency, I added an error message log.
Database locks are different than table locks. In most cases python retries the query automatically as far as I know.

[v6r15] Log message in case the Email cache database is locked

---

.travis.yml
README.rst
pytest.ini
requirements.txt

Use Coveralls for coverage. 
Go to https://coveralls.io/ and link DIRACGrid to coveralls and enable coveralls for the DIRAC and Pilot (I will do it later) repos.
I have already formed the badge to point to the right place.

[v6r14] Enable Coveralls and Landscape

---

docs/Tools/MakeDoc.py
docs/Tools/makeDocs.sh
docs/requirements.txt
docs/source/conf.py
docs/source/fakeEnvironment.py

In the Read the Docs configuration for dirac
under "Admin" and "Advanced settings put "docs/source/conf.py" into "Python Configuration File"
and "docs/requirements.txt" into "Requirements file".
See the result here:
http://diracsailer.readthedocs.io/en/rel-v6r15/CodeDocumentation/index.html
To run this locally:
```
cd DIRAC/docs; READTHEDOCS=True make html
```
I added a MakeDoc script (couldn't figure out the buildCodeDoc). This script creates documentation stumps for all dirac code (except for PlotCache and PlottingHandler and some scripts not in scripts folders, because those crash or hang the sphinx build).

[v6r15] Enable CodeDocumentation via READTHEDOCS

---

DataManagementSystem/Agent/RequestOperations/RemoveReplica.py
WorkloadManagementSystem/Client/CPUNormalization.py

RemoveReplica:
* Some cosmetics
* bulkRemoval() was modifying its input dict argument and returning it: useless, only modify argument
CPUNormalization:
* Get HS06 from JOBFEATURES if present

[v6r14] Fix CPU normalization and few changes in RemoveReplica

---

Core/DISET/RequestHandler.py
FrameworkSystem/private/logging/backends/PrintBackend.py
Resources/Storage/XROOTStorage.py
Resources/Storage/test/Test_XROOTStorage.py

Small fixes aside from that: Replace any file() call with the better construct 'with open()'. (Advantage: Can be mocked easily + cannot forget to close the file)
Fixed 2 bugs in XROOTStorage that were discovered by the unittests.
By doing `sys.modules['moduleName'] = mock`, one can prevent an `import moduleName` statement in another file from being executed (the import is replaced by the mock object). This PR completes the work on this unittest by mocking out all the API calls of the XROOTStorage class (stat, dirlist, ...). This is quite ugly as it requires the test to know how often and in what order each API call is called.
I only focused on getting the tests to work and did not closely look at how much sense the actual unittests make/if they cover all cases, but they seemed fine.

[v6r15] Fix the XROOTStorage unittests by mocking the xrootd import

---

.landscape.yml

Landscape does not work at the moment because there is a missing line for pylint. Sorry was testing on a more advanced example, and then wanted to make it as simple as possible, apparently too simple.

[v6r15] Fix landscape

---

Resources/Storage/DIPStorage.py

In putFile when copying from another DIPStorageElement ( a la third party transfer ), the service name was not properly evaluated, fix for #2413

[v6r14] DIPStorage bug fix

---

WorkloadManagementSystem/Client/WMSClient.py

Strip of comments in the job JDL before submission to the JobManager. In some cases comments are screwing up the job processing

[v6r14] Strip of comments in the job JDL

---

DataManagementSystem/scripts/dirac-dms-replicate-and-register-request.py

We have users who, especially for one off requests, use the dirac-dms-replicate-and-register-request command directly. Right now this command only prints the request name, which doesn't make allowances for duplicate request names. This patch now also prints the requestid(s), giving the user a chance to monitor their request(s).

[v6r15] print request id for replicate and register requests

---

Core/Security/X509Chain.py
docs/source/conf.py

As asked in https://github.com/DIRACGrid/DIRAC/pull/2976#discussion_r66408006
Need to enable this extension: http://www.sphinx-doc.org/en/stable/ext/napoleon.html
Also changed some docstrings to make that work (I am guessing on the types, correct me if they are wrong).
Cf.:
Before:
http://diracsailer.readthedocs.io/en/rel-v6r15/CodeDocumentation/Core/Security/X509Chain.html#DIRAC.Core.Security.X509Chain.X509Chain.generateProxyToFile
After:
http://diracsailer.readthedocs.io/en/docgoogledoc/CodeDocumentation/Core/Security/X509Chain.html#DIRAC.Core.Security.X509Chain.X509Chain.generateProxyToFile

[v6r15] enable google style docstrings

---

Resources/Catalog/FileCatalogClient.py

The File Catalog service interface getFileUserMetadata and getDirectoryUserMetadata methods do not have a standard LFN argument which is a dictionary for the time being. Therefore, the checkCatalogArgument decorator was screwing the client call. Once the service interface will be updated to support bulk query, the client will be updated accordingly with the proper decorator. Fixes #2962

[v6r15] FileCatalogClient fix

---

Resources/Computing/BatchSystems/Torque.py
Resources/Computing/SSHComputingElement.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Modifications in L659 and 666 is necessary to extract output and error files
for all the batch systems.  Result['Value'] is tuple but string is expected to be returned.
Modification in L605 is related to SSHTorque.
The jobStamp of Torque includes hostname of the head node.
But name of output file does not include it. So somehow tricky treatment is necessary.
We confirmed this code is working under Belle II environment.

[v6r14] Bug fix to extract output and error files

---

Core/Utilities/SOAPFactory.py

For some reason in the suds-jurko implementation the extra imports are needed.
Otherwise an AttributeError is thrown.
See: https://github.com/DIRACGrid/Externals/pull/12
With suds
```
In [1]: import suds
In [2]: suds.transport
Out[2]: <module 'suds.transport' from '/home/sailer/software/DIRAC/DiracDevV6r13/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/suds/transport/__init__.pyo'>
In [3]: suds.__version__
Out[3]: '0.4'
In [4]: import suds.transport
In [5]: suds.transport
Out[5]: <module 'suds.transport' from '/home/sailer/software/DIRAC/DiracDevV6r13/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/suds/transport/__init__.pyo'>
```
Additional import doesn't matter, so this is backwards compatible.
with suds-jurko
```
In [1]: import suds
In [2]: suds.__version__
Out[2]: '0.6'
In …
```

[v6r14] Soap with suds-jurko: add imports somehow needed

---

docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/index.rst
tests/Jenkins/utilities.sh

Added `$DEVROOT` to functions `generateCertificates()` and `generateUserCredentials()` to use the correct directory according to developer's guide.

[v6r15] Fixed developer's guide

---

ResourceStatusSystem/scripts/dirac-rss-sync.py
WorkloadManagementSystem/Service/WMSAdministratorHandler.py

Accessing ResourceStatusDB and JobDB through clients rather than directly.
Proper order in the script initialization and import statements

[v6r15] Fix dirac-rss-sync command to not call JobDB directly

---

DataManagementSystem/Utilities/DMSHelpers.py
WorkloadManagementSystem/Executor/JobScheduling.py

Allow staging to take place at an SE accessible by protocol, while until now it was only local. This was preventing a job at NIKHEF to stage at SARA.
After discussion with the reviewer, try and get both the VO and the InputDataPolicy from the job manifest in order to do it more correctly. As the agent is not running with a proxy, Operations() cannot deduce the VO and it should be picked up in the job for multi-VO installations.

[v6r14] Allow staging from an SE accessible by Protocol

---

ResourceStatusSystem/scripts/dirac-rss-set-token.py

The `res[ 'Message' ]` is not an integer value.

[v6r15] Fixed DIRACExit Code

---

DataManagementSystem/DB/FileCatalogComponents/DatasetManager.py

Several callings of "getDatasetParameters" in DatasetManager should be "__getDatasetParameters". "getDatasetParameters" is accepting dataset dict as argument, not a single dataset name.

[v6r15] Fix bugs calling getDatasetParameters in Dataset

---

Resources/Catalog/FileCatalog.py
Resources/Catalog/FileCatalogClient.py

Without this, the checkArgument decorator would throw an error of empty imput

[v6r15] FC: skip execution of method if empty imput

---

Core/Utilities/Mail.py
FrameworkSystem/Client/NotificationClient.py
Interfaces/API/DiracAdmin.py
ResourceStatusSystem/Agent/EmailAgent.py

I added an optional parameter to `Mail.py` and now we can set the MIME type of the email to HTML.
I have also hardcoded the HTML and CSS code in order to send emails that are more readable.
This is how an email should look like now:

[v6r15] Html aggregated notifications in RSS

---

Resources/Storage/ProxyStorage.py

Make sure transferClient connects to the same ProxyStorage instance to which the uploaded/downloaded file has been cached before.
In setups with multiple ProxyStorage instances two independent sURL lookups led to "file not found" errors in case they returned different results.
Should fix: #3020

[v6r14] Make sure transferClient connects to the same ProxyStorage instance

---

Resources/Catalog/ConditionPlugins/ProxyPlugin.py
Resources/Catalog/ConditionPlugins/test/Test_ProxyPlugin.py
Resources/Catalog/FCConditionParser.py

If there is no proxy when the condition is evaluated, return False

[v6r15] FCConditionParser: ProxyPlugin handles the case of having no proxy

---

RequestManagementSystem/Client/Operation.py
TransformationSystem/Client/TaskManager.py
TransformationSystem/Client/Transformation.py
TransformationSystem/Client/test/Test_Client_TransformationSystem.py
docs/source/AdministratorGuide/Systems/Transformation/index.rst

The goal is to stay backward compatible, so we need to identify when we
have a multi-operation request and when the old style is used
And arbitrary chains of requests must be supported. I describe the multiple operations as  list of tuples, where each tuple is a string and a dictionary of parameter and parameter values.
For example
```python
...
transBody = [ ("ReplicateAndRegister", { "SourceSE":sourceSE,
"TargetSE":targetSE }),
("RemoveReplica", { "TargetSE":sourceSE } ),
]
jsonBody = json.dumps( transBody )
trans.setBody( jsonBody )
...
```
Currently defined productions they either have no body, or just a
string, which is not in json format(i.e. `json.loads` fails), so we can use that to differentiate
old and new.
This should allow one to chain all current and future Operations and all …

[v6r15] Add possibility for multiple operations in Data Operation Transformations

---

TransformationSystem/Client/TaskManager.py

The prepareTransformationTasks is always being called with the additional bulkSubmissionFlag argument. https://github.com/DIRACGrid/DIRAC/blob/rel-v6r15/TransformationSystem/Agent/TaskManagerAgentBase.py#L460
This causes an exception for the RequestTaskAgent.

[v6r15] Fix Exception in RequestTaskAgent

---

Resources/Catalog/FileCatalogClient.py

`'Message': 'Unknown method dmeta.getDirectoryMetadata',`
Also want to get userMetadata in this function.

[v6r15] Fix: FCC getDirectoryUserMetadata was not working

---

Resources/Computing/BatchSystems/Condor.py
Resources/Computing/HTCondorCEComputingElement.py
Resources/Computing/test/Test_HTCondorCEComputingElement.py

The output from condor_q/history is not guaranteed to be stable. (as far as I remember it was supposed to change in 8.5, but I don't see any signifcant difference in 8.5.5)
In any case I added "autoformat" calls to condor_q and condor_history to have a guaranteed output from these calls.
Moved parseCondorStatus to BatchSystems/Condor so it can ge re-used.
Also added tests for the getJobStatus functions
Is this needed for v6r14 as well?

[v6r15] HTCondor: more resilient status checking

---

Resources/Computing/CREAMComputingElement.py

printout stdout and stderr for failed calls. (Not entirely sure what is in [1] and what is in [2], or where the commands even put the output on errors, so print both just in case).
first change: the error string is more often in item 1 of `result['Value']`
e.g.:
```
ERROR:  Pilot submission failed with error: 1: 2016-07-26 15:36:56,585 FATAL - Received NULL fault; the error is due to another cause: FaultString=[connection error] - FaultCo
de=[SOAP-ENV:Client] - FaultSubCode=[SOAP-ENV:Client] - FaultDetail=[Connection timed out], 2:
``` 
(added `1:`, `2:` during debugging session)
second change: this was a bug, causing exception.
The 0 item is an int, instead at least 1 should be there

[v6r15] CREAMComputingElement: Fix parsing of return value

---

Core/Utilities/ProcessPool.py
DataManagementSystem/Agent/FTSAgent.py
RequestManagementSystem/Agent/RequestExecutingAgent.py

* When the processing of an operation times out, there was no increment of the attempts done. Now yes.
* Avoid FTS to fetch a request that was canceled (https://groups.google.com/forum/#!topic/diracgrid-forum/J8FOcskLxBU)
This is WIP because I would like @phicharp to double check the fix for FTS, since it is a very tricky system...

[v6r15] RMS TimeOut and FTS Canceled request

---

Resources/Computing/BatchSystems/Condor.py
Resources/Computing/HTCondorCEComputingElement.py
Resources/Computing/test/Test_HTCondorCEComputingElement.py

Can happen if condor_q returns nothing because there are active jobs at the moment.

[6r15] HTCondor: protect against non-standard line in 'job status' list

---

FrameworkSystem/Client/ProxyManagerClient.py
Resources/Computing/ComputingElement.py

Reduce the default length of the payload proxy which is renewed by the pilot to 12 hours. This is the setting which is defined by the /Registry/DefaultProxyLength option. The previous default was set to 1 day which is equal or even longer than VOMS extension length for some VOs. This prevented the use of the proxy cache in the ProxyManager not letting of any length margin. The length in the proxy cache in the ProxyManagerClient is reduced to just 4 hours ( from 12 hours ), to have garanteered caching even in case of shortened by VOMS proxies.

[v6r15] Reduce the default length of the payload proxy 

---

Core/Utilities/DErrno.py
Resources/MessageQueue/MQConnection.py
Resources/MessageQueue/MQConnectionFactory.py
Resources/MessageQueue/MQListener.py
Resources/MessageQueue/MQPublisher.py
Resources/MessageQueue/StompMQConnection.py
Resources/MessageQueue/Utilities.py
Resources/MessageQueue/test/Test_MQ_test.py
docs/source/AdministratorGuide/DIRACSites/ComputingElements/index.rst
docs/source/AdministratorGuide/DIRACSites/MessageQueues/index.rst
docs/source/AdministratorGuide/DIRACSites/StorageElements/index.rst
docs/source/AdministratorGuide/DIRACSites/index.rst
docs/source/DeveloperGuide/AddingNewComponents/Resources/MessageQueues/index.rst
docs/source/DeveloperGuide/AddingNewComponents/Resources/index.rst
docs/source/DeveloperGuide/AddingNewComponents/index.rst

This PR replaces #2985, which was badly screwed by a faulty rebase. All the comments from #2985 are either incorporated or answered. 
This PR contains classes for managing MQ connections as DIRAC Resources. The current implementation is only for the Stomp MQ protocol which is provided by the RabbitMQ. This is a wrapper over the MQConnection classes by Sergio as in #2974, and replaces this PR.
Users are supposed to use MQListener and MQPublisher classes which can be used as simply as the following:
publisher = MQPublisher( "MyQueue" )
listener = MQListener( "MyQueue" )
publisher.put( message )
listener.get( message )
Or:
publisher = MQPublisher( "MyQueue" )
listener = MQListener( "MyQueue", callback = myCallback )
publisher.put( message )
listener.run()
Example of the MQ configuration …

[v6r16] MessageQueue resources

---

Core/scripts/dirac-configure.py
Core/scripts/dirac-install.py
Core/scripts/install_full.cfg
Core/scripts/install_minimal.cfg
Core/scripts/install_secondary.cfg
docs/source/AdministratorGuide/CommandReference/dirac-install.rst
docs/source/AdministratorGuide/InstallingDIRACService/index.rst
docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
docs/source/DeveloperGuide/DevelopmentModel/DIRACProjects/index.rst

This fix the issue reported #2099. The backward compatibility is kept. But there is one exception:
dirac-install --extraModules 
I assume we are using -e instead of --extraModules.

[v6r16] Change ExtraModule to Extensions

---

Core/Utilities/Graphs/__init__.py
FrameworkSystem/Client/ProxyManagerClient.py

On some installations the matplotlib default configuration can point to some interactive backend which can be in the way for DIRAC ploltting services

[v6r15] Graphs - force matplotlib to use Agg backend

---

Core/scripts/dirac-install.py

if a variable is not set (t)csh aborts with an error message
```
LD_LIBRARY_PATH: Undefined variable.
LD_LIBRARY_PATH: Undefined variable.
```

[v6r15] cshrc: protect against undefined variables

---

DataManagementSystem/Service/FileCatalogHandler.py

First argument is always turned into dict by checkCatalogArgument decorator in the client

[v6r15] FileCatalog: fix expected type for getAncestor, getDescendents,

---

Core/DISET/AuthManager.py
Core/test/Test_AuthManager.py

Added a possibility to authorize access to a service method by the caller VO and/or group. The authorization rule is described as, for example:
Authorization
{
myMethod = NormalUser, vo:lhcb, group:biomed_user
}    
In the example above, the myMethod can be called by a user with a group that has NormalUser property, but in addition the user must belong either to VO lhcb or to group biomed_user. This can be useful to limit certain services to the use by a given VO or group. For example, a VO specific file catalog or service from a VO specific extension in a multi-VO environment. 
In the special case of using host certificates, the authorization can be described with group:hosts special property which means that the call must come from a host. This more general solution replaces the Host …

[v6r15] Service authorization rules per VO and group

---

ConfigurationSystem/Client/Helpers/Resources.py
Resources/Computing/ARCComputingElement.py
Resources/Computing/ComputingElement.py
Resources/Computing/ComputingElementFactory.py

This PR allows to define site-wide CE parameters in the section:
/Resources/Sites/_grid_/_site_/CEs
CE parameters specific for a given type for the whole DIRAC installation can be defined in the section:
/Resources/Computing/_ceType_

[v6r15] Site-wide and global CE parameters

---

Resources/Computing/HTCondorCEComputingElement.py
docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst
docs/source/AdministratorGuide/Configuration/ConfReference/Resources/index.rst

Add CS options:
* add extraOption string to the submission file, based on the ARCCE implementation.
* set working directory where the pilot logs etc. are kept
* make the time to keep logs configurable
I place this for now in Computing/CEDefaults, because the ARC extraString was there too, but maybe this should go to Operations somewhere?
Add documentation page for CEDefaults

[v6r15] HTCondorCE: Make better configurable

---

FrameworkSystem/Service/SystemAdministratorHandler.py

The `infoResult['Value']` contains the DIRAC version and Setup information which needs to be passed forward as well

[v6r15] HostLogging: Bring back version and setup information

---

WorkloadManagementSystem/Agent/JobCleaningAgent.py
WorkloadManagementSystem/ConfigTemplate.cfg
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Agents/JobCleaningAgent/index.rst

This update adds an option (disabled by default) to remove Jobs from the dirac server irrespective of their state.
We found this useful for cleaning a large backlog of jobs that had been in the Waiting state for 3+ months.
Also updated the default polling time for this agent, as Job ages are given in days and a default polling time of 120 s seems excessive.
Updated the documentation to list all options for this agent.

[v6r15] JobCleaningAgent: Option for removing Jobs in other states

---

DataManagementSystem/scripts/dirac-dms-remove-replicas.py
Resources/Computing/HTCondorCEComputingElement.py

HTCondorCE: If the WorkingDirectory does not end with a slash the location is changed
dirac-dms-remove-replicas: correct sorted arguments

[v6r15] fixes for condor log/out files location and dirac-dms-remove-replicas

---

TransformationSystem/Agent/ValidateOutputDataAgent.py

Gone for almost 2 years.. this agent really needs to be reviewed because it does nothing

[v6r15] ValidateOutputDataAgent: use the shifter proxy

---

DataManagementSystem/Client/DataManager.py

DataManager.putAndRegister : An UnboundLocal Error may be thrown because of the unreasonable location of variable ‘errStr’.

[v6r15] Fix a bug for DataManager

---

FrameworkSystem/scripts/dirac-admin-get-CAs.py
WorkloadManagementSystem/JobWrapper/WatchdogFactory.py

dirac-admin-get-CAs: log with notice, so information is printed by default
Otherwise the script is silent and a bit confusing for users, or is someone using this in a cronjob and wants it to be quiet except for errors?
Watchdog: FIX exception: Cannot concatenate string and exception objects
(Not sure why the subClassName is twice in that string in line 40)

[v6r15] fix for Watchdog factory, tweak for dirac-admin-get-CAs

---

Core/Utilities/PrettyPrint.py

Makes tables look like this:
```
StorageElement         Size                  Replicas
==========================================================
1 KEK-SRM                  326,232,223,288,747  1086987
2 PNNL-SRM                  16,360,823,970,918    65734
3 gw38.hep.ph.ic.ac.uk               9,953,385        5
4 polgrid4.in2p3.fr            144,026,824,484     2589
5 CERN-DST-EOS             160,052,209,973,062  3732108
```

[v6r15] printTable: Right align numbers, left align other things

---

Resources/Computing/HTCondorCEComputingElement.py

return error if no path was found. Prevent crash in getJobOutput function.

[v6r15] HTCondor: check that some path was found in findFile

---

Core/DISET/private/BaseClient.py

Avoid that when logging ```res['Message']```
2016-08-23 12:32:54 UTC DataManagement/FTSAgent/Monitoring  ERROR: Can't send activities marks Can't connect to dips://lbvobox23.cern.ch:9142/Framework/Monitoring: {'Errno': 0, 'Message': "Could not connect to (
'lbvobox23.cern.ch', 9142): ('128.142.154.93', 9142): Can't connect: [Errno 111] Connection refused", 'OK': False, 'CallStack': ['  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/threading.py", line
783, in __bootstrap\n    self.__bootstrap_inner()\n', '  File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/threading.py", line 810, in __bootstrap_inner\n    self.run()\n', '  File "/opt/dirac/pro/Linux
_x86_64_glibc-2.12/lib/python2.7/threading.py", line 763, in run\n    self.__target(*self.__args, **self.__kwargs)\n', …

[v6r15] BaseClient: proper error propagation

---

Resources/Computing/ARCComputingElement.py

Hi,
This patch changes the mapping of pilots in the hold state on the ARC-CE so they get mapped to Failed and correctly removed from the queue (up to now, they'd sit in the hold state for ever preventing any further jobs from being submitted). It also removes the JobSupervisor object from the killJob function as this didn't seem to work correctly (or at all) in my tests, whereas cancelling the jobs individually does seem to work.
Regards,
Simon

[v6r15] Fix ARC held jobs

---

Resources/Computing/ARCComputingElement.py

This patch ensures that pilot jobs that are queued also get their proxies renewed on ARC-CE.
Regards,
Simon

[v6r15] Renew ARC pilots in the queued state.

---

DataManagementSystem/Client/FTSJob.py
DataManagementSystem/Client/ftsSSLWrapper.py

use requests with no server verification, and add temporary fix for fts-rest
The use of requests is needed because of the memory leak and on top of this we are now for some reason hit by another curl bug (https://curl.haxx.se/mail/lib-2008-09/0197.html)
There is however a bug in the fts-rest library which does not propagate the server verification flag. I have made a PR, but until they merge it and release it (3.5.2, a month from now) I have added the fix in DIRAC (ftsSSLWrapper). As soon as we have the proper release in the bundle, we can remove this file.
This is an important PR, it should be in the next patch, it runs as hotfix in LHCb

[v6r15][IMPORTANT] FTS: use requests library

---

Resources/Catalog/FileCatalogClient.py

There should be some way to ensure that all functions are in the lists...
( This is not part of #3095, https://github.com/DIRACGrid/DIRAC/pull/3095/files#diff-38faa43f37e89cea3917fb128720076dR33 )

[v6r15] Add getFileDescendents/Ancestors to READ methods for FileCatalog

---

Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Agent/SiteDirector.py

This patch ensures that a proxy of at least 3 hours is available to the updatePilotStatus function so that if it renews any proxies (via ce.getJobStatus), it's not renewing them with a very short proxy (which causes expiry problems on the ARC-CE).

[v6r15] Fix proxy renewal (for ARC-CE)

---

WorkloadManagementSystem/DB/JobDB.py
WorkloadManagementSystem/Executor/JobScheduling.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Executors/JobScheduling/index.rst

Commit ac6bff55380a2edddcf0ad4f3952d5a8c8c834fc tidied up the JobScheduling code but also changed the behaviour. The original behaviour was that if only an unknown site was specified in the JDL (i.e. the site wasn't banned or active) the job would be held with a "no active sites" style message. The new behaviour is that unknown sites in the JDL are accepted into the waiting state, which can lead to jobs being left waiting for a site that doesn't exist indefinitely.
This patch returns the original behaviour: It's slightly longer than the original code as it distinguishes between all of the possible failure modes (wrong site names / banned sites) while also avoiding getting the (potentially long) list of all active sites.
The patch also adds a new config option "AllowInvalidSites" …

[r6v15] Correctly handle invalid sites in JobSchduling

---

DataManagementSystem/Client/DataManager.py
TransformationSystem/Agent/TransformationAgent.py
WorkloadManagementSystem/Client/InputDataByProtocol.py

* DataManager: was extremely slow when checking active replicas and filtering tape replicas. Probably due to changes in the cached information from RSS?
* TransformationAgent: no need to get replicas URLs back, and use iterators when possible
* IDR: the failed resolution for local SEs was not considered correctly if there were other SEs that were ignored (e.g. because on tape). This the catalogs were incomplete

[v6r15] Fix TransformationAgent, DataManager and IDR by protocol

---

Core/Base/AgentModule.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Agents/index.rst

This patch adds a simple SIGALRM based watchdog option to the base agent code. This allows a hard timelimit to be set on each run so that it should be impossible for a module (such as the site director) to get stuck forever if there is a bug (if the watchdog time expires, the process is killed and then restarted by runit). The watchdog time limit is configurable in the same way MaxCycles etc. are and we've left the default as 0 (meaning disabled) so that no behaviour is changed by this patch automatically.
The main reason for this is as a workaround for a bug in the ARC code where sometimes contacting an ARC CE causes a infinite hang in the site director, but it should also catch any other future problems like this. We'll send a more specific e-mail about the ARC problem separately next …

[v6r15] Add agent watchdog option

---

Core/Utilities/DErrno.py
Core/Utilities/ElasticSearchDB.py
FrameworkSystem/Service/SystemAdministratorHandler.py
MonitoringSystem/Client/Types/BaseType.py
MonitoringSystem/Client/Types/ComponentMonitoring.py
MonitoringSystem/DB/MonitoringDB.py
WorkloadManagementSystem/Agent/StatesMonitoringAgent.py

Added a periodic task to the SysAdmin service (can be enabled from CS by setting a flag, just like the pseudostatic monitoring) that retrieves profiling information from running components and sends it to a RabbitMQ queue for later storage in ElasticSearch.
Requires PR's #2924 and #3106 to be merged before.

[v6r16] DynamicMonitoring task in SysAdmin

---

Core/Utilities/TimeLeft/LSFTimeLeft.py
Core/Utilities/TimeLeft/test/Test_LSFTimeLeft.py
Core/Utilities/TimeLeft/test/Test_TimeLeft.py
WorkloadManagementSystem/Client/CPUNormalization.py

Pilot matching with KEK fails because the CPUTime returns -1, which results in a negative remaining time...
At the moment the LSFTimeLeft only accepts 4 "words" in the bqueues output, however at KEK there are just two pieces
I.e. KEK gives this
```
2016-09-13 16:11:50 UTC WorkloadManagement/JobAgent/LSFTimeLeft DEBUG:  CPULIMIT
2016-09-13 16:11:50 UTC WorkloadManagement/JobAgent/LSFTimeLeft DEBUG:  720.0 min
```
While at CERN (don't have any other LSF based systems).
```
CPULIMIT
15.0 min of KSI2K
```

[v6r15] LSFTimeLeft accept 2 "word" output from bqueues

---

Core/scripts/dirac-install.py

Allow to define the installation path in the $DIRAC env variable before sourcing bashrc/cshrc. This helps to define community bashrc file when the client is installed from CVMFS.
Allow to override releases.cfg with a local file

[v6r15] Minor changes to installation scripts

---

DataManagementSystem/Client/FTSJob.py

From FTS server 3.5, the behavior changed with respect to the checksum type. To avoid that, always specify it

[v6r15] FIX FTS: specify checksum type at submission

---

Core/scripts/dirac-install.py

Take into account the command line specified version of LcgBundle in dirac install

[v6r15]  fix dirac-install

---

DataManagementSystem/scripts/dirac-dms-find-lfns.py
FrameworkSystem/private/logging/Message.py
WorkloadManagementSystem/Agent/StalledJobAgent.py

* dirac-dms-find-lfns was not working: make it partly work. However the quoted example doesn't work (filter CreationDate<2015-05-15 doesn't work)
* StalledJobAgent: send a kill signal to the job before setting it Failed. This should prevent jobs to continue running after they have been found Stalled and then Failed.
https://its.cern.ch/jira/browse/LHCBDIRAC-554
* Avoid space at the end of a gLogger message when the variable message is void

[v6r16] Various fixes

---

FrameworkSystem/scripts/dirac-proxy-init.py

Hi,
We frequently have users run into problems because their CRLs have expired. This patch updates the CA and CRL bundles as part of the dirac-proxy-init process if none of the files in the certificates directory have been updated for 28 days. This should avoid the problem and not break things if they users have installed fetch-crl or some other method of updating the CRLs.
Regards,
Simon

[v6r17] Update CAs when running dirac-proxy-init if they are out-of-date.

---

Resources/Computing/SudoComputingElement.py

Testing on SL6 turned up a difference in the way sudo works between SL6 and cernvm3 (which simulates SL6). X509_CERT_DIR must be explicitly passed through in this case, as normal SL6 is more restrictive.

[v6r17] Pass X509_CERT_DIR during sudo for SL6

---

WorkloadManagementSystem/Client/SandboxStoreClient.py

Hi,
We found that the web/webapp interface would still return the original output sandbox after a job had been reset. This was being caused by the inMemory = True flag (which is only set by the web interface, all other clients seem to use inMemory = False) causing the loop in downloadSandboxForJob to return after one iteration. This patch moves the inMemory case, making it only return the newest sandbox, fixing the problem.
Regards,
Simon

[v6r15] Ensure the newest sandbox is returned to the client

---

ConfigurationSystem/Client/CSAPI.py

We noticed that we couldn't modify a value that exists in the CS but was empty. This patch fixes this (and shouldn't break anything else).

[v6r15] changed so it works on empty but existing options in config system

---

Resources/Catalog/LcgFileCatalogClient.py

Prior to v6r15, LcgFileCatalogClient.exists() worked with [{lfn: False}] given by checkArgumentFormat.
Because checkCatalogArguments, which has been introduced since v6r15, gives [{lfn: True}], exists() attempts to evaluate the boolean as GUID and results in crash.
We should avoid the evaluation if GUID is given by non-string.

[v6r17] Do not evaluate GUID in LcgFileCatalogClient if it is not a string

---

DataManagementSystem/Client/DataManager.py
Interfaces/API/Dirac.py
StorageManagementSystem/Agent/StageMonitorAgent.py
StorageManagementSystem/Agent/StageRequestAgent.py
StorageManagementSystem/DB/StorageManagementDB.py
StorageManagementSystem/scripts/dirac-stager-monitor-file.py
StorageManagementSystem/scripts/dirac-stager-monitor-jobs.py
StorageManagementSystem/scripts/dirac-stager-monitor-request.py
StorageManagementSystem/scripts/dirac-stager-monitor-requests.py
StorageManagementSystem/scripts/dirac-stager-show-stats.py
StorageManagementSystem/scripts/dirac-stager-stage-files.py

* Stager: mostly streamline code, but also monitor files even when there is no requestID (dCache returns none when staging a file that is already staged!)
* DataManager: add key argument forJobs (default False) in getReplicas() in order to get only replicas that can be used for jobs (as defined in  the CS)
Use this feature in the API as well (default unchanged except for splitting where it is set to True)

[v6r17] Fixes in Stager and DataManager

---

AccountingSystem/Agent/NetworkAgent.py
AccountingSystem/Agent/__init__.py
AccountingSystem/Agent/test/Test_NetworkAgent.py
AccountingSystem/Client/DataStoreClient.py
AccountingSystem/Client/Types/BaseAccountingType.py
AccountingSystem/Client/Types/Network.py
AccountingSystem/ConfigTemplate.cfg
AccountingSystem/private/Plotters/NetworkPlotter.py
ConfigurationSystem/ConfigTemplate.cfg
Core/Utilities/Graphs/GraphData.py
Core/Utilities/Graphs/QualityMapGraph.py
Core/Utilities/Graphs/__init__.py
Resources/MessageQueue/MQConsumer.py
Resources/MessageQueue/StompMQConnector.py
Resources/MessageQueue/test/Test_StompMQConnection.py

I am pushing a new functionality to plot the data gathered by perfSONARs. It allows to present jitter, one-way delay, packet-loss rate and some derived functions.
In the current version DataStore is supplied by NetworkAgent module which does not use the RabbitMQ client provided by DIRAC. Please treat this module (and its requirements i.e. stomp.py=3.1.6, messaging, numpy) as a temporary solution.
Some changes were also needed in the core DIRAC modules but I've tried to make them transparent, so I don't expect any troubles after integration.

[v6r18] Network plots

---

Resources/Storage/GFAL2_XROOTStorage.py

This fix allows to use the GSI authentication instead of the krb one. It is needed for all the interactive use of dirac.

[v6r17] Allow interactive use of xroot plugin

---

Resources/Storage/GFAL2_StorageBase.py

As the title state, it allows ipv6 machine only to work. Problem reported by @rajanandakumar

[v6r17] Enable IPV6 for gsiftp

---

Core/scripts/dirac-deploy-scripts.py
Core/scripts/dirac-install.py

1. It turns out that on recent MacOS ( Darwin version > 10.10 ), the behavior of "/usr/bin/env python" changed preventing finding the python interpreter in the $PATH. As a result the native python is picked up which is compiled differently, e.g. using UCS2 Unicode string treatment. The PR defines explicitely the python interpreter to be used in the DIRAC commands.
2. os.system() normally uses the environment from the calling shell. However DYLD_LIBRARY_PATH, for some obscure reason is not passed from the calling shell to the subshell of the os.system() command in Darwin > 10.10. In the PR DYLD_LIBRARY_PATH is set right in the os.system() command.
The changes should not affect non-MacOS environments.

[v6r17] Fix scripts deployment for MacOS

---

Core/Utilities/Proxy.py

This change allows to pass a lock object to a function call decorated with @executeWithUserProxy. The actual function will be executed with this lock. E.g.:
res = getFilesToStage( inputData, proxyUserName = userName, proxyUserGroup = userGroup, executionLock = lockObject  )
Or just pass it as a string, then no lock object should be created beforehand:
res = getFilesToStage( inputData, proxyUserName = userName, proxyUserGroup = userGroup, executionLock = 'ThisParticularLock'  )

[v617] executionLock optional argument to executeWithUserProxy()

---

FrameworkSystem/private/logging/Logger.py
TransformationSystem/Client/TaskManagerPlugin.py
TransformationSystem/Client/test/Test_Client_TaskManagerPlugin.py
docs/source/AdministratorGuide/Systems/Transformation/index.rst

* In gLogger.<into|warn|...>: return True if the message was printed, False if not
Useful to make differentiate printout according to print level
* In mesh processing, allow to redefine the AutoAddedSites for each type (in particular set it empty)

[v6r17] Minor change in gLogger and mesh processing

---

WorkloadManagementSystem/PilotAgent/pilotCommands.py

That was not using the bashrc from dirac-install. This is probably the cause of the failure in using GFAL2 up to now.

[v6r17] Corrected setting of pilot environment

---

DataManagementSystem/Utilities/DMSHelpers.py
TransformationSystem/Agent/TransformationAgent.py
TransformationSystem/Client/Utilities.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Agents/transformationagent.rst

* Prepare for changing the name of some CS parameters for TransformationAgent: MaxFiles is used for 2 things:
1. Maximum number of files to be considered by the TSAgent -> MaxFilesToProcess
Add possibility to define it for each plugin as well. Can still use old name MaxFiles if not set
2. Maximum number of files in a task -> MaxFilesPerTask
Only in Operations section TransformationPlugins. Can still use old name MaxFiles if not set
* In the case when the plugin adds files to the transformation (LHCb has a use case), only consider the initial files in the tasks for defining the number of Unused files.

[v6r17] Fix TS

---

FrameworkSystem/private/SecurityFileLog.py

Hi,
When the security logs are rotated, the buffer size used is ~2GiB... This seems excessive and on our installation causes the gzip to fail most of the time; any buffer larger than the compression block size should be just as good (>64KiB). This patch lowers the buffer size to 1MiB,
Regards,
Simon

[v6r17] Lower security log gzip memory usage

---

Resources/Computing/CREAMComputingElement.py

Hi,
We found that when a large number of pilot jobs have been submitted to a single CREAM-CE (O(10k-40k)), the proxy renewal can start to fail silently. It appears the problem is caused by a timeout on the server if the list of proxies to be renewed is too long... It works through the list of delegation IDs in sequence and then just gives up part way through resulting in a large number of pilots getting killed. This patch splits the renewals into chunks to avoid the problem. We've picked 10 as a modest chunkSize and tested it extensively: The glite-ce-proxy-renew doesn't seem to have very much overhead, so relatively small chunks are still fairly efficient.
Regards,
Simon

[v6r17] Split CREAM proxy renewal into chunks for improved reliability

---

docs/Tools/fakeEnvironment.py
docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst

replace unicode with quotes
replace symlink with content, solves problems for some eclipse users
The scripts from the Tools folder should move to source so that the two different fakeEnvironment files are no longer necessary.

[v6r17] fixes in documentation

---

AccountingSystem/Service/DataStoreHandler.py
docs/source/AdministratorGuide/Systems/Accounting/index.rst

In case when one DataStore can not scope with the load, we can install multiple helper DataStore services. These services are only inserting the records to the appropriate table. The master service will do the bucketing.

[v6r17] allow to run multiple DataStore

---

Core/Utilities/PrettyPrint.py
Core/scripts/dirac-info.py
WorkloadManagementSystem/scripts/dirac-admin-show-task-queues.py

1. Allow to pass list of values for one field value. In this case values are printed out one per line within the table slot
2. One can pass as a value a dict where justification of the printout for this particular value can be specified ( L or R or C ), for example, { "Value": value, 'Just': 'L' }
3. dirac-info and dirac-admin-show-task-queues commands updated to make use of these features.
An example output of dirac-admin-show-task-queues command:
This PR replaces #3285 from which most of the improvements are imported.

[v6r17] printTable utility enhanced

---

Interfaces/API/Dirac.py

As per https://github.com/DIRACGrid/DIRAC/issues/3280

[v6r18] Expose the protocol parameter of getAccessURL in the API

---

DataManagementSystem/Agent/FTSAgent.py
DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py
DataManagementSystem/Client/FTSClient.py
RequestManagementSystem/Agent/RequestExecutingAgent.py
RequestManagementSystem/Client/ReqClient.py
RequestManagementSystem/DB/RequestDB.py
RequestManagementSystem/Service/ReqManagerHandler.py

We want to be able to run 2 FTSAgents, one for Failover requests, one for other requests (mostly DM transformations). 
This PR modifies the getRequestIDsList() method to get also the JobID in the returned tuple. 
The FTSAgent has a new CS parameter ProcessJobRequests (default None, i.e. same behavior as before). If True, it processes the Job requests only, if False it doesn't process them.
Beware that it is not possible to run 2 agents that process the same requests.
The FTSAgent is getting a list twice as large as the MaxRequests, filters out the requests that it needs and then reduces it after being filtered to MaxRequests

[v6r17] New feature in FTSAgent

---

Resources/Storage/GFAL2_StorageBase.py

Hi,
If the space token is set to an empty string in GFAL2, some SEs (dCache at least) return a "space token not found" error. This patch simply only sets the space token if there is one, which fixes the problem.
Regards,
Simon

[v6r17] Fix GFAL2 space tokens for some SEs

---

StorageManagementSystem/Client/StorageManagerClient.py
StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
WorkloadManagementSystem/Executor/JobScheduling.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Executors/JobScheduling/index.rst

* Add a CS flag to decide whether to check only replicas at tape SEs or all replicas. Default is to test only at Tape SEs
* If any file is not in the FC, make the job Failed instead of looping infinitely
* Avoid checking files if one replica was already found Online
* restrict usage of decorator to strict minimum, i.e. calling the SE.getFileMetadata

[v6r17] Fix JobScheduling

---

DataManagementSystem/DB/FileCatalogComponents/FileManager.py
DataManagementSystem/DB/FileCatalogComponents/WithFkAndPs/FileManagerPs.py

All in the title.
Sorry there's a lot of space removing, but the relevant changes are these
```
[chaen@pclhcb31 DIRAC]$ git diff  --ignore-all-space  HEAD~1
diff --git a/DataManagementSystem/DB/FileCatalogComponents/FileManager.py b/DataManagementSystem/DB/FileCatalogComponents/FileManager.py
index f3f7123..44fe5c3 100755
--- a/DataManagementSystem/DB/FileCatalogComponents/FileManager.py
+++ b/DataManagementSystem/DB/FileCatalogComponents/FileManager.py
@@ -80,7 +80,7 @@ class FileManager( FileManagerBase ):
for fileName in dirDict[dirPath]:
fname = '%s/%s' % (dirPath,fileName)
fname = fname.replace('//','/')
-          failed[fname] = 'No such directory'
+          failed[fname] = 'No such file or directory'
else:
directoryPaths[directoryIDs[dirPath]] = dirPath
directoryIDList = …
```

[v6r18] Return standard error message in the FC

---

requirements.txt

Otherwise the new 6.0 is taken by default, and not compatible with python < 3.3

[v6r17] Restrict ipython version to 5.3.0

---

docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/stuffThatRun.rst
requirements.txt
tests/Jenkins/utilities.sh

Allwo to choose how long a host certificate will be valid in the jenkins functions

[v6r18] generateCertificates accepts validity as parameters

---

Core/Utilities/ProcessPool.py
DataManagementSystem/scripts/dirac-admin-allow-se.py
RequestManagementSystem/Agent/RequestExecutingAgent.py
RequestManagementSystem/private/RequestTask.py
StorageManagementSystem/Client/StorageManagerClient.py
StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
WorkloadManagementSystem/Client/DownloadInputData.py
WorkloadManagementSystem/Executor/JobScheduling.py

* ProcessPool: fix the finalization
* DownloadInputData: metadata keys were used as Storage Elements in case of failure. Make the check... This would fix JIRA issue https://its.cern.ch/jira/browse/LHCBDIRAC-663
* JobScheduling: 
- try and select replicas for staging at the same site as online files
- put sites holding data before others in the list of available sites

[v6r17] Fixes in ProcessPool, DownloadInputData in JobScheduling

---

Resources/Computing/CREAMComputingElement.py

Hi,
When the pilot output is missing from the CREAM service for any reason (normally if the admin requests it immediately after a job finishes, before the CE has had a chance to copy it back to the head node), the text "Standard Output is not available on the CREAM service" gets permanently cached as the output (and there is then no way of getting the pilot output, even if it becomes available on the CE).
This patch changes this behaviour so that the missing output is returned as a proper error; preventing it from being cached. Later attempts at fetching the pilot output then actually try to fetch it from the CE again.
Regards,
Simon

[v6r17] Return error when pilot output is missing

---

Core/Utilities/Adler.py

Sometimes a file can have a checksum with less than 6 char
e.g.
intAdler = 198772
hex( intAdler & 0xffffffff ).lower()
'0x30874'
Notice only 5 char after 0x
Now current code gives
hex( intAdler & 0xffffffff ).lower().replace( 'l', '' ).replace( 'x', '0' )[-8:]
0030874
i.e. 7 char instead of 8 char
This line gives desired 8 char long string by pre pending extra 0
hex( intAdler & 0xffffffff ).lower().replace( 'l', '' ).replace( 'x', '0000' )[-8:]
'00030874'
8 char is important because gfal-sum returns 8 char long string in this case.

Fixing checksum to be 8 char long in Core/Utilities/Adler.py

---

WorkloadManagementSystem/Executor/JobSanity.py
WorkloadManagementSystem/Executor/JobScheduling.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Executors/JobSanity/index.rst
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Executors/JobScheduling/index.rst

Hi,
This code enhances the JobScheduling executor to check the platform specified by the user is actually available at a subset of the sites they've picked. The new tests are only enabled if CheckPlatform = True (default is False) in the CS, so backwards compatibility is maintained. I've removed the old "PlatformCheck" stub from the JobSanity module as this was never implemented and it makes more sense to do it in the JobScheduling module after the list of active sites for the job has been retrieved.
At the same time I've also adjusted the code so that the job manifest is only fetched once, which simplifies some of the other functions slightly.
Regards,
Simon

[v6r17] Implement PlatformCheck code in JobScheduling module.

---

Core/Base/API.py

these functions are called by pickling or deepcopy
solve an issue when the lgger somehow contains a thread.lock object
Solves #3334

[v6r17] API: implement __getstate__, __setstate__

---

Interfaces/scripts/dirac-framework-self-ping.py

All in the title.
And shows very useful for various operational aspects:
* supervision of the containers in Mesos
* CERN load balancing alias selection.

[v6r17] Add a script for a server to self ping using it's own certificate

---

FrameworkSystem/Utilities/MonitoringUtilities.py

Hi,
When installing DIRAC from scratch, the CS isn't initialised fully when running dirac-setup-site (which currently causes a crash on unknown key 'username'). This patch sets a suitable "unknown" username if that is the case, which is enough to get things to bootstrap correctly.
Regards,
Simon

[v6r17] Framework Monitoring - Set username to unknown if CS not fully initialised yet.

---

Core/Utilities/Grid.py

Hi,
Some ARC-CEs have SubClusters where the name isn't set to the hostname of the machine, while this configuration is unusual, there are a few UK CEs that have this quirk. This patch changes the LDAP filter to find the SubClusters based on the ClusterUniqueID (which is always set to the CE hostname) rather than directly on the SubCluster name. As far as I can tell, this doesn't slow down the LDAP search compared to the original filter.
Regards,
Simon

[v6r17] Fix BDII subcluster discovery for some ARC-CEs

---

Core/scripts/dirac-install-client.py
ResourceStatusSystem/Utilities/Synchronizer.py
ResourceStatusSystem/scripts/dirac-rss-sync.py
Resources/Computing/ComputingElement.py
WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Client/Matcher.py
WorkloadManagementSystem/Executor/JobScheduling.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py
__init__.py

1. Few fixes to facilitate dirac-rss-sync command for Sites
2. Allow WholeNode and NumberOfProcessors job JDL parameters instead of the correponding tags 
3. One more case of using SiteMask directly corrected in the JobScheduling executor
4. Introduced QueryCEFlag that can be defined on the level of the CE CS parameters. If evaluated positively ( by default ), the SiteDirector will attempt to get the CE status from the CE itself. In the opposite case, the CE status is evaluated from the information on pilots in PilotAgentsDB. This can be used to avoid direct interrogation of the pilots status at certain CEs that are not providing exact information or otherwise vulnerable, e.g. ARC CEs 
5. Small fix for #3273 in dirac-install-client

[v6r18] More RSS fixes to facilitate Sites/CEs synchronization

---

ResourceStatusSystem/Client/SiteStatus.py

Hi,
When testing v6r18 without the RSS, I found that if a job had InputData, then all sites were being seen as "banned" (so the job was held). I tracked it down to a missing parameter to getSiteMask, so that instead of getting banned sites, it gets all of the sites listed in the DB... This patch fixes the problem.
Regards,
Simon

[v6r18] Fix missing parameter in RSS getSiteMask call

---

WorkloadManagementSystem/PilotAgent/dirac-pilot.py
WorkloadManagementSystem/PilotAgent/pilotTools.py

Hi,
While testing GFAL2, we've found that the PYTHONPATH setting from the base worker-node software (at some sites, mainly ones that use it from CVMFS) causes DIRAC to load the wrong gfal2 library at runtime and segfault (when instantiating the GFAL2_SRM2 plugin for example). This patch adds an option to the pilot to clear the PYTOHNPATH at the start of the dirac-pilot.py which fixes this problem. (I wonder if this should actually be the default behaviour: It seems unlikely that the PYTHONPATH from the WN will ever have anything useful to DIRAC on it).
Regards,
Simon

[v6r18] Add option to clear PYTHONPATH on pilot start

---

Core/Base/Client.py
Core/DISET/RPCClient.py
Core/DISET/ThreadConfig.py
Core/DISET/private/BaseClient.py
Core/DISET/private/InnerRPCClient.py
docs/source/DeveloperGuide/Internals/Core/index.rst
docs/source/DeveloperGuide/Internals/index.rst
docs/source/conf.py

"Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live." Luckily, I do not know the address ... :-)
This is just pure documentation of how the client side works when you perform an RPC call. probably more will come.
I also introduce a change in the config of sphinx to add the graphviz module. I've checked, and it is supported by readthedoc (http://docs.readthedocs.io/en/latest/builds.html#packages-installed-in-the-build-environment)
As a general note: we have a problem with the images we put in the doc. They are PNG, and once they are in, no one has anymore the original file to modify it. If we use a descriptive language like dot directly inside the documentation, anyone can modify it very easily. So I propose we use that when …

[v6r18][please merge quickly] Document Low level client classes

---

ResourceStatusSystem/Client/ResourceStatus.py

Hi,
It seems the patch in #3367 didn't actually fix the problem I was having... When I started testing it, I was still getting the "WriteAccess" key error, due to a bad return from the RSS:
```
x = ResourceStatus()
x.getElementStatus("UKI-LT2-IC-HEP-disk", "StorageElement", "WriteAccess")              
{'OK': True, 'Value': {'UKI-LT2-IC-HEP-disk': {'A': 'Active', 'c': 'Active', 'e': 'Active', 'i': 'Active', 's': 'Active', 'r': 'Active', 't': 'Active', 'W': 'Active'}}}
```
This patch checks the statusType type and changes it to a list if needed, which then gives the expected output:
```
x = ResourceStatus()
x.getElementStatus("UKI-LT2-IC-HEP-disk", "StorageElement", "WriteAccess")
{'OK': True, 'Value': {'UKI-LT2-IC-HEP-disk': {'WriteAccess': 'Active'}}}
```
Regards,
Simon

[v6r18] Fix RSS statusType if it isn't a list.

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE

As discussed today this is the PR template that is the basis for the auto generation of release notes.
This will appear in all future PRs, users only need to fill it out.
I have also added some basic contributing guidelines. A link to this .md file will appear when you want to start a new PR.

[integration] Add PR template and contributing guidelines

---

WorkloadManagementSystem/Agent/SiteDirector.py

Local Condor batchsystem added to the condition in addition to HTCondorCE, for it also has the same feature.
* WorkloadManagementSystem
FIX: SiteDirector - unlink is also to be skipped for Local Condor batchsystem

[v6r17] SiteDirector to skip unlink for Local Condor batchsystem

---

ConfigurationSystem/Client/PathFinder.py
ConfigurationSystem/Client/test/Test_PathFinder.py
Core/DISET/private/BaseClient.py
FrameworkSystem/Client/ComponentInstaller.py
docs/source/AdministratorGuide/Configuration/ConfReference/Operations/index.rst
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/index.rst

NEW: Allow to define FailoverURLs and to reference MainServers in the URLs
@andresailer  @petricm  : Can I put more explanation here outside of the two marks ? I will do, and remove if needed.
Basically, this is what was agreed to simplify the management of the orchestrators, and its behavior (copy/paste of the doc) is illustrated by this example:
```
System
{
URLs
{
Service = dips://$MAINSERVERS$:1234/System/Service
}
FailoverURLs
{
Service = dips://failover1:1234/System/Service,dips://failover2:1234/System/Service
}
}
Operations
{
Defaults
{
MainServers = gateway1, gateway2
}
}
```
This results in all calls going to ```dips://gateway1:1234/System/Service, dips://gateway2:1234/System/Service ``` and if it fails, it will try to go to …

[v6r18] Allow for FailoverURLs and for MainServers

---

docs/Tools/GetReleaseNotes.py
docs/source/DeveloperGuide/DevelopmentModel/ReleaseProcedure/index.rst

This script uses the github api (via curl) to get the release notes for pull requests that were merged since a given date.
You need to get your github Personal Access Token from here https://github.com/settings/tokens
And put it in the place the script expects:
```
Filename: GitTokens.py
Content:
GITHUBTOKEN = "e0b83063396fc632646603f113437de9"
```
(this is some git sha, not my PAT)
The output from the script needs to be copied to the `release.notes` file by hand
At least two things need to be fixed:
Possibly:
See output below. Please have a look @atsareg @fstagni 
anything else you would like the script to do?
There are no two PRs targeting the same system so the collation of changes for a single system is not tested
Right now this produces:
```
[integration]
[rel-v6r18]
*Core
FIX: …
```

[v6r18] Add script to get release notes from pull requests

---

RequestManagementSystem/Agent/RequestExecutingAgent.py

For duplicate requests this continue was just going back to `while True` so we would just try the same `request` over and over
*RMS
FIX: Fix infinite loop for duplicate requests in RequestExecutingAgent

[v6r17] RequestExecutingAgent: Fix infinite loop

---

Core/scripts/dirac-install.py

*Core
NEW: dirac-install will change the shebang of the python scripts to use the environment python instead of the system one

[v6r19] Dirac install: change shebang of python scripts

---

Core/Utilities/ClassAd/ClassAdLight.py
WorkloadManagementSystem/DB/JobDB.py
WorkloadManagementSystem/Utilities/ParametricJob.py

Fixes to the problems reported in the DIRAC User Forum:
https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/9iGEXrVRDQ8
https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/vwyevuhWIyA
*Core
FIX: ClassAdLight - getAttributeInt() and getAttributeFloat() return None if the corresponding JDL attribute is not defined
*WMS
FIX: JobDB - fix the case where parametric job placeholder %j is used in the JobName attribute
FIX: JobDB - take into account that ClassAdLight methods return None if numerical attribute is not defined
FIX: ParametricJob utility - fixed bug in evaluation of the ParameterStart|Step|Factor.X job numerical attribute

[v6r17] Fixes for parametric jobs treatment

---

Resources/Computing/LocalComputingElement.py

jobIDs need to start with ssh even for LocalComputingElement because of hardcoding in `pilotCommands.__setFlavour` (https://github.com/DIRACGrid/DIRAC/issues/3392)
*Resources
FIX: jobIDs for LocalComputingElement adapted to what are set by pilotCommands

[v6r17] LocalComputingElement jobIDs to start with ssh

---

Resources/Computing/LocalComputingElement.py

jobIDs to be passed to `batch.getJobStatus` should be the original IDs, not the ones cooked into the DIRAC convention
*Resources
FIX: LocalComputingElement to use the original jobIDs in getJobStatus

[v6r17] LocalComputingElement to use the original jobIDs in getJobStatus

---

MonitoringSystem/Client/MonitoringReporter.py

FIX: When MQ is not used, then do not try to close the connection

[v6r17] When no MQ is used then do not try to close the connection

---

FrameworkSystem/private/standardLogging/Logging.py
FrameworkSystem/private/standardLogging/LoggingRoot.py
FrameworkSystem/test/testLogging/Test_ConfigForExternalLibs.py
FrameworkSystem/test/testLogging/Test_DisplayOptions.py
FrameworkSystem/test/testLogging/Test_Levels.py
FrameworkSystem/test/testLogging/Test_LogRecordCreation.py
FrameworkSystem/test/testLogging/Test_Logging.py
FrameworkSystem/test/testLogging/Test_SubLogger.py
Resources/Computing/BOINCComputingElement.py
Resources/MessageQueue/StompMQConnector.py
Resources/Storage/GFAL2_StorageBase.py
docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst

This pull request mainly concerns the following code which caused a double display of each log: 
`import logging`
`logging.basicConfig(...)`
These lines are replaced by a gLogger method which enables or disables the display of the logs providing by all the external libraries. I also added a test class for this new method and updated the documentation.
By the way, I change the test path from *FrameworkSystem/test/testLogging/tests/* to *FrameworkSystem/test/testLogging/*

[v6r19] Fix the import logging issue

---

docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst

This is just a little but important correction in the gLogger documentation.

[v6r19] Correct the documentation about the centralized backends

---

ConfigurationSystem/Client/test/Test_PathFinder.py
Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/GFAL2_StorageBase.py
Resources/Storage/StorageElement.py
Resources/Storage/test/Test_StorageElement.py
WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py
docs/source/AdministratorGuide/Systems/DataManagement/index.rst

This implements the logic that we will need in FTS to do something else than srm to srm. 
There's a huge caveat though: even if a protocol is third party capable, it does not mean that the storage implements it. For example, dCache does not have third party for xroot. Uncool... 
The method is not used yet in FTS.
It appears like there are many changes in the tests, but it is mostly replacing the mock of the CS with an actual cfg file (just discovered that recently :-) ), and add tests for this new method at the very end. 
Implement the logic to generate pair of URLs to do third party copy. This will be used mostly by FTS, but is not enabled as of now
*Resources
NEW: New method in the StorageElement to generate pair of URLs for third party copy …

[v6r19] StorageElement: method to generate pairs of URLs for third party copy

---

WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Executor/JobScheduling.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py
WorkloadManagementSystem/PilotAgent/pilotTools.py

This PR is replacing #3433 and #3398. It fixes the pilot local configuration with respect to Tags, RequiredTag and multi-processor related settings. Tags are also properly taken into account in the SiteDirector logic.
*WMS
FIX: pilotTools,pilotCommands - pick up all the necessary settings from the site/queue configuration
related to Tags and multi-processor
CHANGE: pilotCommands - removed debug and useServerCerticate configuration from CheckCECapabilities and CheckWNCapabilities as this is done in ConfigureBasics
FIX: SiteDirector - aggregate tags for the general job availability test
FIX: JobScheduling - bug fix in __sendToTQ()

[v6r19] Fix RequiredTag and multi-processor Tags

---

DataManagementSystem/Agent/FTSAgent.py
DataManagementSystem/Client/DataManager.py
DataManagementSystem/Client/FTSRequest.py
Interfaces/API/Dirac.py
Resources/Storage/SRM2Storage.py
Resources/Storage/StorageElement.py
StorageManagementSystem/Client/StorageManagerClient.py
StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py
TransformationSystem/Client/TransformationCLI.py
TransformationSystem/Client/Utilities.py
TransformationSystem/DB/TransformationDB.py
WorkloadManagementSystem/Client/DownloadInputData.py
WorkloadManagementSystem/Client/InputDataByProtocol.py
WorkloadManagementSystem/Executor/InputData.py
WorkloadManagementSystem/Executor/JobScheduling.py

* DMS
CHANGE: as se.getStatus() always returns S_OK, return directly the values. Remove the checks of OK everywhere
* TS
FIX TransformationDB.py: set the ExternalID before the ExternalStatus in order to avoid inconsistent tasks if setting the ExternalID fails
* StorageManagementSystem
FIX StorageManagementClient.py: return the full list of onlineSites while it was previously happy with only one

[v6r17] Return directly status in se.getStatus()

---

DataManagementSystem/Client/DataManager.py
DataManagementSystem/scripts/dirac-dms-add-file.py

Based on a user request. Default behaviour is unchanged.
NEW:  Added option (-f) to force an overwrite of an existing file in dirac-dms-add-file

[v6r17] add force overwrite option to dirac-dms-add-file

---

WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/DB/JobDB.py
WorkloadManagementSystem/Service/MatcherHandler.py

This prevents SiteDirector cycle interruption in case some queue does not have MaxTotal|WaitingJobs options defined
*WMS
FIX: SiteDirector - if MaxWaitingJobs or MaxTotalJobs not defined for a queue, assume a default value of 10
FIX: MatcherHandler - preprocess resource description in getMatchingTaskQueues()
FIX: JobDB - set CPUTime to a default value if not defined when rescheduling jobs

[v6r19] SiteDirector - give default values to MaxTotal|WaitingJobs

---

FrameworkSystem/Agent/TopErrorMessagesReporter.py

*Framework
FIX: TopErrorMessagesReporter - more precise selection to please stricter versions of MySQL

[v6r19] TopErrorMessagesReporter fix

---

WorkloadManagementSystem/Agent/StalledJobAgent.py
WorkloadManagementSystem/Client/DownloadInputData.py

*WMS
CHANGE: Job parameters report successful downloads but not failed ones! Add them
CHANGE: If no PilotReference found in jobs parameters, do as if there would be no pilot information, i.e. set Stalled job Failed immediately

[v6r17] Add info on failed downloads in job parameters

---

FrameworkSystem/Client/ProxyGeneration.py

Fixes #3472
*Framework
CHANGE: Proxies are now RFC by default, `dirac-proxy-init --legacy/ -L` to disable RFC

[v6r19] make proxies RFC by default

---

WorkloadManagementSystem/DB/JobDB.py
WorkloadManagementSystem/DB/tests/Test_JobDB.py
WorkloadManagementSystem/Executor/InputData.py

The JobScheduling Executor doesn't do the same cleanup of "LFN:/vo/user/u/username/lfn.root" that the InputData Executor is doing
https://github.com/DIRACGrid/DIRAC/blob/9ed6247ad8d0a35e1b20b13d28b24fe98d0ce84f/WorkloadManagementSystem/Executor/JobScheduling.py#L153-L172
Which then causes problems in getFilesToStage.
Instead of adding the cleanup to the JobScheduling, I propose to do it once in the JobDB function where the inputData is coming from
*WMS
FIX: JobDB.getInputData now returns list of cleaned LFNs strings, possible "LFN:" prefix is removed

[v6r19] InputData/JobScheduling Executor, jobDB, clean lfn strings once

---

StorageManagementSystem/Client/StorageManagerClient.py
StorageManagementSystem/Client/test/Test_Client_StorageManagementSystem.py

*SMS
FIX: Fix logic for JobScheduling executor when CheckOnlyTapeSEs is its default `true` and the lfn is only on a tapeSE
In The StorageManagerClient getFilesToStage:
There is a bug in this code deciding if files are online or offline. Our JobScheduling doesn't work for files that have a single replica that is on a TapeSE. And we have `checkOnlyTapeSEs` at the default value (True).
https://github.com/DIRACGrid/DIRAC/blob/e42de42d462007eb21ff8bde2790e8790b52f078/StorageManagementSystem/Client/StorageManagerClient.py#L143-L152
At the moment our LFN is simply ignored, because `checkOnlyTapeSEs` is true, but `diskSE` is false, so the lfn is neither in `onlineLFNs` nor in `filesToCheck`
These are all the possible combinations, assuming `diskIsOK = …

[v6r17] StorageManagerClient: fix logic for checking files on tapeSEs

---

DataManagementSystem/Client/FTSRequest.py
DataManagementSystem/Service/FTS3ManagerHandler.py

We get this exception while trying to install FTS3Manager
```2017-10-11 12:56:07 UTC Framework/SystemAdministrator ERROR: Uncaught exception when serving RPC Function setupComponent
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 256, in __RPCCallFunction
uReturnValue = oMethod( *args )
File "/opt/dirac/pro/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py", line 132, in export_setupComponent
result = gComponentInstaller.setupComponent( componentType, system, component, getCSExtensions(), componentModule )
File "/opt/dirac/pro/DIRAC/FrameworkSystem/Client/ComponentInstaller.py", line 1911, in setupComponent
result = self.installComponent( componentType, system, component, extensions, componentModule, checkModule )
File …
```

[v6r20] FTS3Manager fix type exception

---

DataManagementSystem/Agent/FTS3Agent.py

When the policy was not defined in the CS, it crashed:
```
File "/scratch/workspace/DIRAC_v6r20_INTEGRATION/ServerInstallDIR/DIRAC/Core/Base/AgentReactor.py", line 83, in loadAgentModules
result = instanceObj.am_initialize()
File "/scratch/workspace/DIRAC_v6r20_INTEGRATION/ServerInstallDIR/DIRAC/Core/Base/AgentModule.py", line 174, in am_initialize
result = self.initialize( *initArgs )
File "/scratch/workspace/DIRAC_v6r20_INTEGRATION/ServerInstallDIR/DIRAC/DataManagementSystem/Agent/FTS3Agent.py", line 61, in initialize
self._serverPolicy = FTS3Utilities.FTS3ServerPolicy(srvList, serverPolicy = serverPolicyType)
File "/scratch/workspace/DIRAC_v6r20_INTEGRATION/ServerInstallDIR/DIRAC/DataManagementSystem/private/FTS3Utilities.py", line 275, in __init__ …
```

[v6r20] FTS3: add a default ServerPolicy type in the agent

---

Core/LCG/GOCDBClient.py

Hi,
This is just a quick patch to add extension & scope element support when querying services in GOCDB. We will use this functionality in a GridPPDIRAC module, but thought the patch may be useful to other people in the future.
Regards,
Simon
*Core
FIX: Add extensions & scope tag support to GOCDB service queries.

[v6r17] Add EXTENSIONS and SCOPES tags to GOCDBClient.py parsing.

---

DataManagementSystem/scripts/dirac-admin-allow-se.py

*DMS
FIX: dirac-admin-allow-se: fix crash because of usage of old RSS function

[v6r19] allowSE script: fix crash because of wrong function name

---

WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py

Hi,
While testing v6r19 we found our MultiProcessorSiteDirectors were throwing the following exception:
```
File "/opt/dirac/DIRAC/WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py", line 27, in getQueues
for queueName in self.queueDict:
RuntimeError: dictionary changed size during iteration
```
This patch fixes this issue by moving all deletes outside of the loop.
Regards,
Simon
FIX: Fix dictionary changed size exception in MultiProcessorSiteDirector

[v6r19] Fix 'dictionary changed size' error in MultiProcessorSiteDirector

---

ConfigurationSystem/Client/Helpers/Resources.py

Hi,
We found another place where Tags was treated specially but RequiredTags wasn't... This patch fixes it.
Regards,
Simon
FIX: Fix RequiredTags for Resources Helpers getQueue function

[v6r19] Fix RequiredTags in Resource helpers

---

setup.py

I would like to add a first version of setup.py.
It contains no dependency, does not distributes the tests, and distributes the scripts with their `py` extension.
*None
NEW: add dummy setup.py

[v6r19] add setup.py

---

Interfaces/API/Dirac.py
Interfaces/API/test/Test_DIRAC.py

I get an exception in my agent when trying to get the jobJDL(see below)
I guess in other places this works if DIRAC.Interfaces.API.Job.Job is imported from the calling module.
*API
FIX: fix exception when using Dirac.Job.getJobJDL
```
2017-11-03 15:30:16 UTC ILCTransformation/DataRecoveryAgent ERROR: Agent exception while calling method <bound method DataRecoveryAgent.execute of <DataRecoveryAgent.DataRecoveryAgent object at 0x7ff603de8950>>
File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 320, in am_secureCall
result = functor( *args )
File "/opt/dirac/pro/ILCDIRAC/ILCTransformationSystem/Agent/DataRecoveryAgent.py", line 283, in execute
self.treatProduction( int(prodID), transName, transType )
File …
```

[v6r19] API.Dirac.__getJDLParameters: fix isinstance check for class

---

Resources/Computing/ARCComputingElement.py
WorkloadManagementSystem/Agent/SiteDirector.py

```
2017-11-05 22:48:26 UTC WorkloadManagement/SiteDirectorArc ERROR: Agent exception while calling method <bound method SiteDirector.execute of <SiteDirector.SiteDirector object at 0x7fd0db4a7910>>
File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 320, in am_secureCall
result = functor( *args )
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 386, in execute
result = self.updatePilotStatus()
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 1159, in updatePilotStatus
result = ce.getJobOutput( pRefStamp )
File "/opt/dirac/pro/DIRAC/Resources/Computing/ARCComputingElement.py", line 413, in getJobOutput
self.usercfg.ProxyPath(os.environ['X509_USER_PROXY'])
File …
```

[v6r19] Fix exception in SiteDirector for updatePilotStatus

---

Core/DISET/private/Transports/SSL/SocketInfoFactory.py

This check is meaningless at this stage. And, TBH, LHCb currently struggles in having GSI 0.6.5 :-) 
*Core
CHANGE: version check of GSI at run time is removed

[v6r19] Core: remove hard check of GSI version at run time

---

DataManagementSystem/scripts/dirac-dms-user-lfns.py

without a leading \* for the wildcard no matches were ever found unless the full path is specified or '\*' is prepended in the wildcard expression. This makes the wildcard more intuitive to use, will not affect anybody negatively. Full path will still match even with leading '\*'
*DMS
CHANGE: dirac-dms-user-lfns: the wildcard flag will always assume leading "\*" to match files, unless the full path was specified in the wildcard no files were previously matched

[v6r19] dirac-dms-user-lfn: always prepend '*' for wildcard

---

Core/scripts/dirac-deploy-scripts.py
Core/scripts/dirac-install.py

Joining the pylint rush :) . This fix allows to write commands with module names like dirac_xxx_yyy.py. While installation the command wrappers will be anyway generated as dirac-xxx-yyy, so no surprises for the users. The modules can be renamed except for dirac-install.py and dirac-deploy-scripts.py for the moment. Once the new versions are in place ( in a release ), original dirac-install.py and dirac-deploy-scripts.py can be also renamed.
*Core
CHANGE: dirac-deploy-scripts, dirac-install - allow command modules with underscores in their names in order for better support for the code checking tools 

[v6r20] Allow command modules with underscores in the names

---

Core/Utilities/DErrno.py
WorkloadManagementSystem/Service/JobManagerHandler.py
WorkloadManagementSystem/Utilities/ParametricJob.py
WorkloadManagementSystem/Utilities/test/Test_ParametricJob.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Services/JobManager/index.rst

The MaxParametericJobs configuration option defines the limit for the number of jobs that can be submitted in one go.
*WMS
FIX: JobManagerHandler - restored the use of MaxParametricJobs configuration option
CHANGE: ParametricJob - added getParameterVectorLength() to replace getNumberOfParameters with a more detailed check of the job JDL validity

[v6r19] Restored parametric jobs limit

---

Core/DISET/private/Transports/SSL/SocketInfo.py

Hi,
A very quick fix for a log message... I was debugging something for one of my users and found the DIRAC tools printing "ASD" to my console :-)
Regards,
Simon
*Core
FIX: Log proper message on cadir init failure.

[v6r19] Log proper message on cadir initalisation failure

---

WorkloadManagementSystem/DB/JobDB.py

Hi,
We've found the getSiteSummaryWeb function throws an exception if someone has submitted a job with only one '.' character in the name, this patch fixes the problem.
Regards,
Simon
FIX: Don't trigger exception in webSummary if a site with a single dot is in the system.

[v6r19] Fix web summary exception when site only has single dot

---

WorkloadManagementSystem/Agent/SiteDirector.py

Hi,
We've found that the SiteDirectors crash in v6r19p6 when they try to submit pilots due to a problem with string substitutions in the pilot template; this patch fixes the problem.
Regards,
Simon
FIX: Correct escaping in SiteDirector pilot template

[v6r19] Fix escaping in sitedirector pilot template

---

ConfigurationSystem/Client/Helpers/Resources.py

Hi,
Yet another RequiredTags fix unfortunately... There was an edge case that if the tags were set on the queue (rather than the CE), the required tags would cause the tags list to be overwritten with the original string. There was a bit of logic that should have been outside of the loop (so it doesn't overwrite the updates on the second go around).
Regards,
Simon
FIX: Don't overwrite queue tags if requiredtags are set.

[v6r19] Don't overwrite tags if requiredtags are set.

---

README.rst

Redo.
Better like this ? 
*Documentation
CHANGE: point README to master and add badges for integration

[v6r19] DOC: point README to master and add badges for integration

---

WorkloadManagementSystem/ConfigTemplate.cfg
WorkloadManagementSystem/DB/JobDB.py

Hi,
Following the release of v6r19p7 we noticed that the dirac-admin-get-site-mask command started returning permission denied for normal users. We traced this to a change in the function used (getSiteMask -> getSiteMaskStatus). I can't see any problems with allowing authenticated users access to the getSiteMaskStatus function by default (it gives basically the same information as getSiteMask), although I did notice it has some SQL escaping issues, which this patch also fixes.
Regards,
Simon
FIX: Allow user access to getSiteMaskStatus

[v6r19] Allow user access to getSiteMaskStatus

---

Resources/Computing/CREAMComputingElement.py
docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst

This PR ads a possibility to define extra CREAM job JDL parameters for a given queue of a CREAM CE. The option can contain several JDL parameters separated by ; . For example:
Resources
{
...
Queues
{
pbs-cream-gpu
{
ExtraJDLParameters = GPUProcessors=1; YetAnotherParameter="value"
}
}
...
}
*Resources
FIX: CREAMComputingElement - added CS option for extra JDL parameters 

[v6r19] CS option for extra JDL parameters for a CREAM CE

---

FrameworkSystem/scripts/dirac-proxy-init.py

Hi,
I would like to suggest increasing the CRL update frequency in dirac-proxy-init... We've found that CERN updates their CRLs every 3.5 days, so the in-built 28 day limit is not much help there. I thought about ways that the algorithm could be improved, but I couldn't think of any improvements beyond just decreasing the time (ideally it would just always pull individual CRLs that are nearing the expiry time, but that would require a lot of changes to bundle delivery (to allow pulling single files)) .
Regards,
Simon
*Framework
CHANGE: Increase dirac-proxy-init CRL update frequency

[v6r19] Increase dirac-proxy-init CRL update frequency

---

DataManagementSystem/Utilities/DMSHelpers.py

* DataManagementSystem
FIX: recursive resolution of SEGroup was keeping the SEGroup in the list

[v6r19] Fix recursive resolution of SEGroup

---

Interfaces/API/Job.py
WorkloadManagementSystem/DB/JobDB.py

*Interfaces
CHANGE: using the deprecated decorator for 2 deprecated methods
*WMS
FIX: fixed typo in JobDB().getSiteMaskStatus() method

[v6r19] Bug fix, deprecating 2 methods in Job.py

---

ResourceStatusSystem/Client/SiteStatus.py
WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/DB/JobDB.py

Hi,
I finally finished tracking this down, it turns out there were two bugs, one triggered by the other (if the RSS is inactive):
* SiteStatus.getSiteStatuses expects a list (if it's given a string, it loops over each character).
* getSiteMaskStatus would crash if the given string was for a site which didn't exist (if it's given a single character as a site name, for example).
This patch fixes the above two issues.
Regards,
Simon
FIX: Fix getSiteMaskStatus in SiteDirector and MultiProcessSD

[v6r19] Fix getSiteMaskStatus call in SiteDirector

---

DataManagementSystem/Service/StorageElementHandler.py

Methods of the DIRAC StorageElement service getFreeDiskSpace() and getTotalDiskSpace() are reimplemented without input arguments. The return values are always in MB. 
The MaxStorageSize CS option is now taken into account when reporting free and total space. The check of available disk space when adding new files is also taking into account the MaxStorageSize, however to avoid massive failures after the update only warning is printed if MaxStorageSize is exceeded while there is still enough available disk space. In the next releases this will become an error 
*DMS
NEW: StorageElement service - getFreeDiskSpace() and getTotalDiskSpace() take into account MAX_STORAGE_SIZE parameter value

[v6r20] DIRAC StorageElement report for free and total disk space

---

Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/SRM2Storage.py
Resources/Storage/StorageBase.py
StorageManagementSystem/Agent/StageRequestAgent.py

Because of some hardcoded path, the protocols list for SRM2 was not correctly inherited.
This PR fixes this issue.
It also makes the Stager survive inheritance
I tested the SRM change with our integration tests
*Resources
FIX: Use parameters given at construction for SRM2 protocols List
*StorageManagement
FIX: use StorageElement object to get disk cache size

[v6r19] Fix inheritance of SRM2 protocols List

---

Core/Utilities/MySQL.py

This exception is presumably provoking freezing the FileCatalog service because of an unreleased lock. 
*Core
FIX: MySQL - catch exception when closing closed connection

[v6r19] MySQL - catch exception when closing closed connection

---

WorkloadManagementSystem/JobWrapper/WatchdogLinux.py

Calls to /usr/bin/free happened to fail under unknown circumstances, generating exceptions that were setting the job as "Failed", while the same job happily completed later.
*Subsystem
CHANGE: using python modules in WatchdogLinux instead of shell calls

[v6r20] using python modules in WatchdogLinux

---

FrameworkSystem/private/standardLogging/Logging.py
FrameworkSystem/test/testLogging/Test_DisplayOptions.py
Resources/LogBackends/AbstractBackend.py

*Framework
FIX: Remove the space after log messages if no variable message is printed, fixes #3587 

[v6r19] Logging: add space after message only if varmessage is not empty

---

.gitignore
Core/Utilities/JEncode.py
Core/Utilities/test/Test_Encode.py
docs/README
docs/source/DeveloperGuide/Internals/Core/ClientServer.rst
docs/source/DeveloperGuide/Internals/Core/Serialization.rst
docs/source/DeveloperGuide/Internals/Core/index.rst
docs/source/DeveloperGuide/Internals/index.rst

This PR contains all the code necessary to perform JSON serialization enhanced with datetime and custom types.
I added a doc about the serialization in general.
Tests are updated as well.
This code is still not used anywhere. It will be enabled progressively. 
Future PRs to come.
@andresailer @petricm : you guys are the doc experts. I desperately tried to add a link to the code documentation (using `:py:mod`) but miserably failed. Any hint ? Thanks
*Core
NEW: JEncode for json based serialization

[v6r20] Add JEncode for json serialization

---

Core/Utilities/DEncode.py

BILD SPOILER ALERT:
we want to be able to spot where a serialization that would fail or be incorrect in json happens in DISET.
There are currently 2 known cases: tuples, dictionaries whose keys are numbers.
This PR adds a function that will print the callstack as well as the arguments of the call when such cases are met. The output looks something like that:
```
============================================= Encoding tuples =============================================
File "/tmp/ping.py", line 2, in <module>
print RPCClient('dips://lbtestvobox.cern.ch:9197/DataManagement/FileCatalog').ping()
File "/home/chaen/dirac/DIRAC/Core/DISET/RPCClient.py", line 43, in __call__
return self.__doRPCFunc( self.__remoteFuncName, args )
File "/home/chaen/dirac/DIRAC/Core/DISET/RPCClient.py", line 88, in …
```

[v6r20] Print DEncode traceback information

---

RequestManagementSystem/Agent/RequestExecutingAgent.py

There is still this crazy bug in the processPool that the result queue can return True when calling `empty`, and have a non zero size when asking for `size`. 
This shows as such in the logs
```
2018-01-14 13:01:14 UTC RequestManagement/RequestExecutingAgent/ProcessPool WARN: Results queue is empty but
has non zero size: 8 
```
When this happens, there is absolutely nothing that can be done to unlock the situation, and the agent should just exit. Up to now, we were returning S_ERROR, hopping that starting a new loop would help, but it does not.
So now we just exit all together, and wait for runit to restart.
*RMS
FIX: Really exit the RequestExecutingAgent when the result queue is buggy

[v6r20] RMS: exit the REA when the result queue is buggy

---

FrameworkSystem/private/standardLogging/Formatter/JsonFormatter.py
FrameworkSystem/private/standardLogging/Handler/MessageQueueHandler.py
Resources/LogBackends/MessageQueueBackend.py
requirements.txt

This PR just adds functionality. It allows to send JSON formatted logs to Message queues. Tested in LHCb certification setup.
Requires https://github.com/DIRACGrid/Externals/pull/33
*Framework
NEW: add JsonFormatter for logs
CHANGE: MessageQueue log handler uses JsonFormatter

[v6r20] Logging: add JSON log formatter for the MQ Handler

---

Core/scripts/dirac-distribution.py

*Core
FIX: Provide the extjs path correctly to WebAppDIRAC

[v6r20] fix wrong indentation

---

WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py

Hi,
We found that when a job was submitted with a multiprocessor tag and another tag (for example "8Processors" and "GPU"), no pilots would be generated. I've tracked this down to the MultiProcessorSiteDirector using "Tags" instead of "Tag" in the task-queue dictionaries (SiteDirector, where getQueues is inherited from uses "Tag"). It also only set the ceDict Tag field with multi-processor only ones in one place, which prevents matching too.
This patch changes the code to use "Tag" in the right places (unfortunately "Tags" is still used by the Matcher, so both still appear in various places in the file) and fixes the ceDict to have all CE tags.
Regards,
Simon
FIX: Allow non-processor related tags to match TQ in MPSiteDirector.

[v6r19] Fix non-processor related tags in MPSiteDirector

---

WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
WorkloadManagementSystem/Agent/SiteDirector.py

Hi,
This adds a kwargs parameter to getExecutable and _getPilotOptions in the SiteDirector, which contains job processor count in the MultiProcessorSiteDirector.
This will allow us to pass through to the new maxNumberOfProcessors pilot option in the GridPPDIRAC module without having to override the whole of the submitJobs function (without this we would be unable to get the number of processors in our overridden getPilotOptions function).
Regards,
Simon
CHANGE: Allow kwargs to SiteDirector getExecutable & _getPilotOptions functions.

[v6r19] Pass optional extra flags to getExecutable function in SiteDirector

---

DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py

fix a bug in the ReplicateAndRegister  preventing requests to be retried
Files failing once would never be attempted anymore
* RMS
FIX: Fix a bug in ReplicateAndRegister Operation preventing files having failed once to be retried

[v6r19] RMS: fix a bug in the ReplicateAndRegister 

---

DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql

In prod for LHCb
*DMS
FIX: Fixes for the DFC to be compatible with strict group by mode (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by)

[v6r19] DFC: compatibility with MySQL 5.7

---

WorkloadManagementSystem/PilotAgent/pilotCommands.py
WorkloadManagementSystem/PilotAgent/pilotTools.py

Hi,
We found a couple of minor bugs while testing the new maxNumberOfProcessors flag... It has to be cast to an int at one place to avoid an exception. It also seems that the -P option is passed through to dirac-install (due to code at https://github.com/DIRACGrid/DIRAC/blob/rel-v6r19/WorkloadManagementSystem/PilotAgent/pilotCommands.py#L184 ), I wasn't sure if this was actually used anywhere, so I didn't want to change it. Instead I've simply changed the short code for maxProcs to be -m instead.
Other than this, the maxNumberOfProcs code all seems to work perfectly.
Regards,
Simon
FIX: Cast maxNumOfProcs to an int.
CHANGE: Change maxNumOfProcs short option from -P to -m.

[v6r19] Minor fixes for maxNumberOfProcessors flag

---

docs/source/UserGuide/Tutorials/JDLsAndJobManagementBasic/index.rst

*docs/source/UserGuide/Tutorials/JDLsAndJobManagementBasic/index.rst
FIX: corrected typo: availablae → available

[integration] typo fix

---

Core/scripts/dirac-externals-requirements.py
docs/source/DeveloperGuide/DevelopmentModel/DIRACProjects/index.rst
releases.cfg

The dirac-external-requirements command is restored. It is called in the end of the dirac-install process to collect all the extra python modules requested in the DIRAC package and in the extension packages. It allows to define extra python module dependencies in the releases.cfg of each package
and not put it into the Externals. 
*Core
CHANGE: dirac-external-requirements - reimplemented to use preinstalled pip command rather than 
the pip python API 

[v6r20] dirac-external-requirements restored

---

FrameworkSystem/Client/ComponentInstaller.py

NEW: add default configuration to CS: only TrustedHost can upload file

[v6r20] only TrustedHost can use upload

---

ConfigurationSystem/private/ConfigurationData.py

Our master CS regularely gets stuck with two error messages:
```
FATAL: Cannot write new configuration to disk! file XYX
ERROR: Can't verify proxy or certificate file XYZ:No certificate loaded ( 1105 : )
```
Not terribly useful. Since the first error can only happen at one place, I log a bit more info. it is running as hotfix in LHCb
CHANGE: Better logging of the Configuration file write exception

[v6r19] Configuration: log the exception when not able to write the cfg file

---

DataManagementSystem/Agent/RequestOperations/RemoveReplica.py

FIX: fix typo in monitoring activity name

[v6r20] Fix typo in monitoring activity name

---

container/Dockerfile

cd commands don't cross RUN commands.
FIX: Dockerfile

Fix broken Dockerfile

---

Resources/MessageQueue/StompMQConnector.py
docs/source/AdministratorGuide/DIRACSites/MessageQueues/index.rst

DIRAC logs were unreadable with the stomp logging, so I conditioned them to an environment variable.
Most of the changes are autopep8. I modified the doc accordingly
*Resources
CHANGE: enable Stomp logging only if DIRAC_DEBUG_STOMP environment variable is set to any value

[v6r20] Environment variable for stomp logging

---

Resources/Computing/SingularityComputingElement.py

When we try to test singularity CE, we could not pass the installation step from inner container. Because we are using BES installation and the versions are set multiply like "v0r17, v6r20pre14".
The original codes can only deal with pure DIRAC installation and single version. For our case it will try to execute "`./dirac-install.py -r v0r17,v6r20-pre14 -i 27 -e BES`", which will fail soon.
After this modification, it will execute "`./dirac-install.py -V BES -r v0r17 -i 27 -e BES`" and works properly.
*WMS
FIX: SingularityComputingElement: Install DIRAC from inner singularity does not work correctly for generic VO installation

[v6r20] Generic to VO DIRAC installation in singularity

---

WorkloadManagementSystem/Agent/SiteDirector.py

When a site is running with multi-vo mode, the value of totalSlots is possible to get minus. When getting minus, the site will never get chances to submit pilots again because no case there to deal with minus. The possible reason about this situation is when two instances of SiteDirector are checking and submiting pilots for a nearly full queue, one could possily get a value of totalJobs more than real value.
totalSlots = min( (maxTotalJobs - totalJobs), (maxWaitingJobs - waitingJobs) )
This situation can be solved when returning totalSlots to zero 
*Subsystem
For examples look into …

a bug in multi-vo mode when counting totalslots

---

Interfaces/API/Dirac.py

*Interfaces
CHANGE: Saving output of jobs run with 'runLocal' when they fail (for DEBUG purposes)

[v6r20] Saving output of jobs run with 'runLocal' when they fail (for DEBUG purposes)

---

WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Utilities/PilotWrapper.py
WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Agents/SiteDirector/index.rst

Originally (in v6r19) there was the possibility to deploy "HTTP_PROXY" environment variables. This is a more generic way.
*WMS
NEW: Added possibility for deploying environment variables in the pilot wrapper through SiteDirector

[v6r20] Deploying environment variables through SiteDirector

---

docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/stuffThatRun.rst

Change text from "/your/box/dn/goes/here" to "/your/dn/goes/here" for user's DN.

Correct change certificate DNs

---

WorkloadManagementSystem/Agent/SiteDirector.py

This should solve the issue that by default additional pilots are submitting every hour because SiteDirector agent doesn't count older pilots which are in Waiting state more than hour.

change DB condition to count all waiting pilot jobs

---

dirac.cfg

When looking at big projects outside, you can see a full configuration files, with all the options documented. I think it is a very nice way of doing.
Since I am exploring the code to write doc for the DUW, I took the opportunity to start such a file.
I know, it's work to keep it up to date. But I think it is totally worth it.
What do you think ?
*Docs
NEW: add a documented dirac.cfg
Recap of discussion
I think we agree on the overall. Then it is just a matter of where we put things. I would go for something like the following:
*   Code documentation: perfect just as it is
*  Developer: I think we are getting there. We explain how to develop components, how dirac works under the hood, etc, and we link to Code documentation
*   Administrator: here I think …

[v6r20] Doc: add a documented dirac.cfg

---

WorkloadManagementSystem/DB/TaskQueueDB.py

Hi,
While testing v6r20 we found that the site directors were submitting pilots for jobs they shouldn't, even for jobs owned by other VOs (the pilots themselves never actually pick up the jobs). This causes jobs to take a very long time to run as pilots are submitted randomly until a combination that happens to match a job runs.
We've tracked this down to a change in behaviour of the retrieveTaskQueues when given an empty list of tq IDs... In the old version it would (correctly) return no matches, in the new version it returns _all_ task queues. This patch restores the old behaviour, which seems to fix the problem.
Regards,
Simon
FIX: Ensure retrieveTaskQueues doesn't return anything when given an empty list of TQ IDs.

[v6r20] Fix matcher/taskqueue in no-matches found case

---

WorkloadManagementSystem/Service/JobManagerHandler.py

Hi,
We found that in v6r20 jobs would sit in the received state for up to 5 minutes, whereas in earlier versions processing was almost instantaneous. It looks like nothing calls the Optimizer for normal non-bulk jobs in v6r20, so this patch just adds back that statement...
Regards,
Simon
FIX: Call optimizer fast-path for non-bulk jobs

[v6r20] Call optimizer for non-bulk jobs

---

Resources/Computing/SingularityComputingElement.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

Options to configure Singularity in sites level
1. Container  -- choose which kind of container to use. eg. Singularity  
2. ContainerBin -- choose where to find Singularity, the default is in $PATH of WN env
3. ContainerRoot -- define the default image (reuse the option from the sfayer's version)
4. ContainerBind -- bind extra directories inside singualrity
5. ContainerOptions -- add extra options to start "singularity" command
*WMS
CHANGE:  introduce options for sites to choose usage of sinularity 

[v6r20] Add support options for singularity

---

TransformationSystem/Client/TaskManager.py

Sometimes the order is like:
```
[<DIRAC.Interfaces.API.Job.Job object at 0x7fe0c40aff50>,
{'InputData': '',
'Status': 'Created',
'TargetSE': 'Unknown',
'TaskID': 38L,
'TransformationID': 401094L},
{'InputData': '',
'Status': 'Created',
'TargetSE': 'Unknown',
'TaskID': 39L,
'TransformationID': 401094L}]
```
Sometimes the Job comes later, if the job is the first entry, there will be an exception:
```
File "/opt/dirac/pro/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 306, in _execute
res = getattr(self, operation)(transIDOPBody, clients)
File "/opt/dirac/pro/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py", line 573, in submitTasks
res = clients['TaskManager'].submitTransformationTasks(preparedTransformationTasks['Value'])
File …
```

[v6r20] TaskManager: bulksubmission: fix occasional exception

---

Interfaces/API/Job.py
TransformationSystem/Client/TaskManager.py

This PR addresses the problem reported in the issue #3707 and discussed there. There is also a 
check that JOB_ID and PRODUCTION_ID workflow parameter placeholders are defined. This avoids
the necessity to define then explicitly while creation of a transformation. 
FIX: TaskManager - fix the generated JobName to be of the form ProdID_TaskID
FIX: TaskManager - check the JOB_ID and PRODUCTION_ID parameters are defined in the workflow
*Interfaces
FIX: Job API - do not merge workflow non-JDL parameters with the sequence parameters of the same name

[v6r20] Fix job parameters for bulk submission

---

TransformationSystem/Client/Utilities.py

Not all the exception types are caught, which results in this
```
[LHCbDirac prod] $ dirac-test-plugin --Debug --Plugin=ReplicateDataset --LFN=/lhcb/MC/2011/ALLSTREAMS.DST/00041399/0000/00041399_00000003_2.AllStreams.dst --Dest=NIPNE-07_MC-DST
Transformation type: Replication
1 requested LFNs
Plugin: ReplicateDataset
Parameters: {'Debug': True}
SE parameters: {'DestinationSEs': 'NIPNE-07_MC-DST'}
Now testing the replication plugin ReplicateDataset
Preparing the plugin input data (1 files)
Obtained replicas of 1 files in 0.261 seconds
(V) [NoThread] [-9999] Default plugin param TransformationPlugins/DestinationSEs: 'None'
(V) [NoThread] [-9999] Specific plugin param TransformationPlugins/ReplicateDataset/DestinationSEs: 'None'
(V) [NoThread] [-9999] Transformation plugin param …
```

[v6r19] TS: catch correct exception for ast.literal_eval

---

TransformationSystem/Client/TaskManager.py

This PR addresses #3720
*TS
FIX: TaskManager - pass output data arguments as lists rather than strings to the parametric job description

 [v6r20] TaskManager fix for multiple output data files case

---

docs/source/AdministratorGuide/Systems/Transformation/index.rst

While adding docs for MultiVO (#3723) I found a few typos that should get fixed before v6r21
* Docs:
FIX: AdministratorGuide TransformationSystem spell check and added a few phrases, notably for bulk submission working in v6r20p3

[v6r20] Docs: Transformation: typos, added few phrases, bulk submission

---

Resources/Computing/CREAMComputingElement.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py
WorkloadManagementSystem/PilotAgent/pilotTools.py
docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Sites/index.rst

Several fixes for supporting multi-core jobs. Addresses the same issue as #3730 and replaces it.
Added two options to the dirac-pilot script (--tag and --requiredTag) to pass tags and required tags directly to the pilots. This can be used to pass dynamically created tags in addition to tags statically
defined in the CE/Queue configuration. All the tags are aggregated before passing to the matcher. 
The PR restores the NumberOfProcessors evaluation to 1 if the corresponding Queue does not define
MaxNumberOfProcessors or a WholeNode tag is not defined for the pilot. This avoids pilot to send NumberOfProcessors more than 1 for single-core slots. This assumes that in cloud or BOINC environments, the pilots are supposed to defined WholeNode tag as it should be.
Added possibility to define …

[v6r19] Fixes for multi-core support

---

WorkloadManagementSystem/Client/JobState/JobManifest.py

Hi,
We were seeing crashes from a malformed JDL due to a missing check in JobManifest getSection, this minor patch prevents the crash (so the optimisers keep running...).
Regards,
Simon
*WorkloadManagementSystem FIX: Catch missing section in JobManifest getSection

[v6r19] Ensure section exists before trying to get it in JobManifest

---

docs/Tools/GetReleaseNotes.py

*Docs
FIX: GetReleaseNotes.py no longer depends on curl, but the python requests packe

[v6r20] Docs/GetReleaseNotes: re-implement with requests, no more curl calls

---

DataManagementSystem/Agent/FTS3Agent.py
DataManagementSystem/Client/FTS3File.py
DataManagementSystem/Client/FTS3Operation.py
DataManagementSystem/ConfigTemplate.cfg
DataManagementSystem/DB/FTS3DB.py
dirac.cfg
docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst

*DMS
NEW:  FTS3 add kicking of stuck jobs
FIX: FTS3 update files in sequence to avoid mysql deadlock
CHANGE: Canceled is not a final state for FTS3 Files
CHANGE: FTS3Operations are finalized if the Request is in a final state (instead of Scheduled)

[v6r20] fix fts3 deadlock

---

TransformationSystem/Agent/TaskManagerAgentBase.py
TransformationSystem/Agent/WorkflowTaskAgent.py
TransformationSystem/Agent/test/Test_Agent_TransformationSystem.py
TransformationSystem/Client/TaskManager.py

CHANGE: re-written a large test as pytest (much less verbosity, plan to extend it)
FIX: added BulkSubmission option in documentation for WorkflowTaskAgent

[v6r20] Minor fixes for TransformationSystem

---

RequestManagementSystem/Client/ReqClient.py

In the past the FTSClient instantiation would throw an exception, this is no longer the case, so we ping the service, which fails if it doesn't exist.
Otherwise we always get this error message:
> Failed getFTSJobsForRequest URL for service DataManagement/FTSManager not found
Note that the FTS3Client does not have the equivalent functionality as far as I could see
*RMS
FIX: dirac-rms-request: silence a warning, when not using the old FTS Services

[v6r20] dirac-rms-request: fix check for FTSClient, silence error

---

Core/Utilities/Glue2.py

*Core
FIX: The Glue2 parsing handles some common issues more gracefully
* handle multiple execution environments at a single computing share (i.e., CERN)
* handle multiple execution environments with the same ID (e.g., SARA)
* handle cases where the execution environment just does not exist, use sensible dummy values in this case (many sites)
CHANGE: some print outs are prefixed with "SCHEMA PROBLEM", which seem to point to problems in the published information, i.e. keys pointing to non-existent entries, or non-unique IDs

[V6r20] Fixes for Glue2 at CERN and some other inconsistencies

---

Core/Utilities/Proxy.py
StorageManagementSystem/Client/StorageManagerClient.py

I realise this is a lot of refactoring changes for a patch, and I want to test this more thoroughly, but I put it here now for discussion.
*CORE
NEW: New Core.Utilities.Proxy.UserProxy class to be used as a contextManager
FIX: Fix race condition in Core.Utilities.Proxy.executeWithUserProxy, the $X509_USER_PROXY environment variable from one thread could leak to another, fixes #3764
*SMS:
FIX: Fix setting of the user proxy for StorageElement.getFileMetadata calls, fixes #3764
*WMS
FIX: The solution for bug #3764 fixes a problem with the JobScheduling executor, where files could end up in the checking state with the error "Couldn't get storage metadata of some files"

[v6r20] UserProxy contextManager, StorageManager, JobScheduling fix

---

WorkloadManagementSystem/DB/TaskQueueDB.py

tpIdList's default value is now `None`
```
Exception:
File /opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py, line 270, in __RPCCallFunction
uReturnValue = oMethod(*args)
File /opt/dirac/pro/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py, line 112, in export_getActiveTaskQueues
return gTaskQueueDB.retrieveTaskQueues()
File /opt/dirac/pro/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py, line 1032, in retrieveTaskQueues
if tqIdList is False or tqId in tqIdList:
TypeError: argument of type 'NoneType' is not iterable
```
*WMS
FIX: Fix exception in TaskQueueDB.getActiveTaskQueues, triggered by dirac-admin-show-task-queues

[v6r20] TaskQueueDB: fix exception in getActiveTaskQueues

---

Core/Utilities/Proxy.py

Fixes the messed up indentation from  #3773
This is how it was before, and should be...
https://github.com/DIRACGrid/DIRAC/blob/7515fa9b92803a5bafa378239c6f4b33ac36728a/Core/Utilities/Proxy.py#L63-L72
*Core 
FIX: Fix executeWithUserProxy when called with proxyUserDN, fixes exception in WMSAdministrator getPilotLoggingInfo and TransformationCleaningAgent

[v6r20] Proxy: fix identation in _putProxy, if userDN was given nothing good is happening

---

TransformationSystem/Utilities/ReplicationCLIParameters.py
TransformationSystem/Utilities/ReplicationTransformation.py
TransformationSystem/scripts/dirac-transformation-replication.py

*TS
NEW: new option for dirac-transformation-replication scrip `--GroupName/-R`
FIX: The TransformationGroup is now properly set for transformation created with dirac-transformation-replication, previously a transformation parameter Group was created instead.

[v6r20] add replication transformation groupname

---

Core/Utilities/Glue2.py

*Core
FIX: Glue2 will return a constant 2500 for the SI00 queue parameter, any value is needed so that the SiteDirector does not ignore the queue, fixes #3790 

[v6r20] GLUE2: add 2500 for SI00 benchmark

---

DataManagementSystem/DB/FileCatalogComponents/SEManager.py
Resources/Catalog/FileCatalogClient.py
docs/source/AdministratorGuide/Resources/Storage/index.rst

After changing the meaning of the plugin section name, the SE information was not properly
evaluated by the SEManager of the File Catalog. This PR fixes it. It also takes properly into account the possible definitions of VO specific paths when constructing PFNs on the fly in the getReplicas() client method, this fixes the PFNs reported by dls -L or similar commands.
*DMS
FIX: SEManager - adapt to the new meaning of the SE plugin section name
FIX: SEManager - return also VO specific prefixes for the getReplicas() and similar calls
FIX: FileCatalogClient - take into account VO specific prefixes when constructing PFNs on the fly

[v6r20] Fix in the replica report

---

ConfigurationSystem/Agent/VOMS2CSAgent.py
ConfigurationSystem/Client/VOMS2CSSynchronizer.py

*CS
FIX: The VOMS2CSAgent was not sending notification emails when the DetailedReport option was set to False, it will now send emails again when things change for a VO.
CHANGE: VOMS2CSAgent: Users to be checked for deletion are now printed sorted and line by line

[v6r20] VOMS2CS: fix voChanged flag, bring back notification emails

---

ConfigurationSystem/scripts/dirac-admin-check-config-options.py
Core/Utilities/CFG.py

*CS
NEW: dirac-admin-check-config-options script to compare options and values between the current Configuration and the ConfigTemplates. Allows one to find wrong or missing option names or just see the difference between the current settings and the default values.
This script will become even more useful, when all the options are in the ConfigTemplates.

[v6r20] add dirac-admin-check-config-options script

---

Interfaces/API/Dirac.py
WorkloadManagementSystem/scripts/dirac-jobexec.py

Two changes in this PR: one fixes using inputdata when trying parametric jobs locally. The inputdata resolution was previously done before the parameter replacement.
And I would like to have the module parameters also be replaced in case of parametric jobs.
*WMS
FIX: Testing parametric jobs locally now should also work for parametric input data
NEW: Parameters from Parametric jobs are also replaced for ModuleParameters, and not only for common workflow parameters

[v6r20] parametric jobs and module parameters

---

DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py

if transfer should go to multiple target SEs and one needs more than
one attempt, the file was set to done and therefore the transfer was never
done to the other SEs
If the file is already at all targetSE this will set the file to done:
https://github.com/DIRACGrid/DIRAC/blob/5a63100abe5b155ae07a7137fdcc88c4cc966d85/DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py#L495-L500
*DMS
FIX: ReplicateAndRegister: fix a problem when transferring files to multiple storage elements, if more than one attempt was needed the transfer to all SEs was not always happening.

[v6r20] ReplicateAndRegister: do not set status to done if any targetSE is done

---

TransformationSystem/Agent/TransformationCleaningAgent.py

*TS
FIX: Fix exception in TransformationCleaningAgent: "'str' object not callable"

[v6r20] TransformationCleaningAgent: fix exception in execute 

---

FrameworkSystem/DB/UserProfileDB.py

Following this change https://github.com/DIRACGrid/DIRAC/commit/a4c32b552f307f0acc1383ac640dae4e84b9f11f
DB.\_\_init\_\_ should not be called with maxQueueSize, which would be interpreted as the debug flag, and create *DB.debug.log
FIX: obsolete parameter maxQueueSize in UserProfileDB initialization removed, not to make UserProfileDB.debug.log

[v6r20] Obsolete parameter maxQueueSize removed

---

.gitignore

Emacs specific file pattern is not in .gitignore, while Vim has a section...
I don't know if this needs the following lines for release notes... I don't think it would go into the releases... anyway, I just respect the template.
*Git
CHANGE: emacs backup file pattern added to .gitignore

[v6r20] Emacs file pattern in .gitignore

---

FrameworkSystem/Service/SystemAdministratorHandler.py
MonitoringSystem/Client/MonitoringReporter.py
WorkloadManagementSystem/Agent/StatesMonitoringAgent.py
WorkloadManagementSystem/ConfigTemplate.cfg
requirements.txt

CHANGE: The default name of the Message Queue can be changed

[v6r20]  Allow to define the message queue name

---

FrameworkSystem/DB/InstalledComponentsDB.py

I got this error when trying the component history web app
```
2018-09-13 12:46:02 UTC Framework/ComponentMonitoring NOTICE: 
Returning response ([::ffff:128.142.163.77]:49660)[diracAdmin:sailer] (0.01 secs) 
ERROR: Could not filter the fields: (_mysql_exceptions.OperationalError) 
(1054, "Unknown column 'voilcdirac012.cern.ch' in 'where clause'") 
[SQL: u'SELECT `Hosts`.`HostID` AS `Hosts_HostID`, `Hosts`.`HostName` AS 
`Hosts_HostName`, `Hosts`.`CPU` AS `Hosts_CPU` \n
FROM `Hosts` \nWHERE HostName IN ( voilcdirac012.cern.ch, voilcdirac02.cern.ch )'] 
(Background on this error at: http://sqlalche.me/e/e3q8)
```
This comes from the fact that the host strings are unicode strings (because of the browser?),
so we have to check for `basestring` instance.
Also the datetime type cannot happen …

[v6r20] IntalledComponentDB: fix filterfields with unicode string

---

AccountingSystem/private/Policies/JobPolicy.py

*Accounting
CHANGE: ReportGenerator: Authenticated users without JOB_SHARING will now only get plots showing their own jobs, solves #3776 

[v6r20] Accounting: for users always select only this user

---

Interfaces/API/Dirac.py
WorkloadManagementSystem/Client/SandboxStoreClient.py

*Interface
CHANGE: Make the unpacking of downloaded sandboxes optional in the API

[v6r20] Make unpacking downloaded sandboxes optional

---

RequestManagementSystem/Client/ReqClient.py

Replaces https://github.com/DIRACGrid/DIRAC/pull/3802
@marianne013 can you please test this hack we talked about ? It will just avoid your script to crash, but it won't display the requests. Sorry I did not try it. 
*RMS
FIX:  catch more exception in the ReqClient when trying to display the associated FTS jobs

[v6r20]  catch mroe exception in the ReqClient for displaying FTS Jobs

---

ConfigurationSystem/Agent/Bdii2CSAgent.py
ConfigurationSystem/Agent/GOCDB2CSAgent.py
ConfigurationSystem/Service/ConfigurationHandler.py
ConfigurationSystem/private/ServiceInterface.py
Core/LCG/GOCDBClient.py
FrameworkSystem/Client/NotificationClient.py
WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py

Plus other minor fixes
*Configuration
FIX: Corrected configuration location for Pilot 3 files synchronization

[v6r20] Bug fixes for pilot 3 files synchronization

---

Interfaces/API/Dirac.py

*Interface
FIX: Fix the sandbox download, returning the inMemory default.

[v6r20] Fix the sandbox download in API

---

DataManagementSystem/scripts/dirac-dms-put-and-register-request.py
DataManagementSystem/scripts/dirac-dms-replicate-and-register-request.py

FIX: Update obsolete dirac-rms-show-request command in user message displayed when running dirac-dms-replicate-and-register-request

[v6r20] remove obsolete command in user message

---

Interfaces/API/Dirac.py
Interfaces/API/test/Test_DIRAC.py

`systemCall` does not expand shell variables ($DIRACROOT), which was only defined after the call to `os.path.expandvars`. In the past `shellCall` was called with `$DIRACROOT/scripts/dirac-jobexec`, which worked because `shellCall` expands the variables.
* No release notes, because this is a fix to PR #3808 in the same release
* This currently breaks our nightly `integration` job tests, so a fast merge would be appreciated.

[v7] Dirac.runLocal: have to define DIRACROOT before expandvars is called

---

Core/scripts/dirac-install.py

*Core
FIX: check for empty /etc/grid-security/certificates dir

[v7r0] check for empty /etc/grid-security/certificates dir

---

DataManagementSystem/Client/FTS3Operation.py

This fixes a bug that had as consequence of not resubmitting files that are marked as Canceled by the FTS3 server, while they should (errors like timeout put the file in Canceled and not Failed for FTS...)
*DMS
FIX: FTS3: resubmit files in status Canceled on the FTS server

[v6r20] FTS3: resubmit files in status Canceled on the FTS server

---

RequestManagementSystem/Client/File.py
RequestManagementSystem/Client/Operation.py
RequestManagementSystem/Client/test/Test_Request.py
docs/source/DeveloperGuide/Systems/RequestManagement/index.rst

This fix the issue @andresailer discovered in https://github.com/DIRACGrid/DIRAC/pull/3842 when importing RequestDB. The issue was that a `File` object cannot be reused. The test was incorrectly doing it... So I fixed the test, and added a warning in the developer doc.
* RMS
FIX: tests do not re-use File objects

[v6r20] RMS: correct the test 

---

Resources/Storage/GFAL2_SRM2Storage.py

This PR fixes a problem when trying to stage at StorageElements that do not have a spaceToken
Error messages like:
```
"Invalid request descriptor ( 53 : Error occured while prestaging file GError('[gfal2_bring_online][gfal_plugin_bring_onlineG][gfal_srmv2_bring_onlineG][gfal_srm_report_error] srm-ifce err: Invalid request descriptor, err: [SE][GetSpaceTokens][SRM_INVALID_REQUEST] httpg://dcache-se-desy.desy.de:8443/srm/managerv2: No such space tokens\\n', 53))
```
The SE does not have a spaceToken. When I apply my patch everything is working nicely, or at least without error messages
Also tested with
```python
import os, gfal2, logging
logger = logging.getLogger('')
logging.basicConfig()
logger.setLevel(logging.DEBUG)
gfal2.set_verbose(gfal2.verbose_level.trace) …
```

[v6r20] GFAL2_SRM2Storage: only set spacetoken if not an empty string, fixes stager problem

---

Interfaces/scripts/dirac-dms-lfn-accessURL.py

Hi,
We find it useful to be able to get a specific protocol from dirac-dms-lfn-accessURL, for example if you want to use it with ROOT directly (i..e need a root:// URL rather than srm://) when an SE supports more than one AccessProtocol. This patch just maps this functionality (which is already in the API) through to the command line.
Regards,
Simon
*Interfaces
NEW: Add protocol option to dirac-dms-lfn-accessURL

[v6r20] Add protocol option to dirac-dms-lfn-accessURL

---

Resources/Computing/SingularityComputingElement.py

We found that the site using singularity does not appear in the accounting, while two other site names show up as 'DIRAC.Client.cn' and 'DIRAC.Client.uk'.
This happens because the dirac installation inside singularity does not have a site name configuration.
Then the job wrapper running inside singularity is also not able to report the correct site name.
Here it is added as the dirac-configure argument.
*Resources
FIX: Add site name configuration for the dirac installation inside singularity CE

[v6r20] Add site name configuration for singularity

---

TransformationSystem/Utilities/ReplicationTransformation.py

*TS
CHANGE:  ReplicationTransformation.createDataTransformation: returns S_OK with the transformation object when it was successfully added, instead of S_OK(None)

v6r20] ReplicationTransformation.createDataTransformation: return the transformation object when successful

---

Resources/Catalog/FileCatalogClient.py

Fixes #3828
The Integration tests are working again with this PR
*DMS
FIX: restore correct default value for the SEPrefix in the FileCatalogClient

[v6r20] DFC: fix the sePrefix default return value

---

DataManagementSystem/Client/FTS3Job.py
DataManagementSystem/Client/FTS3Operation.py
Resources/Storage/StorageElement.py

This were the small pieces missing to have transfers going to/from non SRM storage to work. They are used as hotfix in LHCb for ECHO storage. 
*DMS
FIX: FTS3: remove the hardcoded srm protocol for registration
FIX: FTS3: return an empty spacetoken if SRM is not available
*Resources
NEW: SE: return a standard error in case the requested protocol is not available

[v6r20]Fix fts3 space token for non srm storage

---

Core/Base/Script.py

If the loop prior to this change doesn't find the script name an exception is guaranteed. This breaks our tests.
related to #3885
*Core
FIX: Core.Base.Script: Fix exception on import, when the caller module was not like anything on the command line arguments

[v6r20] Core.Base.Script: fix exception for scriptName in tests

---

Core/Utilities/Decorators.py

With this option tests fail when they access a deprecated function, making it possible to automatically track down the usage.
*CORE
NEW: When the environment variable DIRAC_DEPRECATED_FAIL is set to a non-empty value, the use of deprecated functions will raise a NotImplementError exception

[v6r20] Add possiblity to make the use of deprecated functions/class raise an exception

---

ConfigurationSystem/private/ServiceInterface.py
TransformationSystem/Client/Utilities.py

Regarding the exception in the CS, it looks like that, and was introduced here https://github.com/DIRACGrid/DIRAC/commit/806114f82b95313f0c9fe3dff245c4dbecc3e0ca
```
2018-11-22 21:12:40 UTC Configuration/Server INFO: Found dead slave dips://lbvobox100.cern.ch:9135/Configuration/Server
Exception in thread Thread-5:
File "/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/opt/dirac/pro/DIRAC/ConfigurationSystem/private/ServiceInterface.py", line 172, in run
self.__checkSlavesStatus()
File "/opt/dirac/pro/DIRAC/ConfigurationSystem/private/ServiceInterface.py", line 102, in __checkSlavesStatus
for sSlaveURL in self.dAliveSlaveServers:
RuntimeError: dictionary changed size during iterat
``` …

[v6r20] fix dead slave exception and consider ArchiveSE in closerSEs

---

Resources/Catalog/Utilities.py
docs/source/AdministratorGuide/DIRACSites/ComputingElements/index.rst
docs/source/AdministratorGuide/DIRACSites/StorageElements/index.rst

*DMS
FIX: `FileCatalogClient` now properly forwards function docstrings through `checkCatalogArguments` decorator, fixes #3927 
CHANGE: `Resources.Catalog.Utilities`: use functool_wraps in `checkCatalogArguments` 

[V6r20] dfc docstrings

---

TransformationSystem/Agent/TransformationCleaningAgent.py

When the LogSE is a DIRAC storage, the removal of a directory is always recursive. It is not true for the other SEs. 
*TS
CHANGE: make the recursive removal of the log directory explicit in the TransformationCleaningAgent

[v6r20] recursive removal of log directories explicite

---

Core/Base/Script.py
DataManagementSystem/Agent/FTS3Agent.py
DataManagementSystem/Client/FTS3Client.py
DataManagementSystem/Client/FTS3File.py
DataManagementSystem/Client/FTS3Job.py
DataManagementSystem/DB/FTS3DB.py
DataManagementSystem/Service/FTS3ManagerHandler.py
tests/Integration/DataManagementSystem/Test_Client_FTS3.py

So, there is a bug in the logic in the new FTS system, which might result in duplicate transfers. This is of course not good. This PR fixes it a priori, but unfortunately requires a table change.
The duplicate transfers happen like that:
* Operation has two files File1 and File2.
* Job1 is submitted for File1 and File2.
* File1 fails, File2 is still ongoing.
* We submit Job2 for File1.
* Job1 is monitored again, and we update again File1 to failed (because it is so in Job1)
* A Job3 would be created for File1, despite Job2 still running on it.
The idea of the fix is as follow:
* we add an `ftsGUID` attribute to the FTSFile, initialized to None.
* when submitting a job for that file, we set the ftsGUID to the value of the job we just submitted.  
* when the job is monitored, if the …

[v6r21]  fix fts duplicate transfer (and fix Script.py)

---

Resources/LogBackends/MessageQueueBackend.py

Debug is so full of crap that it just makes centralized logging useless. 
This is a good incentive to review a bit the logging. I will update the log messages/levels in the coming weeks/months, based on the logs I will collect.
*Resources
CHANGE: MessageQueue log backends is now set to VERBOSE instead of DEBUG

[v6r21] MessageQueue log backends is now set to VERBOSE instead of DEBUG

---

Core/scripts/dirac-install.py

*CORE
FIX: set DIRACOS environment variable before souring diracosrc

[v6r21] fix bashrc creation in case of diracos

---

Core/Utilities/File.py

This was creating infinite loops.
*Core
CHANGE: Do not follow links when getting files list or size in directory via getGlobbedFiles and getGlobbedTotalSize

[v6r21] Do not follow links when getting files list or size in directory

---

Interfaces/API/Dirac.py

This is a PR to fix issue #3955 
*Interfaces
CHANGE: Dirac.py - getLFNMetadata returns result for both file and directory LFNs

[v6r21] Dirac API returns directory LFN metadata

---

Core/test/Test_API.py

For #3968 
The test will fail if the getstate/setstate are removed

[v6r21] Tests: add a test to check that we can copy API classes

---

Interfaces/API/Dirac.py

* API
FIX: Dirac: replace the use of deprecated function status by getJobStatus

[v6r21] Dirac.API: drop use of deprecated function status (use getJobStatus)

---

TransformationSystem/Agent/TransformationCleaningAgent.py

*TS
FIX: TransformationCleaningAgent: don't return error if log directory does not exist

[v6r21] TransformationCleaningAgent: don't return error if log directory does not exist

---

Core/scripts/dirac-distribution.py
Core/scripts/dirac-install.py
WorkloadManagementSystem/Executor/JobSanity.py
WorkloadManagementSystem/PilotAgent/pilotTools.py

FIX:JobSanity agent must return the number of input data
*Core
CHANGE: Use EOS for installing DIRAC software

[v6r21] JobSanity agent must return the number of input data

---

Core/Utilities/ReturnValues.py

Just fix the syntax for the docstring of returnSingleResult, which gives a warning

[v6r21] returnSingleResult: fix docstring syntax

---

docs/source/AdministratorGuide/Systems/Accounting/index.rst

As far as I can tell the helpers should not run the bucketing. This also seems to be consistent with the description in the text.
Also some fixes for the syntax
*Docs:
FIX: Fix description for using multiple Accounting::Datastore services, RunBucketing needs to be false for the helpers

[v6r21] Docs::Accounting: fixes for formatting and examples

---

releases.cfg

@andresailer which system should I put for the release note ?
@atsareg @zmathe can you please check ?
*Core
NEW: Default DIRACOS version for the integration branch

[v7r0] Add a default DIRACOS version to the integration branch -- Merge order: 1

---

Interfaces/scripts/dirac-admin-get-site-mask.py
WorkloadManagementSystem/DB/JobDB.py

We used to use SubmitPool job parameter in multi-VO installations to allow pilots submitted for a given VO to distinguish jobs coming from this same VO. Now pilots are using explicit VO name when presenting CE description to the Matcher to achieve the same goal. So, setting the default SubmitPool value for the job description is no more needed and actually complicates the matching logic. It is suppressed in this PR.
CHANGE: JobDB.py - do not add default SubmitPool parameter to a job description
FIX: dirac-admin-get-site-mask - show only sites in Active state

[v6r21] No default SubmitPool in a job description

---

Core/DISET/AuthManager.py
Core/Utilities/MySQL.py

This PR is the first one of a looooong serie where I will, as announced, clean the logs. I will do such PR every week. 
@atsareg I will build on top of that one, so please always merge this one just before doing the release
*Core
CHANGE: MySQL class prints only debug logs

[v6r21] Clean logs 1

---

Core/LCG/GOCDBClient.py
Core/scripts/dirac-install.py
WorkloadManagementSystem/Utilities/PilotWrapper.py

Our users reported issues using standard tools like pip because we define `REQUESTS_CA_BUNDLE` in the generated bashrc. I think it is fair that this kind of settings should not "sweat out" of DIRAC. 
We could overcome this either by setting `os.environ['REQUESTS_CA_BUNDLE']` in the `__init__.py`, or by crafting `Sessions` or by just specifying the CA path when calling requests. Given that there was already an occurrence of the later one in the code, I just propagated it everywhere (also, this allows importing DIRAC's API with other standard tools).
I also removed the REQUESTS_CA_BUNDLE definition from the bashrc.
It might be that we once bump into the same issue with `SSL_CERT_DIR`.
When moving to https, it will be anyway cleaner to wrap all that in a Session object once for all. …

[v6r21] Specify CAPath when using requests

---

requirements.txt

I tried to prepare a new virtual env for DIRAC. In order to complete the installation with success I had to add some version restriction at the requirements.txt modules. The exact versions were shown at the errors produced by pip.
OS: openSuse 42.3
python: 2.7.13
References: #3984
Update the requirements.txt to contain version restrictions at some modules.
CHANGE: installing modules from requirements.txt produced version compatibility errors. I updated the file in order to make module installation on a new virtualenv succeed. 

[v7r0]  Add version restrictions to requirements.txt

---

Core/scripts/dirac-install.py

*CORE
FIX: if the DIRACOS version is not given then use the proper release version

[v6r21] use the proper release

---

Core/scripts/dirac-distribution.py

*Core
FIX: getDiracModules is removed, class member is used instead.

[v6r21] getDiracModules method is no longer exists use the class member instead

---

AccountingSystem/Agent/test/Test_NetworkAgent.py
FrameworkSystem/private/standardLogging/Handler/MessageQueueHandler.py
MonitoringSystem/Client/MonitoringReporter.py
Resources/MessageQueue/MQCommunication.py
Resources/MessageQueue/MQConnectionManager.py
Resources/MessageQueue/Utilities.py
Resources/MessageQueue/test/Test_MQConnectionManager.py
Resources/MessageQueue/test/Test_MQConsumer.py
Resources/MessageQueue/test/Test_MQProducer.py
Resources/MessageQueue/test/Test_MQ_Utilities.py
docs/source/AdministratorGuide/DIRACSites/MessageQueues/index.rst
docs/source/DeveloperGuide/AddingNewComponents/Resources/MessageQueues/index.rst
docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/Backends/index.rst

Change the way of defining identifier  format for MQ resources. The middle part  of mqURI is plural instead of singular to be conformed with the currently used  section naming in CS.  After changes the accepted values are  'Topics' or 'Queues'.
Examples:
Before: blablba.cern.ch::Topic::test1
Now: blablba.cern.ch::Topics::test1
Before: blablba.cern.ch::Queue::myQueue1
Now: blablba.cern.ch::Queues:myQueue1
Also, the section explaining Topic/Queue concept has been added.
*Resources/MessageQueue
CHANGE: change the way of defining identifier  format for MQ resources: accepted values are  'Topics' or 'Queues'.

[v6r21] Update of the MQ documentation and standarize CS MQ section 

---

Resources/MessageQueue/StompMQConnector.py

In order to benefit from having several broker behind an alias, randomize the connection list
It is already running as a hotfix in LHCb
*Resources
CHANGE: MQ: randomzied the broker list when putting message

[v6r21] MQ: randomzied the broker list when putting message

---

Core/Security/VOMSService.py

*Core
FIX: Use getCAsLocation in order to avoid non-exist os.environ['X509_CERT_DIR']

[v6r21] Use getCAsLocation instead of os.environ

---

DataManagementSystem/Service/StorageElementHandler.py
Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/StorageElement.py
docs/source/AdministratorGuide/Resources/Storage/index.rst

Up to now, we were in a mixed situation: some places use power of 1024 while others (in fact, just SRM) relied on power of 1000 for sizes. 
This PR aims at making things uniform: all in power of 1024, but still with the existing name (i.e. `MB` and not `MiB`).
The only impact I expect from that is that the values stored in RSS for SRM storages will be smaller.
But up to now, we were in a mixed state, so better to smooth it out.
One thing to note is that the genius of WLCG talking pledges are using power of 1000... 
*Resources
CHANGE: Standardize sizes returned by StoragePlugins in Bytes
*DMS
CHANGE: DIP handler internally uses bytes instead of MB

[v6r21] Standardize sizes returned by StoragePlugins in Bytes

---

WorkloadManagementSystem/Agent/SiteDirector.py

*WMS
FIX: SiteDirector - do not use keywords in addPilotTQReference/setPilotStatus calls

[v6r20] SiteDirector fix

---

Core/DISET/private/Transports/SSL/M2Utils.py
Core/Security/m2crypto/X509Chain.py
FrameworkSystem/scripts/dirac-proxy-init.py

*CORE
FIX: Fix M2Crypto implementation for SkipCAChecks=True, needed when running dirac-configure for the first time
FIX: Fix in M2Crypto.X509Chain.dumpAllToFile: written proxy file was empty
1)
https://github.com/DIRACGrid/DIRAC/blob/c3994972b4fac0b09a60a530bff6bc303261a7ab/Core/DISET/private/Transports/SSL/pygsi/SocketInfo.py#L241-L251
vs
https://github.com/DIRACGrid/DIRAC/blob/c3994972b4fac0b09a60a530bff6bc303261a7ab/Core/DISET/private/Transports/SSL/M2Utils.py#L98-L103
2) `os.write` does not take a file object, but needs a file descriptor returned by os.open

[v7r0] M2Crypto: bug fixes

---

Resources/MessageQueue/MQConnector.py
Resources/MessageQueue/StompMQConnector.py
Resources/MessageQueue/test/Test_StompMQConnection.py

Solving part of the issue presented in #3986 
When MQ server is restarted, the clients are blocked. This fix add a dedicated listener ReconnectListener which in case of the disconnection tries to reconnect to the server.
The set of options such as number of trials, interval time etc  are provided. To reconnect the internal 
stomp.py connect mechanism is used.
The  current solution solves the producer case. Separate patch will be prepared for the consumer case. This needs more refactorization due to the handling of subscription after the disconnection occurs.
As byproduct, the handling of stomp.exception.NotConnectedException which could be raised  inside StompMQConnector subscribe() method, has been added. The exception is  handled  and it is transformed into a standard S_ERROR. …

[v6r21] MQ disconnect only producers

---

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py

WorkloadManagementSystem
CHANGE: Modification of utility function PilotCStoJSONSynchronizer. The modification allows to add information to created json file about the DNs fields of users belonging to 'lhcb_pilot' group. This information is needed for the second level authorization used in the Pilot Logger architecture. 
Also, some basic unit tests are added.

[v6r21] Add DN list from lhcb_pilot group to json file

---

docs/source/AdministratorGuide/InstallingDIRACService/index.rst

This PR changes the doc to explain how to install runit on the system in such a way that it is independent of DIRAC. It works (tested) for SLC6 and CC7
@atsareg, once this has been merged, you can also set the version of DIRACOS to v1r1 (numbered according to your wishes :-) ) where runit has been removed. 
*Docs
CHANGE: update instructions to install and setup runit

[v6r21] Docs: update instructions to install and setup runit

---

Resources/Computing/HTCondorCEComputingElement.py

This PR proposes two modifications to HTCondorCEComputingElement:
- Divide long condor_q by small chunks
- Create a directory before retrieving condor output
The latter is necessary if multiple SiteDirectors run on different nodes, since condor_transfer_data doesn't work if a directory registered as SUBMIT_Iwd doesn't exist on the local.
*WMS
CHANGE: Improve scalability of HTCondorCE jobs

[v6r21] HTCondorCE modifications for better scalability

---

TransformationSystem/Agent/TransformationCleaningAgent.py

Removing a Request can trigger annoying race condition with FTS. 
For that reason, just cancels them, which is handled gracefully
*TS
FIX: TransformationCleaningAgent cancels the Request instead of removing them

[v6r21] TS: cancel the Requests instead of removing them

---

Core/scripts/install_site.sh
DataManagementSystem/ConfigTemplate.cfg
DataManagementSystem/Service/StorageElementHandler.py
docs/source/AdministratorGuide/Authentication/index.rst
docs/source/AdministratorGuide/Resources/Catalog/index.rst
docs/source/AdministratorGuide/Systems/Transformation/index.rst
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst
docs/source/AdministratorGuide/Tutorials/diracSE.rst
docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst
docs/source/AdministratorGuide/Tutorials/index.rst
docs/source/AdministratorGuide/Tutorials/installDFC.rst
docs/source/AdministratorGuide/Tutorials/installRMS.rst
docs/source/AdministratorGuide/Tutorials/managingIdentities.rst
docs/source/AdministratorGuide/index.rst
docs/source/DeveloperGuide/Internals/Core/componentsAuthNandAuthZ.rst
docs/source/UserGuide/HowTo/DataManagement/index.rst

Add a whole bunch of tutorial, replaces https://github.com/DIRACGrid/DIRAC/pull/4026 taking into account all the comments
@andresailer I will need your help for the TS part, so it is mostly empty now
*Core
NEW: allow install_site to install DIRACOS
*Docs
NEW: add a tuto for setting up a basic installation
NEW: add a tuto for setting up two Dirac SEs
NEW: add a tuto for setting up the DFC
NEW: add a tuto for managing identities
NEW: add a tuto for setting up the RMS
NEW: add a tuto for doing DMS with TS

[v6r21] Add some administrator tutorials

---

Core/scripts/dirac-deploy-scripts.py
Core/scripts/dirac-install.py

Replaces https://github.com/DIRACGrid/DIRAC/pull/4039
*Core
FIX: dirac-deploy-scripts uses correct regex to find scripts
NEW: dirac-deploy-scripts can use symplink instead of wrapper

[v6r21] dirac-deploy-scripts can generate symlink

---

WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Client/Matcher.py

*WMS
FIX: SiteDirector - restore the logic of limiting the number of pilots to submit due to the  WaitingToRunningRatio option
FIX: Matcher - if a pilot presents OwnerGroup parameter in its description, this is interpreted as a pilot requirement to jobs and should not be overriden. 

[v6r21] Minor WMS fixes

---

WorkloadManagementSystem/Agent/JobAgent.py
WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/Utilities/PilotWrapper.py
WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py
requirements.txt

I modified the pilot wrapper so that it now makes different things depending if it's pilot 2 (still the default) or pilot 3. For pilot 2 nothing changes. For pilot 3 the input files (.py and .json) will be downloaded at run time. This may be improved with time.
@atsareg : VMDIRAC should maybe invoke the method `pilotWrapperScript` in the PilotWrapper.py module to get pilot wrapper to be used there. I think what's used in VMDIRAC is https://github.com/DIRACGrid/VMDIRAC/blob/integration/VMDIRAC/WorkloadManagementSystem/Bootstrap/vm-pilot and IIUC it's pilot 2.
*WMS
CHANGE: Pilot wrapper for pilot3: download files at runtime

[v6r22] Pilot wrapper for pilot3: download files at runtime

---

docs/source/AdministratorGuide/CommandReference/index.rst
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst
docs/source/AdministratorGuide/Tutorials/diracSE.rst
docs/source/AdministratorGuide/Tutorials/installRMS.rst

Just fixing some warnings that make the docs test in integration fail, but were introduced in v6r21
```
docs/source/AdministratorGuide/CommandReference/index.rst:135: WARNING: toctree contains reference to nonexisting document u'AdministratorGuide/CommandReference/dirac-accounting-report-cli'
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst:144: WARNING: Title overline too short.
-----------------------
Create the ``dirac`` user
-----------------------
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst:289: WARNING: Inconsistent literal block quoting.
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst:294: WARNING: Inconsistent literal block quoting.
docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst:299: WARNING: Inconsistent literal block quoting. …
```

[v6r21] fix documentation warnings

---

.travis.yml
requirements.txt

Travis can run python tests on different versions of Ubuntu: xenial, trusty or precise. At present it switches between them, based on load and this results in slightly different testing behavior. This PR fixes the test environment to trusty 14.04 LTS, we can run only on this version due to fts3/pycurl requirements.
Please merge ASAP to v6r22 and integration.

[v6r21] Fix version of Ubuntu on Travis

---

Core/scripts/dirac-install.py

*Core
FIX: better way of detecting whether DIRACOS was already installed 

[v6r21] fix dirac os detection

---

Core/Utilities/List.py
ResourceStatusSystem/Command/FreeDiskSpaceCommand.py
ResourceStatusSystem/Utilities/CSHelpers.py
Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/StorageBase.py
Resources/Storage/StorageElement.py
dirac.cfg
docs/source/AdministratorGuide/Resources/Storage/index.rst

The idea of this PR is to port the concept of `SpaceToken` SRM has to non SRM protocol. This came out from discussions with many people, including @fstagni @iueda @hmiyake 
@hmiyake will soon propose a PR with more changes regarding getOccupancy.
We realized that such a concept is needed for being able to perform accounting properly. 
This PR basically adds a `SpaceReservation` value to the return of `StorageElement.getOccupancy`. This value is:
* either returned by the StoragePlugin (SRM returns its SpaceToken, but it can be read in the json file)
* or read from the CS in the SE definition
One other change consists in what is returned by `CSHelper.getStorageElementEndpoint`. it was very inconsistent up to now, and it still is. But in the case of non srm protocol, this method now returns …

[v6r21] Adapt the SpaceToken SRM concept to non SRM storage

---

TransformationSystem/Utilities/ReplicationTransformation.py
TransformationSystem/test/Test_replicationTransformation.py

*TS
FIX: The dirac-transformation-replication script will now create valid transformations given only the required arguments. Instead of the 'Broadcast' plugin, the 'Standard' plugin is created if not SourceSE is given. If a value for the plugin argument is given, that will be used.

[WIP] [v6r21] Fix for transformation-replication script

---

Core/scripts/dirac-install.py

*Core
FIX: A certain module like WebAppDIRAC must be checked out from the code repository once.

[v6r21] make sure the module only installed once

---

dirac.cfg

The CFG parsing fails when there is a comment in a section title.
This breaks building the documentation

[v6r21] Fix in dirac.cfg

---

StorageManagementSystem/Agent/StageMonitorAgent.py
StorageManagementSystem/ConfigTemplate.cfg

We have two access protocols defined for castor, SRM and XROOT, in case the SMS SMA contacts castor via XROOT the files were always considered to be staged. This PR adds an option to limit the plugins used to GFAL2_SRM2, for example, or a list of plugins.
This feature depends on #4078 
*SMS
NEW: StageMonitorAgent: new option StoragePlugins to limit the protocols used to contact storagelements for staged files.

[v6r21] Add option to limit StageMonitoringAgent to certain storage plugins

---

TransformationSystem/Agent/RequestTaskAgent.py
TransformationSystem/ConfigTemplate.cfg
docs/source/AdministratorGuide/Tutorials/installTS.rst

*TS
CHANGE: ConfigTemplate for RequestTaskAgent now contains all options
*Docs:
CHANGE: AdministratorGuide install TS tutorial: added options MonitorFiles and MonitorTasks for TaskAgents

[v6r21] RequestTaskAgent options; installTS tutorial options

---

WorkloadManagementSystem/PilotAgent/pilotTools.py

Hi,
Here is the backport of #4091 to v6r20... I guess I should have just targeted it at this branch in the first place.
Regards,
Simon
FIX: Ensure maxNumberOfProcessors is an int

[v6r20] Convert maxNumberOfProcessors to int

---

TransformationSystem/Agent/TransformationPlugin.py
TransformationSystem/Agent/test/Test_Plugins.py
TransformationSystem/Client/Utilities.py
TransformationSystem/Utilities/ReplicationTransformation.py
TransformationSystem/test/Test_replicationTransformation.py
docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst

*TS
CHANGE: the Broadcast TransformationPlugin no longer requires a SourceSE to be set. If it is set, the behaviour is unchanged
CHANGE: dirac-transformation-replication: change default pluging back to Broadcast (reverts #4066)

[v6r21] broadcast without sourceSE

---

WorkloadManagementSystem/Executor/JobScheduling.py

In the job JDL users are often confused in how to specify tags - either with the Tag ot Tags option (the correct way so far is Tags even if there is a single tag). This PR makes both ways possible
*WMS
CHANGE: JobScheduling - allow both Tag and Tags option in the job JDL

[v6r21]  Allow both Tag and Tags option in the job JDL

---

docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst

*docs
NEW: Instruction about setting up the DIRAC web server for pilot3

[v6r22] Add instruction about seting up webapp for pilot3

---

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py

FIX: use CAs to upload the pilot files to a dedicated web server using requests 

[v6r22] use CAs for uploading the pilot files

---

Core/scripts/dirac-deploy-scripts.py

Stupid mistake 
*Core
FIX: correct symlinks in dirac-deploy

[v6r21] Fix symlink creations in deploy-script

---

WorkloadManagementSystem/Service/JobStateUpdateHandler.py

I simply de-commented some lines, which have been commented 10+ years ago. If anyone can shed some light on why they were commented, please let me know. I guess it was a "temporary measure" for performance reasons.
*WMS
CHANGE: restoring the job status to Running after hearbeat

[v6r21] restoring the job status to Running after hearbeat

---

Core/scripts/dirac-install.py

*Core
FIX: dirac-install: correct location for ARC plugins with DIRACOS

[v6r21] dirac-install: correct location for ARC plugins with DIRACOS

---

TransformationSystem/Client/Transformation.py
TransformationSystem/Utilities/ReplicationTransformation.py
TransformationSystem/test/Test_replicationTransformation.py
docs/diracdoctools/CustomizedDocs/CustomTransformation.py
docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst

*TS
NEW: InputDataQuery and OutputDataQuery parameters can be set for Transformations before they are added to the transformation system. Solves #4071 

[v7] Create data queries before transformation is created

---

TransformationSystem/Agent/MCExtensionAgent.py

MCExtension has a logic bug in the code when counting "numberOfTasks = maxTasks - ( total - failed )", total should be "totalcreated" instead of just "created"
original: total = statusDict.get( 'Created', 0 )
modified: total = statusDict.get( 'TotalCreated', 0 )
After changed, the "MaxNumberOfTasks" can correctly limit the number of jobs 
created.
FIX: fixed a logic bug in counting numberOfTasks in MCExtension which is expected 
to limit the total number of tasks for MC transformations

[v6r21] a logic bug in counting numberOfTasks

---

AccountingSystem/DB/AccountingDB.py

I don't think this function is actually called anywhere, or there should have been exceptions showing up, but I stumbled across this...
*Accounting
FIX:  In AccountingDB.insertRecordThroughQueue fix bad dictionary key "0K"

[v6r21] AccountingDB.insertRecordThroughQueue: fix zeroK

---

Resources/Storage/GFAL2_SRM2Storage.py
Resources/Storage/OccupancyPlugins/BDIIOccupancy.py
Resources/Storage/StorageElement.py

This PR proposes to add a plugin mechanism to StorageElement.getOccupancy().
If "OccupancyPlugin" is found from a SE configuration, specified occupancy plugin is called before built-in getOccupancy() of each SE plugin.
As a working sample, add plugin to retrieve the occupancy from BDII.
Additionally enable for GFAL2_SRM2Storage.getOccupancy() to go back parent function if SpaceToken is not given.
This is replacement of #4109 which incorporated unrelated commits
*Resources
NEW: enable to get SE occupancy from plugin
NEW: add occupancy plugin to retrieve the info from BDII
CHANGE: GFAL2_SRM2Storage.getOccupancy() calls parent if SpaceToken is not given

[v6r22] plugin to get SE occupancy

---

codecov.yml

This sets the target coverage diff for the "patch" check to 0 and adds a threshold of 0.03 for the "project" coverage to allow random fluctuations in the diff (caused by calls to "random" in functions that are tested?).
(Also fixes a syntax error in the yaml compared to that of the integration branch.)

[v6r21] codecov configuration

---

WorkloadManagementSystem/DB/JobDB.py

*WMS
FIX: JobDB.getAttributesForJobList: Return S_ERROR if unknown attributes are requested. Instead of potentially returning garbage a clear error message is returned.
If the user provided `attrList` contains an attribute name that is not defined 
Line 130 will filter it out.
But in line 147 the original `attrList` (via `attr_temp_list`) is used to construct the return dictionary, which leads to a shift in the `attrname` to value dictionary (unless the unknown attribute was last in the list).
As the list of attributes doesn't change (it is the list of columns in the JobDB), it doesn't make sense to silently ignore this problem and return "None" or "UNKNOWN ATTRIBUTE" as the dictionary values for the unknown attributes. …

[v6r21] JobDB.getAttributesForJobList: return S_ERROR if unknown attribute is requested

---

WorkloadManagementSystem/Agent/JobAgent.py
WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Sites/index.rst

This PR adds an option for specifying the LocalCEType (which by default is "InProcess"). This option will be interpreted by the Pilot3 (PR in https://github.com/DIRACGrid/Pilot/pull/83) and the idea is basically to specify the "Pool"ComputingElement, with HPC or anyway CEs for large WNs in mind.
*WMS
NEW: added option for specifying a LocalCEType (which by default is "InProcess")

[v6r22] Added option for LocalCEType (for pilot 3)

---

Core/scripts/dirac-distribution.py
Core/scripts/dirac-install.py

This is almost a hack: dirac-install.py will try to install with DIRACOS when:
- the "--dirac-os" flag is not set
- there's no external version specified, which is the case for v7r0-pre17 and everything that will come later.
We can't change much else because it would change the logic for installing older versions. If you have other suggestions, please fire!
*Core
CHANGE: dirac-install.py will use DIRACOS when externals are not defined

[v7r0] use DIRACOS when externals are not defined

---

Core/scripts/dirac-create-distribution-tarball.py

*Core
FIX: $Id$ keyword must be replaced only at the beginning of the file.

[v6r22]  fixing commit id for extensions

---

docs/source/AdministratorGuide/Configuration/ConfReference/Operations/DataManagement/index.rst

Following the comments in the pull-request  #4134:
*Docs
NEW: /Operations/DataManagement - Added a link to the documentation on "Multi Protocol"

[v6r22] Adding a link to the Multi-Protocol documentation

---

Resources/Storage/GFAL2_StorageBase.py

The new DPM dome flavor together with globus bad error handling requires us to catch an weird error when trying to create a directory that already exists.
On the long term, I really want to simplify all these plugins..
*Resources
CHANGE: Storages: catch specific DPM/Globus error code when creating existing directory

[v6r21] Fix for new DPM dome

---

DataManagementSystem/Client/DataManager.py
DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata.py
DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py
DataManagementSystem/scripts/dirac-dms-clean-directory.py

*DMS
FIX: ``dirac-dms-clean-directory`` correct usage message for list of arguments
FIX: ``dirac-dms-clean-directory`` now properly prints error messages
FIX: ``dirac-dms-clean-directory`` will now also clean empty directories
FIX: ``FileCatalog.DirectoryMetadata``: prevent error when removeMetadataDirectory is called on empty list of directories, triggered when calling removeDirectory on non-existing directory
FIX: ``FileCatalog.DirectoryTreeBase``: prevent maximum recursion depth exception when calling remove directory with illegal path

[v6r21] fixes for dirac-dms-clean-directory

---

.travis.d/checkDocs.sh

*CI
FIX: if the building of documentation fails, exit with error

[v7r0] Ensure checkDocs fails on any error

---

Interfaces/API/Dirac.py
WorkloadManagementSystem/Client/SandboxStoreClient.py

*WMS
CHANGE: Add an argument to the constructor of SandboxStoreClient for using in scripts that cannot use the DB directly

[v6r21] Add argument to SandboxStoreClient to allow using the service

---

Resources/Storage/GFAL2_StorageBase.py

The use of this cache was disabled at the time because of a bug (specific globus + specific dCache). The bug is now fixed. We should revert to the previous behavior because this "hacK" hurts very much removals (in particular RAL Echo)
For references:
https://github.com/globus/globus-toolkit/issues/57
https://github.com/dCache/dcache/issues/4830
https://github.com/gridcf/gct/issues/81
*Resources
FIX: re-allow the use of the gsiftp cache in the SE

[v6r22] SE: do not disable Session reuse in GridFTP anymore

---

DataManagementSystem/DB/FileCatalogDB.py

It was unusable by users up to now, making this script basically useless
BEGINRELEASENOTES 
*DMS
CHANGE: relax permissions on getLFNForGUID 

[v6r22] DFC: relax permissions on getLFNForGUID

---

Core/Base/Client.py
Core/Utilities/Decorators.py

If the first line of a docstring looks like a function signature, sphinx uses that instead of what is defined in python. We can use this to properly create the function signatures in the automatically created client functions.
http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature
*Docs
CHANGE: Automatically added client functions now display proper argument names in the function siganture instead of just "*args"
CHANGE: Functions decorated with the deprecated decorator will now mention this in their docstring

[v7r0] better doc strings

---

docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/index.rst

With respect to #4162  .
I was looking how to configure pilot3 usage, and searching for "pilot3" in the search of the documentation did not turn up the page actually describing the use of pilot3 because it only contained the word "pilots3". So I propose to change "pilots3" to "pilot3". The SiteDirector flag is also called "Pilot3". There is a keyword of "Pilots3" on the page, so "pilots3" still finds this page as well.
*Docs
CHANGE: Always refer to pilot3 instead of pilots3

[v7r0] Pilot3 documentation: unify reference to 'pilot3'

---

tests/Workflow/Integration/Test_UserJobs.py

The user jobs script uses `tests/Workflow/Regression/helloWorld.py` instead of `tests/Workflow/Integration/helloWorld.py` in Jenkins.
Fixes: https://jenkins-dirac.web.cern.ch/blue/organizations/jenkins/Pilot3_CVM4_pipeline/detail/Pilot3_CVM4_pipeline/8/pipeline/35/

[v7r0] Hackathon fix for tests

---

DataManagementSystem/scripts/dirac-dms-create-archive-request.py

the script to format the command documentation rst files was adding additional colons at the end of lines, which then caused a warning and failure of the doc generation CI

[v7r0] DMS:CreateArchive command: fix docstring issue

---

Core/scripts/dirac-install.py

It is required by #4197
*Core
CHANGE: A VO with diracos extension, must be able to install the main diracos from DIRAC repository. 

[v6r22] extension can take DIRACOS from DIRAC

---

AccountingSystem/Client/Types/PilotSubmission.py
AccountingSystem/private/Plotters/PilotSubmissionPlotter.py
WorkloadManagementSystem/Agent/SiteDirector.py
WorkloadManagementSystem/ConfigTemplate.cfg

WMS and Accounting
NEW: Statistics of Pilot submission is sent to Accounting System by SiteDirector.

[v6r22] Pilot Submission statistics is counted by SiteDirector based on Accounting System

---

ConfigurationSystem/ConfigTemplate.cfg
ConfigurationSystem/Service/ConfigurationHandler.py
WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
WorkloadManagementSystem/Utilities/PilotWrapper.py
docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Services/Server/index.rst
docs/source/AdministratorGuide/Configuration/ExampleConfig.rst
docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/index.rst
tests/Integration/WorkloadManagementSystem/Test_GenerateAndExecutePilotWrapper.py

*WMS
NEW: PilotWrapper can get the Pilot files from a list of locations
CHANGE: PilotWrapper is compatible with several python versions
*test
NEW: added a test for PilotWrapper
*docs
CHANGE: Pilot 3 is the default

[v7r0] Changes and fixes for pilot wrappers

---

FrameworkSystem/private/standardLogging/Logging.py

In order to avoid a lot of issues with the centralized logging, make sure the variable message is always a string
*Framework
CHANGE: make sure sVarMsg in Logger is always a string

[v7r0] Logger: make sure sVarMsg is always a string

---

Core/scripts/dirac-install.py
Resources/Storage/GFAL2_XROOTStorage.py

In order for the fix to be fully efficient, we will need xroot 4.10
This should fix some permission denied problems we are getting. Details are in the code comments.
@andresailer  this is the fix we discussed a while ago.
This was tested as hotfix on the REA in LHCb. 
*Core
NEW: dirac-install defines XRD_RUNFORKHANDLER environment variable
*Resources
FIX: add proxy location as a virtual user for xroot urls

[v7r0] fix xroot proxy cache

---

TransformationSystem/Agent/InputDataAgent.py
TransformationSystem/DB/TransformationDB.py

The error message was changed in the DB class, so I thought I add an errno to check for this error message to silence it in the InputDataAgent
*TS
CHANGE: TransformationDB.getTransformationMetaQuery returns ENOENT if no meta query exists
FIX: InputDataAgent: silence warnings about transformations not having a input data query

[v7r0] Transformation: silence warning in InputDataAgent

---

Core/DISET/RequestHandler.py
Core/DISET/private/BaseClient.py
Core/DISET/private/Service.py

This PR makes the DIRAC version of the client to be available to service. This will allow, for example, meaningful error message in case of client/service version incompatibility.
*Core
NEW: DISET - pass the client DIRAC version as part of the request description structure

[v7r1] Make the client version known to services

---

DataManagementSystem/DB/FileCatalogComponents/SEManager.py

Sorry apparently I fucked up the PR yesterday. @atsareg all the releases made yesterday are buggy, sorry about that 
*DMS
FIX: SEManager correct order of calls at init

[v6r22] URGENT SEManager: fix order of calls

---

WorkloadManagementSystem/DB/SandboxMetadataDB.py
WorkloadManagementSystem/Service/SandboxStoreHandler.py

Fixes bug introduced in https://github.com/DIRACGrid/DIRAC/pull/4217
```
2019-08-22 08:09:50 UTC WorkloadManagement/SandboxStore ERROR: Exception while setting deletion request Traceback (most recent call last): 
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Service/SandboxStoreHandler.py", line 482, in __deleteSandboxFromExternalBackend credDict = self.getRemoteCredentials() 
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 97, in getRemoteCredentials return self.__trPool.get(self.__trid).getConnectingCredentials()
AttributeError: 'NoneType' object has no attribute 'getConnectingCredentials' 
2019-08-22 08:09:50 UTC WorkloadManagement/SandboxStore ERROR: Cannot delete sandbox from backend Cannot set deletion request: 'NoneType' object has no attribute …
```

[v6r22] SandboxStore: use host credentials to query the DB for async removal

---

Resources/Computing/SSHBatchComputingElement.py

*Resources
FIX: preamble attribute was missing in SSHBatchComputingElement causing an error in _submitJobHost() 

[v6r22] Add preamble attribute in SSHBatchComputingElement

---

Core/Workflow/Workflow.py

Something I've been working on results in obj being a `unicode` filename rather than `str` (still only using ASCII characters). Patching it to accept any string type works as expected.
*Core
FIX: Accept unicode file path to workflow XML

[v6r22] Accept both unicode and str filenames to workflow XML

---

ConfigurationSystem/Client/CSAPI.py
ConfigurationSystem/ConfigTemplate.cfg
ConfigurationSystem/Service/ConfigurationHandler.py
ConfigurationSystem/private/ConfigurationData.py
ConfigurationSystem/private/ServiceInterface.py
Core/DISET/RequestHandler.py

This PR makes possible to synchronize configuration slave services with the master as part of the CS changes commit operation. It provides also an interface to force all the services to update their configuration. This makes configuration changes immediately available in all the services. This is needed, for example, for newly registered users to be able to use the services right after the registration.
*Configuration
NEW: Slave configuration servers are automatically updated as part of the new configuration changes commit
NEW: Configuration Server - added forceGlobalConfigurationUpdate() interface to force all registered service to update their configuration

[v7r1] Synchronize service after the CS update

---

WorkloadManagementSystem/Agent/StalledJobAgent.py

fixes https://github.com/DIRACGrid/DIRAC/issues/4254
*WMS
FIX: handle empty results of getJobParameter in StalledJobAgent

[v6r22] StalledJobAgent: correct treatment of empty result of getJobParameter

---

Resources/Computing/SingularityComputingElement.py

This adds the lcgBundle version to the dirac-install flags within the SingularityCE container to make the behaviour like the normal grid pilot.
*Resources
FIX: Ensure lcgBundle is installed in container if LCGBundleVersion is set.

[v6r22] Ensure lcgBundle is installed in singularity container

---

WorkloadManagementSystem/Utilities/PilotWrapper.py

During the previous hackaton we had some issues with the ARC CEs unable to execute the pilot wrapper script and returning: 
```
<dirac server host>:<port>: unreacheable
None of the locations of the pilot files is reachable
```
This was due to the following exception:
```
File "<stdin>", line 94, in <module>
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 431, in open
response = self._open(req, data)
File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
'_open', req)
File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
result = func(*args)
File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
context=self._context, check_hostname=self._check_hostname)
File …
```

[v7r0] Fix urlopen call in PilotWrapper script

---

FrameworkSystem/Service/ProxyManagerHandler.py

The integration tests are failing as `diracGroup` is set to `None` but the type checking doesn't allow this:
https://github.com/DIRACGrid/DIRAC/blob/fe33283186cd5b1ba15755ecd50307877af64488/FrameworkSystem/Client/ProxyManagerClient.py#L197
Alternatively this could be fixed by relying on the default value.
@atsareg There are a lot failures in the integration tests. Can you make sure they're fixed before the certification hackathon next week?

[v7r1] Fix proxy generation

---

Core/scripts/dirac-install.py

This is in preparation for being able to run the GitLab CI tests locally. The interesting commit is 21b59b3 and the others are just minor linter/readability improvements.
Unfortunately the diff isn't displayed very well but it just adds these 4 lines before cloning the repository. If `sourceURL` is a directory, copy it instead of cloning. I think this is useful as it will allow the integration tests to be ran locally without any need to commit beforehand.
```python
if os.path.isdir(sourceURL):
logNOTICE("Using local copy for source: %s" % sourceURL)
shutil.copytree(sourceURL, fDirName)
else:
```
*Core
NEW: Allow installation from a local directory

[v7r1] Support installing from a local directory in dirac-install.py

---

Interfaces/API/Dirac.py

```bash
$ dirac-wms-job-get-output.py -g $JOB_NAME
File "bin/dirac-wms-job-get-output.py", line 97, in <module>
result = dirac.getOutputSandbox( job, outputDir = outputDir )
File "DIRAC/Interfaces/API/Dirac.py", line 1717, in getOutputSandbox
params = self.getJobParameters(int(jobID))
File "DIRAC/Interfaces/API/Dirac.py", line 2431, in getJobParameters
return S_OK(result['Value'][jobID])
KeyError: 306217237
```
*Interfaces
FIX: Error handling in Dirac().getJobParameters

[v6r22] Fix error handling in Dirac().getJobParameters

---

tests/System/client_dms.sh

In this "Basic DMS client tests" script, the executor's local user name '$USER' is used in composing the test LFN, which would be ok only when the dirac user name and the local system user name are the same.
When they are different, the check with 'dirac-dms-user-lfns' will fail.
The script should take the DIRAC user name.
*tests
FIX: DMS client tests to use DIRAC user name, rather than the local system user name

[v7r1] DMS client tests to use DIRAC user name, rather than the local user name

---

Core/scripts/dirac-install.py

This check was already there for bashrc, now added it to the other cases in the installer (cshrc, diracos).
*Core
FIX: Added protection against empty certificates directory in dirac-install

[integration] added protection against empty certificates directory

---

AccountingSystem/Client/Types/DataOperation.py
AccountingSystem/Client/Types/Job.py
AccountingSystem/Client/Types/Pilot.py

This is a change to the dababase schema, so it needs a warning in the release notes. We need this as both our user and sitenames follow conventions which occasionally result in a site or user name > 32 characters.
*Accounting
FIX: Allow longer user and site names.

[v7r0] increased length of User and Site fields in AccountingDB

---

Resources/Computing/CREAMComputingElement.py

This fix was made in #3739 but was somehow lost afterwards. 
*Resources
FIX: CREAMComputingElement - possibility to defined CEQueueName to be used in the pilot submission command

[v6r22] Define queue name as seen by CE

---

WorkloadManagementSystem/Client/JobState/JobState.py

JobState object is instrumented to have database clients on the class level in order not to recreate them at each JobState object instantiation 
*WMS
FIX: JobState - restored logic of having database clients at the class level

[v7r0] JobState - restored logic of having global database clients

---

docs/source/AdministratorGuide/HowTo/dedicateddfc.rst
docs/source/AdministratorGuide/HowTo/index.rst

This transfers the information from https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/dSsZbW4pyt4 to the documentation
*Docs
NEW: Added how to create a dedicated dirac file catalog

[v7r0] Docs: add how to create dedicated dirac file catalog

---

docs/source/AdministratorGuide/CommandReference/index.rst

Just a small fix for doc entries.

[vr7r0] Docs.Admin.Commands: fix entries for dirac-transformation commands

---

Resources/Storage/StorageElement.py

Currently we are blind when a protocol fails while the next one works. This helps for debugging. 
*Resources
CHANGE: increase the SE logging level for plugin errors

[v6r22] Log Storage plugin error

---

FrameworkSystem/Service/NotificationHandler.py

Since some update last week we no longer receive emails from the Bdii2CSAgent. (I don't know why it was still working last week, maybe the agent or NotificationHandler was not restarted for a long time)
I think is is ultimately caused by the fact that the `initializeNotificationHandler` function is a classMethod of the NotificationHandler and not a module level function (as is the case for the FileCatalogHandler for example). As a `@classMethod` this should be called `initializeHandler`
https://github.com/DIRACGrid/DIRAC/blob/045612125204e96f155fdbd4fd6cf72d0c4fc600/FrameworkSystem/Service/NotificationHandler.py#L46
cf.
https://github.com/DIRACGrid/DIRAC/blob/f07d67a1e96c3fca6983af3cd5b1c2d9d246887c/DataManagementSystem/Service/FileCatalogHandler.py#L31
This function is not called, which …

[v6r22] NotificationHandler: correct name of initializeHandler function

---

DataManagementSystem/Client/FTS3Job.py

There are cases when the FTS job is declared in a final state, while the files are not. This creates problems on our side, because the files are then never monitored nor retransferred. 
This PR aims at preventing that by not updating job/files in an inconsistent state. 
The FTS servers have a cleaning thread running every hour
*DMS
FIX: avoid introducing inconsistencies in the DB due to the FTS inconsistencies

[v6r22] FTS: workaround for FTS job/files inconsistencies

---

WorkloadManagementSystem/Service/WMSUtilities.py

"Backporting" this bugfix: https://github.com/DIRACGrid/DIRAC/pull/4317/files#diff-69fd7edbaf3eaf4d1596939a4e3771c2L155
*WMS
FIX: Fix exception for PilotManager or PilotStatusAgent: itertems -> iteritems

[v6r22] WMSUtilities: fix typo itertems -> iteritems

---

Core/scripts/dirac-info.py

Found thanks to the new automated tests of DIRACOS
*Core
FIX:  remove unexisting import from dirac-info

[v7r0] Core: remove unexisting import from dirac-info

---

.gitignore
environment.yml
tests/Integration/all_integration_client_tests.sh
tests/Integration/all_integration_server_tests.sh
tests/Jenkins/utilities.sh

Fixes quite a few mistakes from the tests:
* https://github.com/DIRACGrid/DIRAC/commit/a9a654e37db44704b2660d3a06f7258a7ecae1eb : the `dbs` argument is a list. Since they are between quote, the parse would interpret it as a single argument, and of course that breaks the call "DROP DATABASE"
* Use `tee` in append mode
*  Use CLIENT_ALTERNATIVE_MODULES instead of just `modules` env variable for client test
* Specify proxy locations in the client tests
* add `parameterized` to the dependencies in `environment.yml`
* ignore test generated files in git
@chrisburr can you please check it ? 
@fstagni @atsareg this one is needed to have any PR against v7r1 show green in githubAction. Please merge it as soon as @chrisburr will have reviewed it. Thanks

[v7r1] fix integration tests

---

Core/Utilities/MySQL.py
WorkloadManagementSystem/DB/JobDB.py
WorkloadManagementSystem/DB/JobLoggingDB.py

CHANGE: remove many calls too gLogger.debug() is low level DB modules (in particular MySQL.py) that may slowdown services
For the moment only commented out the calls but if everybody agrees they should IMHO be removed...
Of course this should be done systematically in all services. This is just because I was looking at possible slowdown in JobDB handling which is very heavily called...

[v6r22] Remove useless calls to gLogger.debug()

---

docs/diracdoctools/Config.py
docs/diracdoctools/cmd/commandReference.py
docs/docs.conf
docs/requirements.txt

*Docs
CHANGE: The options in the command reference sections: 'ignore' and 'scripts', are replaced by 'exclude' and 'manual' respectively. The entries in 'exclude' will now reject scripts that are otherwise picked up by the 'patterns'. Entries in 'manual' will be added to the indexFile, but their rst file has to be provided by hand. Fixes #4345 

[v7] DiracDocTools improvements

---

WorkloadManagementSystem/Agent/SiteDirector.py

NEW: To activate the pilot logging mechanism the following option must be present in CS: Pilot/PilotLogging with a value set to "true", "yes" or "y".

[v7r0] Add pilot option -z in _getPilotOptions for activate pilot logging

---

Core/Base/Client.py
Core/scripts/dirac-configure.py
Core/scripts/dirac-install.py
WorkloadManagementSystem/PilotAgent/pilotCommands.py

This is a draft PR, that needs agreement from @atsareg @marianne013 @andresailer @sfayer @iueda 
This is a continuation from https://github.com/DIRACGrid/DIRAC/pull/3923 and it has the same reasons: python packages shipped with diracos shouldn't be overridden by those same python packages found on the PYTHONPATH.
*Core
CHANGE: {bash,tchs,diracos}rc set the PYTHONPATH to only dirac (ignore existing PYTHONPATH)
CHANGE: dirac-configure might work without the need of a proxy
CHANGE: the timeout of an RPC call is always updated

[v7r0] Always starting from a clean PYTHONPATH

---

.github/workflows/integration.yml
tests/CI/run_docker_setup.sh
tests/Jenkins/utilities.sh

Please review quickly, this can fix the tests for PRs targeting integration (tested in https://github.com/DIRACGrid/DIRAC/pull/4303)

[Integration] Running on integration (fix run of GitHub Actions for PRs targeting integration)

---

Core/Utilities/SiteSEMapping.py
ResourceStatusSystem/Agent/CacheFeederAgent.py
ResourceStatusSystem/Command/FreeDiskSpaceCommand.py
Resources/Storage/StorageElement.py

The aim of the change is to:
-    remove a call to shifterProxy configuration which would not work for multi VO Dirac
-    handle a possible exception which might be thrown in a SE loop, so the SE is skipped and the loop continues to process remaining SEs. This might happen, for example where an SE configuration does not define _Protocol_ configuration option.
This PR replaces #4332
* RSS
CHANGE: remove a call to shifterProxy configuration which would not work for multi VO Dirac

[v7r0] RSS command fixes

---

Core/scripts/dirac-deploy-scripts.py
Core/scripts/dirac-install.py

This is a prerequisite for the environment changes we discussed at the meeting. We believe it's fully backwards compatible and should not interfere with LHCb.
*Core
CHANGE: Simplify and convert command wrapper scripts to bash. Also removed some obsolete MacOS code.

[v7r0] dirac wrapper script cleanup, convert to bash

---

DataManagementSystem/Agent/FTS3Agent.py
DataManagementSystem/Client/FTS3Client.py
DataManagementSystem/Client/FTS3File.py
DataManagementSystem/Client/FTS3Job.py
DataManagementSystem/Client/FTS3Operation.py
DataManagementSystem/ConfigTemplate.cfg
DataManagementSystem/DB/FTS3DB.py
DataManagementSystem/Service/FTS3ManagerHandler.py
DataManagementSystem/private/FTS3Utilities.py
DataManagementSystem/private/test/Test_FTS3Utilities.py
tests/Integration/DataManagementSystem/Test_Client_FTS3.py
tests/Integration/all_integration_client_tests.sh
tests/Integration/all_integration_server_tests.sh

Quite a few pending features and bug fixes
All transparent except the JEncode usage, but that's fine, it's only until both the RMS and the FTS run the latest version. 
*DMS
CHANGE: FTS3 persistOperation method checks that the caller is allowed to do so
CHANGE: FTS3Manager: do not expose updateJobStatus and updateFileStatus on the service
CHANGE: FTS3 operation is canceled if the matching request is canceled 
CHANGE: when a source file does not exist, defunct the FTS3File associated
CHANGE: use the JEncode serializer instead of the custom FTS3Serializer
CHANGE: cancel an FTS3Job together with its associated FTS3Files if the job is not found on the server

[v7r0] Few FTS3 features and bug fixes
