DIRACGrid/DIRAC

docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst, docs/source/AdministratorGuide/Tutorials/basicTutoSetup.sh, docs/source/AdministratorGuide/Tutorials/diracSE.rst, docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst, docs/source/AdministratorGuide/Tutorials/installTS.rst, docs/source/AdministratorGuide/Tutorials/managingIdentities.rst
Please merge as soon as @andresailer gives the green light
*Docs
FIX: few fixes for the tuto for dms with ts
=> [v6r21] Final touches for the tuto

ConfigurationSystem/Client/CSAPI.py
*CS
FIX: Fix exception when calling dirac-admin-add-shifter with already existing values
=> [v6r21] dirac-admin-add-shifter fix

Core/scripts/install_full.cfg, Core/scripts/install_minimal.cfg, Core/scripts/install_secondary.cfg, docs/source/AdministratorGuide/InstallingDIRACService/index.rst
*docs
CHANGE: DIRAC installation procedure is updated taking account DIRACOS
=> [v6r21] update DIRAC installation procedure

DataManagementSystem/Agent/FTS3Agent.py, DataManagementSystem/ConfigTemplate.cfg, docs/source/AdministratorGuide/Resources/Storage/index.rst, docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst
All in the title, not worth to be in the release not I assume
=> [v6r21] Docs: update FTS3 doc with multiprotocol

Resources/Storage/StorageElement.py
*Resources
FIX: Fix the exception when StorageElement objects are created with a list of plugins
Also removing some unnecessary duplication of code
=> [v6r21] StorageElement: fix for list of plugins

Core/Utilities/MySQL.py, ResourceStatusSystem/Utilities/CSHelpers.py, WorkloadManagementSystem/Client/Matcher.py, WorkloadManagementSystem/Service/JobManagerHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, WorkloadManagementSystem/Service/OptimizationMindHandler.py
*WMS
FIX: better logging from services
=> [v6r21] Fixed some logging lines from WMS services

Core/DISET/private/MessageFactory.py, WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/Service/JobPolicy.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, WorkloadManagementSystem/Service/OptimizationMindHandler.py, WorkloadManagementSystem/Service/SandboxStoreHandler.py
...and the usual deluge of pep8 and minor stuff.
*WMS
FIX: fixed service name in ConfigTemplate.cfg
=> [v6r22] fixed PilotManager service name in ConfigTemplate.cfg

Core/scripts/dirac-install.py, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh, tests/Workflow/Regression/Test_RegressionUserJobs.py, tests/Workflow/Regression/helloWorld.xml
...don't deserve a note I think.
=> [v6r22] CI: using --modules instead of replacing code

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Services/Server/index.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
*Configuration
FIX: Minor fix when creating the pilot.json
*docs
CHANGE: Pilots3 options: moved to /Operation/Pilot section
=> [v6r22] Few fixes for pilot 3

ResourceStatusSystem/Client/PublisherClient.py, ResourceStatusSystem/Client/ResourceManagementClient.py, ResourceStatusSystem/Client/ResourceStatusClient.py, ResourceStatusSystem/DB/ResourceManagementDB.py, ResourceStatusSystem/DB/ResourceStatusDB.py, ResourceStatusSystem/Service/PublisherHandler.py, tests/Integration/ResourceStatusSystem/Test_Publisher.py
*RSS
CHANGE: clients: using DIRAC.Core.Base.Client as base
=> [v6r22] RSS clients: using DIRAC.Core.Base.Client as base

Core/Utilities/CFG.py, WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py
I'll merge this as soon as the Travis test ends. This should fix the run of local pytest jobs
=> [integration] removed test that was copying files

.travis.d/checkDocs.sh, DataManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, WorkloadManagementSystem/Service/OptimizationMindHandler.py, docs/diracdoctools/cmd/concatcfg.py, docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst
There was a bad merge in the ConfigTemplete.cfg for DataManagement, @chaen, please check
*Docs:
CHANGE: diracdoctools concatcfg: catch exception when parsing of ConfigTemplate fails, return with 1
=> [v7] fix DataManagement/ConfigTemplate from bad merge

DataManagementSystem/Client/FileCatalogClientCLI.py, DataManagementSystem/DB/FileCatalogComponents/DatasetManager.py, DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py, DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py, DataManagementSystem/DB/FileCatalogComponents/FileMetadata.py, DataManagementSystem/Service/FileCatalogHandler.py, DataManagementSystem/scripts/dirac-dms-find-lfns.py
Fixes the bug reported in #4058. 
*DMS
FIX: FileManagerBase - use returned ID:LFN dict instead of the LFN list. Fixes the bug in getReplicasByMetadata reported in #4058
=> [v6r21] BUG fix in getReplicasByMetadata

WorkloadManagementSystem/JobWrapper/JobWrapper.py
*WMS
CHANGE: Better logging in JobWrapper
=> [v6r21] Better logging in JobWrapper

TransformationSystem/Client/TaskManager.py
FIX: Testing if the request ID is correct was not done properly, test the numerical value
=> [v6r21] Fix RequestTaskManager

FrameworkSystem/Agent/CAUpdateAgent.py, WorkloadManagementSystem/Agent/OptimizerModule.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Client/Limiter.py, WorkloadManagementSystem/Client/Matcher.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/DB/JobLoggingDB.py, WorkloadManagementSystem/DB/PilotAgentsDB.py, WorkloadManagementSystem/DB/TaskQueueDB.py, WorkloadManagementSystem/Executor/InputData.py, WorkloadManagementSystem/Executor/JobPath.py, WorkloadManagementSystem/Executor/JobSanity.py, WorkloadManagementSystem/Executor/JobScheduling.py, tests/Jenkins/dirac_ci.sh
*WMS
FIX: fixes for logging messages for Matcher
FIX: fixes for logging messages for Optimizers
=> [v6r22] fixes for logging messages for Matcher

ConfigurationSystem/Agent/VOMS2CSAgent.py, ConfigurationSystem/Client/VOMS2CSSynchronizer.py, ResourceStatusSystem/Service/PublisherHandler.py
*CS
CHANGE: VOMS2CSSynchronizer: considering the case when no email is provided by VOMS
=> [v6r22] VOMS2CSSynchronizer: considering the case when no email is provided by VOMS

WorkloadManagementSystem/DB/PilotsLoggingDB.py, tests/Integration/WorkloadManagementSystem/Test_PilotsLoggingClient.py, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Integration/all_tests.sh
This is innocuous for all the rest, so I'd like to merge this straight away.
=> [v6r21] added an integration tests file for easing Jenkins tests

requirements.txt
Fix for tests:
maybe review merge and propagate?
=> [v6r21] Freeze typing to 3.6.6 because it causes an exception in hypothesis

docs/source/UserGuide/GettingStarted/InstallingClient/index.rst
*Docs
FIX: UserGuide/ClientInstallation: small changes such as typos and necessary abbreviations to enhance the readability
=> [v7]Docs: typos + minor amendments

docs/source/AdministratorGuide/Configuration/ConfReference/Operations/DataManagement/index.rst
Following 
* https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-v6r17
* https://groups.google.com/forum/#!topic/diracgrid-forum/ycaxn93br-w
*Docs
NEW: Added /Operations/DataManagement parameters for protocols 
=> [v6r21] Docs (/Operations/DataManagement): Parameters for protocols added.

Core/Utilities/SiteSEMapping.py, Core/Utilities/SitesDIRACGOCDBmapping.py, DataManagementSystem/Utilities/DMSHelpers.py, ResourceStatusSystem/Command/DowntimeCommand.py, ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py, ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBSyncCommand.py, ResourceStatusSystem/Service/PublisherHandler.py, ResourceStatusSystem/Utilities/CSHelpers.py, ResourceStatusSystem/Utilities/Synchronizer.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Agent/test/Test_Agent_SiteDirector.py, docs/source/AdministratorGuide/Configuration/ConfReference/Operations/Pilots/index.rst
*DMS
CHANGE: Moved methods from ResourceStatusSystem/CSHelpers to DMSHelpers
*RSS
CHANGE: downtimeCommand will use the GOCServiceType only for SRM SEs
*WMS
NEW: added DIRACOS option (for SiteDirectors)
=> [v6r22] Added DIRACOS option (for SiteDirectors)

FrameworkSystem/Client/ComponentInstaller.py, FrameworkSystem/Client/test/Test_ComponentInstaller.py, FrameworkSystem/scripts/dirac-install-component.py, README.rst, tests/Integration/all_integration_client_tests.sh, tests/Jenkins/dirac_ci.sh, tests/Jenkins/install.cfg
=> [integration] component installer debug, plus pylint stuff, plus better tests

docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst, docs/source/AdministratorGuide/Tutorials/basicTutoSetup.sh
I guess take a look at this when the rest of the software is ready for CentOS 7. 
*Docs
CHANGE: updated basic tutorial for CC7 instead of SLC6. 
=> [LATER] Docs: updated basic tutorial for CC7

tests/Integration/all_integration_server_tests.sh
Test_DataIntegrityDB.py was not logging to testOutputs.txt
*Test
FIX: added missing logging for Test_DataIntegrityDB.py in all_integration_server_tests.sh
=> added missing logging for Test_DataIntegrityDB.py

ResourceStatusSystem/Command/FreeDiskSpaceCommand.py, tests/System/client_dms.sh
Outcome of the hackaton 
*RSS
FIX: only take the first endpoint for the SpaceOccupancy
*Tests
FIX: client_dms.sh not lhcb specific
=> [v6r22]  hackaton fixes

tests/System/transformationSystem.sh, tests/System/transformation_replication.sh
*Tests
CHANGE: adapt transformation certification tests to dteam VO
=>  [v6r22] Certification: transformation tests, adapt to dteam, fix usage, add replica output

Interfaces/API/Job.py, WorkloadManagementSystem/Agent/SiteDirector.py, docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst, setup.cfg, tests/System/unitTestUserJobs.py, tests/Utilities/mpTest.py, tests/Utilities/testJobDefinitions.py, tests/Utilities/testMpJob.sh, tests/Workflow/Integration/Test_UserJobs.py
For #4127 and also #3926.
*Interfaces
NEW: added setNumberOfProcessors method to Job() API
=> [v6r22] added setNumberOfProcessors method to Job() API

tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
*tests
NEW: Using variable for location of INSTALL_CFG_FILE (useful for extensions)
=> [v6r22] Using variable for location of INSTALL_CFG_FILE

Resources/Storage/GFAL2_HTTPSStorage.py
*Resources
NEW: add dav(s) in the protocol lists of GFAL2_HTTPS
=> [v6r22] Storage: add dav(s) in the protocol lists of GFAL2_HTTPS

codecov.yml
Also the paths should not have started with DIRAC
=> [v6r22] CodeCov: remove unused flags section

docs/source/AdministratorGuide/centralizedLogging.rst
=> [v6r22] Update centralizedLogging.rst

ConfigurationSystem/Client/Helpers/Resources.py, ResourceStatusSystem/Command/DowntimeCommand.py, ResourceStatusSystem/Utilities/Synchronizer.py
*RSS
FIX: only use the hostname of FTS servers
=> [v6r21] RSS and GOC DB: the hostname of FTS servers is used

ConfigurationSystem/Agent/VOMS2CSAgent.py, ConfigurationSystem/Client/Helpers/Resources.py, Core/Utilities/Graphs/GraphData.py, Core/Utilities/MySQL.py, Core/scripts/dirac-install.py, FrameworkSystem/Client/ComponentInstaller.py, FrameworkSystem/Client/test/Test_ComponentInstaller.py, FrameworkSystem/scripts/dirac-install-component.py, Interfaces/API/Dirac.py, Interfaces/scripts/dirac-wms-job-attributes.py, README.rst, ResourceStatusSystem/Utilities/CSHelpers.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Agent/StalledJobAgent.py, WorkloadManagementSystem/Agent/test/Test_Agent_SiteDirector.py, WorkloadManagementSystem/Client/JobState/JobState.py, WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, tests/Integration/FIXME_Test_MySQL.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py, tests/System/rss-scripts.sh, tests/System/unitTestUserJobs.py, tests/Utilities/mpTest.py
*Interfaces
CHANGE: removed deprecated methods from Dirac.py
*WMS
NEW: SiteDirectors send by default Pilot3 (flag for pilot2 is still kept)
FIX: removed unicode_literals (messes up things with DEncode)
=> [v7r0] [fixes out of hackhathon of 11/07] SiteDirectors send by default Pilot3, plus several other fixes

docs/source/AdministratorGuide/InstallingWebAppDIRAC/index.rst
*docs
CHANGE: update WebApp administrator docs
=> [v6r22] update the WebApp administrator docs

WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/Utilities/JobParameters.py, WorkloadManagementSystem/scripts/dirac-wms-get-wn-parameters.py, docs/source/AdministratorGuide/CommandReference/dirac-admin-service-ports.rst, docs/source/AdministratorGuide/CommandReference/dirac-framework-ping-service.rst, docs/source/AdministratorGuide/CommandReference/dirac-status-component.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Databases/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/URLs/index.rst, docs/source/AdministratorGuide/SystemAdministratorInterface/index.rst, tests/System/unitTestUserJobs.py
Marking this as WIP as a few discussions may arise. CC @atsareg 
*WMS
CHANGE: added function to get the number of Processors, using it in dirac-wms-get-wn-parameters (invoked by the pilots)
CHANGE: changed port of PilotManager from 9129 to 9171
*docs
CHANGE: removed mentions of MPIService
=> [WIP][v6r22] Fixes for getNumberOfProcessors + changed port of PilotManager

ProductionSystem/DB/ProductionDB.py, ResourceStatusSystem/Policy/JobDoneRatioPolicy.py, ResourceStatusSystem/Policy/JobEfficiencyPolicy.py, ResourceStatusSystem/Policy/JobRunningMatchedRatioPolicy.py, ResourceStatusSystem/Policy/JobRunningWaitingRatioPolicy.py, ResourceStatusSystem/Policy/PilotEfficiencyPolicy.py, ResourceStatusSystem/Policy/PropagationPolicy.py, ResourceStatusSystem/PolicySystem/PDP.py, ResourceStatusSystem/PolicySystem/PEP.py, ResourceStatusSystem/PolicySystem/PolicyCaller.py, ResourceStatusSystem/Service/ResourceManagementHandler.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
*RSS
CHANGE: use the ObjectLoader for Clients, in PEP
*test
FIX: restored test of JobsMonitor().JobParameters
=> [v7r0] Minor fixes in RSS

Core/scripts/dirac-install.py
*Core
NEW: Allow to install an extension of DIRACOS
=> [v6r22] allow to instans an extension of diracos

docs/source/DeveloperGuide/Systems/Transformation/transformationplugin.rst
*Docs
FIX: Create a TransformationAgent Plugin -- more concrete descriptions for adding a plugin to AllowedPlugins
=> [v6r22] Update transformationplugin.rst

tests/Jenkins/utilities.sh, tests/Utilities/utils.py
=> [v6r22] test fixes (for Jenkins)

Core/Security/m2crypto/__init__.py, Core/Security/m2crypto/asn1_utils.py, ProductionSystem/DB/ProductionDB.py
Tested in DIRAC certification
*Core
FIX: Add CountryName OID and be more permissive in the String type for decoding VOMSExtensions
=> [v7r0] fix hack1

TransformationSystem/Client/Transformation.py, tests/System/dirac-test-production.py
=> [v7r0] Fix TS test

FrameworkSystem/Client/ProxyManagerClient.py, MonitoringSystem/Client/MonitoringReporter.py
FIX: This will fix the issue #4193 
=> [rel-v7r0] Make the MonitoringReporter thread safe.

Resources/Storage/GFAL2_SRM2Storage.py
*Resources/Storage
CHANGE: improved treatment for the case without SpaceToken in SpaceOccupancy 
=> [v6r22] improved treatment for the case without SpaceToken in SpaceOccupancy

DataManagementSystem/Client/FailoverTransfer.py, DataManagementSystem/Client/test/Test_Client_DataManagementSystem.py, DataManagementSystem/Client/test/mock_DM.py, Resources/Catalog/test/mock_FC.py, WorkloadManagementSystem/DB/SandboxMetadataDB.py, WorkloadManagementSystem/Service/SandboxStoreHandler.py, docs/source/AdministratorGuide/MultiVO/index.rst
For #4212 
*WMS
CHANGE: Sandbox: Adding OwnerDN and OwnerGroup for DelayedExternalDeletion
=> [v6r22] Adding OwnerDN and OwnerGroup for DelayedExternalDeletion

docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst, docs/source/AdministratorGuide/Tutorials/diracSE.rst
Co-Authored-By: Andre Sailer <andre.philippe.sailer@cern.ch>
*docs
CHANGE: add minor details in the administrator tutorials documentation
=> [v7r0] Add minor details in the documentation: administrator tutorials

FrameworkSystem/Client/ProxyManagerClient.py
*Framework
FIX: correct X509 chain reverted
=> [v7r1] ProxyManagerClient: revert back chain tests

TransformationSystem/Agent/InputDataAgent.py, TransformationSystem/Agent/MCExtensionAgent.py, TransformationSystem/Agent/RequestOperations/SetFileStatus.py, TransformationSystem/Agent/TransformationAgent.py, TransformationSystem/Agent/ValidateOutputDataAgent.py, TransformationSystem/Client/TaskManager.py, TransformationSystem/ConfigTemplate.cfg
*TS
CHANGE: do not set Job type 'hospital' 
=> [v6r22]  do not set Job type 'hospital' 

ConfigurationSystem/Client/Helpers/Registry.py, ConfigurationSystem/Client/Helpers/Resources.py, FrameworkSystem/DB/ProxyDB.py, Resources/ProxyProvider/DIRACCAProxyProvider.py, Resources/ProxyProvider/ProxyProviderFactory.py
Fix some bugs and conflicts
*ConfigurationSystem:
FIX: Add getUserDict and fix getInfoAboutProviders methods in Registry and Resources
*FrameworkSystem:
FIX: fix some bugs in ProxyDB
*Resources:
FIX: Edit DIRACCAProxyProvider to use M2Crypto
=> [v7r1] Fix bugs and conflicts with working with OAuthDIRAC

DataManagementSystem/DB/FileCatalogComponents/SEManager.py
First part of https://github.com/DIRACGrid/DIRAC/issues/4227
Tested in prod on one lhcb server
*Resources
CHANGE: DFC SEManagerDB: only acquire the lock if the cache needs to be modified
=> [v6r22] Better performance for SEManager

Core/Security/m2crypto/X509Chain.py, Core/Utilities/Decorators.py, docs/source/AdministratorGuide/technologyPreviews.rst
*Core
FIX: change orders of @deprecated and @classmethod decorators in X509Chain
=> [v7r0] Fixes from hackaton

Resources/Storage/StorageElement.py
This should address https://github.com/DIRACGrid/DIRAC/issues/4088
Before:
```
File "/tmp/testSE.py", line 6, in <module>
print StorageElement('CERN-USER').getFileMetadata('/lhcb/user/c/chaen/zozo.xml', protocols='root')
File "/opt/dirac/DIRAC/Resources/Storage/StorageElement.py", line 1234, in __executeMethod
res = fcn(urlsToUse, *args, **kwargs)
TypeError: getFileMetadata() got an unexpected keyword argument 'protocols'
```
And after, it just returns the metadata
*Resources
FIX: SE __executeMethod: only pass protocols parameter to getTransportURL
=> [v7r0] only pass protocols parameter to getTransportURL in executeMethod

ConfigurationSystem/Client/Helpers/Resources.py, Resources/Computing/ARCComputingElement.py, Resources/Computing/BOINCComputingElement.py, Resources/Computing/CREAMComputingElement.py, Resources/Computing/GlobusComputingElement.py, Resources/Computing/InProcessComputingElement.py, Resources/Computing/LocalComputingElement.py, Resources/Computing/PilotBundle.py, Resources/Computing/PoolComputingElement.py, Resources/Computing/SSHBatchComputingElement.py, Resources/Computing/SSHComputingElement.py, Resources/Computing/SudoComputingElement.py, tests/System/unitTestUserJobs.py, tests/Utilities/testJobDefinitions.py
... no need for notes. 
I also added more system tests (jobs) for the DIRAC certification, where I added an SSHBatch CE.
=> [v7r0] Minor fixes for Computing Resources

tests/Integration/all_integration_server_tests.sh
=> [v7r1] resolve conflicts

WorkloadManagementSystem/Agent/SiteDirector.py
FIX: Fix documentation inside `WorkloadManagementSystem/Agent/SiteDirector` which was failing the `Travis` test.
=> [v7r0] Fix documentation.

ConfigurationSystem/ConfigTemplate.cfg, ConfigurationSystem/Service/ConfigurationHandler.py, Core/Utilities/CFG.py, Core/Utilities/CountryMapping.py, Core/Utilities/DirectoryExplorer.py, Core/Utilities/EventDispatcher.py, FrameworkSystem/Client/ComponentInstaller.py, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Configuration/Services/Server/index.rst, docs/source/AdministratorGuide/Configuration/ExampleConfig.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst, tests/Jenkins/dirac_ci.sh
In order to overcome bootstrap issues, the flag UpdatePilotCStoJSONFile has been moved to the Operations/[]/Pilot section
*Configuration
CHANGE: The flag UpdatePilotCStoJSONFile has been moved to Operations/[]/Pilot section
=> [v7r0] Hackathon fixes

Workflow/Modules/FailoverRequest.py, Workflow/Modules/UploadOutputs.py, Workflow/Utilities/test/Test_Utilities.py, tests/System/dirac-test-production.py
=> [v7r0] Added module FailoverRequest to test production job 

Resources/Storage/OccupancyPlugins/WLCGAccountingJson.py
Following #4142, a new space occupancy plugin for the WLCG standard accounting JSON.
*Resources/Storage
NEW: Occupancy plugin for WLCG standard accounting JSON
=> [v6r22] add WLCGjsonOccupancy.py

Core/Utilities/PrettyPrint.py, WorkloadManagementSystem/Utilities/QueueUtilities.py, WorkloadManagementSystem/scripts/dirac-wms-match.py
This PR adds dirac-wms-command which allows to test a given job description for matching with computing resources capabilities. Example of usage:
> dirac-wms-match -S EGI.SARA.nl,EGI.BARI.it -F test.jdl 
Site         CE                     Queue               Status  Match  Reason
====================================================================================================================================
1  EGI.BARI.it  cream-ce-2.ba.infn.it  cream-pbs-infinite  Active  Yes 
2  EGI.SARA.nl  creamce3.gina.sara.nl  cream-pbs-medium    Active  No     Resource operational JobType requirement not satisfied
*WMS
NEW: Added dirac-wms-match command to test a given job for matching computing resources
NEW: QueueUtilities - utilities relevent to queues manipultation …
=> [v7r0] New dirac-wms-match command

ConfigurationSystem/Client/CSAPI.py, ConfigurationSystem/Client/Helpers/Registry.py, FrameworkSystem/Client/ProxyManagerClient.py, FrameworkSystem/DB/ProxyDB.py, FrameworkSystem/Service/NotificationHandler.py, FrameworkSystem/Service/ProxyManagerHandler.py, Resources/ProxyProvider/DIRACCAProxyProvider.py, Resources/ProxyProvider/PUSPProxyProvider.py, tests/Integration/Framework/Test_ProxyDB.py
This PR resolve some issues with compatibility, bugs, added helper method.
*Configuration
NEW: Add search emails for group method in Registry
*Framework
NEW: Filter of duplicate mails in Notification
FIX: Delete not used comments
FIX: Optimize test in NotificationHandler
FIX: Add old method storeProxy to proxyDB, fix compatibility for ProxyManager
*Resources
FIX: Rename 'EMail' to 'Email' in ProxyProviders
=> [v7r1] ProxyManager compatibility, add method to get e-mails in Registry, resolve issues

Core/Workflow/Workflow.py
*Core
FIX: Workflow - revert changes introduced in #4253 
=> [v6r22] Revert changes from #4253

Resources/Storage/StorageElement.py
*Resources
FIX: loadObject of occupancyPlugin is called with the path to OccupancyPlugins
=> [v6r22] Add the path to OccupancyPlugins in loadObject of occupancyPlugin

Core/Workflow/Workflow.py
Restoring https://github.com/DIRACGrid/DIRAC/pull/4253 after v6r22
Plus fix of pylint --3k test.
=> [v7r0] Replace isinstance basestring with six.string_type

FrameworkSystem/DB/ProxyDB.py, Resources/IdProvider/IdProvider.py, Resources/IdProvider/IdProviderFactory.py
*FrameworkSystem/DB/ProxyDB:
CHANGE: Add deprecated decorator
*Resources:
NEW: Add Resources/IdProvider
=> [v7r1] Add Identity provider resources

Core/DISET/private/Service.py, FrameworkSystem/Service/ProxyManagerHandler.py, Resources/ProxyProvider/DIRACCAProxyProvider.py, Resources/ProxyProvider/ProxyProviderFactory.py, tests/Integration/Resources/ProxyProvider/Test_DIRACCAProxyProvider.py
This PR will fix some bugs
*Core:
FIX: test if proposalTuple before read clientVersion in /DISET/private/Service
*FrameworkSystem:
FIX: Add None type for vomsAttribute in ProxyManagerHandler
*Resources:
NEW: Add test for None proxyProvider in ProxyProviderFactory
FIX: Fix bugs and change test for DIRACCAProxyProvider
=> [v7r1] Bugs fixes.

Resources/Computing/ComputingElement.py, Resources/Computing/SSHComputingElement.py, WorkloadManagementSystem/Agent/SiteDirector.py
This PR fixes issues #4262 and #4263
*Resources
FIX: SSHComputingElement - define X509_USER_PROXY in case of gsissh access
*WMS
FIX: SiteDirector - do not use keyword arguments when making setPilotStatus call 
=> [v6r21] Several WMS/Resources fixes

AccountingSystem/Agent/NetworkAgent.py, AccountingSystem/Client/Types/Network.py, AccountingSystem/private/Plotters/NetworkPlotter.py, Interfaces/scripts/dirac-wms-job-get-input.py, Interfaces/scripts/dirac-wms-job-get-jdl.py, Interfaces/scripts/dirac-wms-job-kill.py, Interfaces/scripts/dirac-wms-job-reschedule.py, Interfaces/scripts/dirac-wms-job-submit.py, Interfaces/scripts/dirac-wms-jobs-select-output-search.py, WorkloadManagementSystem/Client/PoolXMLSlice.py, WorkloadManagementSystem/scripts/dirac-wms-get-wn.py, WorkloadManagementSystem/scripts/dirac-wms-pilot-job-info.py
*WMS
NEW: dirac-wms-get-wn and dirac-wms-pilot-job-info scripts (ported from LHCbDIRAC)
=> [v7r0] new WMS scripts (ported from LHCbDIRAC)

tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
*tests
CHANGE: removed pilot2 tests
=> [v7r0] Simply removed the pilot 2 tests

Core/scripts/dirac-cert-convert.sh, Core/scripts/dirac-executor.py, Core/scripts/dirac-install-db.py, Core/scripts/dirac-install.py, Core/scripts/dirac-platform.py, Core/scripts/dirac-setup-site.py, Core/scripts/dirac-version.py, Core/scripts/genAllCAs.sh, Core/scripts/genRevokedCerts.sh, Core/scripts/install_site.sh
*Core
FIX: install_site.sh : set UpdatePilotCStoJSONFile=False for initial installations
=> [v7r0] Fixes for core scripts

Core/Utilities/ElasticSearchDB.py, Core/Utilities/ProcessPool.py, DataManagementSystem/scripts/dirac-dms-create-archive-request.py, DataManagementSystem/scripts/dirac-dms-create-moving-request.py, Resources/Storage/GFAL2_XROOTStorage.py
*Core
FIX: Better logs and defaults for ElasticSearchDB base class
=> [v7r0] Minor fixes for ElasticSearchDB base class

TransformationSystem/Agent/DataRecoveryAgent.py, TransformationSystem/Utilities/JobInfo.py, TransformationSystem/test/Test_JobInfo.py
*TS
CHANGE: DataRecoveryAgent: Tweak information printout for email formatting; clarify use of default values; reduce logging verbosity
=> [v6r22] DataRecoveryAgent tweaks

FrameworkSystem/DB/InstalledComponentsDB.py
The "CPU model" of our servers occasionally change, e.g., from
`Intel Core Processor (Haswell, no TSX)`
to
`Intel Core Processor (Haswell, no TSX, IBRS)`
When we then install a new component on the server the ComponentMonitoring adds a new entry in the Hosts table of the InstalledComponentsDB, which leads the WebApp SysAdmin to show these servers multiple times (of course picking up the CPU from the machine and not the DB).
This patch changes the behaviour to update the CPU model instead of adding additional Host entries with the same HostName.
There is the danger that if people did not clean up their Hosts table of the duplicate entries, this current implementation will result in an S_ERROR, but I can also change things to accept there to be multiple entries with the same HostName? …
=> [v6r22] InstalledComponentsDB: do not create new host if only the CPU has changed

docs/source/AdministratorGuide/HowTo/multiVO.rst, docs/source/AdministratorGuide/Resources/storage.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/ServerInstallations/index.rst
This belongs to #4334 but to avoid conflicts because of the admin doc restructuring this is a separate PR.
=> [v7r0] Docs: add words about GRIDFTP SESSION_REUSE

Resources/Storage/GFAL2_StorageBase.py
=> just fix docstring

docs/diracdoctools/Utilities.py
@atsareg @fstagni please merge and propagate as soon as @andresailer has approved please
*Docs
CHANGE: create the subdirs for the automatically generated doc
=> [v7r0][urgent] Docs: create directory for generated files if needed

Core/Security/Properties.py, docs/source/AdministratorGuide/HowTo/authentication.rst
https://github.com/DIRACGrid/DIRAC/issues/4077 still needs to be done, but I just formatted correctly the comments
=> [v7r0] Documentation formating for properties

.travis.yml
=> do not fail when skipping travis format check for non PRs

FrameworkSystem/Service/ProxyManagerHandler.py
FIX: PRIVATE_LIMITED_DELEGATION role can download a proxy
=> [v6r22] allow to download proxy for PRIVATE_LIMITED_DELEGATION role

ResourceStatusSystem/Service/PublisherHandler.py
*ResourceStatusSystem
FIX: Convert set to list, because set can not be serialized using DEncode.
=> [v6r22] fix RSS method used by web

.travis.yml
=> V7r0 fixes27

Core/scripts/dirac-configure.py, WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, docs/source/DeveloperGuide/CodeTesting/index.rst, docs/source/DeveloperGuide/ReleaseProcedure/index.rst, tests/CI/README.MD, tests/CI/run_docker_setup.sh, tests/CI/run_tests.sh
*Configuration
CHANGE: Let update the config, even if the Pilot info is not in the CS
=> [v7r0]  Let update the config, even if the Pilot info is not in the CS

Core/Utilities/test/Test_Encode.py
This just changes the `Test_Encode.py` test to use the hypothesis public api, since they changed the internals I was using (my fault)
https://github.com/HypothesisWorks/hypothesis/pull/2264
=> [PLEASE MERGE AND PROPAGATE NOW] Use Hypothesis public API

.github/workflows/integration.yml, docs/source/DeveloperGuide/CodeTesting/index.rst
*docs
CHANGE: using docker images from docker hub
cc @chrisburr
=> [v7r0] Using images from docker hub

Core/DISET/RequestHandler.py, Core/DISET/TransferClient.py, Core/DISET/private/BaseClient.py, Core/DISET/private/FileHelper.py, Core/DISET/private/InnerRPCClient.py, Core/DISET/private/Service.py, Core/Utilities/DEncode.py, FrameworkSystem/Client/BundleDeliveryClient.py, ResourceStatusSystem/Agent/SummarizeLogsAgent.py, WorkloadManagementSystem/Client/SandboxStoreClient.py
This contains the first changes for JSON serialization. It should cover the very underlying layers. More changes will need to be done, see all the tasks tagged [JSON]
This is not forward compatible: new clients cannot talk to old server. Anyway, it's already not the case in this release. 
*Core
CHANGE: RPC parameters are cast to list/tuples when needed
*Framework
CHANGE: BundleDeliveryFramework uses list instead of tuple
*RSS
CHANGE: SQL query orders using list instead of tuples
*WMS
CHANGE: SandboxStoreClient uses list instead of tuple
=> [v7r1] JSON serialization first steps

.github/workflows/integration.yml
=> Fix integration tests

WorkloadManagementSystem/JobWrapper/Watchdog.py, tests/Jenkins/utilities.sh, tests/Workflow/Regression/helloWorld.xml
I think this is rather urgent. 
*WMS
FIX: Watchdog: get the CPU consumed by children processes too
=> [v7r0] Watchdog: get the CPU consumed by children processes too

Core/Utilities/Grid.py, Resources/Computing/ARCComputingElement.py, Resources/Computing/CREAMComputingElement.py, Resources/Computing/GlobusComputingElement.py, Resources/Computing/HTCondorCEComputingElement.py
*Resources
FIX: ComputingElement classes: use GridEnv if present
=> [v7r0] use GridEnv if present

Core/scripts/dirac-install.py, Interfaces/API/Job.py, Interfaces/API/test/Test_JobAPI.py, WorkloadManagementSystem/Agent/SiteDirector.py, tests/Utilities/testJobDefinitions.py, tests/Workflow/Integration/Test_UserJobs.py
*WMS
FIX: SiteDirector: Pilot3 option easier to interpret
*Core
NEW: dirac-install accepts userEnvVariables switch, adds user-requested env variables to *rc files
=> [v7r0] Some fixes for running pilots

ConfigurationSystem/private/ConfigurationClient.py
Add new method named getOptionsDictRecursively to get options from CS recursively to dictionary, this method will use in future WebAppDIRAC PR and add some docs
NEW: Add getOptionsDictRecursively method, add docs
=> [v7r1] Add getOptionsDictRecursively method

.github/workflows/diracinstall.yml, Core/Utilities/Platform.py, Core/scripts/dirac-install.py
*Core
FIX: Make dirac-install tool python 3 compatible
=> [v7r0] makde dirac-install python3 compatible

FrameworkSystem/Service/SystemLoggingHandler.py, WorkloadManagementSystem/Service/WMSAdministratorHandler.py
FIX: docs, optimize
FIX: docs, optimize
=> [v7r1] small PR with docs, optimize

.github/workflows/nightly.yml
This PR adds a GitHub Actions workflow that builds and uploads, every 24 hours, an "integration" and a "master" tarball. The "integration" tarball is then used for checks on PRs targeting the integration branch.
=> [integration] added nigthly action (for creating tarball of integration and master)

.github/workflows/integration.yml
=> [v7r1] Test against more MySQL server versions

Core/DISET/private/Service.py
=> [integration] Trying to fix the integration branch after bad merge

TransformationSystem/Client/TaskManager.py, TransformationSystem/Client/test/Test_Client_WorkflowTasks.py
*WMS
FIX: fix bug in finding the settings for Clinics in the hospital
=> [v6r22] Fix bug in clinic handling

WorkloadManagementSystem/Client/DownloadInputData.py, WorkloadManagementSystem/Executor/Base/OptimizerExecutor.py, WorkloadManagementSystem/Executor/InputData.py, WorkloadManagementSystem/Executor/JobPath.py, WorkloadManagementSystem/Executor/JobSanity.py, WorkloadManagementSystem/Executor/JobScheduling.py, WorkloadManagementSystem/Utilities/QueueUtilities.py
*WMS
FIX: Better logging for WMS Optimizers
=> [v7r0] Just better logging in WMS

tests/Integration/README.rst, tests/Jenkins/README.rst, tests/Performance/README.rst, tests/README.rst, tests/System/README.rst, tests/Workflow/README.rst
*tests
NEW: added README.rst for every subdirectory
=> [v7r0] added README for tests dirs

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, docs/source/AdministratorGuide/Configuration/ConfReference/Operations/VOs/index.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
*WMS
NEW: PilotCS2JSONSynchronizer: added options pilotRepoBranch and pilotVORepoBranch
=> [v7r0] PilotCS2JSONSynchronizer: radded options pilotRepoBranch and pilotVORepoBranch

tests/Integration/Framework/Test_Proxy.sh, tests/System/client_core.sh
*Test
FIX: restored system test, moved Jenkins test to appropriate location
=> [v7r1] fixes from hackathon

.gitignore, ResourceStatusSystem/Command/DowntimeCommand.py, tests/Workflow/Integration/Test_UserJobs.py, tests/Workflow/Regression/Test_RegressionUserJobs.py, tests/Workflow/Regression/helloWorld.xml
*RSS
FIX: fix typo in DowntimeCommand that was preventing to update expired or deleted downtimes from RSS downtime cache.
=> [v6r22] Fix typo in RSS

ConfigurationSystem/Client/Utilities.py, Core/Base/ElasticDB.py, Core/Utilities/ElasticSearchDB.py
*Core
FIX: If no port is set in the CS for ES assume that the URL points to right location
=> [v6r22] Fix ES port

ConfigurationSystem/private/ConfigurationClient.py, MonitoringSystem/Client/MonitoringReporter.py
Resolves #4446
FIX: remove logging from inside getConfigurationTree
FIX: add check if MQ is setup for Monitoring
=> [v6r22] Check if MQ is setup for Monitoring

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
*Docs
NEW: get-release-notes can take a sinceLatestTag option, header and footer messages, and can create github/gitlab release
=> [v7r0] Few new features for get-release-notes.py

Core/Utilities/Subprocess.py, Core/Utilities/test/ProcessesCreator.py, Core/Utilities/test/Test_Subprocess.py
...because the previous one to me and my tests looked completely broken
*Core
FIX: SubProcess: rewritten function for getting child PIDs
=> [v7r0] rewritten function for getting child PIDs

WorkloadManagementSystem/Utilities/PilotWrapper.py
*WMS
FIX: PilotWrapper: try to untar also with system tar 
=> [v7r0] PilotWrapper: try to untar also with system tar

Core/scripts/dirac-agent.py, Core/scripts/dirac-install.py, Core/scripts/dirac-service.py, Interfaces/API/Dirac.py, Resources/Computing/ComputingElement.py, Resources/Computing/ComputingElementFactory.py, Resources/Computing/InProcessComputingElement.py, Resources/Computing/PoolComputingElement.py, Resources/Computing/SSHComputingElement.py, Resources/Computing/SingularityComputingElement.py, Resources/Computing/SudoComputingElement.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py
*Core
CHANGE: agents exit with sys.exit(2) in case of errors
*Resources
CHANGE: InProcess CE correctly reports number of processors available
=> [v7r0] Fixes in Core and Resources

TransformationSystem/Agent/InputDataAgent.py, TransformationSystem/Client/TransformationClient.py, TransformationSystem/Service/TransformationManagerHandler.py
=> [v7r0] Simple fixes to logging in TransformationSystem

WorkloadManagementSystem/Client/JobState/JobState.py, WorkloadManagementSystem/DB/TaskQueueDB.py, WorkloadManagementSystem/Executor/InputData.py, WorkloadManagementSystem/Executor/test/Test_Executor.py
*WMS
CHANGE: Optimizer: treat input sandboxes uploaded as LFNs ad Input Data
=> [v7r0] Optimizer: treat input sandboxes uploaded as LFNs ad Input Data

Resources/MessageQueue/StompMQConnector.py
Addresses https://github.com/DIRACGrid/DIRAC/issues/4422
I am wondering whether I should add a few more layers of abstractions for the MQ....
*Resources
FIX: Stomp reconnection only reconnect the connection that dropped
=> [v7r0]Stomp: fixes the wild reconnections

.github/workflows/integration.yml, tests/CI/run_docker_setup.sh
I'll simplify the matrix in a PR directly to v7r1 as there are more jobs tested there (3 databases x 2 thread pools x 2 operating systems).
=> [v7r0] Test all combinations of M2Crypto and PyGSI

AccountingSystem/Client/ReportsClient.py, FrameworkSystem/Service/MonitoringHandler.py, ResourceStatusSystem/Command/AccountingCacheCommand.py, ResourceStatusSystem/Command/DIRACAccountingCommand.py, ResourceStatusSystem/Command/TransferCommand.py, tests/Integration/Monitoring/Test_MonitoringSystem.py
*RSS
FIX: JSON: convert the dictionary keys to number, when it is required.
=> [v7r1] JSON serialization: cast the result when it is needed

ResourceStatusSystem/Service/ResourceManagementHandler.py, ResourceStatusSystem/Service/ResourceStatusHandler.py
Dynamically load database handlers for ResourceStatus and ResourceManagement modules in preparation for a schema changes needed by multi-VO versions of these.
=> [v7r1] RSS DB handlers loaded dynamically

.github/workflows/basic.yml, .github/workflows/integration.yml, .github/workflows/pilotWrapper.yml, AccountingSystem/Client/DataStoreClient.py, AccountingSystem/DB/AccountingDB.py, AccountingSystem/Service/DataStoreHandler.py, DataManagementSystem/Service/StorageElementHandler.py, DataManagementSystem/Service/test/Test_Service.py, ResourceStatusSystem/Utilities/Synchronizer.py, Resources/Storage/DIPStorage.py
*DMS
FIX: StorageElementHandler: removed ignoreMaxStorageSize flag from getTotalDiskSpace and getFreeDiskSpace
=> [v7r0] Fix for getting a DIRAC SE total space

.github/workflows/integration.yml
MySQL server no longer runs on GitHub Actions (https://github.com/actions/virtual-environments/issues/375)
=> [v7r0] Fix CI failures due to GitHub actions environment changes

tests/Integration/Core/Test_MySQLDB.py
@aldbr can you please check ? I think it is from when you factorized the MySQL db tests in 1aa7317832
=> [v7r1] Fix MySQLDB race condition Tests

Core/Base/private/ModuleLoader.py, Interfaces/API/Dirac.py, Interfaces/API/Job.py, Interfaces/API/test/Test_DIRAC.py, TransformationSystem/DB/TransformationDB.sql, WorkloadManagementSystem/JobWrapper/JobWrapper.py, requirements.txt
*API
CHANGE: run jobs locally: use $DIRAC for $DIRACROOT
=> [v7r0] A few fixes for running jobs locally

tests/Integration/all_integration_client_tests.sh
=> [v7r0] Tests: force the DataManager test setup to use the DFC

FrameworkSystem/private/monitoring/MonitoringCatalog.py
=> Fix bad merge

Resources/Computing/HTCondorCEComputingElement.py
*Resources
FIX: added missing multicore option to HTCondorCE
=> [v6r22] added multiprocessor option to HTCondorCE

DataManagementSystem/Agent/FTS3Agent.py, DataManagementSystem/Client/FTS3Job.py, DataManagementSystem/ConfigTemplate.cfg
@zhangxiaomei that should also address your issue with FTS3 lifetime
*DMS
CHANGE: explicitly delegate the proxy to FTS3 with a configurable lifetime
=> [v7r0] FTS3: explicitely delegate and make the lifetime a CS param

Core/Utilities/Mail.py
These changes are required to use some SMTP settings in the Mail, such as Host, Port, Login, Password, Protocol.
*Core
FIX: add SMTP parameters
=> [v7r0] Use SMTP parameters in Mail

DataManagementSystem/Client/FailoverTransfer.py
We have a design flaw which is that, when uploading the output of a job, if it fails, we just upload it somewhere else and create a failover request. However, in the case where the DFC is totally down, you can't even reach this state, because you cannot perform the `hasAccess` operation. 
In practice, this results in losing the result of your job. 
This PR introduces a sleep & retry in case this happens
@fstagni this is what we discussed
*DMS
CHANGE: failoverTransfer sleep & retries in case of FC unavailability
=> [v7r0] Sleep and retry if the FC is unavailable when uploading output

tests/Integration/DataManagementSystem/Test_UserMetadata.py
=>  [v7r1] Multi-VO metadata. Test fix - remove debug print statement. 

WorkloadManagementSystem/Agent/SiteDirector.py
Just a simple fix to complete this change: 
https://github.com/DIRACGrid/DIRAC/commit/01ae5d1fa52cae5ba2d052f17eec551d5263e430#diff-ed886d0dfc6dcbc6b62699e32f11b07b
FIX: Remove strip() in SiteDirector.sendPilotAccounting() that was processing dict instead of str
=> [v7r1] Hackaton fix: SiteDirector.sendPilotAccounting() remove strip()

DataManagementSystem/Service/StorageElementHandler.py
*DMS
FIX: Do not return negative values in StorageElement.getFreeDiskSpace
=> [v7r1]  StorageElement.getFreeDiskSpace: fix for negative values

.github/workflows/integration.yml
This should allow the number of CI jobs to be reduced without compromising on test coverage.
=> [v7r1] Reduce number of CI jobs

TransformationSystem/Client/TransformationClient.py, TransformationSystem/Client/Utilities.py
*TS
FIX: infinite loop when a file was requested an it was not in the TS
CHANGE: show headers in Utilities sub logger (but this is not effective yet)
=> [v6r22] Urgent fix of TSClient

MonitoringSystem/DB/MonitoringDB.py, MonitoringSystem/private/Plotters/BasePlotter.py
*Monitoring
CHANGE: Allow to retrieve multiple variables from Monitoring DB.
Add functions to calculate efficiency.
=> [v6r22] Allow to retrieve multiple variables from MonitoringDB

FrameworkSystem/private/monitoring/MonitoringCatalog.py
Because after all, it is not so bad to know when we enter an infinite loop.... also, fixes the infinite loop, since we are at it
*Framework
CHANGE: Don't loop forever if a query does not work in the MonitoringCatalog
=> [v7r0] Framework/Monitoring: log exception when executing a query

Core/scripts/dirac-cert-convert.sh, Core/scripts/genAllCAs.sh, Core/scripts/genRevokedCerts.sh, Core/scripts/install_site.sh, tests/CI/install_client.sh, tests/CI/run_docker_setup.sh, tests/CI/run_tests.sh, tests/Integration/Framework/Test_Proxy.sh, tests/Integration/WorkloadManagementSystem/Test_TimeLeft.sh, tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh, tests/Performance/DFCPerformance/extractResult.sh, tests/System/client_core.sh, tests/System/client_dms.sh, tests/System/client_scripts.sh, tests/System/random_files_creator.sh, tests/System/rss-scripts.sh, tests/System/transformationSystem.sh, tests/System/transformation_replication.sh, tests/checkDocs.sh
=> [v7r1] only code updates for shell scripts

FrameworkSystem/private/monitoring/MonitoringCatalog.py, MonitoringSystem/DB/MonitoringDB.py, TransformationSystem/Client/TransformationClient.py, TransformationSystem/Client/Utilities.py, environment.yml, release.notes, requirements.txt
This is just a PR to trigger the tests
=> [v7r1] Merging v7r0

dashboards/diracLogsDashboard.json, docs/source/AdministratorGuide/ServerInstallations/centralizedLogging.rst
This is the kibana dashboard we use to visualize the logs in  LHCb prod and DIRAC certification
=> [v7r0] Add the centralized logging kibana dashboard

AccountingSystem/private/Policies/JobPolicy.py, ConfigurationSystem/Client/Helpers/Registry.py, ConfigurationSystem/Client/Utilities.py, Core/Base/API.py, Core/DISET/ThreadConfig.py, Core/DISET/private/BaseClient.py, Core/Utilities/DictCache.py, Core/Utilities/Mail.py, Core/Utilities/Shifter.py, DataManagementSystem/Agent/FTS3Agent.py, FrameworkSystem/Client/ProxyGeneration.py, FrameworkSystem/DB/NotificationDB.py, FrameworkSystem/scripts/dirac-admin-get-proxy.py, FrameworkSystem/scripts/dirac-proxy-get-uploaded-info.py, WorkloadManagementSystem/Service/JobManagerHandler.py, WorkloadManagementSystem/private/ConfigHelper.py
This small PR provides some documentation.
*Core
FIX: docs, optimize
FIX: docs
FIX: docs
FIX: docs
FIX: docs
=> [v7r1] docs

Resources/ProxyProvider/PUSPProxyProvider.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/ProxyProviders/index.rst, docs/source/AdministratorGuide/Resources/index.rst, docs/source/AdministratorGuide/Resources/proxyprovider.rst
This PR adds some documentation of ProxyProvider resources.
*docs
NEW: add ProxyProvider docs
=> [v7r1] ProxyProvider docs

DataManagementSystem/Client/DataManager.py, docs/diracdoctools/scripts/dirac-docs-get-release-notes.py, tests/Integration/DataManagementSystem/Test_DataManager.py, tests/Integration/WorkloadManagementSystem/Test_ElasticJobDB.py, tests/Integration/all_integration_client_tests.sh
A collection of various fixes
*Docs
CHANGE: allow release notes to be empty in dirac-docs-get-release-notes
*Tests
FIX: DataManager tests check VO dynamically
=> [v7r0] misleanous... misclenaous... miscallenous... various fixes

docs/requirements.txt, docs/source/conf.py
Some fixes to get the documentation build correctly again
=> [v7r0] doc fixes

Core/scripts/dirac-deploy-scripts.py
*Core
CHANGE: Source bashrc in wrapper script
As mentioned in #4480
=> [rel-v7r1] Source bashrc in wrapper script

Interfaces/API/Dirac.py
*Interfaces
CHANGE: Move DIRAC/VOPolicy/InputDataModule to DIRAC/Operations/InputDataPolicy
=> [v7r2] Move DIRAC/VOPolicy/InputDataModule under Operations/InputDataPolicy

Core/Utilities/Profiler.py, DataManagementSystem/Client/DataManager.py, TransformationSystem/Client/TransformationClient.py, TransformationSystem/Client/Utilities.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py
*Core
FIX: The CPU for the jobWrapper process group was incorrectly calculated as it was not including former children of the JobWrapper.
In addition fix a few modules for preparing for python3 (remove .keys(), .iterxxx() -> xxx(), basestring ->six.string_types...)
=> [v7r0] Fix Profiler for CPU estimate

FrameworkSystem/DB/ProxyDB.py
This is what I see in DIRAC certification: is it correct/expected?
```
bash-4.2$ dirac-proxy-init --upload
Generating proxy...
Enter Certificate password:
Uploading proxy..
Proxy generated:
subject      : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fstagni/CN=693025/CN=Federico Stagni/CN=7051768206
issuer       : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fstagni/CN=693025/CN=Federico Stagni
identity     : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fstagni/CN=693025/CN=Federico Stagni
timeleft     : 23:59:58
DIRAC group  : dirac_user
path         : /tmp/x509up_u49429
username     : fstagni
properties   : NormalUser
Proxies uploaded:
DN                                                                               | Group       | Until (GMT)
/DC=ch/DC=cern/OU=Organic …
```
=> [v7r1] removed group from proxy expiration notification

WorkloadManagementSystem/Agent/JobAgent.py
For https://github.com/DIRACGrid/DIRAC/issues/4600
*WMS
FIX: JobAgent: check if there are arguments
=> [v7r0] check if there are arguments

WorkloadManagementSystem/Client/JobDescription.py, WorkloadManagementSystem/Client/JobState/JobManifest.py
This PR is updates of JobManifest and JobDescription, and they enable to customize the JobType of user jobs.
I welcome your comments, especially about where the UserJobType parameter should put in CS with you.
*WMS
CHANGE: Updated to customize the JobType of user jobs in JobDescription and JobManifest
=> [v6r22] Updates to customize the JobType of user jobs.

Core/Utilities/Profiler.py, Core/Utilities/test/Test_File.py, Core/Utilities/test/Test_Profiler.py, FrameworkSystem/Service/SystemAdministratorHandler.py, WorkloadManagementSystem/JobWrapper/Watchdog.py, tests/Utilities/ProcessesCreator_withChildren.py
*Core
NEW: Added test for profiler.py
*WMS
FIX: Watchdog: use 2 flags for profiler: withChildren and withTerminatedChildren
=> [v7r0] Fixes for Profiler (and so for Watchdog)

container/docker_compose_setup/dockerfiles/DIRAC_CC7_Dockerfile, container/docker_compose_setup/dockerfiles/DIRAC_SLC6_Dockerfile, container/docker_compose_setup/dockerfiles/ES6_Dockerfile
*Container
FIX: Increase the health check interval in the dockerfiles
=> Health check interval increase for dockerfile

docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/editingCode.rst
*Docs
FIX: add missing packages for the UBUNTU Linux Distribution that need to be installed before installing DIRAC
*Docs
NEW: add useful commands for working with conda environments
=> [v7r0] Update editingCode.rst

WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Executor/JobScheduling.py, WorkloadManagementSystem/JobWrapper/Watchdog.py, WorkloadManagementSystem/JobWrapper/WatchdogLinux.py, WorkloadManagementSystem/JobWrapper/test/Test_Watchdog.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst, docs/source/AdministratorGuide/Configuration/ConfigurationStructure/index.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/editingCode.rst
*WMS
NEW: Watchdog: added DISABLE_WATCHDOG_CPU_WALLCLOCK_CHECK env variable
FIX: Watchdog: Split check methods for better control
*documentation
FIX: added doc about DIRACSYSCONFIG environment variable
=> [v7r0] WMS Watchdog: Split check methods for better control

DataManagementSystem/DB/FileCatalogComponents/DirectoryTreeBase.py, __init__.py, release.notes, setup.py
Release v7r0p26 to be checked by the CI actions
=> [v7r0] Release v7r0p26

Core/scripts/dirac-cert-convert.sh, Core/scripts/genAllCAs.sh, Core/scripts/genRevokedCerts.sh, Core/scripts/install_site.sh, tests/CI/run_docker_setup.sh, tests/CI/run_tests.sh, tests/Integration/WorkloadManagementSystem/Test_TimeLeft.sh, tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh, tests/Performance/DFCPerformance/extractResult.sh, tests/System/client_dms.sh, tests/System/random_files_creator.sh, tests/System/rss-scripts.sh, tests/System/transformationSystem.sh, tests/System/transformation_replication.sh
=> [v7r1] Bunch of fixes for sh files

environment.yml, requirements.txt
Add xmltodict
NEW: xmltodict makes working with XML feel like working with JSON.
=> [v7r1] Add xmltodict

Core/Utilities/MySQL.py, WorkloadManagementSystem/Service/WMSUtilities.py
Maybe it fixes #4579 
*Framework
FIX: Commit transaction when creating tables
=> [v7r0] Commit transaction when creating tables

AccountingSystem/private/Plotters/BaseReporter.py, AccountingSystem/private/Plotters/JobPlotter.py
It is depend on #4497 
*AccountingSystem
NEW: Add histogram of CPU usage to Job accounting
NEW: Implement the method used to retrieve data for creating histograms
=> [v7r2] Add histogram of CPU usage to Job accounting

TransformationSystem/Client/TaskManager.py
*TS
FIX: hospital sites were not look for correctly, which generated an exception
=> [v7r0] fix hospital handling

Core/Utilities/ElasticSearchDB.py
*ElasticSearchDB
Change: Existing index function is modified to add argument option of document id 
NEW:  update function is added.
=> [v6r22] Update of index function and addition of update function in ElasticSearchDB.py

Resources/Computing/ARCComputingElement.py
*Resources
CHANGE: ARCComputingElement - reserve the number of cores as defined in the NumberOfProcessors configuration parameter
FIX: ARCComputingElement - use CEQueueName configuration parameter if defined
=> [v6r22] Multi-core pilots in the ARC CE

ProductionSystem/Utilities/ProdValidator.py, ProductionSystem/scripts/dirac-prod-get-trans.py
* Production System
FIX: minor fix in ProdValidator and more detailed output added in dirac-prod-get-trans
=> Fix PS v7r0

TransformationSystem/DB/TransformationDB.py
FIX: Bug fixed in updateFilterQueries. The bug was affecting only TS catalog interface.
=> Fix TS v7r0

Core/DISET/private/Transports/M2SSLTransport.py, docs/requirements.txt, environment.yml, requirements.txt
Requires M2Crypto >= 0.36, which is in DIRACOS v1r13
*Core
FIX: M2Crypto: force bio free and shutdown when closing
=> [v7r0] M2Crypto: force bio free and shutdown when closing

docs/source/AdministratorGuide/ServerInstallations/scalingAndLimitations.rst, tests/Integration/WorkloadManagementSystem/Test_TaskQueueDB.py
*Docs
FIX: some more info on duplications
=> [v7r1] Docs: some more info on duplications

Resources/Computing/HTCondorCEComputingElement.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst, docs/source/AdministratorGuide/Resources/computingelements.rst
*docs
NEW: Added documentation for HTCondor/use full proxy length setting.
=> [v7r0] added documentation for HTCondor/use full proxy length setting

Core/LCG/GOCDBClient.py, Core/LCG/test/Test_LCG.py, ResourceStatusSystem/Command/DowntimeCommand.py, ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py
*RSS
NEW: GOC DB : interpret also downtimes with URLs different from the hostname
=> [v7r0] RSS and GOC DB : interpret also downtimes with URLs different from the hostname

DataManagementSystem/Client/FailoverTransfer.py, WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/JobWrapper/JobWrapper.py
@marianne013 would that be ok with you ? 
*WMS
NEW: add a retryUpload option in the JobWrapper
*DMS
NEW: add a retryUpload option to FailoverTransfer
=> [v7r1] Add a retryUpload option in the jobWrapper

DataManagementSystem/Client/FailoverTransfer.py
CHANGE: Retry file upload for any error condition, not just file catalogue failure.
=> [v7r1] retry stageout for any failure condition

docs/source/DeveloperGuide/ReleaseProcedure/index.rst
=> [v7r0] update the release guide

TransformationSystem/Agent/TransformationAgent.py, docs/source/DeveloperGuide/WebAppDIRAC/DevelopWebApp/index.rst
See https://github.com/DIRACGrid/management/pull/13.
I also tidied up the formatting the WebApp docs.
=> [v7r0] Add documentation for "overrides" folder in WebApp pages

ConfigurationSystem/Client/Helpers/Resources.py, ConfigurationSystem/scripts/dirac-admin-add-resources.py, DataManagementSystem/scripts/dirac-admin-allow-se.py, DataManagementSystem/scripts/dirac-admin-ban-se.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Executor/JobScheduling.py, WorkloadManagementSystem/Service/WMSAdministratorHandler.py, docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/Systems/Transformation/index.rst, docs/source/AdministratorGuide/technologyPreviews.rst, docs/source/DeveloperGuide/Internals/Core/ClientServer.rst, docs/source/UserGuide/glossary.rst, docs/source/UserGuide/index.rst
=> [v7r1] fixes for Resources config section inspection

Core/Utilities/DEncode.py, ProductionSystem/Service/ProductionManagerHandler.py, TransformationSystem/Client/TransformationClient.py, TransformationSystem/Service/TransformationManagerHandler.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Service/JobManagerHandler.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, docs/source/AdministratorGuide/Systems/WorkloadManagement/architecture.rst, tests/Integration/TransformationSystem/Test_Client_Transformation.py
For issues #4388 #4387 #4384 #4383 #4382 #4373
*Production
FIX: Fixes for JSON serialization
*WMS
FIX: Fixes for JSON serialization
* Transformation
FIX: TransformationManagerHandler: fixes for JSON serialization
=> [v7r1] Various fixes for enabling JSON serialization

FrameworkSystem/Service/NotificationHandler.py
These changes avoid having to wait long for an email, but still avoids a deluge if the same email is sent separately. However, emails are no longer bundled together, if that was the intention of the previous implementation.
*Framework
CHANGE: NotificationService: if ``avoidSpam=True`` the email is now sent immediately and cached for up to one hour, instead of being cached and then sent after up to an hour.
=> [v7r0] NotificationHandler: spam protection: send immediately, but not again too quickly

Core/LCG/GOCDBClient.py
=> [v7r0] Fix for silly-formed XMLs from GOCDB

tests/System/transformation_replication.sh
=> [v7r1] Tests: transformation_replication: fix bash syntax

FrameworkSystem/Client/MonitoringClient.py, FrameworkSystem/Service/MonitoringHandler.py, RequestManagementSystem/Agent/RequestOperations/ForwardDISET.py, WorkloadManagementSystem/Client/JobMonitoringClient.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py
A few casts/ignores for JSON enconding
*WMS
CHANGE: JobMonitoring casts for JSON
*Framework
CHANGE: ignore serialization error for JSON in the Monitoring
*RMS
CHANGE: ignore serialization error in ForwardDISET
=> [v7r1]  Few JSON fixes

Resources/Computing/SingularityComputingElement.py
Closes #4764.
*Resources
FIX: Mount the host's DIRAC installation in the container when using SingularityCE without InstallDIRACInContainer
=> [v7r0] Fix mounting the host's DIRAC installation in Singularity CE

docs/requirements.txt, docs/source/DeveloperGuide/TornadoServices/index.rst
just doc syntax and rtd requirements.
=> [integration] Fix tornado doc

AccountingSystem/Client/DataStoreClient.py, AccountingSystem/Client/ReportsClient.py, Core/Security/Utilities.py, FrameworkSystem/Client/ProxyGeneration.py, ResourceStatusSystem/Agent/ElementInspectorAgent.py, ResourceStatusSystem/Agent/SummarizeLogsAgent.py, TransformationSystem/Agent/DataRecoveryAgent.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py
Based on https://github.com/DIRACGrid/DIRAC/pull/4767
*RSS
CHANGE: SummarizeLogAgent uses list instead of tuples
*WMS
CHANGE: JobMonitoring uses cls/self attributes instead of global variable
=> [v7r1] SummarizeLogsAgent uses list instead of tuples

FrameworkSystem/Client/BundleDeliveryClient.py, FrameworkSystem/Client/ProxyManagerClient.py
*Framework
CHANGE: expose deleteProxyBundle call to ProxyManagerClient
=> [v7r2] expose deleteProxyBundle to ProxyManagerClient

ConfigurationSystem/Client/LocalConfiguration.py, DataManagementSystem/private/FTS3Utilities.py, DataManagementSystem/private/test/Test_FTS3Utilities.py, Resources/Storage/CTAStorage.py
@andresailer the FTS and CTA commits might be of interest to you
*Configuration
FIX: --cfg option supports tilde
*DMS
CHANGE: FTS3 gives priority to disk replicas
*Resources
NEW: CTA compatible Storage plugin
=> [v7r0] Add CTA storage plugin

ConfigurationSystem/Client/CSAPI.py
* Configuration
FIX: Show username when deleting users
=> [v7r0] Fix typo when deleting users

ConfigurationSystem/Client/SyncPlugins/CERNLDAPSyncPlugin.py, docs/requirements.txt, environment.yml, requirements.txt
Requires (though safe to merge beforehand):
* https://github.com/DIRACGrid/DIRACOS/pull/151 
* https://github.com/DIRACGrid/DIRAC/pull/4784
*Configuration
NEW: Add CERNLDAPSyncPlugin for VOMS2CSAgent
=> [v7r1] Add CERNLDAPSyncPlugin

FrameworkSystem/scripts/dirac-admin-update-instance.py, FrameworkSystem/scripts/dirac-admin-update-pilot.py, docs/source/AdministratorGuide/CommandReference/index.rst
NEW: new tool dirac-admin-update-instance to update all servers of a dirac instance from command line
NEW: new tool dirac-admin-update-pilot to update version of pilot in CS from command line
=> [v7r0] Add two new tools to update all servers of a dirac instance and pilot

Core/Base/ExecutorMindHandler.py, ResourceStatusSystem/Service/PublisherHandler.py, tests/Jenkins/dirac-test-job.py, tests/Jenkins/utilities.sh, tests/System/rss-scripts.sh
A few fixes, not worthy release notes.
=> [v7r2] hackathon fixes

.github/workflows/integration.yml
=> [v7r2] GA: MySQL 8 default; Only CC7 server

docs/source/AdministratorGuide/HowTo/pitExport.rst
=> [v7r0] Docs: correct link to LHCb documentation

ConfigurationSystem/Agent/Bdii2CSAgent.py, ConfigurationSystem/Client/CSAPI.py, ConfigurationSystem/Client/Helpers/Resources.py, ConfigurationSystem/Client/Utilities.py, ConfigurationSystem/ConfigTemplate.cfg, ConfigurationSystem/scripts/dirac-admin-add-resources.py, ConfigurationSystem/scripts/dirac-admin-add-site.py, ConfigurationSystem/scripts/dirac-admin-bdii-info.py, Core/Utilities/Grid.py, Interfaces/API/DiracAdmin.py, ResourceStatusSystem/Command/AccountingCacheCommand.py, ResourceStatusSystem/Command/DowntimeCommand.py, ResourceStatusSystem/Command/PilotCommand.py, ResourceStatusSystem/Command/test/Test_RSS_Command_GOCDBStatusCommand.py, ResourceStatusSystem/Utilities/CSHelpers.py, ResourceStatusSystem/Utilities/Synchronizer.py, Resources/scripts/dirac-resource-info.py
For #3908
*Configuration
CHANGE: BDII2CSAgent: stop looking for SEs in BDII
=> [v7r1] Stop looking for SEs in BDII

ResourceStatusSystem/Agent/SummarizeLogsAgent.py, ResourceStatusSystem/Client/ResourceStatusClient.py
* RSS
FIX: added vo field to ResourceStatusClient calls
=> [v7r1] RSS: fix for VO

FrameworkSystem/scripts/dirac-admin-update-instance.py
NEW: Add option to retry to update hosts in dirac-admin-update-instance
=> [v7r0] Add option to retry update of hosts

Core/Security/m2crypto/X509Chain.py
Backport a fix from #4843 
*Core
FIX: Fix hashing SubjectName in X509Chain
=> [v7r0] Fix hashing SubjectName in X509Chain

Interfaces/API/Job.py, MonitoringSystem/Client/Types/ComponentMonitoring.py, MonitoringSystem/Client/Types/WMSHistory.py, MonitoringSystem/DB/MonitoringDB.py, MonitoringSystem/private/DBUtils.py, MonitoringSystem/private/Plotters/BasePlotter.py, RequestManagementSystem/Client/ReqClient.py, ResourceStatusSystem/Agent/TokenAgent.py, ResourceStatusSystem/DB/ResourceStatusDB.py, WorkloadManagementSystem/DB/ElasticJobParametersDB.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Jenkins/utilities.sh
*Interfaces
FIX: Job.py: use --cfg option for JobConfigArgs
*RSS
FIX: Added one field for retrieving the corrected order of columns
*WMS
CHANGE: JobStateUpdateHandler: use class variables instead of global
=> [v7r1] Several fixes (from LHCbDIRAC hackathon)

WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/Agent/StalledJobAgent.py, WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py, WorkloadManagementSystem/Client/JobReport.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py
*WMS
CHANGE: using JobReport and delayed send for JobStateUpdate
=> [v7r2] JobAgent: using JobReport and delayed send for JobStateUpdate

Core/Security/m2crypto/X509Chain.py
*Python 3
FIX: Fix downloading X509 certificates
=> [v7r2] PY3: Fixes for X509Chain

ConfigurationSystem/Agent/Bdii2CSAgent.py, Core/DISET/private/Transports/SSL/M2Utils.py, Core/Security/m2crypto/X509Chain.py, FrameworkSystem/Service/NotificationHandler.py, FrameworkSystem/scripts/dirac-admin-update-instance.py, FrameworkSystem/scripts/dirac-admin-update-pilot.py, Interfaces/API/Job.py, MonitoringSystem/Client/Types/WMSHistory.py, MonitoringSystem/DB/MonitoringDB.py, MonitoringSystem/private/DBUtils.py, MonitoringSystem/private/Plotters/BasePlotter.py, RequestManagementSystem/Client/ReqClient.py, ResourceStatusSystem/Agent/TokenAgent.py, ResourceStatusSystem/DB/ResourceStatusDB.py, Resources/Computing/SingularityComputingElement.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Client/JobReport.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/DB/JobLoggingDB.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, __init__.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst, docs/source/AdministratorGuide/Systems/Framework/Notification/index.rst, release.notes, setup.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Jenkins/utilities.sh
=> Validate v7r2 pre22 release

Resources/Computing/SingularityComputingElement.py
*Resources
FIX: Fix SingularityComputingElement for non-server-style installations
=> [v7r1] Fix SingularityComputingElement for non-server-style installations

FrameworkSystem/private/standardLogging/Handler/MessageQueueHandler.py, Resources/LogBackends/MessageQueueBackend.py, tests/System/client_dms.sh
*Framework
FIX: MQ logging sends also the message,asctime and levelname field
=> [v7r2] Hackathon fixes: logging and tests

WorkloadManagementSystem/DB/JobLoggingDB.py
*WMS
FIX: JobLoggingDB: fix for backward compatibility
=> [v7r1] fix for backward compatibility

src/DIRAC/Core/scripts/dirac-install.py, tests/Integration/all_integration_server_tests.sh
=> One more fix v7r2

Core/scripts/dirac-install.py, src/DIRAC/Core/scripts/dirac-install.py
This partially reverts commit 4f978bfde9fb9bc2a6aaca19efe6fa8d37f13928. Fix #4880
=> Revert "Deleted moved stuff", bring back dirac-install.py

TransformationSystem/Utilities/ReplicationTransformation.py
*Transformation System
FIX: fix to allow to pass a list of sourceSE to dirac-transformation-replication
=> [v7r1] fix to allow to pass a list of sourceSE to dirac-transformation-replication

docs/diracdoctools/cmd/commandReference.py, docs/source/AdministratorGuide/CommandReference/index.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/index.rst, src/DIRAC/ConfigurationSystem/Service/ConfigurationHandler.py, src/DIRAC/ConfigurationSystem/Service/TornadoConfigurationHandler.py, src/DIRAC/DataManagementSystem/Client/DataManager.py, src/DIRAC/WorkloadManagementSystem/Agent/PilotSyncAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/PilotsSyncAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac-admin-sync-pilot.py
For addressing https://github.com/DIRACGrid/DIRAC/issues/4697
*WMS
NEW: new agent PilotsSyncAgent for syncing pilot files.
NEW: new script dirac-admin-sync-pilots for syncing pilot files.
CHANGE: largely simplified PilotCStoJSONSynchronizer
CHANGE: don't call PilotCStoJSONSynchronizer from the CS
=> [v7r2] added new agent: PilotsSyncAgent

src/DIRAC/ConfigurationSystem/Agent/GOCDB2CSAgent.py, src/DIRAC/ConfigurationSystem/Client/CSAPI.py, src/DIRAC/ConfigurationSystem/Client/CSShellCLI.py, src/DIRAC/ConfigurationSystem/Client/Helpers/Resources.py, src/DIRAC/Core/Utilities/ClassAd/ClassAdLight.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryFlatTree.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerPs.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/SecurityManager/test/Test_VOMSSecurityManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogDB.py, src/DIRAC/FrameworkSystem/private/standardLogging/LogLevels.py, src/DIRAC/FrameworkSystem/scripts/dirac-populate-component-db.py, src/DIRAC/ResourceStatusSystem/PolicySystem/PDP.py, src/DIRAC/ResourceStatusSystem/PolicySystem/StateMachine.py, src/DIRAC/Resources/Catalog/FileCatalog.py, src/DIRAC/Resources/Catalog/FileCatalogClient.py, src/DIRAC/Resources/Catalog/LcgFileCatalogClient.py, src/DIRAC/Resources/MessageQueue/MQConnectionManager.py, src/DIRAC/Resources/Storage/test/FIXME_Test_RFIOPlugIn.py, src/DIRAC/Resources/Storage/test/FIXME_Test_StorageElement.py, src/DIRAC/Resources/Storage/test/FIXME_Test_StoragePlugIn.py, src/DIRAC/StorageManagementSystem/Agent/RequestPreparationAgent.py, src/DIRAC/StorageManagementSystem/Agent/StageMonitorAgent.py, src/DIRAC/StorageManagementSystem/Agent/StageRequestAgent.py, src/DIRAC/Workflow/Modules/ModuleBase.py, src/DIRAC/WorkloadManagementSystem/Client/InputDataByProtocol.py, src/DIRAC/WorkloadManagementSystem/Client/JobState/JobState.py, tests/Integration/DataManagementSystem/Test_Client_DFC.py, tests/Integration/DataManagementSystem/Test_FileCatalogDB.py
A number of fixes for python 3, basically dealing with the `.keys()` method change.
=> [v7r2] fixes for python 3

Resources/Computing/ARCComputingElement.py
closes https://github.com/DIRACGrid/DIRAC/issues/4785
*Resources
CHANGE: ARC CE: request all processors on the same node.
=> [v7r0] ARC CE: all processors on the same node

WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py
*WMS
FIX: JobAgent: adding ExtraOptions as argument iff the executable is a DIRAC script
=> [v7r0] adding ExtraOptions as argument iff the executable is a DIRAC script

WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, WorkloadManagementSystem/Service/WMSAdministratorHandler.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
*WMS
FIX: fix for retrieving the pilot reference when it's an ES JobParameter
FIX: fix for using the ES JobParameters for static data of hearbeats (app std out)
=> [v7r1] Fixes for interactions with JobParameters on ES

Core/Utilities/MySQL.py, DataManagementSystem/Agent/RequestOperations/RegisterFile.py, DataManagementSystem/Agent/RequestOperations/RemoveFile.py, DataManagementSystem/Agent/RequestOperations/RemoveReplica.py, tests/Utilities/testJobDefinitions.py
*Core
CHANGE: logging failing MySQL commands
=> [v7r1] logging failing MySQL commands

src/DIRAC/ResourceStatusSystem/DB/ResourceManagementDB.py, src/DIRAC/WorkloadManagementSystem/Agent/PilotSyncAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, src/DIRAC/WorkloadManagementSystem/Utilities/PilotWrapper.py
*WMS
FIX: fixes for PilotSyncAgent
=> [v7r2] fixes for PilotSyncAgent

src/DIRAC/Core/Base/DB.py, src/DIRAC/Core/Base/DIRACDB.py, src/DIRAC/Core/Base/ElasticDB.py, src/DIRAC/Core/Base/SQLAlchemyDB.py, src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/MonitoringSystem/Client/Types/BaseType.py, src/DIRAC/MonitoringSystem/ConfigTemplate.cfg, src/DIRAC/MonitoringSystem/DB/MonitoringDB.py, src/DIRAC/MonitoringSystem/Service/MonitoringHandler.py
* Core
NEW: added a base DB class for all DB types
* Monitoring
NEW: added possibility to configure the period and so the indexing strategy
=> [v7r2] Monitoring: added possibility to configure the period and so the indexing strategy

src/DIRAC/ResourceStatusSystem/Agent/CacheFeederAgent.py, src/DIRAC/ResourceStatusSystem/Agent/SummarizeLogsAgent.py, src/DIRAC/ResourceStatusSystem/ConfigTemplate.cfg
closes #4629 
*RSS
NEW: Remove old entries from history
=> [v7r2] RSS: remove old entries from history

release.notes, setup.py, src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/RegisterFile.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/RemoveFile.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/RemoveReplica.py, src/DIRAC/Resources/Computing/ARCComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/WMSAdministratorHandler.py, src/DIRAC/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, src/DIRAC/__init__.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
=> Validate v7r2 pre28 release

DataManagementSystem/Client/FTS3Job.py
Explanation in #4878 
*DMS
FIX: FTS3Job: fix the check of isTapeSE for multiVO instances, fixes #4878 
FIX: FTS3Job: pass VO for fetchSpaceToken function to StorageElement
=> [v7r0] FTS3Job, fix isTapeSe for multiVO

Resources/Storage/OccupancyPlugins/WLCGAccountingHTTPJson.py
*Resources
FIX: use grid CA to download the srr file
=> [v7r1]WLCG HTTP SRR: use grid CA

Resources/Computing/ARCComputingElement.py, Resources/Computing/SingularityComputingElement.py, WorkloadManagementSystem/Agent/JobAgent.py
*Resources
FIX: ARCComputingElement: fixed a few places where unicode literals have leaked: wrapped in str
*WMS
FIX: JobAgent: using internal function for rescheduling jobs
=> [v7r1] fixes for ARC and JobAgent

src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/DataManagementSystem/DB/DataIntegrityDB.py, src/DIRAC/DataManagementSystem/Service/DataIntegrityHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
*DMS
CHANGE: DataIntegrityDB: global DB object -> class instance
For #4825
=> [v7r2] Minor: global DB object -> class instance for DataIntegrityDB

Core/Security/VOMS.py, docs/source/AdministratorGuide/HowTo/multiVO.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
Resolves #4846 
*Core
CHANGE: Resolve location of etc/grid-security/vomses via env variable X509_VOMSES
=> [v7r0] Resolve etc/grid-security/vomses via env variable X509_VOMSES

setup.cfg, src/DIRAC/MonitoringSystem/Client/MonitoringReporter.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_list_status.py, src/DIRAC/Resources/scripts/dirac_resource_get_parameters.py, src/DIRAC/Resources/scripts/dirac_resource_info.py, src/DIRAC/TransformationSystem/scripts/dirac_transformation_replication.py
@chrisburr can you check the script fixing ?
*RSS
FIX: fix dirac_rss_list_status after conversion to proper python scripts
*Resources
FIX: fix dirac_resource_get_parameters, dirac_resource_info after conversion to proper python scripts
* Monitoring
*CHANGE: do not print an error if failover queue is not defined
FIX: fix dirac_transformation_replication after conversion to proper python scripts
=> [v7r2] Fix a few scripts after conversion to proper python script

src/DIRAC/Core/Workflow/Parameter.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryClosure.py, src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/Interfaces/API/Job.py, src/DIRAC/RequestManagementSystem/Service/ReqManagerHandler.py, src/DIRAC/Resources/Computing/BatchSystems/executeBatch.py, src/DIRAC/Resources/Computing/SSHComputingElement.py, src/DIRAC/TransformationSystem/Service/TransformationManagerHandler.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/PilotManagerHandler.py, src/DIRAC/tests/Utilities/testJobDefinitions.py, tests/Integration/RequestManagementSystem/Test_Client_Req.py, tests/System/unitTestUserJobs.py
*python3
FIX: use six.moves for urllib
*tests
FIX: better names for the test jobs
=> [v7r2] Python 3 fixes

docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst
Description of the WebDav module as optional for installation. 
*docs
CHANGE: WebDav module as optional
=> [v7r2] WebDav module as optional

tests/CI/run_tests.sh
Required to make it possible for the LHCbDIRAC integration tests to find `tests/Integration/WorkloadManagementSystem/pilot.cfg` when running against integration (example failure below). Hopefully I can clean this up again as part of #4859.
```
++ /home/dirac/ClientInstallDIR/LHCbDIRAC/tests/Integration/WorkloadManagementSystem/Test_dirac-jobexecLHCb.sh
++ tee -a clientTestOutputs.txt
======> Test_dirac-jobexecLHCb.sh <======
==> Running in DEBUG mode
2021-01-29 14:46:12 UTC Framework [139846125688640] DEBUG: dirac.cfg should be at /home/dirac/ClientInstallDIR/etc/dirac.cfg
2021-01-29 14:46:12 UTC Framework [139846125688640] DEBUG: CFG merged
2021-01-29 14:46:12 UTC Framework [139846125688640] DEBUG: Updating configuration internals
2021-01-29 14:46:12 UTC Framework [139846125688640] …
```
=> [v7r2] Minor fix for LHCbDIRAC integration tests

ConfigurationSystem/Agent/Bdii2CSAgent.py, ConfigurationSystem/ConfigTemplate.cfg, Core/Utilities/Grid.py, Resources/Storage/OccupancyPlugins/BDIIOccupancy.py
...as lcg-bdii.cern.ch will be dismissed.
*Subsystem
CHANGE: change default top-level bdii to cclcgtopbdii01.in2p3.fr (was lcg-bdii.cern.ch)
=> [v7r0] change default top-level bdii to cclcgtopbdii01.in2p3.fr

WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Client/test/Test_Client_WorkloadManagementSystem.py
*WMS
FIX: SiteDirector: fix for case of empty tag
=> [v7r1] SiteDirector: fix for case of empty tag

src/DIRAC/tests/Utilities/testJobDefinitions.py, tests/System/unitTestUserCloudJobs.py
*tests
NEW: added a helloworld test for the (yet to be implemented) cloud testing in certfication
=> [v7r2] added basic infrastructure for VMDIRAC certification tests

src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/Core/Tornado/Server/HandlerManager.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/Core/Tornado/scripts/tornado_start_all.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileMetadata/FileMetadata.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py
Core
* CHANGE: improve tornado Logging
* FIX: fix credentials resolution with TornadoClient
DMS
* FIX: DFC base manager compatible with py3 string types and unicode
Resources
* FIX: explicitly cast gfal2 parameters to str (to be removed when moved to python 3)
=> [v7r2] Various fixes from 04.02.21 hachathon, mostly https related

src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
*WMS
NEW: JobAgent adds GridCE and queue to Job Parameters
=> [v7r2] Reporting GridCE and queue in Job Parameters

Workflow/Modules/ModuleBase.py
*Workflow
FIX: Remove deprecated function that does not do anything
this is in line with #4928
=> [v7r1] Remove deprecated function that does not do anything

Core/Utilities/ObjectLoader.py
*Core
NEW: ObjectLoader: do not fail if one module fails importing in recursive loading
=> [v7r1] ObjectLoader: allow recursive continueOnError option

.github/workflows/integration.yml, tests/CI/README.MD, tests/CI/run_docker_setup.sh
*tests
CHANGE: Change the defaults for tests (to MySQL 8 and ES 7)
=> [v7r2] Change the defaults for tests (to MySQL 8 and ES 7)

WorkloadManagementSystem/Client/Limiter.py, WorkloadManagementSystem/Client/Matcher.py, WorkloadManagementSystem/DB/TaskQueueDB.py, WorkloadManagementSystem/Service/MatcherHandler.py
*WMS
CHANGE: Improved the logging of the matcher: adding pilotReference
=> [v7r1] Improved the logging of the matcher: adding pilotReference

src/DIRAC/WorkloadManagementSystem/Agent/PilotSyncAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac_admin_sync_pilot.py
*WMS
CHANGE: added flag to exclude the master CS from the list of servers synchronized by PilotCS2JSON
=> [v7r2] added flag to exclude the master CS from the list of servers synchronized by PilotCS2JSON

README.rst, docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst
Small PR fix link to DIRAC install instruction and small comments for `WebApp`.
*docs
FIX: fix link to DIRAC install instruction and comments for WebApp
=> [v7r2] fix readme

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
This will be used by DIRACOS2 as part of running the `dirac-docs-get-release-notes.py` script.
=> [v7r2 Support passing tokens to dirac-docs-get-release-notes.py as an argument

setup.cfg
=> Typo in setup.cfg

Resources/Computing/HTCondorCEComputingElement.py
closes #4935
*Resources
CHANGE: HTCondorCE: add a periodic remove in case we are not using the local schedd
=> [v7r1] HTCondorCE: add a periodic remove in case we are not using the local schedd

Core/Utilities/MySQL.py
Ability to perform LIKE queries using DIRAC native MySQL API. 
*Core
CHANGE: Adding MySQL LIKE query feature.
=> [v7r0] MySQL LIKE Query

Resources/Computing/BatchSystems/TimeLeft/SGEResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/test/Test_LSFResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/test/Test_SGEResourceUsage.py, WorkloadManagementSystem/Agent/JobAgent.py
*Resources
FIX: fix CPU time calculation for SGE
*WMS
CHANGE: JobAgent: if we don't match a job, independently from the reason, we wait a bit longer before trying again
CHANGE: JobAgent: moved check of availability of CE before doing anything else
=> [v7r1] Jobs matching improvements

src/DIRAC/FrameworkSystem/Service/ComponentMonitoringHandler.py
This PR about https://github.com/DIRACGrid/WebAppDIRAC/issues/252 issue. And need for https://github.com/DIRACGrid/WebAppDIRAC/pull/440 PR.
*Framework
NEW: new method to get the logs for all the hosts
=> [v7r2] add getLogs method in ComponentMonitoring

docs/requirements.txt, docs/requirements_py3.txt
needed for readthedocs compilation
=> Docs: add prompt_toolkit to dependencies

src/DIRAC/ConfigurationSystem/Service/ConfigurationHandler.py, src/DIRAC/ConfigurationSystem/private/ServiceInterface.py, src/DIRAC/ConfigurationSystem/private/ServiceInterfaceBase.py, src/DIRAC/ConfigurationSystem/private/ServiceInterfaceTornado.py
*Configuration
FIX:  harmonize https and dips version of ServiceHandler, and make doc consistent with reality
=> [v7r2] Hackaton fixes 

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
Fix v7r2-pre37 hackathon issues.
FIX: fix parameter name
=> [v7r2] fix v7r2-pre37 hackathon

src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py, src/DIRAC/FrameworkSystem/DB/InstalledComponentsDB.py, src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py, src/DIRAC/WorkloadManagementSystem/Agent/PilotSyncAgent.py, tests/Integration/Framework/NotRun_Test_ComponentInstallUninstall.py
=> [v7r2] Fixes from LHCbDIRAC hackathon

src/DIRAC/Core/Base/Script.py
This PR is designed to solve the problem described in [comment](https://github.com/DIRACGrid/DIRAC/pull/5032#discussion_r593079690), will fix only scripts docs in python3 env. Compact version.
*Core
FIX: set usage massage in Script global methods
=> [v7r2 pre39] small py3 doc fix

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
*WMS
CHANGE: JobDB: compress JDLs by default (no need for flag anymore)
=> [v7r3] compress JDLs by default

Core/Security/ProxyInfo.py
Just a cast
*Core
FIX: (M2Crypto) fixes proxy serial parsing
=> [v7r0] M2: fix serial proxy deserialization

src/DIRAC/AccountingSystem/private/Plotters/NetworkPlotter.py, src/DIRAC/Core/Utilities/Graphs/GraphUtilities.py, src/DIRAC/DataManagementSystem/Client/FileCatalogClientCLI.py, src/DIRAC/FrameworkSystem/DB/NotificationDB.py, src/DIRAC/Resources/ProxyProvider/DIRACCAProxyProvider.py, src/DIRAC/TransformationSystem/Utilities/TransformationInfo.py, src/DIRAC/WorkloadManagementSystem/Client/Matcher.py, src/DIRAC/tests/Utilities/ProcessesCreator_withChildren.py, src/DIRAC/tests/Utilities/mpTest-flexible.py, src/DIRAC/tests/Utilities/mpTest.py, tests/CI/run_tests.sh, tests/Integration/Core/Test_MySQLDB.py
*Python 3
FIX: Explicitly convert variables assigned to range() into lists
=> [v7r2] PY3: Explicitly convert variables assigned to range() into lists

src/DIRAC/Core/Utilities/MySQL.py
*Core
CHANGE: Added  IS NULL mySql condition
=> [v7r2] Added IS NULL mySql condition

src/DIRAC/AccountingSystem/Client/DataStoreClient.py, src/DIRAC/Core/DISET/private/MessageBroker.py, src/DIRAC/Core/Utilities/DErrno.py, src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/FrameworkSystem/private/standardLogging/Logging.py, src/DIRAC/ResourceStatusSystem/Utilities/RSSCache.py, src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_StalledJobAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py
*WMS
CHANGE: Using ThreadPool in StalledJobAgent
=> [v7r2] Using ThreadPool in StalledJobAgent 

docs/source/DeveloperGuide/WebAppDIRAC/InstallWebAppDIRAC/index.rst, docs/source/UserGuide/Tutorials/ClientInstallation/index.rst
Fragment from #5035. Notify to use --cfg in documentation.
*docs
CHANGE: add --cfg before *.cfg file
=> [v7r3] add --cfg to docs

src/DIRAC/FrameworkSystem/Service/NotificationHandler.py
=> [v7r3] NotificationHandler: remove bool from type

src/DIRAC/Core/Utilities/Graphs/GraphUtilities.py, src/DIRAC/DataManagementSystem/Client/MetaQuery.py, src/DIRAC/DataManagementSystem/Service/FileCatalogHandler.py, src/DIRAC/ProductionSystem/Utilities/ProdValidator.py, src/DIRAC/RequestManagementSystem/Agent/RequestExecutingAgent.py
I don't think this is worthy of release notes
=> [v7r2] Fix more assignments of dict methods for Python 3

DataManagementSystem/DB/FTS3DB.py, RequestManagementSystem/DB/RequestDB.py
CHANGE: Backport SQLAlchemy 1.4 compatibility
CHANGE: Backport SQLAlchemy 1.4 compatibility
=> [v7r0] Backport SQLAlchemy 1.4 compatibility

Core/Utilities/RabbitMQAdmin.py
*Core
FIX: Undefined variable error when RabbitMQAdmin fails to connect
=> [v7r0] Fix undefined variables in RabbitMQAdmin

src/DIRAC/RequestManagementSystem/Client/Operation.py, src/DIRAC/RequestManagementSystem/Client/Request.py, src/DIRAC/RequestManagementSystem/Client/test/Test_Operation.py, src/DIRAC/RequestManagementSystem/DB/RequestDB.py, src/DIRAC/RequestManagementSystem/private/RequestValidator.py
FIX: Ensure BLOB columns are always passed bytes data
=> [v7r2] Ensure BLOB columns are always passed bytes data

.github/workflows/basic-python3.yml, environment-py3.yml, src/DIRAC/Core/Utilities/Network.py, src/DIRAC/Core/Utilities/ProcessPool.py, src/DIRAC/Core/Utilities/test/Test_Network.py, src/DIRAC/Core/Utilities/test/Test_ProcessPool.py, src/DIRAC/Resources/Computing/BOINCComputingElement.py, src/DIRAC/Resources/Computing/PilotBundle.py, src/DIRAC/TransformationSystem/scripts/dirac_production_runjoblocal.py
*Python 3
FIX: Fix various Python 3.9 deprecations
=> [v7r2] Fix Python 3.9 deprecations and add DIRAC.Core.Utilities.Network tests

src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/RequestManagementSystem/Client/ReqClient.py, src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py, src/DIRAC/WorkloadManagementSystem/Client/WMSClient.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/JobLoggingDB.py, src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobPolicy.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/WMSAdministratorHandler.py, tests/Integration/Core/Test_ElasticsearchDB.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_ElasticJobParametersDB.py, tests/System/rss-scripts.sh
*WMS
NEW: JobManager service now exposes a "RemoveJob" RPC call
NEW: implementing bulk indexing for jobs parameters
CHANGE: JobCleaningAgent will not remove those jobs that, while marked "DELETED", have still Operations to do in RMS
=> [v7r2] implementing bulk indexing for jobs parameters

src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py
*Framework
CHANGE: in the run files created by ComponentInstaller, execute directly the deployed scripts
=> [v7r2] executing the deployed script directly

docs/source/DeveloperGuide/AddingNewComponents/DevelopingCommands/index.rst
Fix `Coding commands` manual.
*docs
FIX: fix DiracScript to DIRACScript
=> [v7r2] fix instruction

src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/Core/Utilities/DEncode.py, src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py, src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py, tests/Integration/Core/Test_ElasticsearchDB.py, tests/Integration/DataManagementSystem/Test_FileCatalogDB.py
Handful more Python 3 fixes which are probably better targetted to v7r3 as they only affect server installs but aren't worthy of release note in themselves.
=> [v7r3] Various minor Python 3 compatibility fixes

WorkloadManagementSystem/JobWrapper/JobWrapper.py
The output sandbox tar is created in the local tmp directory. If it's uploaded, it's then immediately deleted from the file system. But if it's not uploaded because being too large, then it's uploaded to a grid storage, but in this case it was not deleted. This PR should solve this issue.
*WMS
FIX: delete the local output sandbox tarfile in case it's still there
=> [v7r1] Delete the local output sandbox tarfile in case it's still there

docs/requirements.txt, docs/requirements_py3.txt, environment.yml, requirements.txt
Just freeze SQLAlchemy to 1.3 until we/they solve all the issues
=> [v7r1] Freeze SQLALchemy to 1.3 until problems with 1.4 are solved

WorkloadManagementSystem/DB/JobDB.py
*WMS
CHANGE: JobDB.setJobAttributes: use _update instead of _transaction (as not needed)
=> [v7r1] use _update instead of _transaction (as it's only 1 command)

src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Client/WMSClient.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/JobLoggingDB.py, src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobPolicy.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
WIP
*WMS
CHANGE: JobCleaningAgent will first DELETE and only then REMOVE jobs
=> [v7r2] JobCleaningAgent will first DELETE and only then REMOVE jobs

DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerPs.py, DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql
Not legally binding measurements, but still:
Before
`Getting replicas for 45540 LFNs : completed in 130.1 seconds`
After
`Getting replicas for 45540 LFNs : completed in 15.7 seconds`
It requires an update to the DB, so I'll add a note to the wiki
*DMS
CHANGE: FileManagerPS has bulk method for getReplicas
=> [v7r1] DFC FileManagerPS: getReplicas speed improvment

FrameworkSystem/scripts/dirac-proxy-init.py
*Core
CHANGE: Read X509_CERT_DIR from central place
=> [v7r1] Read X509_CERT_DIR from central place

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Utilities/MySQL.py
This should hopefully fix #5140 
*CORE
CHANGE: Move MySQL.ConnectionPool class to the module level
CHANGE: Move RequestHandler.ConnectionError to the module level
=> [v7r2] doc class class

src/DIRAC/Core/Workflow/Parameter.py, src/DIRAC/Core/Workflow/WorkflowReader.py
This started as an attempt to optimise `DIRAC.Core.Workflow.Workflow.fromXMLString` but I didn't manage to gain more than ~10% without introducing breaking changes so I gave up on those changes. Despite this I think the minor cleaning I did is still worthwhile so here it is.
Not worthy of release notes.
=> [v7r3] Minor cleanups in DIRAC.Core.Workflow

src/DIRAC/WorkloadManagementSystem/Client/JobState/CachedJobState.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py
*WMS
FIX: list -> tuple for serialization fixes
=> [integration] Encoding fixes from hackaton

DataManagementSystem/DB/FileCatalogComponents/DatasetManager/DatasetManager.py
FIX: Fix the syntax of the query to get dataset files
=> [v7r1] fix query syntax

WorkloadManagementSystem/Agent/SiteDirector.py
*Subsystem
WorkloadManagement CHANGE: Combine CE and Queue name in PilotSubmissionAccounting to avoid duplicated queue name
=> [v7r1] Combined CE and Queue information

AccountingSystem/private/Plotters/PilotSubmissionPlotter.py
*Accounting
FIX: Bug in PilotSubmission efficiency plot
=> [v7r1] Bug fix for pilot submission efficiency plot

FrameworkSystem/private/monitoring/MonitoringCatalog.py
This PR improves the performance of the monitoring service by an order of magnitude at the cost of running in a less safe mode. However, given that it's monitoring data, it's acceptable.
It also reduces the number of 'database is locked' exceptions from several thousands per hour to a handful.
This image shows the response time of just a `ping` call to the service before and after the change. The difference for actual method call is even bigger 
*Framework
CHANGE: change SQLITE connection option for speed improvement 
=> [v7r1] Framework/Monitoring: increase perf at the cost of data safety

environment.yml, release.notes, requirements.txt, src/DIRAC/AccountingSystem/private/Plotters/PilotSubmissionPlotter.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DatasetManager/DatasetManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py, src/DIRAC/FrameworkSystem/Client/UserProfileClient.py, src/DIRAC/FrameworkSystem/DB/UserProfileDB.py, src/DIRAC/FrameworkSystem/Service/UserProfileManagerHandler.py, src/DIRAC/FrameworkSystem/private/monitoring/MonitoringCatalog.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/__init__.py
=> Validate-v7r2p8

tests/System/client_multivo.sh
*tests
NEW: Added a script intended for multi-VO certification that actually uses two different VOs. If approved would need a trello card as well.
=> [integration] added script for multiVO certification

docs/source/DeveloperGuide/CodeTesting/index.rst, src/DIRAC/Core/Utilities/StateMachine.py, src/DIRAC/Core/Utilities/Time.py, src/DIRAC/FrameworkSystem/Service/BundleDeliveryHandler.py, src/DIRAC/FrameworkSystem/Service/ComponentMonitoringHandler.py, src/DIRAC/FrameworkSystem/Service/RabbitMQSyncHandler.py, src/DIRAC/FrameworkSystem/Service/SecurityLoggingHandler.py, src/DIRAC/FrameworkSystem/Service/UserProfileManagerHandler.py, src/DIRAC/ResourceStatusSystem/PolicySystem/StateMachine.py, src/DIRAC/WorkloadManagementSystem/Agent/PilotStatusAgent.py, src/DIRAC/WorkloadManagementSystem/Client/JobMinorStatus.py, src/DIRAC/WorkloadManagementSystem/Client/JobState/JobState.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py, src/DIRAC/WorkloadManagementSystem/Executor/Base/OptimizerExecutor.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/OptimizationMindHandler.py, tests/System/unitTestUserJobs.py
A bunch of fixes that don't deserve to be in release notes
=> [v7r3] hackathon fixes

FrameworkSystem/DB/UserProfileDB.py
*Framework
FIX: Avoid minor caching bug which causes constraints to be violated when rapidly writing to UserProfileDB
=> [v7r1] Fix caching in UserProfileDB

src/DIRAC/FrameworkSystem/scripts/dirac_admin_update_instance.py
NEW: Add option to exclude list of hosts from dirac-admin-instace-update
=> [v7r2] Add option to exclude list of hosts from instance update

src/DIRAC/FrameworkSystem/Client/UserProfileClient.py, src/DIRAC/FrameworkSystem/DB/UserProfileDB.py, src/DIRAC/FrameworkSystem/Service/UserProfileManagerHandler.py, tests/Integration/Framework/Test_UserProfileClient.py, tests/Integration/all_integration_client_tests.sh
Needs to be rebased once the other branches are propagated 
*Framework
CHANGE: Remove HashTag table from Framework/UserProfile
CHANGE: Remove dataTypeRE argument when retrieving values from Framework/UserProfileClient
=> [v7r3] Clean up and add basic tests for Framework/UserProfile

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/Core/DISET/private/GatewayService.py, src/DIRAC/Core/DISET/private/MessageBroker.py, src/DIRAC/Core/DISET/private/Service.py, src/DIRAC/FrameworkSystem/Agent/MyProxyRenewalAgent.py, src/DIRAC/ResourceStatusSystem/Agent/ElementInspectorAgent.py, src/DIRAC/ResourceStatusSystem/Agent/SiteInspectorAgent.py, src/DIRAC/ResourceStatusSystem/Agent/test/Test_Agent_ElementInspectorAgent.py, src/DIRAC/ResourceStatusSystem/Agent/test/Test_Agent_SiteInspectorAgent.py, src/DIRAC/TransformationSystem/Agent/TaskManagerAgentBase.py, src/DIRAC/TransformationSystem/Agent/TransformationAgent.py, src/DIRAC/TransformationSystem/Agent/TransformationAgentsUtilities.py, src/DIRAC/TransformationSystem/Agent/test/Test_Agent_TransformationSystem.py, src/DIRAC/TransformationSystem/Client/Utilities.py, src/DIRAC/TransformationSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py
*Subsystem
CHANGE: removing env variable DIRAC_USE_NEWTHREADPOOL
=> [v7r3] removing env variable DIRAC_USE_NEWTHREADPOOL

ConfigurationSystem/Agent/RucioSynchronizerAgent.py, ResourceStatusSystem/Agent/RucioRSSAgent.py, Resources/Catalog/RucioFileCatalogClient.py, docs/requirements.txt, docs/requirements_py3.txt, environment.yml
*Resources
NEW: RucioFileCatalog plugin based on Belle II implementation
=> [v7r0] Rucio File Catalog prototype

src/DIRAC/Resources/Computing/SSHComputingElement.py
Aim to fix the following error:
```
File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 346, in am_secureCall
result = functor(*args)
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 449, in execute
result = self.submitPilots()
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 568, in submitPilots
res = self._submitPilotsToQueue(pilotsToSubmit, ce, queueName)
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 833, in _submitPilotsToQueue
submitResult = ce.submitJob(executable, '', pilotsToSubmit)
File "/opt/dirac/pro/DIRAC/Resources/Computing/SSHComputingElement.py", line 597, in submitJob
result = self._submitJobToHost(submitFile, numberOfJobs, …
```
=> [v7r2] Fix SSHCE submitJobToHost: inputs

src/DIRAC/TransformationSystem/Client/TaskManager.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py, src/DIRAC/WorkloadManagementSystem/Service/SandboxStoreHandler.py
This is not worthy of release notes but it makes a few minor changes to the messages that are logged to make the messages easier to aggregate in elasticsearch. For example:
```
[gsiftp://marcce02.in2p3.fr:2811/jobs/54fMDmDOOAznu8aJ7o041qXmABFKDmABFKDmnTXYDmABFKDmjeNoGo] Error requesting job: 
```
becomes:
```
Error requesting job
```
=> [v7r2] Improve message/varmessage split in some places

src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/RequestManagementSystem/Client/ReqClient.py, src/DIRAC/RequestManagementSystem/DB/RequestDB.py, src/DIRAC/RequestManagementSystem/Service/ReqManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, tests/Integration/Core/Test_MySQLDB.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
*WMS
FIX: JobDB: Getting InputDataModule from Operations section
FIX: JobCleaningAgent: get jobIDs old and recent, and combine
=> [v7r2] Getting InputDataModule from Operations

src/DIRAC/tests/Utilities/assertingUtils.py
Failed to find the ConfigTemplates in ILCDIRAC when running against clone of DIRAC, because of the src/*DIRAC folder where the sources are now.
*Test
CHANGE: AgentOptionTests: re-work ConfigTemplate discovery, should be transparent for the users, but work better for extensions
=> [v7r2] AgentOptionTests: re-work configtemplate discovery

src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py
*Framework
FIX: ComponentSupervisionAgent: add necessary SystemAdministrator Authorization Settings in the docstring
=> [v7r2] Framework.CSA: add info about SystemAdministrator permissions

src/DIRAC/Resources/Computing/ComputingElement.py, src/DIRAC/Resources/Computing/InProcessComputingElement.py, src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/Resources/Computing/SudoComputingElement.py, src/DIRAC/Resources/Computing/test/Test_PoolComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
With these changes the JobAgent will wait that all processes are finished before finalizing.
*Reources
CHANGE: PoolComputingElement use concurrent.futures.ProcessPoolExecutor
CHANGE: PoolComputingElemnet: added a shutdown (called by JobAgent)
=> [v7r2] PoolComputingElement updates

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py, src/DIRAC/FrameworkSystem/Agent/test/Test_ComponentSupervisionAgent.py
*Framework
FIX: ComponentSupervisionAgent: Pick up PollingTime from a base agent config
=> [v7r2] ComponentSupervisionAgent: inherit agent options

src/DIRAC/FrameworkSystem/Agent/test/Test_ComponentSupervisionAgent.py, src/DIRAC/TransformationSystem/test/Test_JobInfo.py, src/DIRAC/WorkloadManagementSystem/Client/Matcher.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py
*WMS
FIX: Matcher: use custom exception for Pilot Version Error
=> [v7r2] Better logging of few errors in WMS

Resources/Storage/GFAL2_XROOTStorage.py
*Resources/Storage
NEW: 
set XrdSecGSIDELEGPROXY to enable third party copy
=> [v7r1] added XrdSecGSIDELEGPROXY to enable third party copy

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
*WMS
NEW: SiteDirector: added flag for pilots to install python3 DIRAC clients
=> [v7r2] SiteDirector: added flag for pilots to install python3 DIRAC clients

src/DIRAC/WorkloadManagementSystem/Executor/JobPath.py, src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py
*WMS
FIX: JobPath executor: fix bug for per-job list of optimizers
=> [v7r2] JobPath executor: fix bug for per-job list of optimizers

src/DIRAC/ConfigurationSystem/Service/TornadoConfigurationHandler.py
PR to collect python3 DIRAC server fixes.
*Configuration
FIX: decode bytes to string before encoding it to JSON in TornadoService
=> [v7r3] py3 fixes

src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py, tests/Integration/Core/Test_MySQLDB.py, tests/Integration/DataManagementSystem/Test_DataIntegrityDB.py, tests/Integration/Monitoring/Test_MonitoringDB.py, tests/Integration/Monitoring/Test_MonitoringSystem.py
This PR adds an error message in the tests if `S_OK` is expected and `S_ERROR` is returned. This should provide more information in case of a test error.
*tests
FIX: add error message to assert
=> [v7r3] add error message

docs/source/DeveloperGuide/AddingNewComponents/DevelopingExecutors/PingPongMindHandler.py, src/DIRAC/Core/Base/ExecutorMindHandler.py, src/DIRAC/WorkloadManagementSystem/Client/JobState/CachedJobState.py
*Python 3
FIX: Fix serialisation of data for Executors
=> [v7r3] Fix serialisation of data for Executors in Python 3

src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py
* WMS (JobCleaningAgent)
CHANGE: When removing Deleted jobs, they could not be removed if they had still an attached request. With this change, if the request is in final state, it will be removed and the job as well.
=> [v7r2] Fix JobCleaningAgent

docs/source/AdministratorGuide/Resources/computingelements.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/JobsMatching.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/index.rst, src/DIRAC/Resources/Computing/ARCComputingElement.py, src/DIRAC/Resources/Computing/CREAMComputingElement.py, src/DIRAC/Resources/Computing/ComputingElement.py, src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py, src/DIRAC/WorkloadManagementSystem/Client/Limiter.py, src/DIRAC/WorkloadManagementSystem/Client/Matcher.py, src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py, src/DIRAC/WorkloadManagementSystem/Utilities/QueueUtilities.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
*Resources
FIX: HtCondorCE: corrected ClassAd for requesting MP slots
=> [v7r2] HtCondorCE: request MP slots

src/DIRAC/Core/scripts/dirac_configure.py
*Core
CHANGE: dirac-configure: no upload attempt upon initial proxy generation
=> [v7r3] hachathon fixes

src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/WorkloadManagementSystem/Client/JobState/CachedJobState.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py
=> [v7r3] hackthon fixes (v7r3)

docs/source/DeveloperGuide/AddingNewComponents/DevelopingExecutors/PingPongMindHandler.py, docs/source/DeveloperGuide/AddingNewComponents/DevelopingServices/HelloHandler.py, docs/source/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.rst, src/DIRAC/FrameworkSystem/private/standardLogging/Formatter/BaseFormatter.py, src/DIRAC/FrameworkSystem/private/standardLogging/Logging.py, src/DIRAC/FrameworkSystem/private/standardLogging/test/Test_Logging_GetSubLogger.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
This PR addresses https://github.com/DIRACGrid/DIRAC/issues/5280
The meat of this PR is in b473d1a , and I apply it as a test to `JobStateUpdate` in b473d1a 
*Framework
NEW: Introduce Local SubLogger
*WMS
CHANGE: attempt to use Local subLogger
=> [v7r2] Introduce Local SubLogger

tests/System/client_scripts.sh, tests/System/wms-scripts.sh
=> [v7r3] Created system test wms-scripts.sh

.github/workflows/integration.yml, src/DIRAC/Core/Tornado/Server/TornadoServer.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/DataManagementSystem/Service/TornadoFileCatalogHandler.py, tests/CI/install_server.sh, tests/Jenkins/utilities.sh
=> [v7r3] HTTPS services for python3

docs/source/DeveloperGuide/ReleaseProcedure/index.rst, src/DIRAC/ConfigurationSystem/Client/VOMS2CSSynchronizer.py
*Configuration
FIX: VOMS2CSSynchronizer: if a user is in QuarantineGroup, remove it from all other VOMS groups
=> [v7r2] if a user is in quarantinegroup, remove it from all other VOMS groups

environment-py3.yml, environment.yml, requirements.txt, src/DIRAC/RequestManagementSystem/DB/RequestDB.py, src/DIRAC/RequestManagementSystem/DB/test/RMSTestScenari.py, src/DIRAC/RequestManagementSystem/DB/test/Test_RequestDB.py, tests/CI/run_tests.sh, tests/Integration/RequestManagementSystem/Test_ReqDB.py
Core:
CHANGE: Release constraint on SQLALchemy versions
RMS:
CHANGE: ReqDB don't cast datetime to strings
=> [v7r3] Release SQLALchemy constraints

tests/System/client_multivo.sh
*tests/System
CHANGE: added RALPP as a multi-VO test site and added env dump to job.log to ease debugging
=> [integration] added RALPP as a multi-VO test site and added env dump to job.log

src/DIRAC/ConfigurationSystem/Client/Helpers/Path.py, src/DIRAC/ConfigurationSystem/Client/PathFinder.py, src/DIRAC/ConfigurationSystem/Client/test/Test_PathFinder.py, src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py, src/DIRAC/FrameworkSystem/Agent/test/Test_ComponentSupervisionAgent.py
*Framework
FIX: ComponentSupervisionAgent: support Tornado
=> [v7r3] Path-related fixes (ComponentSupervisionAgent)

.gitignore, src/DIRAC/DataManagementSystem/Agent/FTS3Agent.py, src/DIRAC/DataManagementSystem/Client/DataManager.py, src/DIRAC/DataManagementSystem/Client/FTS3Job.py, src/DIRAC/DataManagementSystem/Client/FTS3Operation.py, src/DIRAC/DataManagementSystem/scripts/dirac_dms_directory_sync.py, src/DIRAC/RequestManagementSystem/private/OperationHandlerBase.py, src/DIRAC/RequestManagementSystem/scripts/dirac_rms_list_req_cache.py, src/DIRAC/Resources/Catalog/FCConditionParser.py, src/DIRAC/Resources/Storage/DIPStorage.py, src/DIRAC/Resources/Storage/FCOnlyStorage.py, src/DIRAC/Resources/Storage/FileStorage.py, src/DIRAC/Resources/Storage/GFAL2_SRM2Storage.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py, src/DIRAC/Resources/Storage/StorageElement.py, src/DIRAC/TransformationSystem/Client/TransformationClient.py
This PR changes some verbose to debug, and update some calls to use a more recent Logger API
*Resources
CHANGE: changes some log levels in StorageElement
=> [v7r2] logging changes

docs/diracdoctools/Utilities.py, docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst
@TaykYoku FYI for the param grep
=> [v7r2] fix doc setInputMetaQuery, better grep for :param

src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/MonitoringSystem/Client/MonitoringReporter.py
This is a possible solution to the bug in https://github.com/DIRACGrid/DIRAC/issues/5320 (not a full solution to the issue).
*Subsystem
=> [v7r2] ElasticSearch generateDocs: work on a copy of the documents

src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_set_status.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_set_token.py
closes #5247 
*RSS
FIX: VO parameter is optional. When omitted commands will act on all VOs.
=> [integration] RSS scripts - VO parameter optional. Address issue #5427.

src/DIRAC/TransformationSystem/Agent/DataRecoveryAgent.py, src/DIRAC/TransformationSystem/Agent/TransformationAgent.py, src/DIRAC/TransformationSystem/Agent/test/Test_Agent_TransformationSystem.py, src/DIRAC/TransformationSystem/Client/TaskManager.py, src/DIRAC/TransformationSystem/Client/TransformationCLI.py, src/DIRAC/TransformationSystem/Client/TransformationClient.py, src/DIRAC/TransformationSystem/Client/TransformationFilesStatus.py, src/DIRAC/TransformationSystem/Service/TransformationManagerHandler.py, src/DIRAC/Workflow/Modules/FailoverRequest.py, tests/Integration/TransformationSystem/Test_Client_Transformation.py
*TS
NEW: Added TransformationFilesStatus module
=> [v7r3] Added TransformationFilesStatus module

src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/Core/Utilities/MySQL.py, tests/Integration/AccountingSystem/Test_AccountingDB.py, tests/Integration/all_integration_server_tests.sh
*tests
NEW: added integration test for AccountingDB
=> [v7r3] Added integration test for AccountingDB

src/DIRAC/WorkloadManagementSystem/Utilities/PilotWrapper.py
*WMS
CHANGE: PilotWrapper: added file:/cvmfs/dirac.egi.eu/pilot/ as location
=> [v7r2] PilotWrapper added /cvmfs/dirac.egi.eu/pilot/ as location

WorkloadManagementSystem/Service/PilotManagerHandler.py
In the webapp, when one selects `Owner` to get statistics about pilots from a certain user: no result appear and an error is generated in the `PilotManagerHandler` log.
```
2021-08-26 12:15:24 UTC WorkloadManagement/PilotManager/WorkloadManagement/PilotAgentsDB ERROR: _query (SELECT `Status`, COUNT(*) FROM `PilotAgents`     WHERE `Owner` IN ( "toto" ) AND `OwnerGroup` IN ( "vo_pilot" ) AND `LastUpdateTime` < "2021-08-26 12:15" GROUP BY `Status` ORDER BY `Status`): Execution failed. 1054: Unknown column 'Owner' in 'where clause'
```
This is because `Owner` does not exist in `PilotAgentsDB` and needs to be converted into an `OwnerDN`.
FIX: convert Owner attribute into OwnerDN in PilotManagerHandler.getPilotStatistics
=> [v7r1] PilotManagerHandler: convert Owner attribute into OwnerDN in getPilotStatistics

WorkloadManagementSystem/Service/JobMonitoringHandler.py
Fix JobMonitoring MySQL error:
```
WorkloadManagement/JobMonitoring (88.84 ms) ERROR: MySQL Error ( 1131 : Execution failed.: ( 1054: Unknown column 'PilotJobReference' in 'where clause' ))
```
FIX: Unknown column 'PilotJobReference'
=> [v7r1] fix show jobs

tests/System/wms-scripts.sh
*tests
CHANGE: Add proxy correct setup within wms-script.sh
=> [v7r3] Hackaton Fix: Setup proxy in wms-script.sh

src/DIRAC/ConfigurationSystem/Client/Helpers/Resources.py
Similar to https://github.com/DIRACGrid/DIRAC/pull/5373 but this one only affects integration.
=> [v7r3] Fix un-returned use of S_ERROR and S_OK

src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, tests/Integration/Resources/ProxyProvider/Test_DIRACCAProxyProvider.py, tests/Integration/all_integration_server_tests.sh
Update DIRACCAProxyProvider test to use pytest.
*Resources
CHANGE: Update DIRACCAProxyProvider test to use pytest
=> [v7r2] update DIRACCAProxyProvider test

src/DIRAC/Core/Security/VOMS.py, src/DIRAC/DataManagementSystem/Client/ConsistencyInspector.py, src/DIRAC/TransformationSystem/scripts/dirac_production_runjoblocal.py
#5367 made me wonder if there were any other cases of `S_ERROR`/`S_OK` being created without actually being returned and it turns out the answer is yes!
=> [v7r2] Fix un-returned use of S_ERROR and S_OK

src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/DataManagementSystem/Service/FileCatalogHandler.py, src/DIRAC/DataManagementSystem/Service/TornadoFileCatalogHandler.py, src/DIRAC/WorkloadManagementSystem/Client/JobMonitoringClient.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/Client/Matcher.py, src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/TornadoJobManagerHandler.py, tests/CI/install_server.sh
The HTTPs tests were not really executed: the fix in https://github.com/DIRACGrid/DIRAC/pull/5354/commits/b32ff00e023e0ebbfdaeb57042342cf9be310d27 makes sure that the configuration is correctly updated, so now it "correctly fails". 
*Subsystem
=> [v7r3] Partial fixes for Tornado handlers (+ other fixes for v7r3)

AccountingSystem/DB/AccountingDB.py
resolves #5261  
*Accounting
FIX: do not attempt to write buckets if there's nothing to write
=> [v7r1] fix: do not attempt to write buckets if there's nothing to write

docs/source/AdministratorGuide/Resources/storage.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py
Addresses  https://github.com/DIRACGrid/DIRAC/issues/5401 and https://github.com/DIRACGrid/DIRAC/issues/5393
*Resources
NEW: DIRAC_GFAL_GRIDFTP_ENABLE_IPV6 to control gridftp behavior
=> [v7r2] Introduce DIRAC_GFAL_GRIDFTP_ENABLE_IPV6 environment variable

src/DIRAC/Resources/Storage/OccupancyPlugins/WLCGAccountingJson.py
*Resources
FIX: making use of freesize in WLCGAccountingJson if exists, instead of calculating as Total - usedsize
=> [v7r2] making use of freesize in WLCGAccountingJson if exists

docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst
Documents the option added in https://github.com/DIRACGrid/WebAppDIRAC/pull/484/ as part of https://github.com/DIRACGrid/WebAppDIRAC/issues/485.
I'll leave this as a draft until the changes are merged into the WebApp.
=> [v7r3] Document /WebApp/StaticResourceLinkDir configuration

docs/source/AdministratorGuide/Tutorials/installWMS.rst, docs/source/UserGuide/GettingStarted/GettingUserIdentity/index.rst, docs/source/UserGuide/GettingStarted/InstallingClient/index.rst, docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst, docs/source/conf.py, docs/source/index.rst, src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py
*docs
FIX: some minor fixes for user documentation
=> [v7r3] docs: some minor fixes for documentation

src/DIRAC/Resources/LogBackends/MessageQueueBackend.py
When poking around in the elastic search logging I found myself being confused by messages appearing out of order due to the timestamps being identical at the millisecond level. I think it would be nicer to send the full microsecond precision timestamp.
*Resources
CHANGE: asctime now includes microsecond precision when using the MessageQueueBackend for logging
=> [v7r2] Include microsecond precision in asctime in MessageQueueBackend

src/DIRAC/Core/Utilities/List.py, src/DIRAC/DataManagementSystem/Client/DataManager.py, src/DIRAC/RequestManagementSystem/private/RequestTask.py, src/DIRAC/Resources/MessageQueue/StompMQConnector.py, src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py
In the hope of being able to apply pre-commit+black today, this PR merges the approved PRs in to `rel-v7r2`:
Closes #5442
Closes #5439
Closes #5438
=> [v7r2] Merge party for rel-v7r2

src/DIRAC/Core/Utilities/List.py, src/DIRAC/DataManagementSystem/Client/DataManager.py, src/DIRAC/RequestManagementSystem/private/RequestTask.py
*RMS
CHANGE: delay the execution of a request in case the user has been suspended (6 hours for the time being)
=> [v7r2] Fix in RMS suspended user

docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst, src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/Core/Utilities/List.py, src/DIRAC/DataManagementSystem/Client/ConsistencyInspector.py, src/DIRAC/DataManagementSystem/Client/DataManager.py, src/DIRAC/DataManagementSystem/ConfigTemplate.cfg, src/DIRAC/DataManagementSystem/Service/FTS3ManagerHandler.py, src/DIRAC/DataManagementSystem/Service/TornadoFTS3ManagerHandler.py, src/DIRAC/FrameworkSystem/DB/ProxyDB.py, src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg, src/DIRAC/RequestManagementSystem/Service/ReqManagerHandler.py, src/DIRAC/RequestManagementSystem/Service/TornadoReqManagerHandler.py, src/DIRAC/RequestManagementSystem/private/RequestTask.py, src/DIRAC/Resources/MessageQueue/StompMQConnector.py, src/DIRAC/WorkloadManagementSystem/Agent/VirtualMachineMonitorAgent.py, src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py, tests/Integration/WorkloadManagementSystem/Test_TaskQueueDB.py
In the hope of being able to apply pre-commit+black today, this PR merges the approved PRs in to `rel-v7r3` and propogates #5443:
Closes #5437
Closes #5436
Closes #5435 
Closes #5409
=> [v7r3] Merge party for rel-v7r3

src/DIRAC/DataManagementSystem/ConfigTemplate.cfg, src/DIRAC/DataManagementSystem/Service/FTS3ManagerHandler.py, src/DIRAC/DataManagementSystem/Service/TornadoFTS3ManagerHandler.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg, src/DIRAC/RequestManagementSystem/Service/ReqManagerHandler.py, src/DIRAC/RequestManagementSystem/Service/TornadoReqManagerHandler.py
*DMS
NEW: FTS3 tornado Handler
*RMS
NEW: ReqManager tornado Handler
=> [v7r3] Add more HTTPS services

docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst
*docs
FIX: Corrected some grammar mistakes and unclear wording in the documentation
=> [v7r3] Corrected some grammar mistakes and unclear wording in the documentation

src/DIRAC/DataManagementSystem/Client/ConsistencyInspector.py, src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py, tests/Integration/WorkloadManagementSystem/Test_TaskQueueDB.py
*Framework
FIX: SystemAdministratorHandler: download dirac-install from management repo if py2 server
*DMS
FIX: minor fixes for ConsistencyInspector when no LFNs are given
=> [v7r3] (LHCb) hackathon fixes

src/DIRAC/WorkloadManagementSystem/Agent/VirtualMachineMonitorAgent.py
FIX:  only halt VM if JobAgent finished
=> [v7r3] only halt VM if JobAgent finished

.github/labeler.yml, .github/workflows/labeler.yml, .github/workflows/pr-sweep.yml
Closes #5139  
TODOs:
@fstagni Can you take care of the first two points? (We can coordinate offline for sharing the @DIRACGridBot credentials.)
=> [v7r2] Use sweeper to propogate PRs

.github/workflows/semantic.yml
*Tests
CHANGE: add sweep as keyword and case insensitive
=> [v7r2] CI: add sweep as keyword and case insensitive

src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py
*WMS
FIX: wait an incremental amount of seconds for finding the child PID
=> [v7r2] fix: wait an incremental amount of seconds for finding the child PID

.pylintrc
*Test
CHANGE: adapt pylintrc to black
=> [v7r2] Adapt pylintrc to black

.github/workflows/basic-python3.yml, .github/workflows/basic.yml, .github/workflows/deployment.yml, .github/workflows/integration.yml
To reduce the load on the CI I think we can remove some CI jobs without reducing the effective coverage.
Any thoughts?
=> [v7r3] Reduce number of CI jobs

src/DIRAC/FrameworkSystem/Client/SecurityLogClient.py
*SecurityLog
CHANGE: fed up with unreadable job logs...
=> [v7r2] Set security log message to DEBUG

docs/source/AdministratorGuide/Configuration/ConfReference/DiracSection.rst, docs/source/DeveloperGuide/DIRACProjects/index.rst, docs/source/DeveloperGuide/ReleaseProcedure/index.rst, src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py, src/DIRAC/FrameworkSystem/API/AuthHandler.py, src/DIRAC/FrameworkSystem/private/authorization/AuthServer.py, src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
*WMS
CHANGE:  SiteDirector submits only py3 pilots
=> [8.0] Somewhat minor fixes

src/DIRAC/Core/Security/m2crypto/X509CRL.py, src/DIRAC/Core/Security/m2crypto/X509Chain.py
Sweep #5554 `Fixes to X509CRL and X509Chain` to `rel-v7r3`.
*Core
FIX: Fix overwriting files from an X509Chain object
Closes #5557
=> [sweep:v7r3] Fixes to X509CRL and X509Chain

src/DIRAC/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
*WMS
FIX: PilotCStoJSONSynchronizer: do not look anymore in releases.cfg
=> [v7r3] fix: do not look anymore in releases.cfg

src/DIRAC/Core/Base/ExecutorMindHandler.py, src/DIRAC/Core/DISET/MessageClient.py, src/DIRAC/Core/DISET/private/MessageBroker.py, src/DIRAC/Core/Utilities/ExecutorDispatcher.py, src/DIRAC/WorkloadManagementSystem/Client/JobState/JobState.py, src/DIRAC/WorkloadManagementSystem/DB/JobLoggingDB.py, src/DIRAC/WorkloadManagementSystem/Service/OptimizationMindHandler.py
I suggest reviewing this on a commit-by-commit basis as I've included the associated exception each commit's description.
FIX: Various fixes to executor infrastructure
=> [rel-v7r2] Fixes to executor infrastructure

tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
*Test
FIX: fix typo in the HTTPs Resources tests
=> [v7r3] test: fix http/https typo in Test_Resources_GFAL2StorageBase

docs/source/AdministratorGuide/ServerInstallations/InstallingWebAppDIRAC.rst
Align `WebApp` installation manual with last changes (using BaseRequestHandler in WebAppDIRAC 5.0).
*docs
FIX: update nginx installation instruction
=> [integration] update Nginx installation instruction

src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py
*Framework
FIX: display correctly the help in sysadmin-cli
=> [v7r3] fix: display correctly the help in sysadmin-cli

src/DIRAC/WorkloadManagementSystem/Service/OptimizationMindHandler.py
FIX: Error logging when optimisation fails
=> [v7r2] Error logging when optimisation fails

src/DIRAC/Core/Utilities/StateMachine.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
Sweep #5597 `Don't run JobsStateMachine if newStat is ''` to `integration`.
Closes #5599
FIX: Don't run JobsStateMachine if newStat is ''
=> [sweep:integration] Don't run JobsStateMachine if newStat is ''

src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py
*Framework
FIX: Cleaning old installations from a Python 3 based server
=> [v7r3] Cleaning old installations from a Python 3 based server

dirac.cfg, docs/source/AdministratorGuide/Resources/identityprovider.rst, docs/source/AdministratorGuide/Resources/index.rst
This PR provide guide about Identity Providers
*Resources
NEW: Identity Providers documentation
=> [integration] add Identity Providers documentation

src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
*WMS
CHANGE: better logging output in the JobStateUpdate
=> [8.0] Hackaton fixes

src/DIRAC/WorkloadManagementSystem/Service/OptimizationMindHandler.py
FIX: Bad error handling in OptimizationMindHandler.exec_taskError
=> [v7r2] Fix typo in OptimizationMindHandler.exec_taskError

src/DIRAC/ResourceStatusSystem/Client/ResourceManagementClient.py, src/DIRAC/ResourceStatusSystem/Command/DowntimeCommand.py, src/DIRAC/ResourceStatusSystem/Service/ResourceManagementHandler.py
*RSS
FIX: specifying the gocDB type for known types
=> [v7r3] RSS: downtimeCommand fixes

src/DIRAC/FrameworkSystem/Service/BundleDeliveryHandler.py, src/DIRAC/FrameworkSystem/Service/ComponentMonitoringHandler.py, src/DIRAC/FrameworkSystem/Service/MonitoringHandler.py, src/DIRAC/FrameworkSystem/Service/NotificationHandler.py, src/DIRAC/FrameworkSystem/Service/PlotCache.py, src/DIRAC/FrameworkSystem/Service/PlottingHandler.py, src/DIRAC/FrameworkSystem/Service/ProxyManagerHandler.py, src/DIRAC/FrameworkSystem/Service/RabbitMQSyncHandler.py, src/DIRAC/FrameworkSystem/Service/SecurityLoggingHandler.py, src/DIRAC/FrameworkSystem/Service/TokenManagerHandler.py, src/DIRAC/FrameworkSystem/Service/TornadoBundleDeliveryHandler.py, src/DIRAC/FrameworkSystem/Service/UserProfileManagerHandler.py
Review each commit separately
*Framework
NEW/CHANGE/FIX: avoid duplication of code in TornadoBundleDeliveryHandler
=> [8.0] avoid duplication of code in TornadoBundleDeliveryHandler

dashboards/WMSDashboard.json, docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst
JSON file for WMS monitoring dashboard for users to import to ElasticSearch or OpenSearch 
*Monitoring 
NEW: JSON file for WMS monitoring dashboard 
=> [integration] WMS monitoring dashboard import file 

docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst
*docs
FIX: fix trailing-whitespace
=> [integration] Fix pre-commit for #5634

src/DIRAC/TransformationSystem/Client/test/Test_Client_RequestTasks.py
*TS
FIX: fix RequestTasks flaky tests
=> [v7r3] test (RequestTasks): fix flaky test

src/DIRAC/Resources/Computing/SSHComputingElement.py
FIX: Python 3 support in SSHComputingElement
=> [v7r3] bytes/str confusion in SSHComputingElement

src/DIRAC/RequestManagementSystem/Client/ReqClient.py, src/DIRAC/WorkloadManagementSystem/Client/JobMinorStatus.py
*  RMA
FIX: If a job was Killed, set it Killed at request completion
=> [v7r3] Handle requests for killed jobs

src/DIRAC/ConfigurationSystem/Agent/RucioSynchronizerAgent.py
=> [rel-v7r2] change keyword args from type to type_

src/DIRAC/Core/Base/ExecutorMindHandler.py, src/DIRAC/Core/DISET/MessageClient.py, src/DIRAC/Core/Utilities/ExecutorDispatcher.py
453daa10a16c83446e8bff345b14d87ec33e9636 is the commit which actually fixes things, the other is just improving the logging.
*Core
FIX: Race condition which causes multiple connectioons to be opened when the connection to an executor drops
CHANGE: Improve logging split between message/varmessage in execuctors
=> [v7r2] Yet more executor fixes

src/DIRAC/Resources/Storage/OccupancyPlugins/WLCGAccountingHTTPJson.py
*Resources
FIX: decode the http response in WLCGAccountingHTTPJson
=> [v7r3] Fix decoding of content in WLCGAccountingHTTPJson

src/DIRAC/Core/Utilities/Time.py, src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py, src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py, src/DIRAC/WorkloadManagementSystem/Client/JobReport.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/Client/Matcher.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
hopefully resolves #5699 
*WMS
CHANGE: JobAgent and JobWrapper: only reporting changes on major status when needed
=> [v7r3] Fixes for setting the Jobs Status

.pylintrc, docs/diracdoctools/__init__.py, environment.yml, setup.cfg, tests/Jenkins/dirac_ci.sh
resolves #5193 
(no need for release notes)
=> [8.0] re-allowing rucio

src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, tests/CI/install_server.sh
Sweep #5718 `Add URLs to CS when installing HTTPS services` to `integration`.
*HTTPS
FIX: Add URLs to CS when installing HTTPS services
Closes #5723
=> [sweep:integration] Add URLs to CS when installing HTTPS services

src/DIRAC/ResourceStatusSystem/Utilities/CSHelpers.py
*RSS
FIX: CSHelpers: some sites have no resources
=> [v7r3] RSS fix: some sites have no resources

src/DIRAC/FrameworkSystem/private/SecurityFileLog.py
Sweep #5737 `fix: gzipping in py2 and py3` to `integration`.
Closes #1081264923
=> [sweep:integration] fix: gzipping in py2 and py3

docs/source/AdministratorGuide/HowTo/SystemAdministratorInterface.rst, src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py, src/DIRAC/FrameworkSystem/scripts/dirac_admin_update_instance.py, src/DIRAC/__init__.py
*Core
FIX: removed isPy3VersionNumber function
=> [8.0] removed isPy3VersionNumber function

src/DIRAC/AccountingSystem/Client/ReportsClient.py, src/DIRAC/Core/DISET/private/GatewayService.py, src/DIRAC/FrameworkSystem/Client/BundleDeliveryClient.py, src/DIRAC/FrameworkSystem/Client/PlottingClient.py, src/DIRAC/Resources/Storage/DIPStorage.py, src/DIRAC/Resources/Storage/ProxyStorage.py, src/DIRAC/WorkloadManagementSystem/Client/SandboxStoreClient.py, tests/Integration/Monitoring/Test_MonitoringSystem.py
*HTTPS
FIX: Replace DIRAC.Core.DISET.TransferClient with DIRAC.Core.Tornado.Client.ClientSelector
=> [v7r3] Replace DISET.TransferClient with ClientSelector

docs/source/DeveloperGuide/AddingNewComponents/DevelopingAgents/index.rst, docs/source/DeveloperGuide/WebAppDIRAC/DevelopWebApp/index.rst, src/DIRAC/AccountingSystem/Client/Types/BaseAccountingType.py, src/DIRAC/AccountingSystem/Service/DataStoreHandler.py, src/DIRAC/FrameworkSystem/Client/MonitoringClient.py, src/DIRAC/FrameworkSystem/Client/PlottingClient.py, src/DIRAC/FrameworkSystem/Client/ProxyManagerClient.py, src/DIRAC/FrameworkSystem/Client/SecurityLogClient.py, src/DIRAC/FrameworkSystem/Client/UserProfileClient.py, src/DIRAC/FrameworkSystem/scripts/dirac_proxy_destroy.py, src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/Interfaces/scripts/dirac_framework_self_ping.py, src/DIRAC/MonitoringSystem/Client/ServerUtils.py, src/DIRAC/RequestManagementSystem/Service/ReqProxyHandler.py, src/DIRAC/ResourceStatusSystem/Command/AccountingCacheCommand.py, src/DIRAC/ResourceStatusSystem/Command/VOBOXAvailabilityCommand.py, src/DIRAC/ResourceStatusSystem/Command/test/Test_RSS_Command_VOBOXAvailabilityCommand.py, src/DIRAC/ResourceStatusSystem/Service/ResourceManagementHandler.py, src/DIRAC/ResourceStatusSystem/Service/ResourceStatusHandler.py, src/DIRAC/Resources/Catalog/FileCatalogProxyClient.py, src/DIRAC/Resources/Storage/DIPStorage.py, src/DIRAC/Resources/Storage/ProxyStorage.py, src/DIRAC/StorageManagementSystem/Agent/RequestFinalizationAgent.py, src/DIRAC/WorkloadManagementSystem/Client/SandboxStoreClient.py, src/DIRAC/WorkloadManagementSystem/Client/ServerUtils.py, tests/Integration/WorkloadManagementSystem/Test_VirtualMachineManagerClient.py, tests/Performance/Service/test_scripts/service.py
*All
CHANGE: use Client instead of RPCClient
=> [v7r3] Replace RPCClient with Client

src/DIRAC/TransformationSystem/scripts/dirac_production_runjoblocal.py
*Subsystem
FIX: dirac_production_runjoblocal.py: moved to py3 Pilot install
=> [v7r3] dirac_production_runjoblocal.py: moved to py3 Pilot install

src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
Sweep #5752 `DIRAC APIs check if a JobState transition is allowed` to `integration`.
*Interfaces
CHANGE: DIRAC APIs check if a JobState transition is allowed
Closes #5769
=> [sweep:integration] DIRAC APIs check if a JobState transition is allowed

src/DIRAC/DataManagementSystem/scripts/dirac_dms_directory_sync.py
Untested but I'm fairly sure this will fix https://github.com/DIRACGrid/DIRAC/issues/5775.
FIX: Fix pickle error in dirac-dms-directory-sync
=> [v7r2] Fix pickle error in dirac-dms-directory-sync

docs/source/DeveloperGuide/AddingNewComponents/DevelopingAgents/index.rst, docs/source/DeveloperGuide/WebAppDIRAC/DevelopWebApp/index.rst, src/DIRAC/AccountingSystem/Client/Types/BaseAccountingType.py, src/DIRAC/AccountingSystem/Service/DataStoreHandler.py, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/FrameworkSystem/Client/MonitoringClient.py, src/DIRAC/FrameworkSystem/Client/PlottingClient.py, src/DIRAC/FrameworkSystem/Client/ProxyManagerClient.py, src/DIRAC/FrameworkSystem/Client/SecurityLogClient.py, src/DIRAC/FrameworkSystem/Client/UserProfileClient.py, src/DIRAC/FrameworkSystem/scripts/dirac_proxy_destroy.py, src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/Interfaces/scripts/dirac_framework_self_ping.py, src/DIRAC/MonitoringSystem/Client/ServerUtils.py, src/DIRAC/RequestManagementSystem/Service/ReqProxyHandler.py, src/DIRAC/ResourceStatusSystem/Command/AccountingCacheCommand.py, src/DIRAC/ResourceStatusSystem/Command/VOBOXAvailabilityCommand.py, src/DIRAC/ResourceStatusSystem/Command/test/Test_RSS_Command_VOBOXAvailabilityCommand.py, src/DIRAC/ResourceStatusSystem/Service/ResourceManagementHandler.py, src/DIRAC/ResourceStatusSystem/Service/ResourceStatusHandler.py, src/DIRAC/Resources/Catalog/FileCatalogProxyClient.py, src/DIRAC/Resources/Storage/DIPStorage.py, src/DIRAC/Resources/Storage/ProxyStorage.py, src/DIRAC/StorageManagementSystem/Agent/RequestFinalizationAgent.py, src/DIRAC/WorkloadManagementSystem/Client/SandboxStoreClient.py, src/DIRAC/WorkloadManagementSystem/Client/ServerUtils.py, tests/Integration/WorkloadManagementSystem/Test_VirtualMachineManagerClient.py, tests/Performance/Service/test_scripts/service.py
Sweep #5761 `Replace RPCClient with Client` to `integration`.
*All
CHANGE: use Client instead of RPCClient
Closes #1095391213
=> [sweep:integration] Replace RPCClient with Client

docs/source/AdministratorGuide/Introduction/diraccomponents.rst, docs/source/DeveloperGuide/OAuth2Authorization/index.rst
To make it possible to change the images without redrawing them, a link to the source is added under each of them. All sources are collected in https://github.com/TaykYoku/DIRACIMGS.
*docs
CHANGE: add document image source files
=> [integration] add document image source files

src/DIRAC/DataManagementSystem/scripts/dirac_dms_directory_sync.py
FIX: dirac-dms-directory-sync crashes on macOS
=> [v7r2] Fix dirac-dms-directory-sync for macOS

src/DIRAC/DataManagementSystem/scripts/dirac_dms_directory_sync.py
Sweep #5776 `Fix pickle error in dirac-dms-directory-sync` to `rel-v7r3`.
FIX: Fix pickle error in dirac-dms-directory-sync
Closes #5787
=> [sweep:v7r3] Fix pickle error in dirac-dms-directory-sync

.readthedocs.yaml
=> [v7r2] Backport readthedocs configuration changes

.readthedocs.yaml
=> [v7r3] Backport readthedocs configuration changes

docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst
The PR adds a few details about the server installation process with Python3.
*docs
CHANGE: add further details about the server installation process with python3
=> [v7r3] change doc installing dirac server

docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst
Sweep #5812 `change doc installing dirac server` to `integration`.
*docs
CHANGE: add further details about the server installation process with python3
Closes #1112283054
=> [sweep:integration] change doc installing dirac server

src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_cpu_normalization.py
Sweep #5813 `feat(wms): enable logs from db12 in dirac-wms-cpu-normalization` to `integration`.
CHANGE: enable logs from db12 in dirac-wms-cpu-normalization
Closes #1112283218
=> [sweep:integration] feat(wms): enable logs from db12 in dirac-wms-cpu-normalization

src/DIRAC/WorkloadManagementSystem/Client/Matcher.py
resolves #5826 
*WMS
FIX: Matcher: fix understanding of tags
=> [v7r2] fix: (backport) fix Matcher understanding of tags

src/DIRAC/TransformationSystem/DB/TransformationDB.py, src/DIRAC/TransformationSystem/DB/__init__.py, src/DIRAC/TransformationSystem/Utilities/JobInfo.py, src/DIRAC/TransformationSystem/Utilities/ReplicationCLIParameters.py, src/DIRAC/TransformationSystem/Utilities/ReplicationTransformation.py, src/DIRAC/TransformationSystem/Utilities/TransformationInfo.py, src/DIRAC/TransformationSystem/Utilities/__init__.py, src/DIRAC/TransformationSystem/__init__.py
*TS
FIX: TransformationDB: removed old compatibility layer with mySAM tables
=> [8.0] TransformationDB: removed old compatibility layer with mySAM tables

src/DIRAC/Core/Utilities/JEncode.py, src/DIRAC/Core/Utilities/test/Test_Encode.py, src/DIRAC/TransformationSystem/DB/TransformationDB.py
Sweep #5831 `JEncode bytes` to `integration`.
Adding original author @TaykYoku as watcher.
*Core
CHANGE: JEncode bytes, tests
*CS
CHANGE: align with JEncode changes
Closes #5832
=> [sweep:integration] JEncode bytes

src/DIRAC/AccountingSystem/Client/Types/PilotSubmission.py, src/DIRAC/AccountingSystem/private/Plotters/PilotSubmissionPlotter.py, src/DIRAC/MonitoringSystem/Client/Types/PilotSubmissionMonitoring.py, src/DIRAC/MonitoringSystem/private/Plotters/PilotSubmissionMonitoringPlotter.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, tests/Integration/Monitoring/Test_MonitoringReporter.py
Solving issue arisen from certification Hackaton for release v8.0.0a13.
*Monitoring
FIX: Fixing nomenclature and other issues with PilotMonitoringSubmission
=> [integration] Hackaton Fix: PilotSubmissionMonitoring 

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
The logging was not correct.
*Tornado
FIX: better logging formatting
=> [8.0] fix (Tornado): correct formating of the logging

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py
Sweep #5841 `WMS DBs: do not try to decode when it's not bytes` to `integration`.
*WMS
FIX: WMS DBs: do not try to decode when it's not bytes
Closes #5845
=> [sweep:integration] WMS DBs: do not try to decode when it's not bytes

src/DIRAC/FrameworkSystem/scripts/dirac_login.py
*Framework
NEW: add password mask to dirac-login
=> [integration] add password mask to dirac-login

src/DIRAC/AccountingSystem/DB/AccountingDB.py
*Accounting
CHANGE: decrease some logs verbosity
=> [v7r3] Decrease log level of insanely verbose message

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
(no need for further release notes I believe)
=> [v7r3] fix: backports to account for use of BLOBs in 8.0

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
Sweep #5869 `Show callstack in service logs before cleaning it` to `integration`.
*Core
CHANGE: Show callstack in service logs when returning S_ERROR
Closes #5874
=> [sweep:integration] Show callstack in service logs before cleaning it

src/DIRAC/Resources/Computing/BatchSystems/SLURM.py, src/DIRAC/Resources/Computing/SSHComputingElement.py
*WMS
NEW: Added Account option for SLURM
=> [v7r3] fix: added account option to SLURM

src/DIRAC/FrameworkSystem/scripts/dirac_login.py
1.
Show infomation message:
```
You are currently using proxy/token to access new HTTP DIRAC services....
```
only if the current state of the user environment does not match the authorization result
2.
No local certificate:
```bash
(dirac-development) Armstrongs-MacBook-Pro:DIRAC TaykYoku$ dirac-login
Can't find user certificate and key
```
No local certificate:
```bash
(dirac-development) Armstrongs-MacBook-Pro:DIRAC TaykYoku$ dirac-login
Can't find user certificate and key, trying to connact to DIRAC AS..
Use next link to continue
https://dirac.egi.eu/auth/device?user_code=RWKG-MBCK
Authorization pending.. (use CNTL + C to stop)
^CUser canceled the operation..
```
With local certificate:
```bash
(dirac-development) Armstrongs-MacBook-Pro:DIRAC TaykYoku$ dirac-login
Enter Certificate …
```
=> [8.0][OAuth 2] dirac-login try to connect to DIRAC AS if no local certificate

src/DIRAC/FrameworkSystem/private/authorization/AuthServer.py, src/DIRAC/FrameworkSystem/scripts/dirac_login.py
If there are settings in the user group configuration to add a VOMS extension, add it automatically.
*Framework
NEW: dirac-login (AS) added VOMS extension
=> [8.0][OAuth 2] dirac-login (AS) added VOMS extension

.git-blame-ignore-revs, src/DIRAC/FrameworkSystem/private/authorization/grants/DeviceFlow.py, src/DIRAC/__init__.py
=> [8.0] Some real minor fixes

src/DIRAC/WorkloadManagementSystem/Client/Matcher.py
*WMS
FIX:  Matcher: fixed parsing of (required) tags
=> [v7r2] fix: fixed parsing of tags

src/DIRAC/ConfigurationSystem/private/TornadoRefresher.py, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/RequestManagementSystem/Client/File.py, src/DIRAC/RequestManagementSystem/Client/Operation.py, src/DIRAC/RequestManagementSystem/Client/ReqClient.py, src/DIRAC/RequestManagementSystem/Client/Request.py, src/DIRAC/RequestManagementSystem/Client/test/Test_Request.py, src/DIRAC/RequestManagementSystem/DB/RequestDB.py, src/DIRAC/RequestManagementSystem/Service/ReqManagerHandler.py, src/DIRAC/RequestManagementSystem/Service/ReqProxyHandler.py
*RMS
FIX: removing python2 support
=> [8.0] Removing python2 support from RMS

src/DIRAC/Resources/Storage/FileStorage.py, src/DIRAC/Resources/Storage/test/Test_FilePlugin.py
Fixes for the local File storage protocol
*Resources
FIX: File protocol listDirectory returns metadata
=> [v7r3] fix (Resources): fix listDirectory for local storage

src/DIRAC/Interfaces/API/Job.py, src/DIRAC/WorkloadManagementSystem/DB/TaskQueueDB.py, src/DIRAC/WorkloadManagementSystem/Executor/JobScheduling.py, src/DIRAC/WorkloadManagementSystem/Utilities/QueueUtilities.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac_admin_show_task_queues.py
*WMS
CHANGE: removed last SubmitPool entries
=> [8.0] removed last SubmitPool entries

src/DIRAC/Core/Base/AgentModule.py, src/DIRAC/Core/Utilities/DErrno.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/PushJobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_PushJobAgent.py, src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py
*WMS
FIX: using a DErrno for no match found
=> [v7r3] using a DErrno for no match found

src/DIRAC/FrameworkSystem/DB/UserProfileDB.py
=> [v7r3] fix: backport for BLOB->TEXT changes

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
* WMS
FIX: escape time stamp in setHeartBeatData
=> [v7r3] Escape Time stamp in JobDB

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
Sweep #5946 `Escape Time stamp in JobDB` to `integration`.
Adding original author @phicharp as watcher.
* WMS
FIX: escape time stamp in setHeartBeatData
Closes #5949
=> [sweep:integration] Escape Time stamp in JobDB

src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerPs.py, src/DIRAC/DataManagementSystem/DB/FileCatalogDB.py, src/DIRAC/DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql, src/DIRAC/DataManagementSystem/Service/FileCatalogHandler.py, src/DIRAC/DataManagementSystem/Service/TornadoFileCatalogHandler.py, src/DIRAC/Resources/Catalog/FileCatalogClient.py, tests/Integration/DataManagementSystem/Test_Client_DFC.py, tests/Integration/DataManagementSystem/Test_FileCatalogDB.py
* DMS
CHANGE: DFC dump feature can dump more than one SE at the same time
=> [v7r3] DFC allows to dump more than one SE at the time

docs/source/AdministratorGuide/Systems/WorkloadManagement/JobPriorities/index.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/JobsPriorities.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/index.rst, docs/source/DeveloperGuide/Internals/index.rst, src/DIRAC/Interfaces/API/Job.py
*docs
FIX: added better docs for JobShare and priorities
=> [v7r3] docs: added better docs for JobShare and priorities

src/DIRAC/AccountingSystem/private/Plotters/PilotSubmissionPlotter.py, src/DIRAC/MonitoringSystem/Client/MonitoringReporter.py, src/DIRAC/MonitoringSystem/Client/Types/PilotSubmissionMonitoring.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Fixing the discrepancies between the plots in accounting and monitoring for PilotSubmissions
*Accounting/Monitoring
FIX: Fixed the plotter for pilot submission accounting and other small fixes
=> [integration] Hackaton fix: pilotsubmission discrepancies between Accounting and Monitoring

docs/source/AdministratorGuide/Systems/WorkloadManagement/JobsPriorities.rst, docs/source/AdministratorGuide/Systems/WorkloadManagement/index.rst, docs/source/DeveloperGuide/Internals/index.rst
Sweep #5928 `docs: added better docs for JobShare and priorities` to `integration`.
*docs
FIX: added better docs for JobShare and priorities
Closes #5966
=> [sweep:integration] docs: added better docs for JobShare and priorities

src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
Sweep #5959 `fix: update PoolCE.innerCESubmissionType from JobAgent` to `rel-v7r3`.
FIX: update PoolCE.InnerCESubmissionType from JobAgent
Closes #5970
=> [sweep:v7r3] fix: update PoolCE.innerCESubmissionType from JobAgent

src/DIRAC/ConfigurationSystem/Agent/RucioSynchronizerAgent.py, src/DIRAC/ResourceStatusSystem/Agent/RucioRSSAgent.py, src/DIRAC/Resources/Catalog/RucioFileCatalogClient.py
This is a MultiVO modification to `RucioFileCatalogClient` and 2 sync agents based on the code developed by _Belle II_. It preserves the 'Belle way' of contacting a Rucio server which uses configuration parameters stored in a config file.
The multiVo setup does not require a config file, it uses all necessary info from the VO-specific Resources section of the CS. It requires a multi-VO enabled Rucio server.
=> [rel-v7r3] MultiVO RucioFileCatalogClient + Agents

docs/source/AdministratorGuide/Configuration/ConfReference/Systems/DataManagement/Services/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/DataManagement/URLs/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Framework/Services/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/StorageManagement/Services/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Services/index.rst, docs/source/AdministratorGuide/Configuration/ConfReference/Systems/WorkloadManagement/Services/index.rst, src/DIRAC/AccountingSystem/Service/ReportGeneratorHandler.py, src/DIRAC/Core/Utilities/Plotting/Plots.py, src/DIRAC/MonitoringSystem/Client/MonitoringReporter.py, src/DIRAC/MonitoringSystem/Client/Types/BaseType.py, src/DIRAC/MonitoringSystem/Client/Types/ComponentMonitoring.py, src/DIRAC/MonitoringSystem/Client/Types/PilotSubmissionMonitoring.py, src/DIRAC/MonitoringSystem/Client/Types/RMSMonitoring.py, src/DIRAC/MonitoringSystem/Client/Types/WMSHistory.py, src/DIRAC/MonitoringSystem/ConfigTemplate.cfg, src/DIRAC/MonitoringSystem/Service/MonitoringHandler.py, src/DIRAC/MonitoringSystem/Service/TornadoMonitoringHandler.py, src/DIRAC/MonitoringSystem/private/DBUtils.py, src/DIRAC/MonitoringSystem/private/MainReporter.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Service/TornadoJobManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/TornadoJobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/TornadoJobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/TornadoWMSAdministratorHandler.py, tests/Integration/AccountingSystem/Test_Plots.py
Plus other minor fixes.
*Monitoring
NEW: TornadoMonitoring handler
=> [8.0] Tornado Monitoring/Monitoring handler

docs/source/AdministratorGuide/Configuration/ConfReference/Resources/StorageElements/index.rst, docs/source/DeveloperGuide/Internals/Core/Serialization.rst, docs/source/DeveloperGuide/TornadoServices/index.rst, docs/source/UserGuide/HowTo/DataManagement/index.rst, src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/DISET/private/BaseClient.py, src/DIRAC/Core/DISET/private/Transports/BaseTransport.py, src/DIRAC/Core/Security/m2crypto/X509Chain.py, src/DIRAC/Core/Security/m2crypto/asn1_utils.py, src/DIRAC/Core/Security/test/x509TestUtilities.py, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/DataManagementSystem/private/FTS3Utilities.py, src/DIRAC/FrameworkSystem/Agent/ProxyRenewalAgent.py, src/DIRAC/FrameworkSystem/scripts/dirac_login.py, src/DIRAC/Resources/Catalog/ConditionPlugins/ProxyPlugin.py, src/DIRAC/Resources/Storage/FileStorage.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py, src/DIRAC/Resources/Storage/StorageBase.py, src/DIRAC/Resources/Storage/StorageElement.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py, tests/Integration/TornadoServices/Test_TornadoAndDISETmixed.py, tests/System/transformation_replication.sh
=> [8.0] hackathon fixes

src/DIRAC/DataManagementSystem/Agent/FTS3Agent.py, src/DIRAC/DataManagementSystem/DB/FTS3DB.py, src/DIRAC/DataManagementSystem/DB/test/Test_FTS3DB.py
The reasons and explanations for this change are described in detail in `test_raceCondition`
This has been running under very heavy load in LHCb for a week
*DMS
FIX: fix a race condition when running multiple FTS3Agents in parallel
=> [v7r3] Fix race condition in FTS3DB.getNonFinishedOperations

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
*Core
FIX: Set default value of BaseRequestHandler.COMPONENT_NAME
=> [integegration] Set default value of BaseRequestHandler.COMPONENT_NAME

src/DIRAC/Core/Base/AgentModule.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/PhysicalRemoval.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/PutAndRegister.py, src/DIRAC/DataManagementSystem/Agent/RequestOperations/ReTransfer.py, src/DIRAC/RequestManagementSystem/Agent/CleanReqDBAgent.py, src/DIRAC/RequestManagementSystem/Agent/RequestExecutingAgent.py, src/DIRAC/RequestManagementSystem/Agent/RequestOperations/ForwardDISET.py, src/DIRAC/RequestManagementSystem/Agent/RequestOperations/test/ForwardDISETTests.py, src/DIRAC/RequestManagementSystem/Service/test/OperationHandlerBaseTests.py
*RMS
FIX: moved REA initialization inside the initialize() method
=> [8.0] moved REA initialization inside the initialize() method

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Minor refactor, no need for release notes.
=> [8.0] Pylint sitedirector

dirac.cfg, docs/source/AdministratorGuide/Resources/storage.rst, docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst, src/DIRAC/DataManagementSystem/Client/FTS3Job.py, src/DIRAC/DataManagementSystem/Client/FTS3Operation.py, src/DIRAC/DataManagementSystem/Client/test/Test_FTS3Objects.py, src/DIRAC/DataManagementSystem/DB/test/Test_FTS3DB.py, src/DIRAC/DataManagementSystem/Utilities/DMSHelpers.py, src/DIRAC/DataManagementSystem/private/FTS3Plugins/DefaultFTS3Plugin.py, src/DIRAC/DataManagementSystem/private/FTS3Plugins/test/Test_DefaultFTS3Plugin.py, src/DIRAC/DataManagementSystem/scripts/dirac_dms_protocol_matrix.py
Ladies and Gentlemen, this PR is one of a kind. With one single PR, I will:
* make you travel back in time
* embark you on a fascinating journey into graph theory
* use my crystal ball for fortune telling
Let's begin right away.
The more experienced people (I did not say old) will remember the good old days of FTS2. Back in the days, in order to transfer files, you had to define _channels_, describing which service to use for a given source and a given destination. Adding a new storage element meant adding many new _channels_. This was bringing back fond memories to old people (yes, this time I said old) that were accustomed to telephone switchboard.
Then, something terrible happened. FTS3 was born, and with it, the abrupt stoppage of the channels definition. 
> And it's been the ruin of …
=> [v7r3] Implement time machine

environment.yml, setup.cfg, src/DIRAC/Resources/Computing/CloudComputingElement.py, src/DIRAC/Resources/Computing/cloudinit.template, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Sweep #5988 `add CloudComputingElement` to `integration`.
Adding original author @marianne013 as watcher.
*Resources
NEW:  add CloudComputingElement
CHANGE:  add hook for pilot cleanup
Closes #6037
=> [sweep:integration] add CloudComputingElement

src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py
*Framework
FIX: ComponentSupervisionAgent: skip Tornado service
=> [80] fix: ComponentSupervisionAgent skip Tornado service

dirac.cfg, docs/source/AdministratorGuide/Resources/storage.rst, docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst, src/DIRAC/DataManagementSystem/Client/FTS3Job.py, src/DIRAC/DataManagementSystem/Client/FTS3Operation.py, src/DIRAC/DataManagementSystem/Client/test/Test_FTS3Objects.py, src/DIRAC/DataManagementSystem/DB/test/Test_FTS3DB.py, src/DIRAC/DataManagementSystem/Utilities/DMSHelpers.py, src/DIRAC/DataManagementSystem/private/FTS3Plugins/DefaultFTS3Plugin.py, src/DIRAC/DataManagementSystem/private/FTS3Plugins/test/Test_DefaultFTS3Plugin.py, src/DIRAC/DataManagementSystem/scripts/dirac_dms_protocol_matrix.py
Sweep #5809 `Implement time machine` to `integration`.
*DMS
NEW: bitterly implement multihop
Closes #6035
=> [sweep:integration] Implement time machine

src/DIRAC/Workflow/Modules/Script.py
*WMS
FIX: Don't crash if systemCall fails
=> [v7r2] Don't crash if systemCall fails

src/DIRAC/Core/Utilities/ElasticSearchDB.py
Fixes the formatting as #5987 was merged with failing CI.
=> [v7r2] Fix CI due to bad PR merge

src/DIRAC/FrameworkSystem/Client/NotificationClient.py, src/DIRAC/FrameworkSystem/Service/NotificationHandler.py
=> [8.0] Minor fix for NotificationClient

src/DIRAC/Resources/Cloud/CloudEndpoint.py
*Resources
FIX: Error in the condition to get FlavorName
=> [v7r3] CloudEndpoint fix:  Error in the condition to get FlavorName

src/DIRAC/Core/Tornado/Client/ClientSelector.py, src/DIRAC/Core/Tornado/Server/TornadoService.py
*Core
FIX: fix error reporting in TornadoService
=> [v7r3] Fixes for tornado logging

src/DIRAC/Resources/MessageQueue/StompMQConnector.py
*Resources
FIX: Adapt StompMQConnector to Stomp 8
=> [8.0] fix (StompMQConnector): adapt to stomp 8

src/DIRAC/Core/Tornado/Client/ClientSelector.py, src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
Sweep #6123 `Fixes for tornado logging` to `integration`.
*Core
FIX: fix error reporting in TornadoService
Closes #6125
=> [sweep:integration] Fixes for tornado logging

tests/Integration/WorkloadManagementSystem/Test_JobDB.py
*WMS
NEW: adding a test to show the modifications made to the JDL before being inserted in the JobDB
=> [8.0] test: adding jdl assert to test jobDB

src/DIRAC/Core/Security/VOMS.py
@sfayer and me think the old code is basically cargo cult code.
*Core
FIX: Replaced old vomses/vomsdir code to be able to handle cvmfs vomses. See #6150 
=> [v7r3] replaced old vomses/vomsdir code to be able to handle cvmfs vomses

src/DIRAC/Core/Utilities/JEncode.py, src/DIRAC/FrameworkSystem/private/authorization/utils/Tokens.py, src/DIRAC/FrameworkSystem/private/authorization/utils/Utilities.py, src/DIRAC/Interfaces/API/DiracAdmin.py, src/DIRAC/Interfaces/scripts/dirac_admin_get_job_pilots.py, src/DIRAC/TransformationSystem/Agent/TransformationAgentsUtilities.py, src/DIRAC/TransformationSystem/Client/FileReport.py, src/DIRAC/TransformationSystem/Client/PluginBase.py, src/DIRAC/TransformationSystem/Client/RequestTasks.py, src/DIRAC/TransformationSystem/Client/TaskManagerPlugin.py, src/DIRAC/TransformationSystem/Client/Transformation.py, src/DIRAC/TransformationSystem/Client/TransformationClient.py, src/DIRAC/TransformationSystem/Client/Utilities.py, src/DIRAC/TransformationSystem/Client/WorkflowTasks.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_RequestTasks.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_TaskManagerPlugin.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_TransformationSystem.py, src/DIRAC/TransformationSystem/Utilities/TransformationInfo.py
=> [8.0] Some really minor fixes

src/DIRAC/RequestManagementSystem/Agent/CleanReqDBAgent.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg
NEW: Add option to automatically cancel Scheduled requests after a defined time period.  Default behaviour unchanged. Relates to #6136
Closes #6171'
=> sweep: #6148 feat: add option to automatically cancel Scheduled requests

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
I propose to rename these methods to make clear they're part of the public interface of this class and can be overridden in the webapp.
=> [8.0] Rename __executeMethod

src/DIRAC/WorkloadManagementSystem/Executor/JobScheduling.py
fix request staging call in JobScheduling
=> [Integration] fix: fix request staging call in JobScheduling

tests/Integration/WorkloadManagementSystem/Test_JobDB.py
Fixing the issue met by @chaen in LHCbDIRAC by patching getVOForGroup
=> [Integration] fix: fixing the expected jdl test in vo environments by patching the getVOForGroup

tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_WMSAdministratorClient.py, tests/Integration/all_integration_client_tests.sh
rewriting Test_Client_WMS in pytest and creating a seperate WMSAdministratorClient test.
=> [Integration] refactor: rewriting in pytest and seperating the WMSAdministratorClient test

.github/workflows/semantic.yml
Tested in https://github.com/DIRACGrid/DIRAC/pull/6197
=> [v7r2] Allow semantic CI check to accept git-revert commits

src/DIRAC/Resources/MessageQueue/StompMQConnector.py
Backport https://github.com/DIRACGrid/DIRAC/pull/6080
*Resources
NEW: Adapt MQConnector to stomp 8
=> [v7r3] Backport adapt to stomp 8

.github/workflows/semantic.yml
=> [v7r3] Sweep #6202 Allow semantic CI check to accept git-revert commits

.github/labeler.yml
Sweeping #6202 manually now it's been shown to work
=> [v7r2] Sweep #6202: Add workaround for labeler ignoring hidden files

src/DIRAC/Resources/Computing/ARC6ComputingElement.py, src/DIRAC/Resources/Computing/ARCComputingElement.py
Sweep #6211 `fix: ARC6 CE issues` to `rel-v7r3`.
*Resources
FIX: ARC6 typo issues
FIX: ARC writeXRSL becomes protected
Closes #6212
=> [sweep:v7r3] fix: ARC6 CE issues

src/DIRAC/MonitoringSystem/Client/DataOperationSender.py, src/DIRAC/MonitoringSystem/private/Plotters/BasePlotter.py, src/DIRAC/MonitoringSystem/private/Plotters/DataOperationPlotter.py
Fixing errors that were blocking the commission of data by the DataOperationSender to Elasticsearch
*Monitoring
FIX: Fixing errors blocking commission of data operations to Elasticsearch
=> [8.0] fix: Errors in dataOperationSender

src/DIRAC/Core/Utilities/Graphs/GraphUtilities.py, src/DIRAC/Core/Utilities/TimeUtilities.py, tests/Integration/Core/Test_TimeUtilities.py
Fixing errors in TimeUtilites module. Adding furhter testing for new methods.
*Core
FIX: Fixing errors, adding tests for TimeUtilities module
=> [8.0] Hackaton fix: TimeUtilities module 

src/DIRAC/WorkloadManagementSystem/Executor/JobPath.py
*WMS
CHANGE: removing the possibility to get the optimizers to run with a vo plugin
=> [8.0] refactor: removing the possibility to get the optimizers to run with a vo plugin

src/DIRAC/Core/Tornado/Server/TornadoREST.py
Using `cls.__dict__` means that methods from parent classes are ignored. Fixing it check parent classes then means that the OAuth stuff is broken as it starts exposing tornado methods like `get_secure_cookie` as `/secure_cookie/`.
*Core
FIX: Discovery of HTTPS methods from parent classes
=> [8.0] Fix discovery of HTTPS methods from parent classes

integration_tests.py
Cherry-pick of https://github.com/DIRACGrid/DIRAC/pull/6261
=> [integration] Fix integration_tests.py for latest release of typer

environment.yml, integration_tests.py, src/DIRAC/Resources/Catalog/RucioFileCatalogClient.py
Cherry-pick of https://github.com/DIRACGrid/DIRAC/pull/6261
Includes https://github.com/DIRACGrid/DIRAC/pull/6254 along with a hack to get the CI passing which I'll open an issue so it gets fixed properly.
=> [v7r3] Fix integration_tests.py for latest release of typer

src/DIRAC/FrameworkSystem/private/standardLogging/Formatter/MicrosecondJsonFormatter.py, src/DIRAC/Resources/LogBackends/MessageQueueBackend.py, src/DIRAC/Resources/LogBackends/StdoutJsonBackend.py
Sweep #6237 `feat (logging): add an stdout Backend with json formatting` to `integration`.
*Framework
NEW: Add StdoutJsonBackend 
Closes #6243
=> [sweep:integration] feat (logging): add an stdout Backend with json formatting

src/DIRAC/Resources/Computing/SingularityComputingElement.py
Some sites use a local networked filesystem to provide access to data and therefore extra paths need to be bind bounted inside containers. This PR expands the ContainerBind option to be available at the Site and CE level rather than only the computing element type.
NEW: ContainerBind option can be set on the per-site and per-CE level
=> [v7r3] Support Site/CE specific container bind mounts

src/DIRAC/WorkloadManagementSystem/Executor/JobScheduling.py
*WMS
CHANGE: removing filtering user sites by platform during the CHECKING state
=> [8.0] refactor: removing filtering by platform in the optimizers

src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_ParametricJob.py
This PR also improves the test by iterating through the jobDescList to test all the jobs created
=> [8.0] Rewriting Test_ParametricJob to make it more comprehensible

src/DIRAC/Resources/Computing/PoolComputingElement.py
Closes #6308 .
*Resources
FIX: Forward jobDesc to innerCE in PoolCE
=> [v7r3] Forward jobDesc to innerCE in PoolCE

environment-py3.yml, setup.cfg
See https://github.com/DIRACGrid/DIRAC/issues/6322 for details.
*Core
CHANGE: Replace suds-jurko with suds
=> [v7r3] Replace suds-jurko with suds

environment-py3.yml, setup.cfg
See https://github.com/DIRACGrid/DIRAC/issues/6322 for details.
*Core
CHANGE: Replace suds-jurko with suds
=> [v7r2] Replace suds-jurko with suds

README.rst, src/DIRAC/ConfigurationSystem/Client/Helpers/Operations.py, src/DIRAC/Core/Base/AgentModule.py, src/DIRAC/Core/DISET/ServiceReactor.py, src/DIRAC/Core/DISET/private/Service.py, src/DIRAC/Core/DISET/private/ServiceConfiguration.py, src/DIRAC/Core/Tornado/Server/TornadoServer.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
*Core
NEW: adding general flag for disabling Monitoring for Agents (used by JobAgent)
=> [8.0] adding general flag for disabling Monitoring for Agents (used by JobAgent)

setup.cfg, src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/ConfigurationSystem/Client/Helpers/Resources.py, src/DIRAC/ConfigurationSystem/Client/Helpers/test/Test_Helpers.py, src/DIRAC/ConfigurationSystem/private/Refresher.py, src/DIRAC/ConfigurationSystem/private/ServiceInterface.py, src/DIRAC/Core/Base/AgentModule.py, src/DIRAC/Core/Base/Client.py, src/DIRAC/Core/Base/Script.py, src/DIRAC/Core/DISET/private/MessageBroker.py, src/DIRAC/Core/Security/VOMS.py, src/DIRAC/Core/Utilities/DEncode.py, src/DIRAC/Core/Utilities/Devloader.py, src/DIRAC/Core/Utilities/EventDispatcher.py, src/DIRAC/Core/Utilities/Extensions.py, src/DIRAC/Core/Utilities/Os.py, src/DIRAC/Core/Utilities/Plotting/DataCache.py, src/DIRAC/Core/Utilities/ProcessPool.py, src/DIRAC/Core/Utilities/ThreadPool.py, src/DIRAC/Core/Utilities/ThreadScheduler.py, src/DIRAC/DataManagementSystem/Service/StorageElementProxyHandler.py, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/FrameworkSystem/private/SecurityFileLog.py, src/DIRAC/ResourceStatusSystem/Utilities/RSSCache.py, src/DIRAC/Resources/Computing/test/Test_HTCondorCEComputingElement.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py, src/DIRAC/StorageManagementSystem/DB/StorageManagementDB.py, src/DIRAC/Workflow/Modules/Script.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_QueueUtilities.py
Not worthy of release notes.
See the individual commit messages for details.
=> [8.0] Fix various deprecation warnings

docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst
Closes https://github.com/DIRACGrid/DIRAC/issues/6272
Closes https://github.com/DIRACGrid/DIRAC/issues/6280
=> [8.0] Sweeping #6270 and #6271

environment-py3.yml
=> [v7r2] Add suds-jurko-compat to environment-py3.yml

environment-py3.yml
See https://github.com/DIRACGrid/DIRAC/issues/6322
=> [v7r3] Add suds-jurko-compat to environment-py3.yml

src/DIRAC/Resources/Storage/EchoStorage.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py, src/DIRAC/Resources/Storage/test/test_utilities.py
*Resources
NEW: Add a setGfalSetting decorator 
CHANGE: add a 30s timeout for removal at RAL
=> [v7r3] Add a gfal2 context manager as well as a removal timeout for echo

src/DIRAC/Resources/Storage/EchoStorage.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py, src/DIRAC/Resources/Storage/test/test_utilities.py
Sweep #6352 `Add a gfal2 context manager as well as a removal timeout for echo` to `integration`.
*Resources
NEW: Add a setGfalSetting decorator 
CHANGE: add a 30s timeout for removal at RAL
Closes #6356
=> [sweep:integration] Add a gfal2 context manager as well as a removal timeout for echo

environment.yml, setup.cfg
*Core
FIX: Explicitly depend on db12
=> [8.0] Update dependencies in setup.cfg

src/DIRAC/DataManagementSystem/Agent/FTS3Agent.py, src/DIRAC/DataManagementSystem/Client/FTS3Job.py
For https://github.com/DIRACGrid/DIRAC/issues/6360
*DMS
NEW: cancel the FTS transfers when an RMS request is found to be canceled
=> [v7r3] cancel the FTS transfers when an RMS request is canceled

src/DIRAC/WorkloadManagementSystem/Executor/Base/OptimizerExecutor.py, src/DIRAC/WorkloadManagementSystem/Executor/test/Test_Executor.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, tests/Integration/Framework/Test_UserProfileClient.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_JobCleaningAgent.py, tests/Integration/WorkloadManagementSystem/Test_JobParameters_MySQLandES.py, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Jenkins/dirac-cfg-update-server.py, tests/Jenkins/dirac_ci.sh, tests/Jenkins/install.cfg, tests/Jenkins/utilities.sh
*tests
NEW: launching the Optimizers in integration-tests
=> [8.0] feat: launching optimizers in the integration environment

src/DIRAC/Resources/Computing/ARCComputingElement.py, src/DIRAC/Resources/Computing/AREXComputingElement.py
This is a first release of the AREX computing element. The documentation for this PR is essentially the same as that in
https://github.com/DIRACGrid/DIRAC/pull/5471
Hopefully I have addressed most of the comments in the above PR. However, if I have missed something, please do comment again here.
Some of the parts of the code need to wait for testing for the following reasons.
1. The LHCbDirac certification system is currently not accepting jobs
2. The "delegation" part of the ARC REST interface involving adding delegation ID to XRSL string at time of job submission is awaiting the next release of ARC computing software - supposedly imminent. So, this is done as per the documentation, but not yet tested.
=> [rel-v7r2]: WIP : First version of AREX computing element

docs/source/AdministratorGuide/ServerInstallations/HTTPSServices.rst, docs/source/AdministratorGuide/ServerInstallations/index.rst, docs/source/DeveloperGuide/TornadoServices/index.rst, src/DIRAC/FrameworkSystem/scripts/dirac_install_tornado_service.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
*Docs
NEW: Improve documentation on installing HTTPs services
=> [v7r3] Proper documentation for HTTPs services

src/DIRAC/ConfigurationSystem/Client/LocalConfiguration.py, src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py, src/DIRAC/Core/Tornado/scripts/tornado_start_all.py
Fixes https://github.com/DIRACGrid/DIRAC/issues/6363
*Core
FIX: Tornado components are initialized using the Tornado system section
FIX: each Tornado handler reads its own log level
=> [8.0] Tornado log fixes
