Core/Base/Client.py
This fix https://github.com/DIRACGrid/DIRAC/pull/4340/commits/6b7732eb14abbef6b1be88b52658405f748b1f58 prevented setting a global timeout, while this is needed in the LHCb extension
This PR restore the possibility to do so.
Now, looking in detail about it, I realized something quite nasty: the `self.__kwargs` attribute created in the `Client` object ripples down to the `BaseClient.kwargs` where it is actually modified. So it does not matter because:
* it only changes basic types, and not inner containers
* we plan on moving to HTTP anyway 
But still, I wanted to note it
*Core
FIX: restore the possibility to set a global timeout for a Client
=> [v7r0] Core: restore the possibility to set a global timeout for a Client

requirements.txt
Newer releases are python3 only. This results in pylint tests failing with `Instance of 'StompConnection11' has no 'start' member`
Also in https://github.com/DIRACGrid/DIRACOS/pull/109
=> [v6r22][URGENT] freeze stomp.py version 

WorkloadManagementSystem/Client/Limiter.py
I think this fixes the matching delay functionality. 
*WMS
FIX: Fix the matching delay functionality, fixes #2983 
=> [v7r0] WMS.Limiter: move some variables to class static level, fix matchingdelay

WorkloadManagementSystem/Agent/JobCleaningAgent.py, WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/DB/JobDB.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
*WMS
NEW: JobCleaningAgent: Add possibility to remove HeartBeatLoggingInfo before jobs are completely removed.
By the way, I couldn't find anything in LHCbDIRAC which uses information from the HeartBeatLoggingInfo table:
https://gitlab.cern.ch/search?utf8=%E2%9C%93&search=heartbeat&group_id=&project_id=3588&search_code=true&repository_ref=master&nav_source=navbar
=> [v7r0] JobDB, JobCleaningAgent: add HeartBeatLoggingInfo cleanup functionality

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
*Docs
CHANGE: dirac-docs-get-release-notes.py does not require a GITLABTOKEN
=> [v7r0] Docs: GITLABTOKEN not mandatory to generate changelog

DataManagementSystem/DB/FTS3DB.py, RequestManagementSystem/DB/RequestDB.py
*RMS
CHANGE: ReqDB: Add pool_recycle=3600 parameter for sql engine setup, might prevent occasional "Mysql Server has gone away" errors
*DMS
CHANGE: FTS3DB: Add pool_recycle=3600 parameter for sql engine setup, might prevent occasional "Mysql Server has gone away" errors
PS:
We occasionally get this error:
```
2020-01-08 13:16:22 UTC DataManagement/FTS3Manager NOTICE: Returning response ([::ffff:128.142.152.229]:59950)[ilc_fcadmin:sailer] (0.03 secs) ERROR: persistOperation: unexpected exception (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away')
```
I think this is because during periods without activity the mysql server will after 8 hours (wait_timeout parameter) close connections. sqlalchemy can be instructed to drop connections …
=> [v7r0] FTS3DB, ReqDB: add pool_recycle to create_engine

Core/DISET/AuthManager.py, Core/DISET/RequestHandler.py, Resources/Computing/ARCComputingElement.py, WorkloadManagementSystem/Agent/SiteDirector.py
Several small fixes to make backward compatibility of a v7r1 client accessing v7r0 service.
*WMS
FIX: SiteDirector - do not add downloading files ti the pilot if Pilot3 flag is False
*Core
FIX: RequestHandler - fix log output for the case where the ActionTuple is actually a string
FIX: AuthManager - manage the case where ExtraCredentials are in a form of a list
=> [v7r0] Small fixes

Resources/Computing/ARCComputingElement.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/ConfigTemplate.cfg
All the following changes should improve the execution time of the SiteDirector:
CHANGE: getStatus method in ARC CE now uses a JobSupervisor to get status of multiple pilots at once.
CHANGE: SiteDirector.updatePilotStatus has been parallelized using threads.
NEW: AvailableSlotsUpdateCycleFactor is a parameter part of the configuration allowing to control the rate of the update of the available slots in the queues.
FIX: Revert to queueCECache being an object attribute to fix the CEs instanciation.
* The getStatus method was manually tested with 120 pilots on ARC CEs. While the current method takes around 17 seconds to get the status of every pilots, this new one was able to do the same job in 0.90 seconds.
* The update of the status is …
=> [v7r0] SiteDirector: improve execution time

Resources/Computing/HTCondorCEComputingElement.py, Resources/Computing/test/Test_HTCondorCEComputingElement.py, WorkloadManagementSystem/Service/PilotManagerHandler.py, WorkloadManagementSystem/Service/WMSUtilities.py
To avoid to have too many of them in a single directory, job outputs are randomly sorted into multiple directories on two levels on the server: `workingDirectory/<random_dir1>/<random_dir2>/<job_output>`
The information about their locations is not kept in the pilot job reference which is only composed of the job id. Therefore, the only way to retrieve an output is to perform a `find` command in the `workingDirectory` with the job id.
This PR aims at adding the name of the directories in the pilot job reference to quickly retrieve the associated job output.
Here is the current structure of the pilot job reference:
`htcondorce://<ce name>/<clusterid>.<jobid>`
Here is the proposed one:
`htcondorce://<ce name>/<random dir1><random dir2>-<clusterid>.<jobid>`
The previous pilot job references …
=> [v7r0] HTCondorCE: modify the PilotJobReferences to determine the paths of the job outputs

Core/scripts/install_site.sh
CC7 does not have wget by default
*Core
CHANGE: install_site uses curl instead of wget
=> [integration] Core: install_site uses curl instead of wget

Core/scripts/dirac-install.py
*Core
NEW: When `dirac-install` creates the bashrc file all currently existing "DIRAC_" environment variables are added as comments to the file, fixes #4351 
=> [integration] dirac-install: add possible env vars to bashrc

DataManagementSystem/Agent/FTS3Agent.py
Operationally, we noticed that when having a low FTS activity, the proxy was expiring too soon, resulting in failed transfers.
*DMS
CHANGE: change proxy lifetime of FTS3Agent from 2 to 12 hours
=> [v6r22] FTS3: change proxy lifetime from 2 to 12 hours

FrameworkSystem/Client/ComponentInstaller.py
Partially solves https://github.com/DIRACGrid/DIRAC/issues/4408
*Subsystem
CHANGE: the ComponentInstaller is a bit more relaxed when looking for runsvdir
=> [v6r22] SystemAdministrator: do not start runsvdir if not needed

.github/workflows/integration.yml, Core/scripts/dirac-install.py, tests/CI/CONFIG, tests/CI/install_client.sh, tests/CI/run_docker_setup.sh, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
Currently all integration tests are being ran with CentOS 7 due to `HOST_OS` not being propagated correctly. This exposes an issue with the images which is fixed in https://github.com/DIRACGrid/management/pull/1.
This PR also allows `--dirac-os-version` to be a path so that DIRAC OS tarballs can be tested without them being uploaded to EOS (will be used in an upcoming DIRAC OS PR).
*Core
NEW: Allow `--dirac-os-version` argument to `dirac-install.py` to be a path or URL to a tarball
=> [v7r0] Fix SLC6 integration tests and allow installation from local DIRACOS tarball

DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryTreeBase.py, DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py, DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerBase.py, DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerDB.py, DataManagementSystem/DB/FileCatalogDB.py, Resources/Catalog/FileCatalogClient.py
The SE management has nothing to do in the DFC, as discussed already a long time.
So I remove it, and do what I said in the ticket https://github.com/DIRACGrid/DIRAC/issues/4227
*DMS
CHANGE: remove all the SE mangling in the DFC (SEPrefix, resolvePFN, SEDefinition)
=> [v7r1] DFC: remove SEPrefix, VOPath, VOPrefix, ResolvePFN and SEDefinition from the DFC

WorkloadManagementSystem/DB/JobDB.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
Addressing one of the proposal from #4363 
*WMS
NEW: Added option "CompressJDLs" to JobDB, which compresses JDLs before they are added to the JobJDLs table
=> [integration] JobDB: add CompressJDLs option for JobDB

Core/scripts/dirac-install.py, tests/Jenkins/utilities.sh
This was resulting in the `LHCbDIRAC` being partially installed in `etc/grid-security`.
Targets v7r0 so as that branch is used by some integration tests.
=> [v7r0] Create installation symlinks in the target directory

WorkloadManagementSystem/Client/ServerUtils.py
FIX: server name in ServerUtils.getPilotAgentsDB()
=> [v6r22] Fix serverName in ServerUtils.getPilotAgentsDB()

DataManagementSystem/Client/DataManager.py, FrameworkSystem/scripts/dirac-install-component.py, tests/Integration/DataManagementSystem/Test_DataManager.py, tests/Integration/all_integration_client_tests.sh, tests/Jenkins/dirac-cfg-update-server.py, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
Currently trying to revive the DataManager tests, installing two local SEs and copying files. Adding some tests for cleaning directories once this is working.
*DMS
FIX: dirac-dms-clean-directory: also works on single empty directory, fixes #4420 
*Framework
FIX: dirac-install-component: fix bug prohibiting use of the -m/--module parameter
=> [v7r0]  Fix cleaning empty directory, revive DataManager tests

DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata/DirectoryMetadata.py, DataManagementSystem/DB/FileCatalogComponents/FileMetadata/FileMetadata.py
Split getMetadataFields methods for files and directories into an interface and implementation part to allow overriding implementation in derived classes. Plus added few doc strings
*DMS
CHANGE: FileMetadata - split  getFileMetadataFields into getFileMetadataFields and _getFileMetadataFields
CHANGE: DirectoryMetadata - split  getMetadataFields into getMetadataFields and _getMetadataFields
=> [v7r1] File catalog metadata methods split 

Core/Utilities/MySQL.py, tests/Integration/Core/Test_MySQLDB.py, tests/Integration/all_integration_server_tests.sh
The `MySQLDB._connect()` does not ensure the connection with a DB is established properly and always return `S_OK()`:
https://github.com/DIRACGrid/DIRAC/blob/integration/Core/Utilities/MySQL.py#L583
This PR fixes the method by trying to establish a connection with the DB.
It may take several minutes so it does not retry a lot of times if it doesn't work.
If the connection fails, then the method returns an error.
*Core
FIX: MySQLDB _connect method
*tests
CHANGE: integrate test_MySQLDB to all_integration_server_tests
=> [v7r1] Fix MySQLDB _connect() method

MonitoringSystem/DB/MonitoringDB.py
CHANGE: Read the IndexPrefix for the CS and use this index prefix when creating ES indices, if not given use the name of the setup
This is needed or us, since we have an ES instance es-ilcdirac with IT, but our setup name in DIRAC is ilc. The problem is that IT wants that the index prefix matches instance name.
=> [v6r22] Read ES IndexPrefix from CS, if none given use setup name

Core/scripts/dirac-install.py
*Core
FIX: dirac-install: fix check for using diracos for integration or master, fixes #4449 
=> [integration] diracInstall: fix check for using diracos for integration or master

FrameworkSystem/Service/SystemAdministratorHandler.py
*Framework
CHANGE: Web portal compilation is done during the DIRAC distribution, it is not required to compile during the installation
=> [v6r22] do not try to compile the WebApp

MonitoringSystem/Client/MonitoringReporter.py
As discussed a warning log about not having MQ setup in Monitoring. I don't this this needs release notes.
=> [v6r22] Add warning about no MQ in Monitoring

Resources/Computing/ARCComputingElement.py, Resources/Computing/CREAMComputingElement.py, Resources/Computing/ComputingElement.py, Resources/Computing/ComputingElementFactory.py, Resources/Computing/GlobusComputingElement.py, Resources/Computing/HTCondorCEComputingElement.py, Resources/Computing/LocalComputingElement.py, Resources/Computing/PoolComputingElement.py, Resources/Computing/SSHBatchComputingElement.py, Resources/Computing/SSHComputingElement.py
There is a discrepancy between the definition of the `_reset()` method in LocalCE and SSHCE, and in the others.
LocalCE and SSHCE return a value (`S_OK`/`S_ERROR`) while the others don't.
https://github.com/DIRACGrid/DIRAC/blob/integration/Resources/Computing/CREAMComputingElement.py#L102
https://github.com/DIRACGrid/DIRAC/blob/integration/Resources/Computing/LocalComputingElement.py#L71
Errors are not handled as ComputingElement ignores the value returned by _reset.
https://github.com/DIRACGrid/DIRAC/blob/integration/Resources/Computing/ComputingElement.py#L234
In this PR, I add a value to return in every definition of `_reset` and the value that it returns is considered.
*Resources
FIX: discrepancy in CE._reset()
=> [v7r1]Fix discrepancy in CE _reset()

DataManagementSystem/Client/DataManager.py
Allows for better error handling.
Currently, if you do `DataManager.getFile` of a file that does not exist, you get
```
{'Errno': 1604, 'Message': 'FileCatalog error ( 1604 : Failed to perform getFileMetadata from any catalog)', 'OK': False, 'CallStack': ['  File "/tmp/testFix.py", line 10, in <module>\n    print dm.getFile(lfn)\n', '  File "/opt/dirac/DIRAC/DataManagementSystem/Client/DataManager.py", line 375, in getFile\n    res = self.fileCatalog.getFileMetadata(lfnReplicas.keys())\n', '  File "/opt/dirac/DIRAC/Resources/Catalog/FileCatalog.py", line 323, in r_execute\n    return S_ERROR( DErrno.EFCERR, "Failed to perform %s from any catalog" % self.call )\n']}
```
Now you get
```
{'OK': True, 'Value': {'Successful': {}, 'Failed': {'/lhcb/nonExisitng': 'No such file or directory'}}} …
```
=> [v6r22] DMS: dm.getFile only checks metadata of files with replicas

Core/Security/m2crypto/X509Certificate.py, Core/Security/m2crypto/asn1_utils.py, Core/Security/test/Test_X509Certificate.py, Core/Security/test/x509TestUtilities.py
I finally understood why it was not showing up in the unit tests. It's because `openssl` keeps some memory, and since the pyGSI tests were running before the `M2Crypto` one, the name `vomsExtensions` was known. I changed the order in which we test to make sure M2Crypto starts from scratch.
Also, the test `isVOMS` is now done by retrieving the extension by OID.
*Core
FIX: X509Chain.isVOMS returns correct value
=> [v7r0] M2Crypto: fix isVOMS

Core/scripts/dirac-install.py
*Core
FIX: Try to untar using system tar in case tarfile module is failing
=> [v6r22] roll back to system tar in case of tarfile module failure

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, WorkloadManagementSystem/Utilities/PilotWrapper.py, WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py
Addresses #4483 
I started with implementing on the server side, using sha512 (should be available a;ready in python 2.6, https://docs.python.org/2.6/library/hashlib.html) and very simple reading of the file contents.
I don't think these files are going to be very large? So efficient calculation and memory issues maybe don't have to be taken into considerations here?
~~I will look at the pilot side next~~
Also implemented the pilotwrapper side
*WMS
NEW: Add checksum calculation for PilotCSToJsonSynchroniser
NEW: Add checksum checks to PilotWrapper
FIX: Fix download checks in PilotWrapper in case the webserver does not return 404 but not the expected file content either.
=> [v7r0] PilotCSToJsonSynchronizer: implement checksumming

Resources/Computing/BatchSystems/TimeLeft/SLURMResourceUsage.py
A small fix to `SLURMResourceUsage`, I forgot the option to remove the header from the output which creates an error when parsing the output. It stops the `JobAgent` when using Slurm with `fillingMode`.
*Resources
FIX: Slurm Resource Usage
=> [v7r0] Fix SLURM Resource Usage

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py
*WMS
FIX: PilotCS2Json: fix writing of local pilot.json file, which is used to calculate the hash
FIX: PilotCS2Json: write checksum file in text mode
In the test: clear CFG before and after the test to ensure expected hash is created
=> [v7r0] PilotCSToJson fix  checksumming

FrameworkSystem/DB/SystemLoggingDB.py, TransformationSystem/DB/TransformationDB.sql, WorkloadManagementSystem/DB/JobLoggingDB.py
Some issues we had to fix after we moved to mysql 5.7
*Framework
FIX: SystemLoggingDB: reduce too long messages to 255 characters (see also  #1780 ?)
*WMS
FIX: JobLoggingDB: Limit StatusSource to 32 characters
*TS
CHANGE: TransformationDB.Transformations TransformationGroup column increased to 255 characters (`ALTER TABLE Transformations MODIFY TransformationGroup VARCHAR(255) NOT NULL default 'General';`)
Other issues not related to code changes:
For tables created a long time ago, these were changed in v6r6 but not written in the migration notes
* The SystemLoggingDB MessageRepository LogLevel column was changed to varchar(15) instead of int. (see also  #1095) 
* ALTER TABLE `ac_type_ILC-Production_Job` MODIFY COLUMN `DiskSpace` BIGINT;
Also if one is …
=> [v6r22] mysql57 entries too long for the table field

Resources/Computing/SSHComputingElement.py
In the current code, when there is a problem in the _prepareRemoteHost, 
self.preamble is not set. This cause problem when submitJob is executed:
https://github.com/DIRACGrid/DIRAC/blob/eececa18abc346cf0262a43452f1d3cc2a2999bd/Resources/Computing/SSHComputingElement.py#L497-L503
This caused problem in Belle II environment
(SiteDirector could not submit jobs to some of sites)
*Resources
FIX: Moved _prepareRemoteHost in SSHComputingElement
=> [v6r22] Place to execute _prepareRemoteHost is changed

ConfigurationSystem/Agent/Bdii2CSAgent.py, ConfigurationSystem/Agent/GOCDB2CSAgent.py, ConfigurationSystem/ConfigTemplate.cfg, Core/Utilities/StateMachine.py, ResourceStatusSystem/PolicySystem/PDP.py, ResourceStatusSystem/PolicySystem/StateMachine.py, docs/source/AdministratorGuide/Resources/agents2CS.rst, docs/source/AdministratorGuide/Resources/index.rst, tests/Jenkins/utilities.sh, tests/System/client_core.sh
*RSS
FIX: correct verbosity (avoid non-necessary warnings)
*docs
NEW: Minimal documentation on Bdii2CSAgent and GOCDB2CSAgent
=> [v7r0] Minor fixes + doc on Bdii

tests/CI/run_docker_setup.sh
The DIRAC OS CI is currently broken as `$DIRACOS_TARBALL_PATH` is set to `/`. Unsurprisingly copying the entire system from the host to the container causes the container to get stuck until the job times out.
Instead, check if the folder actually contains a `diracos-*.tar.gz` file.
=> [v7r0] URGENT: Fix DIRACOS CI

TransformationSystem/DB/TransformationDB.py, tests/Jenkins/utilities.sh
to fix https://github.com/DIRACGrid/DIRAC/issues/3710 because I have enough of those 8h long cleaning queries
*TS
CHANGE: clean the DataFiles table when cleaning a Transformation
=> [v7r0] TS: __deleteTransformationFiles also attempts to remove DataFiles

Resources/Storage/OccupancyPlugins/WLCGAccountingHTTPJson.py, Resources/Storage/OccupancyPlugins/WLCGAccountingJson.py, docs/source/AdministratorGuide/Resources/storage.rst
This allows to fetch the space report accounting generated natively by the new DPM (so based on HTTP)
*Resources
NEW: WLCGAccountingHTTPJson plugin
=> [v7r0] DMS: add WLCGAccountingHTTPJson occupancy plugin

Core/Security/ProxyInfo.py, FrameworkSystem/DB/ProxyDB.py, Resources/ProxyProvider/DIRACCAProxyProvider.py, Resources/ProxyProvider/PUSPProxyProvider.py, Resources/ProxyProvider/ProxyProvider.py, Resources/ProxyProvider/test/Test_DIRACCAProxyProvider.py, tests/Integration/Framework/Test_ProxyDB.py, tests/Integration/Resources/ProxyProvider/Test_DIRACCAProxyProvider.py
This PR add debug and test about problem with VOMS proxy creation with this tests utilits, add new method to DIRACCA that try to create a fake proxy for tests.
*ProxyDB
FIX: add new test, debug, correct proxyProvider.getProxy argument
*Resources/DIRACCA
NEW: add method to do fake proxy, needed for tests, add tests for DIRACCA
*Core
FIX: add exception to ProxyInfo
=> [v7r1] Fix proxyDB test

RequestManagementSystem/Client/ReqClient.py, TransformationSystem/Client/TransformationClient.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py
*WMS
FIX: When the job status was updated from a failover request, the job status was by mistake set to `Running` when the job was initially `Stalled`. This was however not visible in the job logging info that was correct.
This is fixed in the `JobStateUpdateHandler`.
*RMS
When finalising the request, one should take into account the fact that if the job is `Stalled` one must find its previous status. This is fixed in `ReqClient`
=> [v7r1] Fix handling of job status when changed by requests

WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py, WorkloadManagementSystem/JobWrapper/JobWrapperTemplate.py, WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py
*Subsystem
FIX: JobWrapper: try to send the failover requests BEFORE declaring the job status
FIX: JobAgent: do not override the job status after the job has finished
=> [v7r1] JobWrapper and JobAgent: fixes for setting of the job status

Core/DISET/private/Transports/BaseTransport.py, Core/Utilities/MixedEncode.py, Core/Utilities/test/Test_Encode.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/technologyPreviews.rst
This PR introduces the necessary code and tools to do the transition to JSON serialization. 
Basically, instead of doing 4 releases (i.e. transition of about 40 months), we control the changes with environment variable. Of course, this needs that all the JSON tasks that are still opened are addressed.
*Core
NEW: Allows for json serialization transition
=> [v7r1] Allows the transition to JSON serialization to start

Core/scripts/dirac-create-distribution-tarball.py, environment.yml, requirements.txt
It's useless, not python3 compatible, and some dependency are breaking DIRACOS.
*Core
CHANGE: remove rst2pdf from dirac-create-distribution-tarball
=> [v7r0]Remove rst2pdf from dirac-create-distribution-tarball

.github/workflows/basic.yml, Core/DISET/private/Transports/SSLTransport.py, Core/Security/__init__.py, Core/Security/test/Test_pygsiToM2Crypto.py, docs/diracdoctools/environmentSetup.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/technologyPreviews.rst
First part of https://github.com/DIRACGrid/DIRAC/issues/4272
*Core
CHANGE:  use M2Crypto by default
=> [v7r1] Make M2Crypto the default over pyGSI

Core/DISET/private/Transports/BaseTransport.py
In the `setExtraCredentials` method the value of the `group` argument besides the group it can be a tuple with the user DN and the group. 
*Core
FIX: rename setExtraCredentials methods argument, docs
=> [v7r1] BaseTransport: group -> extraCredentials

Resources/ProxyProvider/ProxyProviderFactory.py, Resources/ProxyProvider/test/Test_ProxyProviderFactory.py
This PR provide the unittest for `ProxyProviderFactory`.
*Resources
NEW: add Test_ProxyProviderFactory, docs
=> [v7r1] ProxyProviderFactory unittest

ConfigurationSystem/Client/Helpers/Registry.py, docs/source/AdministratorGuide/Configuration/ConfReference/Registry/Users/index.rst, tests/Integration/Framework/Test_ProxyDB.py
This PR provides a description of the DN properties that can be set in the `Registry/Users` subsection. A `DN` attribute has also been added for greater readability.
*Configuration
CHANGE: change search DN properties logic
*docs
NEW: add DNProperties description to Registry/Users subsection
*tests
FIX: align ProxyDB test to current changes
=> [v7r1] DN properties

WorkloadManagementSystem/Client/JobStatus.py
I cherry-picked the commit from #4552 and added comments for the constants so they show up in the sphinx documentation, this page is pretty empty at the moment
https://dirac.readthedocs.io/en/rel-v7r1/CodeDocumentation/WorkloadManagementSystem/Client/JobStatus.html
*WMS
CHANGE: Add Deleted and Killed to JOB_STATES list
=> [v7r1] JobStates and docs

.github/workflows/integration.yml, tests/CI/docker-compose.yml
The CI started failing as elastic search stops accepting more data once disk usage is at 95%. For some reason the amount of available disk space has been decreasing recently causing this to now happen (https://github.com/actions/virtual-environments/issues/709).
I've also added a stage for showing the logs from elasticsearch to make problems easier to debug in future.
=> Fix CI tests

.github/workflows/basic.yml, tests/.pylintrc3k, tests/py3Check.sh
*tests
NEW: Add full pylint py3k test for selected directories
If you want a folder to be checked for all possible python3 compatibility warnings please add it to `tests/py3CheckDirs.txt`(currently none set ) and execute `tests/py3Check.sh`. Unicode warnings are disabled as it is a separate topic.
=> [v7r2] Extensive py3 check for selected directories

TransformationSystem/Client/TransformationClient.py
*TS
FIX:  as the service was accepting the conditions `'LFN'`as a string, allow this on the client side... It was working before but after the recent fix it was no longer working (due to the `sorted()`)... This doesn't seem to pose any problem with the LHCb system as all calls apparently use a list, but this is an additional safety in case other VOs don't...
=> [v6r22] Accept single LFN in getTransformationFiles()

FrameworkSystem/private/monitoring/MonitoringCatalog.py, Resources/Storage/OccupancyPlugins/WLCGAccountingHTTPJson.py
*Framework
FIX: MonitoringCatalog only prints an error when there is really one
=> [v7r0] Framework/Monitoring: print error only when there really is one

.readthedocs.yml, AccountingSystem/Service/DataStoreHandler.py, docs/diracdoctools/Config.py, docs/diracdoctools/CustomizedDocs/CustomTransformation.py, docs/diracdoctools/Utilities.py, docs/diracdoctools/cmd/codeReference.py, docs/diracdoctools/cmd/concatcfg.py, docs/diracdoctools/environmentSetup.py, docs/diracdoctools/fakeEnvironment.py, docs/requirements.txt, docs/requirements_py3.txt
I ran pylint3k, and then with python3 on readthedocs to see if it works.
After a bit more tweaking:
With these changes one could use either python3 and python2 to build the dirac documentation.
Of course for python3, code documentation and command reference are severely limited because `import DIRAC` is not possible at the moment.
And since `import DIRAC` actually calls `sys.exit`, without commenting that line one cannot even get any documentation build. Temporarily removed the line and added the necessary try/except blocks.
*Docs:
NEW: the DiracDocTools are now also compatible with python3
NEW: added ".readthedocs.yml" config
=> [v7r0] make diracdoctools python3 compatible

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, dirac.cfg, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
Currently, the pilot3 files are downloaded wherever the `cwd` of the ConfigurationServer is. This allows to specify `workDir` in the configuration. Default behaviour remains the same
@fstagni I've added some of the options in the `dirac.cfg`, but it's probably far from complete. Can you please check ? 
This was tested on the LHCb certification instance
*WMS
NEW: add a workDir to PilotCStoJSONSynchronizer
=> [v7r0] WMS: PilotCStoJSONSynchronizer uses a workDirectory

.github/workflows/basic.yml, .github/workflows/diracinstall.yml, .github/workflows/fail-fast.sh, .github/workflows/integration.yml, .github/workflows/pilotWrapper.yml
As pull requests tend to be merged in batches it's easy to overload the CI. This PR adds a step to check if the current pipeline is running against an outdated commit. If this is the case, it fails early rather than wasting CI resources.
It might be useful to run this script between each stage of the integration tests but I'll only do that if it continues to be a problem.
=> [v7r0] Fail-fast for pipelines running against outdated commits

Resources/Computing/HTCondorCEComputingElement.py
Every pilots outputs, errors and logs from HTCondor are stored in a specific directory: `workingDirectory`.
To avoid to get too many files stored in this directory, files are regularly deleted.
The number of days we want to keep these files in configurable in each CE section. 
However in reality, as the `workingDirectory` is the same for every CE, each of them is able to delete the pilots files of other CEs which can create issues to retrieve the pilot outputs:
```
WorkloadManagement/SiteDirector INFO: Retrieving output for pilot htcondorce://ce/1234.56
WorkloadManagement/SiteDirector ERROR: Failed to get pilot output ce: Failed to find condor job 1234.56
``` 
Since `v7r0`, the pilot files of a same CE are stored in `workinDirectory/<ceName>`. Thus, a given CE has the possibility to only …
=> [v7r0] Fix HTCondor cleanup

DataManagementSystem/scripts/dirac-dms-protocol-matrix.py, Resources/Computing/HTCondorCEComputingElement.py, Resources/Computing/test/Test_HTCondorCEComputingElement.py
*DMS
FIX: allow dirac-dms-protocol-matrix be run for non LHCb VOs
*WMS
FIX: Fix exception when calling HTCondorCE killJob, used when killing pilots with dirac-admin-kill-pilot for example. Fixes #4590 
=> [v7r0] Fixes for DMS Matrix, HTCondorCE.killJob

.github/workflows/basic.yml, Core/DISET/private/Transports/M2SSLTransport.py, Core/DISET/private/Transports/SSL/M2Utils.py, Core/Security/m2crypto/X509Chain.py, docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/technologyPreviews.rst, tests/CI/run_docker_setup.sh
TLDR;
=====
Based on hotfixes in LHCb. It works.
More details
=========
When enabling M2Crypto in production, some heavily loaded services were basically blocked. I tracked this down to two issues:
* when retrieving the remote credentials, I was doing several `Registry` lookup to have more info about the peer. This is useless, so disabled that in 852d25aa7922485275444d675d7010bd280a1473 and 810971ee6945ef77702ef71597eb8f387c48bd42
* The SSL handshake was done in the `ServiceReactor` thread (the main one) and only the actual work was delegated to a task thread. This lead to the socket backlog being filled rapidly. Funnily enough, on the tests I've done, it turns out to be faster this way, but probably isn't sustainable at big scale. So I've changed that and now do the SSL handshake in the …
=> [v7r0] M2Crypto various fixes

WorkloadManagementSystem/Executor/InputData.py, WorkloadManagementSystem/Executor/test/Test_Executor.py
The idea is to fail/reschedule jobs with unavailable InputSandbox. https://github.com/DIRACGrid/DIRAC/pull/4471/files was a first attempt, but it expected the sandbox to be on the same site as the data, which is not guaranteed. 
@fstagni please check carefully. I am not sure how it works though: if the inputSandbox is on a banned SE, it should be rescheduled. But if the file literally does not exist, then the job should be failed. That is true for the InputData as well. And I am not quite sure this is the current behaviour ? 
*WMS
CHANGE: Check LFN InputSandbox separately from InputData
=> [v7r0]InputData resolution: check InputSandbox separately than InputData

Resources/Computing/HTCondorCEComputingElement.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/ConfigTemplate.cfg
+ When the option "GetPilotOutput" of a Site Director agent is enabled, this one tries to get the pilot outputs of the sites it manages, even if they are old.
Old pilot outputs may be completely deleted and may not be retrieved.
Thus, the Site Director endlessly tries to find pilot outputs that don't exist anymore and this operation may take a long time...
To prevent the Site Director continuing to search for an old pilot output that doesn't exist anymore, I just give it a pilot output with the following content: 
"Pilot output is no longer available"
Is this okay? 
I noticed that in `v7r0` but I think this is older than that, which version should I target?   
+ And a small improvement to retrieve some pilot outputs in HTCondorCEs using the fact that paths to the pilot outputs are now …
=> [v7r0] Add a new SiteDirector option to stop trying to get pilot outputs endlessly

.github/workflows/integration.yml
As the tests have been expanded we've started coming very close to the 30 minute timeout for each job. The majority of the time is spent in the server installation and optimising this would be worthwhile but for now I suggest increasing the timeout.
=> [v7r0] Increase integration tests timeout to 45 minutes

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
*docs
FIX: Use also time in addition to date to get list of PRs since last tag
This is problem in diracos where you can have a pattern of merge tag merge in the same day and this causes problems. In addition the flag `--date` can now take any iso date as input.
=> [v7r0] Use also time in addition to date to get list of PRs since last tag

README.rst
Now that the "stable" branch is v7r1 the links in the README need to be updated
=> [v7r1] Update CI status links in README

.github/workflows/integration.yml, Core/DISET/private/GatewayService.py, Core/DISET/private/MessageBroker.py, Core/DISET/private/Service.py
*Core
CHANGE: Use concurrent.future.ThreadPoolEcecutor by default.
=> [v7r2] use concurrent futures by default

DataManagementSystem/scripts/dirac-dms-remove-catalog-files.py, DataManagementSystem/scripts/dirac-dms-remove-catalog-replicas.py, docs/source/AdministratorGuide/Configuration/ConfReference/Operations/DataManagement/index.rst
CHANGE: 
dirac-dms-remove-catalog-files and dirac-dms-remove-catalog-files introduce an extra check on proxy properties that causes inconsistent behaviour wrt to other DIRAC tools  performing the same tasks when used in a multi-VO setup. 
=> [v6r22] removed easily avoided proxy cross check

Core/DISET/private/Transports/M2SSLTransport.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, docs/source/AdministratorGuide/technologyPreviews.rst
Still based on hotfixes in LHCb on heavily loaded services
*Core
FIX: M2SSLTransport does not catch all the exceptions
FIX: M2SSLTransport calls parent class when renewing context
CHANGE: default to split handshake
=> [v7r0] More fixes for m2crypto

FrameworkSystem/Service/ProxyManagerHandler.py, FrameworkSystem/scripts/dirac-admin-get-proxy.py
This small change should solve the issue [#4608](https://github.com/DIRACGrid/DIRAC/issues/4608)
*Framework
FIX: allow bool type for vomsAttribute parameter on service side
=> [v7r1] fix issue #4608

Core/scripts/dirac-install.py
*Core
FIX: Handle expected HTTP status codes in dirac-install (#4562)
Fixes #4562
=> [integration] Handle all return codes in dirac-install.py

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, dirac.cfg, docs/diracdoctools/scripts/dirac-docs-get-release-notes.py, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
Add an absolute path fix in CS2Json and add the possibility to disable the upload. 
Also a change in the release notes generation (@petricm @andresailer ). If there were no PR merged, the release notes would still generate the header and setter. This is useful for example if you release an extension and just changed the base DIRAC version. 
*WMS
NEW: uploadToWebApp flag to disable the json upload for the CSToJson
FIX: Fix an absolute path in the CSToJSON
*Docs:
CHANGE: allow to generate only header/footer in the release notes if no PR were merged
=> [v7r0] Few fixes for CStoJSON

Resources/Computing/SingularityComputingElement.py
The config file change in pilot3 (from "etc/dirac.cfg" to "pilot.cfg") triggers a bug in the SingularityCE as the new config name is passed through to the JobWrapper, but the version installed in the container still uses the old name. This creates a symlink in the container for compatibility with both (as changing the JobWrapper options correctly in just this case is too complicated). Could be back-ported to older versions if needed.
*Resources
FIX: Add pilot.cfg symlink in SingularityCE for Pilot3 compatibility.
=> [v7r0] Add pilot3 compatibility to SingularityCE

Core/scripts/dirac-install.py
Fixes #4565 
*Core
CHANGE: Create symlinks to `bashrc` when using `versions` directory structure with `dirac-install.py`
=> Symlink bashrc when UseVersionsDir is enabled

.gitignore, FrameworkSystem/Client/ComponentInstaller.py, virtualmachine/Vagrantfile
I also added a Vagrantfile. I use it from time to time and I decided to add it here.
*Framework
FIX: Install of ES DBs: only search in *DB.py files
=> [v7r1] Install of ES DBs: only search in *DB.py files

DataManagementSystem/scripts/dirac-dms-add-file.py
Hi,
dirac-dms-add-file exits silently if the input LFN list is the only argument and is missing. This adds an error message in this case to minimise user confusion.
Regards,
Simon
FIX: Print error from dirac-dms-add-file if input LFN list file is missing.
=> [v6r22] Print error if LFN list is missing

Core/DISET/private/Transports/M2SSLTransport.py, pytest.ini
*Core
FIX: M2Crypto closes the socket after dereferencing the Connection instance
=> [v7r0] Change the closing of socket in M2Crypto

.gitignore, DataManagementSystem/Agent/FTS3Agent.py, RequestManagementSystem/DB/RequestDB.py
*DMS
FIX: Cancel FTS3 Operation if the RMS request does not exist
*RMS
NEW: `getRequestStatus` returns `ENOENT` if the request does not exist
=> [v7r0] Cancel FTS3 Operation if the RMS request does not exist

ConfigurationSystem/Client/CSAPI.py, ConfigurationSystem/Client/Config.py, Interfaces/scripts/dirac-admin-add-host.py
I have been installing a number of servers recently, and one annoyance is that new hosts don't show up in the WebApp SystemAdministrator unless they are in the ComponentMonitoring.
This PR adds the addition of new hosts to the ComponentMonitoring, so they show up immediately.
Plus some tweaks to the documentation for gConfig and CSAPI.
*Interfaces
CHANGE: ``dirac-admin-add-host`` now inserts hosts into the ComponentMonitoring if the host is not yet known
=> [v7r0] dirac-admin-add-host adds host to ComponentMonitoring

FrameworkSystem/Client/ComponentInstaller.py, TransformationSystem/scripts/dirac-transformation-archive.py, TransformationSystem/scripts/dirac-transformation-clean.py, TransformationSystem/scripts/dirac-transformation-remove-output.py, TransformationSystem/scripts/dirac-transformation-verify-outputdata.py
ComponentInstaller: allow underscores in installed components
The previous split would drop things after an underscore in the installed components name (e.g., Bdii2CSAgent_GLUE2), this leads to bad displays and log file displaying in the webapp SystemAdministrator. (Show Errors -> Show Log fails to find log file)
I am not sure if this change affects anyone negatively? Maybe somewhere something other then SystemName_ComponentName would be in the startup directory, where superfluous characters need to be dropped, or they should be ignored?
*Framework
FIX: ComponentInstaller did not allow having underscores in the IntanceNames affecting the WebApp SystemAdministrator log file display via show errors -> show log
*TS
FIX: fix parsing of command line flags (e.g., -ddd) for …
=> [v7r0] transformation scripts command line parsing, Components with underscores

StorageManagementSystem/DB/StorageManagementDB.sql, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
A whole bunch of small fixes. Including the controversial `readonly` variables. I really do not want to spend time debugging it, but as long as we have them, running the jenkins integartion tests are impossible as such. Up to everybody to measure pro/cons of having them readonly
*Tests
FIX: dropDBs uses real array; 
FIX: remove readonly variables
*SMS
FIX: drop the tables in the correct order to avoid foreign key errors
=> [v7r1] Few fixes for the integration tests on jenkins

ConfigurationSystem/Client/Helpers/Registry.py, TransformationSystem/Agent/MCExtensionAgent.py, TransformationSystem/Agent/TaskManagerAgentBase.py, TransformationSystem/Agent/TransformationCleaningAgent.py, TransformationSystem/Agent/TransformationPlugin.py, TransformationSystem/Agent/ValidateOutputDataAgent.py, TransformationSystem/Client/TaskManager.py, TransformationSystem/Client/Transformation.py, TransformationSystem/Client/TransformationCLI.py, TransformationSystem/DB/TransformationDB.py, TransformationSystem/Service/TransformationManagerHandler.py, TransformationSystem/Utilities/TransformationInfo.py, TransformationSystem/test/Test_TransformationInfo.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, virtualmachine/Vagrantfile
Transformation
NEW: TransformationCleaningAgent will (re)clean very old transformations that are still in the system
=> [v7r1] TransformationCleaningAgent will (re)clean very old transformations that are still in the system

ConfigurationSystem/Client/Helpers/Registry.py, DataManagementSystem/Client/FTS3Client.py, DataManagementSystem/Client/S3GatewayClient.py, FrameworkSystem/Client/BundleDeliveryClient.py, FrameworkSystem/Client/ComponentInstaller.py, FrameworkSystem/Client/ProxyManagerClient.py, FrameworkSystem/Client/SystemAdministratorClient.py, FrameworkSystem/Service/ProxyManagerHandler.py, ProductionSystem/Client/ProductionClient.py, StorageManagementSystem/Client/StorageManagerClient.py, TransformationSystem/Client/TransformationClient.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Client/PilotsLoggingClient.py
*Framework
CHANGE: BundleDeliveryClient: inheriting from Client
=> [v7r1] Various minor fixes for FrameworkSystem

ConfigurationSystem/Client/LocalConfiguration.py, docs/source/AdministratorGuide/Configuration/ConfigurationStructure/index.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
We propose this fix in response to user requirements to be able to upload/download/replicate .cfg files using the DIRAC command line tools. We are aware that there is a workaround, but it should just work properly to avoid the issue from resurfacing on a regular basis. 
We are aware that fully removing the non-option parsing of config files will require updates to other parts of the DIRAC code (pilot3). This would go into a later release (v7r4?).
*Configuration
CHANGE: Add --cfg option for config files, deprecating old non-option version.
=> [v7r0] add cfg option to commands to standardize behaviour

Resources/Computing/BatchSystems/TimeLeft/SLURMResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/test/Test_TimeLeft.py
This is a temporary hack, that should help jobs to stop running out of time when multi-processors are allocated in Slurm.
Indeed, CPU and CPULimit values are based on the number of processors allocated.
Thus, a job that doesn't use all the processors has a wrong CPU Time left estimation and runs out of time.
The following PR aims at better fixing this issue: https://github.com/DIRACGrid/DIRAC/pull/4545
*Resources
FIX: hack in Slurm ResourceUsage to stop jobs running out of time on multi-processors resources
=> [v7r0] Hack: jobs running out of time when multi-procs allocated

tests/Integration/DataManagementSystem/Test_UserMetadata.py
Again a case of static LFN breaking integration tests  when not ran in Jenkins/CI setup
*Test
FIX: Test_UserMetadata makes dynamic lfns using VO
=> [v7r1] Test: Test_UserMetadata makes dynamic lfn using vo

DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerDB.py
See this https://github.com/DIRACGrid/DIRAC/issues/4653#issuecomment-658633588 for the problem that is solved with this PR
Targeting v7r1 because of refactoring of FC components, this also affects v6r22 and v7r0
*DMS
FIX: Fix problem where a FileCatalog instance was not aware of SEs added by a different instance. SEManager.getSEName now refreshes if an seID is not known. Fixes #4653
=> [v7r1] SEManager: refresh SEs in getSEName if SE not found

WorkloadManagementSystem/Client/DownloadInputData.py, WorkloadManagementSystem/Client/test/Test_Client_DownloadInputData.py, WorkloadManagementSystem/Client/test/Test_Client_WorkloadManagementSystem.py
This PR contains some simplifications for the DownloadInputData module by using `returnSingleResult`, and some changes in behaviour.
I use a copy of this in iLCDirac. I started on v7r0, but there should be certification for this maybe? I also added unit tests
*WMS
CHANGE: DownloadInputData no longer fails if ``getFileMetadata`` fails for the first SE, tries others if available
=> [v7r1] DownloadInputData improvements

environment.yml
Fixes the M2Crypto installation inside the "basic" CI tests by uploading new build to a `diracgrid` channel on anaconda.org:
https://anaconda.org/diracgrid/m2crypto
This is needed because of DIRAC v7r0 and v7r1 needs to be able to use OpenSSL 1.0.2 which hasn't been supported by conda-forge for a long time. I'm currently writing documentation about how it was generated which will be useful for DIRACOS v2 (I hope we don't use this mechanism very often, but it will be useful to have).
The issue with the pip build is that:
* swig needs to be reran to compile the M2Crypto binaries successfully
* M2Crypto hard codes `/usr/include/openssl` by default
* It's tricky to pass the flag needed to change the base directory of the desired OpenSSL installation
It could be hacked by making the …
=> [v7r0] Fix installation of m2crypto in the CI's conda environment

Resources/Computing/ARCComputingElement.py
This is a WIP as the certification instance is still not properly up and I do not know if the code actually works (my custom printout has not yet triggered). This replaces PR #4658 and PR #4659
*Resources
CHANGE: ArcCE: This is a change to enable GLUE2 queries on ARC CEs, which is now strongly recommended as GLUE1 publishing is stopped in ARC6.
=> [v7r0] Updating the getCEState to be GLUE2 compliant - take 3

Core/Utilities/Glue2.py
resExeInfo is an internal loop variable that shouldn't be used outside of its loop
MANAGER has to be something compatible with the split/rsplit expectations
The result is the second entry in norgugrid-MANAGER-queueName, which is discarded in ARCComputingElement
Supersede #4696 , @fstagni can you try with this patch?
*Core
FIX: Glue2: Fix crash in bdii2CSAgent, when ARC CEs do not have an ExecutionEnvironment
PS: should this go to v7r0?
=> [v7r0] Glue2: fix problem for ARC CEs without execution environments

WorkloadManagementSystem/Utilities/JobParameters.py
In LHCb there has been an issue with a VAC site returning a value from MJF for the number of processors like `\n1\n` and recent changes in the pilot (https://github.com/DIRACGrid/Pilot/pull/110) causes this to be parsed incorrectly. This fixes the problem by making sure the return value of `JobParameters.getNumberOfProcessors` is always an `int`.
FIX: Ensure JobParameters.getNumberOfProcessors always returns an integer
=> [v7r0] Ensure JobParameters.getNumberOfProcessors always returns an integer

.github/workflows/basic.yml
M2CRYPTO is now the sole option in any case
as mentioned here https://github.com/DIRACGrid/DIRAC/pull/4661#discussion_r447114174
@chaen Is it still needed to separate tests for Core/Security ?
=> [integration] CI: (re)remove superfluous tests (M2CRYPTO=Yes)

Core/scripts/dirac-install.py
*Core
CHANGE: Add an example for DIRAC_NO_CFG to bashrc.
=> [integration] added example of DIRAC_NO_CFG into bashrc

WorkloadManagementSystem/Utilities/JobParameters.py
I've been conservative and made sure it still returns `None` but if changing `getProcessorFromMJF` is acceptable it might be preferable for this to be simplified to:
```diff
-  return int(getJobFeatures().get('allocated_cpu'))
+  return int(getJobFeatures().get('allocated_cpu', 0))
```
FIX: Crash getting available memory limits when MJF is not available
=> [v7r0] Fix getting available memory limits when MJF is not available

Resources/Computing/ARCComputingElement.py
In #4666 a `gLogger` was (correctly) used, which when merged into v7r1 would give an exception (as pylint points out) because gLogger was removed at some point in v7r1 from the ARCComputingElement.
Would have been spotted by a merge PR.
*Resources  
FIX: ARCComputingElement: fix use of `gLogger`, which was replaced by `self.log` 
=> [v7r1] ARCCE: gLogger was replaced by self.log

Core/Security/pygsi/X509CRL.py
https://github.com/DIRACGrid/WebAppDIRAC/pull/400 is the correct thing to do, but only works with M2Crypto implementation. I've added an alias for pyGSI implementation. tested working in LHCb
@atsareg @fstagni  in practice, it means the previous release is broken if the WebApp does not use M2Crypto. You may want to advertise it, together with this fix
*Core
NEW: add loadCRLFromFile to pyGSI implementation of X509CRL
=> [v7r0][URGENT] GSI: add loadCRLFromFile alias for loadChainFromFile for X509CRL

FrameworkSystem/Client/ComponentInstaller.py, tests/Integration/WorkloadManagementSystem/Test_TimeLeft.sh, tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Jenkins/dirac_ci.sh, tests/Jenkins/utilities.sh
*Framework
CHANGE: ComponentInstaller uses --cfg
*Tests
CHANGE: uses --cfg
=> [v7r1] ComponentInstaller uses --cfg

Interfaces/API/Dirac.py
The `DIRAC.Interfaces.API.DIRAC.Dirac` class has a `useCertificates=False` argument in the initialiser:
https://github.com/DIRACGrid/DIRAC/blob/50dee195dd30279feb73f92a37f811ed292d97ca/Interfaces/API/Dirac.py#L82-L83
This is passed to the `SandboxStoreClient`:
https://github.com/DIRACGrid/DIRAC/blob/50dee195dd30279feb73f92a37f811ed292d97ca/Interfaces/API/Dirac.py#L1658
but none of the other clients. This PR makes it so that it is also passed to the `WMSClient`.
Without this PR, `Dirac().submitJob` cannot be used when using server certificates for authentication as `WMSClient` has a default value of `useCertificates=False`:
https://github.com/DIRACGrid/DIRAC/blob/50dee195dd30279feb73f92a37f811ed292d97ca/WorkloadManagementSystem/Client/WMSClient.py#L35-L42
which overrides and local settings …
=> [v7r0] Pass useCertificates to WMSClient in Dirac API 

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
The `create release` API has changes a bit: `target_commitish` should be only used when creating a tag from a branch and not when tag is already present then you get an error
```
ERROR - GetReleaseNotes.Requests: Unable to access API: {"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-release"}
```
And it is now recommended to use a the header `application/vnd.github.v3+json` when doing a POST or GET, see [here](
https://docs.github.com/en/rest/reference/repos#list-organization-repositories)
*docs
FIX: update the release notes generator to comply with GitHub API update
Please merge this ASAP
=> [integration] Fix Github API change for creating releases 

Resources/Computing/PoolComputingElement.py, Resources/Computing/SudoComputingElement.py
Changes made in https://github.com/DIRACGrid/DIRAC/pull/4716/commits/1b0bb781113dccdb93ea0c094dc6976622547a6b#diff-6f078601851c19591c520ff380368f56R133 has broken the PoolCE.
By not creating `kwargs` from scratch before passing it to `createAndTaskQueue`, the `ProcessPool` fails to process the task:
```
File "/cvmfs/lhcb.cern.ch/lib/lhcb/LHCBDIRAC/v10r0p12/diracos/usr/lib64/python2.7/multiprocessing/queues.py", line 268, in _feed
send(obj)
TypeError: can't pickle thread.lock objects
```
Indeed, `kwargs` contains a logger object that cannot be serialized.
Thus, I have just restored the original mechanism: creating `kwargs` from scratch before adding the required arguments and passing it to the `ProcessPool`.
I have renamed `kwargs` in `taskKwargs` to …
=> [v7r0] Restore task kwargs in PoolComputingElement.submitJob()

DataManagementSystem/Client/DataManager.py
If there are no LFNs passed `res` can be unset. It looks like it's only there as a relic of the 5 year old commit that changed `getReplicas` to work in chunks of 1000 LFNs (2ef9189b5bfa94fd99fa98f4048f36fc89174996).
* DataManagement
FIX: Allow no LFNs to be passed to `getReplicas`
=> [v7r0] Fix indentation in DataManager.getReplicas

Resources/Computing/ARCComputingElement.py
@VladimirRomanovsky has noticed several pilots labeled `Aborted` by DIRAC while they were still running properly.
This happens when the `Arc.JobSupervisor` is handling a very large number of pilots: the `Update()` command fails because of timeout and returns `Unknown` status for all pilots that are finally labeled `Aborted` by DIRAC.
Thus, this PR just breaks the list of pilots into chunks before passing them to the `Arc.JobSupervisor` to avoid timeouts. 
*Resources
FIX: create chunks before using the Arc.JobSupervisor
=> [v7r0] Create chunks before using JobSupervisor in ArcCE

ResourceStatusSystem/DB/ResourceManagementDB.py, ResourceStatusSystem/DB/ResourceStatusDB.py, tests/Integration/ResourceStatusSystem/Test_ResourceManagement.py, tests/Integration/ResourceStatusSystem/Test_ResourceStatus.py
Add a VO column to Resource Status and Resource Management DB tables. 
*ResourceStatusSystem
CHANGE: add a VO column to all tables as apart of the primary key and a default value='all'
TODO:
=> [v7r1] RSS DB schema change to include a VO column

Core/DISET/private/MessageBroker.py, tests/System/rss-scripts.sh
This MessageBroker is silly because it does not create any error. We just saw that no Optimizer was optimizing
anything
*Tests
FIX: fix rss-scripts syntax
*Core:
FIX: correctly pass the argument to the new ThreadPool in MessageBroker
=> [v7r1]Fix MessageBroker with new threadpool

FrameworkSystem/Client/BundleDeliveryClient.py
In https://github.com/DIRACGrid/DIRAC/pull/4643 various uses of `io.open` where added. In `BundleDeliveryClient` this was incorrect as the written object was still a `str` type instead of `unicode`. The exception is caught by the `except BaseException` and has the effect of causing the CAs and CRLs to be downloaded every time as the `.dab.CAs` and `.dab.CRLs` files are always empty causing the hash to never match with the server version.
As DIRAC isn't going to convert every `str` object to `unicode` before migrating to Python 3 it makes sense to stick to `open()` instead of using `io.open()`.
*Framework
FIX: Fix hashing of local CA and CRL bundles
=> [v7r1] Fix use of io.open in BundleDeliveryClient

Core/scripts/dirac-configure.py, FrameworkSystem/Client/BundleDeliveryClient.py
This PR to implement the proposal from the issue #4734 to to get more readable message in the case described there.
*Core:
FIX: modify logging when CAs & CRLs sync
*Framework:
FIX: add check of availability of directories for sync CAs in BundleDeliveryClient
=> [v7r1] add check of availability of directories for sync CAs

Core/scripts/dirac-install.py
*Core
FIX: dirac-install: use system tar command for extracting tarballs, fixes #4246 
=> [integration] dirac-install: use system tar for extracting tarballs

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
*docs
FIX: make `dirac-docs-get-release-notes.py` python3 compatible
=> make dirac-docs-get-release-notes.py python3 compatible

DataManagementSystem/DB/FTS3DB.py
As discussed in #4727, FTS3Agent.getNonFinishedOperations() should rotate FTS3Operation list by lastUpdate.asc() to cover all operations to fetch.
*DMS
FIX: FTS3Agent: Rotate FTS3Operations list to fetch all 
=> [v6r22] Fetch all non finished FTS3Operation in FTS3Agent

Resources/Storage/GFAL2_XROOTStorage.py
Dots in the virtual username results in
```
bash-4.2$ gfal-stat  root://virtual.with.dot@server.fr//pnfs/myFile.txt
gfal-stat error: 103 (Software caused connection abort) - Failed to stat file (Software caused connection abort)
```
Issue opened against xroot https://github.com/xrootd/xrootd/issues/1283
*Resources
FIX: remove dots in xroot virtual username
=> [v7r0] XRoot: remove dots in virtual user name

Core/Security/VOMSService.py
*Core
FIX: Do not read suspensionReason from VOMS as it's not used anywhere and needs special permissions to give this information
Summary from Andrea Ceccanti
> The problem derives from the changes introduced to meet the CERN GDPR compliance requirements. Now the API returns only limited information to any authenticated user, basically the certificate subject and group and role information. To get all the info you should use a certificate linked to more privileges in VOMS.
>To disseminate this information if you want to go to VOMS admin and then:
> 1. Go to the ACL management panel (by clicking on the acl link)
> 2. Click on "Add entry"
> 3. Choose "Add entry for VO members with a specific role" from the dialog
> 4. Choose the role (e.g., production) …
=> [v7r0] Do not read suspensionReason from VOMS as it's not used anywhere

Core/Utilities/Os.py, WorkloadManagementSystem/JobWrapper/Watchdog.py, WorkloadManagementSystem/JobWrapper/WatchdogLinux.py
So that mountpoints can be cleaned up by automount after a period unused (specific request from CERN batch service).
*WMS
FIX: exclude fuse from df (watchdog checks)
=> [v6r22] exclude fuse from df (watchdog checks)

Resources/Storage/StorageBase.py, Resources/Storage/StorageFactory.py, Resources/Storage/test/Test_StorageFactory.py
Implements https://github.com/DIRACGrid/DIRAC/issues/3516
Also contains https://github.com/DIRACGrid/DIRAC/issues/2790
*Resources
CHANGE: remove backward compatibility for BaseSE defined in StorageElements section (issue 3516)
CHANGE: Clearer error message related to LFN convention (issue #2790)
=> [v7r1] Remove backward compatibility hack of baseSE 

ConfigurationSystem/Agent/Bdii2CSAgent.py, ConfigurationSystem/Agent/test/Test_Bdii2CS.py, ConfigurationSystem/Client/Utilities.py, ConfigurationSystem/ConfigTemplate.cfg, ConfigurationSystem/scripts/dirac-admin-add-resources.py, Core/Utilities/Glue2.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst
I would appreciate feedback on the list of functionality, still need to test this on v7r1. Started with v6r22 for iLCDirac (where it works nicely), but rebased to v7r1 because of changes in the resource information retrieval functions.
*Core
CHANGE: Glue2: the number of ldap searches has been reduced to three making lookups much faster
CHANGE: Glue2: return also unknown sites not found in the information provider for given VO
CHANGE: Glue2: fill value for SI00 for queues as well. Value is fixed at 2500 and will overwrite any existing value. 
CHANGE: Glue2: architecture will now always be lowercase.
CHANGE: Glue2: Read the GLUE2ComputingShareMaxSlotsPerJob value and fill the NumberOfProcessors entry for the respective queue. Ignores CREAM CEs. A Ceiling for this number …
=> [v7r1]Glue2 restructuring (faster mostly), warning on unknown CEs

Interfaces/scripts/dirac-wms-job-parameters.py, TransformationSystem/Client/TaskManagerPlugin.py
*TS
CHANGE: consider all sites when getting sites with storage (not only LCG sites with Tier0, 1 or 2
*WMS
FIX: dirac-wms-job-parameters: output was printed twice
=> [v7r0] Ignore LCG tiers when looking for sites with storage

.github/workflows/diracinstall.yml, .github/workflows/pilotWrapper.yml
Currently the "dirac install" and "pilot wrapper" pipelines run on both the DIRACGrid and fork's CI. This PR copies the line used by the other pipelines for avoiding this.
=> [v7r0] Disable dirac install and pilot wrapper CI on forks

ConfigurationSystem/Agent/Bdii2CSAgent.py, FrameworkSystem/Service/NotificationHandler.py
@fstagni this is currently the hotfix on lbcertifdirac, so the last email you received should only contain "new" cern CEs.
Did you also want to receive notification that there are sites ignored? Because that could result in emails being sent every time.
*CS
FIX: Bdii2CSAgent: Fix exception if selectedSites was set, but some unknown Sites were found by the agent
CHANGE: Bdii2CSAgent: if selectedSites is configured, also remove all CEs from unknown sites from the results
*Framework
CHANGE: NotificationHandler: sendMail: the `avoidSpam` parameter is deprecated. All emails (same subject, address, body) are now only sent once per 24h
=> [v7r1] bdii2csagent purgeSites fix

WorkloadManagementSystem/Service/JobMonitoringHandler.py
The `PilotMonitor/showJobs` feature opens a `JobMonitor` window to see the `CurrentJobID` only.
DIRAC Pilot-Jobs are able to handle multiple jobs: on HPCs, Pilot-Jobs can handle tens of jobs at the same time.
It would be easier to debug issues in the Pilot-Jobs if we would have access to all the jobs bound to a specific Pilot-Job instead of the current one.
This PR includes Pilot-Job references in the `JobMonitoring` web summary.
Change made in the WebApp are available here: https://github.com/DIRACGrid/WebAppDIRAC/pull/405
CHANGE: JobMonitoring.getJobPageSummaryWeb can provide jobIDs according to the pilotJobReferences
=> [v7r1] Fix WebApp/PilotMonitor/showJobs

Resources/Computing/SingularityComputingElement.py
Backports #4773 which accidentally targetted integration
*Resources
FIX: Mount the host's DIRAC installation in the container when using SingularityCE without InstallDIRACInContainer
=> [v7r1] Backport fix mounting the host's DIRAC installation in Singularity CE

Resources/Catalog/FileCatalogClient.py
*Resources
FIX: FileCatalogClient: correctly returning error in getReplicas call
=> [v7r1] Return error if needed

.github/workflows/integration.yml
*tests
FIX: Use GitHub Container registry due to pull limit on dockerhub
=> [v7r0] Use GitHub Container registry due to pull limit on dockerhub

Resources/Computing/SSHComputingElement.py
The job ID contains the name of the CE which can be different from the `SSHHost` parameter. For example we may have the following CE configuration:
```
aldbr.github.fr
{
SSHHost = aldbr32.github.fr
...
}
```
The job ID will contain `aldbr.github.fr`.
Currently, the `SSHComputingElement` extracts the hostname from the job ID to get the job output: `aldbr.github.fr`.
Thus, in some cases, the `SSHComputingElement` is not able to access the remote node to get the job output.
Either we make sure that the name of the CE correspond to `SSHHost`, or we extract the hostname from `SSHHost`.
The second solution is chosen in this PR.
*Resources
FIX: get SSH hostname from the CE config instead of the job ID to get the job output
=> [v7r0] SSHCE: get SSH host from the CE config instead of the jobID to get job output

ConfigurationSystem/Agent/VOMS2CSAgent.py, ConfigurationSystem/Client/SyncPlugins/DummySyncPlugin.py, ConfigurationSystem/Client/VOMS2CSSynchronizer.py, ConfigurationSystem/ConfigTemplate.cfg, tests/Utilities/assertingUtils.py
LHCb use case is to add a CERN primary username into the CS. It will also prevent against typo in nicknames when creating new users in VOMS
I'd have been happy to add even more docs than what is already here, but there does not seem to be a VOMS2CS dedicated part (though it would surely deserve it :-) )
*Configuration
NEW: VOMS2CSAgent introduce SyncPlugins to add extra or validate user information information
=> [v7r1] VOMS2CS: introduce SyncPlugins 

Resources/Computing/ARCComputingElement.py
*Resources
FIX: Initialisation of arc.Endpoint in ARCComputingElement
Fixes the error seen in the hackathon but I think there is no reason not to backport to v7r0:
```
2020-10-29 10:10:12 UTC WorkloadManagement/SiteDirector ERROR: Agent exception while calling method <bound method SiteDirector.execute of <SiteDirector.SiteDirector object at 0x7f243c394e50>>
File "/opt/dirac/pro/DIRAC/Core/Base/AgentModule.py", line 344, in am_secureCall
result = functor(*args)
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 459, in execute
result = self.submitPilots()
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 579, in submitPilots
res = …
```
=> [v7r1] arc.Endpoint doesn't accept unicode in ARCComputingElement

AccountingSystem/Client/Types/DataOperation.py, AccountingSystem/Client/Types/Job.py, AccountingSystem/Client/Types/Network.py, AccountingSystem/Client/Types/Pilot.py, AccountingSystem/Client/Types/PilotSubmission.py, AccountingSystem/Client/Types/StorageOccupancy.py, AccountingSystem/Client/Types/WMSHistory.py, AccountingSystem/private/Plotters/JobPlotter.py, MonitoringSystem/Client/Types/WMSHistory.py, WorkloadManagementSystem/JobWrapper/JobWrapper.py, WorkloadManagementSystem/JobWrapper/Watchdog.py
This should solve (partially) this task: https://github.com/DIRACGrid/DIRAC/issues/1863
*Accounting
CHANGE: multiply wallclock per the number of processors used
=> [v7r1] Job Accounting: multiply wallclock per the number of processors used

.github/workflows/nightly.yml
*tests
FIX: Use GitHub Container registry due to pull limit on dockerhub
=> [Integration] Use GitHub Container registry due to pull limit on dockerhub

ConfigurationSystem/Client/Utilities.py, ConfigurationSystem/scripts/dirac-admin-add-resources.py, Core/Utilities/Glue2.py
use the list of CEs in the CEs section instead
*Configuration
FIX: Bdii2CSAgent: Updating CE information wasn't working because the list of CEs wasn't picked up from the right place (Site/CE option, instead of `Site/CES/<CE_Sections>`)
FIX: Glue2: fix association of CEs to sites if the CE associated sitename in the BDII differs from the Name given in the CS
FIX: dirac-admin-add-resources: Fix bug preventing the use of GLUE2 mode
=> [v7r1] Config.Client.Utilities: fix use of site/CE option

Resources/Computing/SingularityComputingElement.py
Hi,
This fix re-adds a line of code in SingularityCE to create a symlink for pilot.cfg (if installDIRAC mode is used) to fix a bug with dirac-jobexec jobs (they won't run if pilot.cfg is missing). We're not sure why this line was removed in the first place, we couldn't find any issues or e-mails explaining why it was removed, so we think it may just have been an accident (but if anyone does find an issue with it, let me know and I'll investigate further).
Regards,
Simon
*Resources
FIX: SingularityCE: Create pilot.cfg as part of the inner DIRAC install.
=> [v7r1] Add pilot.cfg fix for SingularityCE in install mode

FrameworkSystem/scripts/dirac-admin-update-pilot.py
FIX: pilot update script, update global CS not the local one
=> [v7r0] Fix pilot update script - update global CS not the local

WorkloadManagementSystem/Client/JobReport.py, WorkloadManagementSystem/DB/JobDB.py, WorkloadManagementSystem/DB/JobLoggingDB.py, WorkloadManagementSystem/Service/JobMonitoringHandler.py, WorkloadManagementSystem/Service/JobStateUpdateHandler.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py
FIX: There was a bug handling the bulk status updates that was not updating correctly the job status although the job logging information was correct). This PR fixes this bug. It was tested in certification as a hotfix
CHANGE: internally always call the `setJobStatusBulk()` method in order to be consistent
CHANGE: in `JobReport`, only send statuses that are not empty, and remove handling of `ApplicationCounter` that is never sent nor used anywhere
=> [v7r1] Fix jobStatusBulk

ConfigurationSystem/Agent/Bdii2CSAgent.py, FrameworkSystem/Service/NotificationHandler.py, docs/source/AdministratorGuide/Systems/Framework/Notification/index.rst
These commits were meant to be part of #4766 but apparently I forgot to push them 😭 
*Framework
CHANGE: NotificationHandler: sendMail: the avoidSpam parameter is deprecated. All emails (same subject, address, body) are now only sent once per 24h
=> [v7r1] notificationHandler avoidSpam unification

Resources/Computing/SingularityComputingElement.py
`SingularityComputingElement.__findInstallBaseDir` was missing a `os.path.dirname` causing it to try to source `/path/to/bashrc/bashrc`.
@fstagni This fixes the issue seen in the last LHCbDIRAC hackathon. I've already applied it on CVMFS to test that it now works properly (at least for a basic job).
*Resources
FIX: Fix using SingularityComputingElement with the host's DIRAC installation
=> [v7r1] Fix SingularityComputingElement.__findInstallBaseDir

Core/DISET/private/Transports/SSL/M2Utils.py
*Core
CHANGE: TLS: read proxy flag from M2Crypto.X509
=> [v7r1] TLS: read proxy flag from M2Crypto.X509

Core/Utilities/Graphs/GraphUtilities.py, MonitoringSystem/DB/MonitoringDB.py
**I am not sure if this is correct!!!**
When adding `from __future__ import division` to LHCbDIRAC I found noticed some suspicious divisions in vanilla DIRAC. It's possible these are supposed to return floats but I suspect the integer division was intentional and was broken by #4586. Can someone who familiar with the code take a look and check?
*Monitoring
FIX: Correct the rounding of integers when computing buckets in MonitoringDB
=> [v7r2] Explicitly cast some values to integers

ConfigurationSystem/Client/SyncPlugins/CERNLDAPSyncPlugin.py
This field is a list of 1 item so it should be stored as a string rather than a list.
=> [v7r1] Fix typo in CERNLDAPSyncPlugin

ConfigurationSystem/Client/LocalConfiguration.py, Core/scripts/dirac-install.py, docs/source/AdministratorGuide/Configuration/ConfigurationStructure/index.rst, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
*Subsystem
CHANGE: Added possibility to load more then one cfg file from DIRACSYSCONFIGFILE env variable
=> [v7r0] load more than one DIRACSYSCONFIGFILE

.github/workflows/basic-python3.yml, src/DIRAC/Core/Security/m2crypto/X509Request.py
Renable the test disabled here https://github.com/DIRACGrid/DIRAC/pull/4858
The real problem was a incorrect test in the code, exposed by a change of behaviour of openssl. 
*Core
FIX: Correct comparison of public key for X509Request
For the curious (and my memory in the future), details here
```python
import M2Crypto
import six
IS_OPENSSL_1_1_1 = six.PY3
rsa = M2Crypto.RSA.gen_key(1024, 65537, callback=M2Crypto.util.quiet_genparam_callback)
pkeyObj = M2Crypto.EVP.PKey()
pkeyObj.assign_rsa(rsa)
reqObj = M2Crypto.X509.Request()
reqObj.set_pubkey(pkeyObj) 
reqObj.sign(pkeyObj, "sha256")
assert reqObj.verify(pkeyObj)
reqStr = reqObj.as_pem()
reqObj2 = M2Crypto.X509.load_request_string(reqStr, format=M2Crypto.X509.FORMAT_PEM)
print("pkeyObj.as_pem") …
```
=> [v7r2] X509Request: correct comparison of public keys

docs/diracdoctools/Utilities.py, docs/source/conf.py
Some small tweaks to fix the build on read the docs following #4858 
Make compatible with other packages
https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/blob/master/docs/source/conf.py#L74
*Docs
NEW: diracdoctools.setUpReadTheDocsEnvironment: new parameter location to refer to the relative location of the source code of the given moduleName
=> [int] Docs: RTD: fix path to DIRAC source code

ResourceStatusSystem/Agent/ElementInspectorAgent.py, ResourceStatusSystem/Agent/SiteInspectorAgent.py
Prevent the SIA from getting blocked
If an exception in `enforce` occurs "Task_Done()" wasn't called, which prevented `join` from continuing.
*RSS
FIX: SiteInspectorAgent: prevent the agent from getting locked if an exception occurs during enforcement
FIX: ElementInspectorAgent: prevent the agent from getting locked if an exception occurs during enforcement
=> [v7r0] RSS: catch all exception in _execute in SiteInspectorAgent

WorkloadManagementSystem/JobWrapper/JobWrapper.py, WorkloadManagementSystem/Utilities/Utils.py
*WMS
CHANGE: JobWrapper: Add extraOptions only when the executable is a DIRAC script
=> [v7r0] Add extraOptions only when the executable is a DIRAC script

Core/Security/Locations.py, Core/scripts/dirac-install.py, DataManagementSystem/Client/FTS3Job.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
@petricm this is what you should do for `X509_VOMSES` too
The 2 new environment variables allow to specify a location for the host certificate and key, that takes precedence over the CS locations. This is in line with what is done for the other `X509_*` variables
*Core
CHANGE: default generated bashrc does not overwrite `X509*` variables if already set
NEW: Add ``DIRAC_X509_HOST_CERT`` and ``DIRAC_X509_HOST_KEY`` environment variables
=> [v7r0] bashrc: X509 variables are left untouched if already set

src/DIRAC/ConfigurationSystem/private/Refresher.py, src/DIRAC/ConfigurationSystem/private/RefresherBase.py, src/DIRAC/ConfigurationSystem/private/TornadoRefresher.py
*Configuration
CHANGE: split standard and tornado refresher in two files to avoid tornado dependency on the client
=> [v7r2] Refresher: import tornado modules only if needed

__init__.py
This isn't strictly needed but I think it will make the conflicts with #4865 easier to handle.
=> [v7r0] Modify __init__.py to avoid conflicts with rel-v7r2

WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, WorkloadManagementSystem/Utilities/test/Test_PilotCStoJSONSynchronizer.py
closes https://github.com/DIRACGrid/DIRAC/issues/4612
*WMS
FIX: added timestamp to pilot.json
=> [v7r1] added timestamp to pilot.json

src/DIRAC/Core/DISET/private/Service.py, src/DIRAC/RequestManagementSystem/Agent/RequestExecutingAgent.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg
The REA was using the `ActivityMonitoring` flag to enable ES monitoring, so I changed that.
*Core
FIX: fix exception in Services when trying to use uninitialized gMonitor client while targeting ES monitoring
*RMS
CHANGE: use dedicated ES monitoring flag `RMSMonitoring`
=> [v7r2] RMS: correct settings for RMS monitoring

src/DIRAC/Core/Utilities/ExecutorDispatcher.py
Fixes this exception
```
2021-01-20 15:52:11 UTC WorkloadManagement/OptimizationMind ERROR: Exception while calling initialization function
File "/opt/dirac/pro/DIRAC/Core/DISET/private/Service.py", line 159, in initialize
result = initFunc(dict(self._serviceInfoDict))
File "/opt/dirac/pro/DIRAC/Core/Base/ExecutorMindHandler.py", line 71, in initializeHandler
cls.__eDispatch = ExecutorDispatcher(cls.srv_getMonitor())
File "/opt/dirac/pro/DIRAC/Core/Utilities/ExecutorDispatcher.py", line 317, in __init__
self.__monitor.registerActivity("executors", "Executor reactors connected",
AttributeError: 'MonitoringReporter' object has no attribute 'registerActivity'
```
This PR just disable the monitoring for the new ES based system, but it should be implemented …
=> [v7r2] Fix incorrect call for new Monitoring in ExecutorDispatcher

src/DIRAC/Core/Tornado/scripts/tornado_start_all.py, src/DIRAC/Core/scripts/dirac-agent.py, src/DIRAC/Core/scripts/dirac-executor.py, src/DIRAC/Core/scripts/dirac-service.py
A couple of left over review comments from #4865 from @andresailer
=> [v7r2] Remaining review comments from #4865

src/DIRAC/FrameworkSystem/scripts/dirac_install_component.py, src/DIRAC/FrameworkSystem/scripts/dirac_install_tornado_service.py, src/DIRAC/FrameworkSystem/scripts/dirac_uninstall_component.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_sync.py
When refactoring the scripts for setuptools I made a few mistakes which cause the global DIRAC state to be broken slightly for the scripts. This doesn't affect installations using the current `dirac-install.py` script (hence why it was missed). This just fixes it in a similar way to the other refactoring in #4774.
Also picks up #4913 as the CI is broken without it.
=> [v7r2] Fix global state issues setuptools scripts

Core/Utilities/Glue2.py
cesDict content was overwritten, and not deepmerged
*Core
FIX:  Glue2: fix problem for CEs with multiple Queues, only one queue was discovered
=> [v7r1] Glue2: fix problem for sites with multiple queues

WorkloadManagementSystem/Agent/StalledJobAgent.py
*WMS
FIX: The StalledJobAgent's behaviour changed (for bad) as only jobs stalled for more than 24.5 hours were checked before being set Failed... Restore v7r0 behaviour with immediate check
=> [v7r1] Fix StalledJobAgent

ConfigurationSystem/Client/Utilities.py, ConfigurationSystem/test/Test_agentOptions.py, Core/Utilities/ElasticSearchDB.py, Core/scripts/dirac-cert-convert.sh, WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Agent/test/Test_Agent_SiteDirector.py, WorkloadManagementSystem/ConfigTemplate.cfg, WorkloadManagementSystem/JobWrapper/Watchdog.py, WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py, WorkloadManagementSystem/Utilities/QueueUtilities.py, docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Sites/index.rst
*Configuration
CHANGE: Adding Pool as LocalCEType for MultiProcessor queues (invoked by BDII2CSAgent)
*WMS
CHANGE: JobAgent: getting CEType only from LocalSite/LocalCE config
CHANGE: JobAgent: flipped the default for fillingMode
CHANGE: SiteDirector: The max number of jobs in filling mode is not set anymore by the SD. The option MaxJobsInFillMode  was removed
*Core
FIX: ElasticSearchDB: fix exception handling when checking existence of indices
=> [v7r1] fixes for MultiProcessor queues

FrameworkSystem/private/standardLogging/Logging.py
I know nothing about why but they're removed in v7r2 so they should probably be marked as deprecated to make them easier to spot.
*Framework
CHANGE: initialized, processMessage and flushAllMessages functions of Logging are deprecated
=> [v7r1] Add deprecated decorators to standard logging

Resources/Computing/InProcessComputingElement.py, Resources/Computing/SingularityComputingElement.py
Fixes this issue seen in LHCb pilots:
```log
2021-01-29 03:33:39 UTC WorkloadManagement/JobAgent ERROR: Exception while executing scheduled task
File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r1p1/DIRAC/Core/Utilities/ThreadScheduler.py", line 188, in __executeTask
task['func'](*task['args'])
TypeError: _monitorProxy() takes at most 2 arguments (15 given)
```
*Resources
FIX:  Fix calling _monitorProxy as a periodic task 
=> [v7r1] Fix calling _monitorProxy as a periodic task

.github/workflows/basic-python3.yml, .github/workflows/basic.yml, pytest.ini, src/DIRAC/Core/Security/m2crypto/X509Request.py, src/DIRAC/Core/Security/test/Test_X509Chain.py, src/DIRAC/Core/Security/test/Test_X509Request.py, src/DIRAC/Core/Security/test/x509TestUtilities.py, src/DIRAC/Core/Utilities/test/Test_Encode.py, src/DIRAC/Core/Utilities/test/Test_ProcessPool.py, src/DIRAC/Core/Utilities/test/Test_Profiler.py, src/DIRAC/Core/Utilities/test/Test_Subprocess.py, src/DIRAC/Resources/Computing/test/Test_InProcessComputingElement.py, src/DIRAC/Resources/Computing/test/Test_PoolComputingElement.py, src/DIRAC/Resources/ProxyProvider/test/Test_DIRACCAProxyProvider.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py, tests/conftest.py
See https://docs.pytest.org/en/stable/example/simple.html#control-skipping-of-tests-according-to-command-line-option for details about what is being done. The `--runslow` flag is passed in the CI so we still ensure that the tests are passing without being burdened by them locally.
I merge all the unit tests together in to a single job now that they can be. Also enables the `Test_X509Request.py` which was accidentally misnamed (and fixed a couple of associated Python 3 incompatibilities. cc @chaen for review
*Testing
NEW: --runslow option on unit tests to allow faster local tests
=> [v7r2] Skip slow unit tests by default

environment-py3.yml, pyproject.toml
Also adds `make` to the Python 3 environment.yaml file to avoid issues building the docs in very lightweight docker containers.
=> [v7r2] Prevent setuptools_scm from trying to use old style version tags

Core/Security/VOMSService.py
*CS
FIX: Fix exception in VOMS2CSAgent for missing 'suspended' and other entries occurring if the credentials used to query the VOMS server have insufficient privileges to obtain this information
=> [v7r0] VOMS: protect against missing entries in dict

ConfigurationSystem/Client/Utilities.py
If there is no `/` in the string then an IndexError exeption comes up. @fstagni can there be a ValueError here as well?
*CS
FIX:  CS.Client.Utilities: change exception caught to IndexError
=> [v7r1] CS.Client.Utilities: change exception caught to IndexError

Core/scripts/dirac-install.py, src/DIRAC/Core/scripts/dirac-install.py
*Core
CHANGE: Rename DIRAC_VOMSES to X509_VOMSES in dirac-install.py
=> [v7r2] Rename variable for default location of vomses

Core/DISET/__init__.py, Core/DISET/private/Transports/M2SSLTransport.py, Core/DISET/private/Transports/SSL/M2Utils.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
*Core
NEW: introduce DIRAC_M2CRYPTO_SSL_METHODS to configure accepted protocols
NEW: introduce DIRAC_M2CRYPTO_SSL_CIPHERS to configure accepted ciphers
=> [v7r0] Allow to change SSL methods and ciphers with M2Crypto

Core/scripts/dirac-install-extension.py, Core/scripts/dirac-platform.py, Core/scripts/dirac-version.py, WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py
This fixes a minor compatibility issue with the way the DIRAC pilot invokes the dirac-platform script (seen in https://jenkins-dirac.web.cern.ch/view/DIRAC/job/Pilot3_CVM4_pipeline/106/console which might be a problem for VMDIRAC)
*Core
CHANGE: using argparse for a few scripts instead of getopt
=> [v7r1] Some fixes for scripts

FrameworkSystem/Client/ProxyManagerClient.py, FrameworkSystem/DB/ProxyDB.py, FrameworkSystem/scripts/dirac-proxy-init.py, docs/source/AdministratorGuide/Tutorials/managingIdentities.rst, tests/Integration/Framework/Test_Proxy.sh, tests/Jenkins/utilities.sh
The change for `dirac-proxy-init` is needed because before, groups that would have the `AutoUploadProxy=True` set in the CS were automatically uploaded. This check is not here anymore, and do not make so much sense. The net result is that some users could 
- create a proxy
- Create jobs
- Jobs will be rescheduled because no proxy uploaded (I remind you about that, if one wants to reconsider https://github.com/DIRACGrid/DIRAC/pull/4558 )
So this PR changes the default, and always upload a proxy, unless `--no-upload` is specified
The other change is for backward compatibility purpose, as long as we are going to have proxies with groups in the DB. 
*Framework
CHANGE: dirac-proxy-init always uploads the proxy unless --no-upload is specified
FIX: ProxyManagerClient checks for …
=> [v7r1]  Backward compatibility fix for group less proxy

Resources/Computing/BatchSystems/TimeLeft/SLURMResourceUsage.py, WorkloadManagementSystem/Agent/JobAgent.py
This PR pushes the "filling mode" (more than 1 job/pilot) by always resorting to calculate the time left with the info in our possession. Basically, if we can't get such info from the batch system, we use just `os.times()` and what we know. This should improve the situation for the case of e.g. Condor.
*WMS
CHANGE: resorting to calculate time left with info in possession
=> [v7r1] resorting to calculate time left with info in possession

Core/scripts/dirac-install.py, src/DIRAC/Core/scripts/dirac-install.py
Because of these multiplications of dirac-install, they have diverged, and changes were lost. 
This bring them back, and align the two versions of this repo.
*Core
FIX: re-align dirac-install(s).py
=> [Please merge now] [v7r2]Core:re-align dirac-install(s).py

ConfigurationSystem/Client/Helpers/Resources.py
*CS
FIX: The loop in the siteCE mapping was exiting as soon as a mis-configured site was found. This for instance had some dide effect, like preventing the SiteDirector for ARC sites to read the configuration of correctly configured CEs. Fixed to continue the loop, while adding an error message.
=> [v7r1] Fix in loop of SiteCEMapping CS helper

ConfigurationSystem/Client/Utilities.py
Fix bug:
```
File "/vo/dirac/pro/DIRAC/ConfigurationSystem/Client/Utilities.py", line 346, in getSiteUpdates
changeSet.add(queueSection, 'Tag', tag, newTag)
TypeError: add() takes exactly one argument (4 given)
```
*Configuration
FIX: use tuple instead 4 arguments
=> [v7r1] fix bug ConfigurationSystem/Utilities

Resources/Computing/BatchSystems/TimeLeft/HTCondorResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/LSFResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/MJFResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/PBSResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/ResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/SGEResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/SLURMResourceUsage.py, Resources/Computing/BatchSystems/TimeLeft/TimeLeft.py, Resources/Computing/BatchSystems/TimeLeft/test/Test_TimeLeft.py, Resources/Computing/HTCondorCEComputingElement.py, WorkloadManagementSystem/Agent/JobAgent.py, WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py, docs/source/AdministratorGuide/Resources/computingelements.rst
closes https://github.com/DIRACGrid/DIRAC/issues/4788
- Add a condition in `TimeLeft.getTimeLeft()` to know whether a Batch System relies on wallclock time and/or cpu time for allocated resources (e.g. Slurm and CERN-HTCondor only rely on wallclock time). This also reverts the change made on the `SlurmResourceUsage` plugin introduced in https://github.com/DIRACGrid/DIRAC/pull/4965#pullrequestreview-591048491
- Modify the cpu work left computation in `JobAgent` when the batch system cannot provide (relevant) information: `timeLeft` decreases linearly instead of decreasing exponentially.
- Add a `HTCondorResourceUsage` plugin: which is actually a CERN-specific HTCondor Resource Usage module to get the time left in CERN-HTCondor resources. To modify the wallclock time limit of the …
=> [v7r1] TimeLeft and JobAgent changes

setup.cfg
As it's causing a nuisance and the client mostly works without it I propose removing it from the setuptools metadata for now.
Should be reverted once https://github.com/DIRACGrid/DIRACOS2/issues/10 is resolved.
=> [v7r2] Remove fts3-rest from the setuptools configuration for now

src/DIRAC/Core/DISET/private/BaseClient.py, src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py
PR fix log message and resolve problem with unicode:
```
File "/opt/dirac/cli/DIRAC/Core/DISET/private/BaseClient.py", line 471, in _connect
retVal = transport.initAsClient()
File "/opt/dirac/cli/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 145, in initAsClient
self.oSocket.set_tlsext_host_name(host)
File "/opt/dirac/cli/diracos/usr/lib64/python2.7/site-packages/M2Crypto/SSL/Connection.py", line 708, in set_tlsext_host_name
m2.ssl_set_tlsext_host_name(self.ssl, name)
TypeError: in method 'ssl_set_tlsext_host_name', argument 2 of type 'char const *'
```
*Core
FIX: encode serviceName
*Framework
FIX: fix log message about responded hosts in sysadmin cli
=> [v7r2] fix dirac-admin-sysadmin-cli

.github/workflows/integration.yml, docs/source/UserGuide/Tutorials/JobManagementAdvanced/index.rst, setup.cfg, src/DIRAC/Core/scripts/dirac_platform.py, src/DIRAC/Core/scripts/dirac_version.py, src/DIRAC/Interfaces/API/Job.py, src/DIRAC/Interfaces/API/test/Test_DIRAC.py, src/DIRAC/Interfaces/API/test/testWF.jdl, src/DIRAC/Interfaces/API/test/testWFSIO.jdl, src/DIRAC/TransformationSystem/test/Test_JobInfo.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, tests/CI/run_docker_setup.sh, tests/CI/run_tests.sh, tests/Integration/WorkloadManagementSystem/Test_JobDB.py, tests/Integration/WorkloadManagementSystem/Test_JobWrapper.py, tests/Integration/WorkloadManagementSystem/Test_TimeLeft.sh, tests/Integration/WorkloadManagementSystem/Test_dirac-jobexec.sh, tests/Integration/all_integration_client_tests.sh, tests/Jenkins/utilities.sh
Includes the two already approved PRs as it will be broken without them: #4980 #4975
The main change here is to use DIRACOS2 and `pip install` when running the Python 3 client integration tests (up until now the version from `chrisburr/DIRACOS2` was being used with `dirac-install`).
The only notable change is that use of `$DIRACROOT/scripts/` doesn't really make sense with a Python 3 + pip installation but I think it should be safe to take it from `$PATH` in all situations. Any thoughts?
CHANGE: Take dirac-jobexec from PATH by default
*Python 3
NEW: Run Python 3 integration tests with DIRACOS2 and pip install
=> [v7r2] Use DIRACOS2 for Python 3 client integration tests

WorkloadManagementSystem/JobWrapper/JobWrapper.py
Backport from https://github.com/DIRACGrid/DIRAC/pull/4989/files#r582924573 to improve the compatibility during updates between v7r1 pilots and jobs submitted with v7r2.
NEW: Find executables from PATH if not using an absolute filename
=> [v7r1] Find executables from PATH if not using an absolute filename

Resources/Computing/BatchSystems/TimeLeft/HTCondorResourceUsage.py
Just a small fix to the `HTCondorResourceUsage` module that we've just introduced.
The module is not able to get `$_CONDOR_JOB_AD` and is, thus, inefficient.
*Resources
FIX: Getting access to $_CONDOR_JOB_AD in HTCondorResourceUsage
=> [v7r1] HTCondorResourceUsage: fix the access to $_CONDOR_JOB_AD

docs/source/AdministratorGuide/ExternalsSupport/index.rst, docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst, docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst, docs/source/AdministratorGuide/index.rst
closes #4940 
I also added a note with a link to the DIRAC puppet modules that are used at CERN by LHCb and CLIC. Honestly those info should be expanded but I don't have enough knowledge for doing it @andresailer @chaen 
*Docs
FIX: added explanation on connecting to ES using certificates
=> [v7r1] Added docs for connection to ES

WorkloadManagementSystem/JobWrapper/JobWrapper.py
*WMS
FIX: As the job status is set AFTER the request is uploaded, it may happen that the request is executed BEFORE the status is set... Add thus a delay of 2 minutes for execution
=> [v7r1] Add a 2 mn delay to failover request execution

docs/diracdoctools/Utilities.py, docs/diracdoctools/cmd/codeReference.py, src/DIRAC/ConfigurationSystem/scripts/dirac_admin_sort_cs_sites.py, src/DIRAC/Core/scripts/dirac_executor.py, src/DIRAC/Core/scripts/dirac_service.py, src/DIRAC/Core/scripts/install_full.cfg, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/FrameworkSystem/Client/ComponentMonitoringClient.py, src/DIRAC/FrameworkSystem/DB/InstalledComponentsDB.py, src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py, src/DIRAC/FrameworkSystem/Utilities/MonitoringUtilities.py, src/DIRAC/FrameworkSystem/private/standardLogging/LogLevels.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Utilities/PilotWrapper.py, tests/Integration/Framework/Test_InstalledComponentsDB.py
*Core
FIX: use logging.warning in favor of deprecated logging.warn
*Framework
CHANGE: renames of column names to avoid reserved keywords
=> [v7r2] renames of column names to avoid reserved keywords

environment-py3.yml, environment.yml, src/DIRAC/FrameworkSystem/Client/ProxyGeneration.py, src/DIRAC/FrameworkSystem/Client/ProxyUpload.py
Extracted from #4997 
*Core
CHANGE: Use prompt-toolkit for password input when generating proxies
=> [v7r2] Use prompt_toolkit for reading passwords

setup.cfg
I'm fairly sure there is no reason for it to be there and it's impossible to install outside of DIRACOS as we need the M2Crypto patches that aren't suitable for conda-forge.
=> [v7r2] Remove tornado from client dependencies

docs/source/DeveloperGuide/TornadoServices/index.rst, src/DIRAC/Core/Tornado/scripts/tornado_start_CS.py
This is to allow to run the master CS together with other services on the same host but different processes
*Configuration
FIX: HTTPS: allow to run master CS in parallel of other tornado services
=> [v7r2] HTTPS: fixes to run master CS

src/DIRAC/ConfigurationSystem/Client/CSCLI.py, src/DIRAC/ConfigurationSystem/Client/CSShellCLI.py
No idea if this is correct but I noticed while preparing https://github.com/DIRACGrid/WebAppDIRAC/pull/439
*Configuration
CHANGE: Use ConfigurationClient in CSCLI and CSShellCLI
=> [v7r2] Use ConfigurationClient in CSCLI and CSShellCLI to fix more HTTPS issues

Core/Utilities/Glue2.py, Core/Utilities/Subprocess.py
*Core
FIX: Glue2: fix error when too many execution environments were looked for
FIX: Subprocess: when the systemCall failed, S_ERROR now contains a string in 'Message' instead of an exception object
=> [v7r1] bdii fix

setup.cfg
Was missed when extracting #5004 from #4997.
*Python 3
FIX: Add prompt-toolkit to setuptools metadata.
=> [7r2] Add prompt-toolkit to setup.cfg

src/DIRAC/Core/Utilities/MySQL.py
I don't think this warrants release notes.
=> [v7r2] MySQLdb.thread_safe() does not exist in mysqlclient, use MySQLdb.threadsafety instead

src/DIRAC/Core/Utilities/ObjectLoader.py
This is following https://github.com/DIRACGrid/DIRAC/pull/4957
*Core
CHANGE: protect ObjectLoader against all exceptions 
=> [v7r2] ObjectLoader: protect against all exceptions instead of just ImportError

DataManagementSystem/Client/FTS3Job.py, DataManagementSystem/scripts/dirac-dms-protocol-matrix.py, RequestManagementSystem/Client/ReqClient.py
@andresailer  dc0b6d3 should please you :-D
@atsareg since this adds some script modification, it may need special attention when you propagate upstream
*DMS
FIX: FTS3 explicitly use verify_checksum
NEW: add ``--FTSOnly`` and ``--ExcludeSE`` options to dirac-dms-protocol-matrix
*RMS
CHANGE: ReqClient prints the FTS3 job url directly
=> [v7r1] Add FTSOnly and ExcludeSE options to dirac-dms-protocol-matrix

ConfigurationSystem/Client/VOMS2CSSynchronizer.py, docs/requirements.txt
Otherwise the user was not added to the new VO group
*Configuration
FIX: VOMS2CSAgent: fix an issue in the agent that prevented users being added to a second VO if they were already existing in another VO
=> [v7r0] VOMS2CSSync: if a user joins a second vo, pick up existing groups

tests/CI/docker-compose.yml, tests/CI/run_docker_setup.sh
For me, CI tests(running locally with docker) fall for two reasons:
```
+ cp -r /home/dirac/LocalRepo/TestCode/DIRAC DIRAC
cp: cannot open '/home/dirac/LocalRepo/TestCode/DIRAC/tests/__pycache__/conftest.cpython-27-PYTEST.pyc' for reading: Permission denied
cp: cannot open '/home/dirac/LocalRepo/TestCode/DIRAC/src/DIRAC/ConfigurationSystem/Client/test/__pycache__/Test_LocalConfiguration.cpython-27-PYTEST.pyc' for reading: Permission denied
```
and
```
+ docker-compose -f ./docker-compose.yml up -d
Creating elasticsearch ... done
Creating s3-direct     ... done
Creating mysql         ... done
ERROR: for dirac-server  Container "ae9b230765db" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
*tests
FIX: give permissions for the dirac user before …
=> [v7r2] fix CI params

src/DIRAC/Core/Utilities/DIRACScript.py, src/DIRAC/Core/scripts/dirac_configure.py, src/DIRAC/__init__.py
This PR uses `prompt-toolkit` (a dependency of IPython) to improve the CLI interactions. As this inherently interactive I've included videos of how it looks. If this is accepted I'll add `prompt-toolkit` to DIRACOS (it's already there, but I'll make it an explicit dependency).
* 803e53b: Gets rid of the globals used by `dirac-configure`. I could easily rebase this commit out of this PR if desired.
* c12c515: Use `prompt-toolkit` to read the certificate password instead of plain `getpass`. This fixes the long standing bug that pressing `Control + C` while typing your password breaks the prompt. (moved to #5004)
https://user-images.githubusercontent.com/5220533/109291419-40bc3300-7829-11eb-9501-fbbd52175273.mov
* 5687a7a: If `dirac-configure` is ran without any arguments with a Python 3 …
=> [v7r3] Support running dirac-configure without arguments

requirements.txt
*tests
CHANGE: fix version, newer versions of setuptools_scm do not support py2
=> [v7r2] newer versions of setuptools_scm do not support py2

WorkloadManagementSystem/Agent/JobAgent.py
The CPU work left computation was performed at the end of cycle *N* and the value was used in cycle *N+1*. 
If no slot is available or no job is matched for a while, the `timeleft` value is not updated and wrong.
FIX: Move the CPU work left computation at the beginning of the JobAgent execution
=> [v7r1] Move cpu work left computation at the beginning of the jobagent execution

Resources/Computing/BatchSystems/TimeLeft/TimeLeft.py, Resources/Computing/BatchSystems/TimeLeft/test/Test_TimeLeft.py
This PR removes `CPUMargin` and `WallClockMargin` from the TimeLeft utility.
They were not really used anymore and were causing some bugs in the `Watchdog` and `JobAgent` execution.
CHANGE: Remove margins from the TimeLeft utility
=> [v7r1] Remove old CPU/WallClock margins from the TimeLeft utility

DataManagementSystem/Agent/RequestOperations/RegisterReplica.py, Interfaces/scripts/dirac-wms-job-logging-info.py, WorkloadManagementSystem/Agent/StalledJobAgent.py, WorkloadManagementSystem/DB/JobDB.py
* WMS
CHANGE: if the `HeartBeatTime` of a job is not set, it cannot be seen as `Stalled`. Hence set the `HeartBeatTime` (if not set) when setting the `StartExecTime`
CHANGE (`StalledJobAgent`): don't try and get pilot status if "Unknown"
* Interface
CHANGE: print the jobID in dirac-wms-job-logging-info 
* DMS
CHANGE: lower logging level for individual LFNs (from INFO to VERBOSE) to decrease amount of logged information. Replace with a summary
=> [v7r1] Fix HeartBeatTime

Core/DISET/private/Transports/SSL/M2Utils.py, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst
Add an environment variable that allows for in depth SSL debugging
*Core
NEW: DIRAC_M2CRYPTO_DEBUG env variable for SSL debugging
=> [v7r1] M2Crypto: add a DIRAC_M2CRYPTO_DEBUG env variable for SSL debuging

README.rst
See here for how it actually looks: https://github.com/chrisburr/DIRAC/blob/py3-install-docs/README.rst
=> [v7r2] Add Python 3 install docs to README

Core/Utilities/MySQL.py, tests/Integration/Core/Test_MySQLDB.py
Reduces the time taken to run the server integration tests from ~14 minutes to ~4 minutes by avoiding pointless sleeps and retries.
=> [v7r1] Avoid pointless sleeping during server tests

DataManagementSystem/Client/FTS3Job.py
A bug in xrootd https://github.com/xrootd/xrootd/issues/1433 requires that we submit transfers with lower case checksum 
This was found in this ticket https://ggus.eu/index.php?mode=ticket_info&ticket_id=151081
it is currently being tested in LHCb, so far so good
*DMS
FIX: Submit FTS3 jobs with lowercase checksum
=> [v7r1] FTS3: submit FTS3Job with lowercase checksum

docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst
The link to install_site.sh seems to have changed
=> correct link to install_site.sh

container/docker_compose_setup/env_files/env_install.cfg, container/docker_compose_setup/resources/install.cfg, docs/source/AdministratorGuide/Tutorials/basicTutoSetup.rst, docs/source/AdministratorGuide/Tutorials/basicTutoSetup.sh, docs/source/AdministratorGuide/Tutorials/installRMS.rst, docs/source/AdministratorGuide/Tutorials/managingIdentities.rst, docs/source/DeveloperGuide/TornadoServices/index.rst, src/DIRAC/Core/DISET/private/Transports/BaseTransport.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Jenkins/config/ci/openssl_config_host.cnf, tests/Jenkins/config/ci/openssl_config_user.cnf, tests/Jenkins/install.cfg, tests/Jenkins/utilities.sh
The proxies generated with the self signed test users were not following the RFC3820 (see details bellow). This went unnoticed because this specific part of the RFC is only enforced since openssl 1.1 series (https://github.com/openssl/openssl/commit/c8223538cb05e5aac6418a5ba6dc4775b7ab486b.
The specific part we are not respecting is section `3.4`
```
The subject field of a Proxy Certificate MUST be the issuer field
(that is the subject of the Proxy Issuer) appended with a single
Common Name component.
```
This is the certificate we were generating:
```
[dirac@server user]$ openssl x509 -in /home/dirac/ServerInstallDIR/user/client.pem -noout -subject -issuer
subject=C = ch, O = DIRAC, OU = DIRAC CI, CN = ciuser, emailAddress = lhcb-dirac-ci@cern.ch
issuer=O = DIRAC CI, CN = DIRAC CI …
```
=> [v7r3] Tests: remove the email address of the self generated certificates

ConfigurationSystem/Agent/VOMS2CSAgent.py, ConfigurationSystem/Client/VOMS2CSSynchronizer.py
A fix for #5037, the added group wasn't part of the notification email
And the complement to #5037, this time when a user is no longer part of a second VO, but still in others, only drop from the relevant VO
*CS
FIX: VOMS2CSSynchronizer: add email information about a user joining groups for an additional VO
FIX: VOMS2CSSynchronizer: When a user leaves a second VO, only the membership in these groups is removed
CHANGE: VOMS2CSSynchronizer: If email of user is known, do not replace it with `None`
=> [v7r0] VOMS: fixes when user leaves secondary VO

DataManagementSystem/Agent/FTS3Agent.py, DataManagementSystem/Client/FTS3Operation.py, DataManagementSystem/private/FTS3Plugins/DefaultFTS3Plugin.py, DataManagementSystem/private/FTS3Plugins/__init__.py, DataManagementSystem/private/FTS3Utilities.py, DataManagementSystem/private/test/Test_FTS3Utilities.py, DataManagementSystem/scripts/dirac-dms-protocol-matrix.py, dirac.cfg, docs/source/AdministratorGuide/Resources/storage.rst, docs/source/AdministratorGuide/Systems/DataManagement/fts3.rst
Because some links may be special or some sites shitty, this mechanism allows for more flexibility in choosing a third party protocol or a source SE when transferring with FTS.
This comes with a Default plugin which does exactly what the hardcoded behavior was doing, and serves as documentation. It is totally backward compatible.
This is currently tested in LHCb
*Subsystem
NEW: FTS3 plugins to alter TPC and source SE preferences
=> [v7r1] FTS3: allow to alter TPC preference list and source SE with plugins

src/DIRAC/Core/Base/Script.py
Fixes the following error when using Ganga:
```python
ERROR    Error submitting job to Dirac: GangaDiracError: Traceback (most recent call last):
File "<stdin>", line 697, in <module>
File "<string>", line 11, in <module>
File "/cvmfs/lhcbdev.cern.ch/lhcbdirac/v10r2-pre5/DIRAC/Core/Base/Script.py", line 63, in parseCommandLine
localCfg.setUsageMessage(inspect.currentframe().f_back.f_globals['__doc__'])
KeyError: '__doc__'
ERROR
===
/afs/cern.ch/user/c/cburr/gangadir/workspace/cburr/LocalXML/0/input/dirac-script-0.py
===
ERROR
====
ERROR    resultdict = {}
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from LHCbDIRAC.Interfaces.API.DiracLHCb import DiracLHCb
from LHCbDIRAC.Interfaces.API.LHCbJob import LHCbJob
dirac = DiracLHCb()
sjNo='0'
j = LHCbJob() …
```
=> [v7r2] Fix using DIRAC v7r2 with Ganga

src/DIRAC/FrameworkSystem/DB/InstalledComponentsDB.py
When running the integration tests locally I noticed:
```
2021-04-07 13:54:48 UTC Framework/SystemAdministrator ERROR: Could not commit changes: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'DIRACVersion' at row 1")
[SQL: INSERT INTO `HostLogging` (`HostName`, `DIRACVersion`, `Extension`, `Load1`, `Load5`, `Load15`, `Memory`, `DiskOccupancy`, `Swap`, `CPUClock`, `CPUModel`, `CertificateDN`, `CertificateIssuer`, `CertificateValidity`, `Cores`, `PhysicalCores`, `OpenFiles`, `OpenPipes`, `OpenSockets`, `Setup`, `Uptime`, `Timestamp`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('server', '7.3.0a4.dev23+g30c910240.d20210407', 'LHCb:10.2.0a3.dev154+g0601f588e.d20210407', '0.75', '0.5', '0.4', …
```
=> [v7r2] Use String(64) for DIRACVersion column

tests/CI/run_tests.sh, tests/Integration/Core/Test_ElasticsearchDB.py, tests/Integration/DataManagementSystem/Test_DataIntegrityDB.py, tests/Integration/RequestManagementSystem/Test_Client_Req.py, tests/Integration/RequestManagementSystem/Test_ReqDB.py, tests/Integration/WorkloadManagementSystem/Test_JobParameters_MySQLandES.py, tests/Integration/all_integration_server_tests.sh
This PR makes it possible to re-run the integration tests when running them against a local installation without recreating the entire server.
*Tests
NEW: Integration tests can be re-ran locally without re-installing the entire setup
=> [v7r2] Re-runable integration tests

Core/Utilities/test/Test_Mail.py
It turns out the hostname changes on GitHub actions between the first and second initialisations of `Mail()`:
```python
{'_attachments': [], '_fromAddress': 'runner@fv-az296-124.internal.cloudapp.net', '_html': False, '_mailAddress': '', ...}
{'_attachments': [], '_fromAddress': 'runner@fv-az296-124', '_html': False, '_mailAddress': '', ...}
```
I workaround it by monkey-patching `socket.getfqdn` (27eeaef) and convert it to be `pytest` style while I'm here (8ce51c2). As it's a flaky test I'm backporting to v7r0.
=> [v7r0] Prevent random failures in test_compareEmails

TransformationSystem/Agent/DataRecoveryAgent.py
*TS
FIX: DataRecoveryAgent: immediately skip transformations without jobs, prevents exception later on
=> [v7r0] DataRecoveryAgent: skip transformations without jobs

src/DIRAC/__init__.py
*Core
CHANGE: Update URL for DIRAC-Certification setup
=> [v7r3] Use HTTPS URL for DIRAC-Certification setup

integration_tests.py
Currently `./integration_tests.py create` was not exiting with an error if the integration tests failed due to a stupid typo. This doesn't affect the DIRAC CI as it runs the steps individually however interactively and in the LHCbDIRAC CI we just run the one-liner.
=> [v7r2] Fix exiting with errors from ./integration_tests.py create

Resources/Computing/HTCondorCEComputingElement.py
*Resources
FIX: HTCondorCE: Limit calls to actual cleanup (find and delete files on disk) to once per minute per SiteDirector, fixes #5118 
CHANGE: HTCondorCE cleanup: Run the DIRAC_  executable purge with `-O3` and `-maxdepth 1` to speed up the find
=> [v7r0] HTCondorCE: Limit cleanup to a single run per minute per SiteDirector

WorkloadManagementSystem/Agent/SiteDirector.py, WorkloadManagementSystem/Agent/test/Test_Agent_SiteDirector.py
The `SiteDirector` writes the executable in its own `self.workingDirectory` (taken from the agent config) [1] while the `HTCondorCEComputingElement` tries to clean them in its own `self.workingDirectory` (taken from `Resources`) [2]. Since they can be different, that cannot work. 
So use the CE working directory for the executables
[1] https://github.com/DIRACGrid/DIRAC/blob/95dc4b26e0c7feb89c0ad108b3ccc606075f5214/WorkloadManagementSystem/Agent/SiteDirector.py#L1078
[2] https://github.com/DIRACGrid/DIRAC/blob/95dc4b26e0c7feb89c0ad108b3ccc606075f5214/Resources/Computing/HTCondorCEComputingElement.py#L543
*WMS
CHANGE: for HTCondor, the SiteDirectory write the executable in the globally defined working directory
=> [v7r1] SiteDirector: for HTCondor, write the executable in the globally defined working directory

src/DIRAC/ResourceStatusSystem/Agent/CacheFeederAgent.py, src/DIRAC/ResourceStatusSystem/Agent/ElementInspectorAgent.py, src/DIRAC/ResourceStatusSystem/Agent/test/Test_Agent_ElementInspectorAgent.py, src/DIRAC/ResourceStatusSystem/Client/ResourceManagementClient.py, src/DIRAC/ResourceStatusSystem/Client/ResourceStatus.py, src/DIRAC/ResourceStatusSystem/Client/ResourceStatusClient.py, src/DIRAC/ResourceStatusSystem/Client/SiteStatus.py, src/DIRAC/ResourceStatusSystem/Command/PilotCommand.py, src/DIRAC/ResourceStatusSystem/DB/ResourceManagementDB.py, src/DIRAC/ResourceStatusSystem/Policy/PilotEfficiencyPolicy.py, src/DIRAC/ResourceStatusSystem/Policy/test/Test_RSS_Policy_PilotEfficiencyPolicy.py, src/DIRAC/ResourceStatusSystem/PolicySystem/Actions/LogPolicyResultAction.py, src/DIRAC/ResourceStatusSystem/PolicySystem/Actions/LogStatusAction.py, src/DIRAC/ResourceStatusSystem/PolicySystem/PDP.py, src/DIRAC/ResourceStatusSystem/Utilities/InfoGetter.py, src/DIRAC/ResourceStatusSystem/Utilities/RSSCacheNoThread.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_list_status.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_query_db.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_set_status.py, src/DIRAC/ResourceStatusSystem/scripts/dirac_rss_set_token.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, src/DIRAC/WorkloadManagementSystem/Service/PilotManagerHandler.py, tests/Integration/WorkloadManagementSystem/Test_PilotAgentsDB.py, tests/Integration/all_integration_server_tests.sh
**Multi VO Resource Status and Resource Management implementation.**
This PR is done against the integration branch and it supersedes https://github.com/DIRACGrid/DIRAC/pull/5006
The base for the dynamic, VO-based resource management is the ResourceStatus
table. This table would	normally have some Active resources:
```
Name                         | VO          | Status   | Reason
ceprod03.grid.hep.ph.ic.ac.uk | all         | Active   | whatever reason
```
For the purpose of this	demonstration we	activate the _DowntimePolicy_
and the _PilotEfficiencyPolicy_. After the first one is run, we have:
`ceprod03.grid.hep.ph.ic.ac.uk | all    | Active   | No DownTime announced ###`
The _DowntimePolicy_ is not _VO_-aware, so its result is valid for all _VOs_.
Now, when we try to submit some …
=> [v7r3] Multi VO RSS

WorkloadManagementSystem/Utilities/PilotWrapper.py
This message is a constant source of confusion for people in the pilot logs so I propose we put at least something to help people realise this isn't actually the problem. I've gone for the concise option but an alternative would be to actually check if there are locations remaining in the list.
CHANGE: Clarify that "tarfile failed with message" can be normal
=> [v7r1] Clarify tarfile error message in pilot logs

WorkloadManagementSystem/Agent/SiteDirector.py
*WMS
FIX: SiteDirector._getPilotsWeMayWantToSubmit: fix return type in case of error
=> [v7r1] SiteDirector: fix wrong return type in function

integration_tests.py
Not worthy of release notes but makes the integration tests script slightly more robust.
=> [v7r2] Allow groupadd to fail when running integration tests

src/DIRAC/Core/Base/Client.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_JobAgent.py
*Core
FIX: The RPC Client class should now be threadsafe
FIX: Correctly add RPC attributes to client objects in Python 3 
=> [v7r2] Make DIRAC.Core.Base.Client.Client threadsafe

src/DIRAC/Core/Base/private/ModuleLoader.py, src/DIRAC/Core/Utilities/DErrno.py, src/DIRAC/Core/Utilities/ObjectLoader.py, src/DIRAC/__init__.py
Operations using the ObjectLoader machinery in threads can fail with traces like:
```python
File "/miniconda/envs/analysis-productions/lib/python3.8/site-packages/dirac_prod/classes/input_dataset.py", line 32, in replicas
for se, pfn in dw(Dirac().getReplicas([str(self)], active=True))[str(self)].items():
File "/miniconda/envs/analysis-productions/lib/python3.8/site-packages/DIRAC/Interfaces/API/Dirac.py", line 858, in getReplicas
repsResult = dm.getReplicas(lfns, active=active, preferDisk=preferDisk, diskOnly=diskOnly)
File "/miniconda/envs/analysis-productions/lib/python3.8/site-packages/DIRAC/DataManagementSystem/Client/DataManager.py", line 1742, in getReplicas
succPfn = seObj.getURL(se_lfn[se],
File "/miniconda/envs/analysis-productions/lib/python3.8/site-packages/DIRAC/Resources/Stor …
```
=> [v7r2] Backport: Factorise recurseImport to DIRAC.Core.Utilities.Extensions

FrameworkSystem/Client/UserProfileClient.py, FrameworkSystem/DB/UserProfileDB.py, FrameworkSystem/Service/UserProfileManagerHandler.py, docs/requirements.txt, docs/requirements_py3.txt, environment.yml, requirements.txt
This PR fixes an issue in the web app which cases the Public State Manager to almost never load for some users due to the response being too slow. There are two main optimisations:
1. Add a bulk endpoint to avoid the request scaling with `latency * number of shared states`
2. Add a cache in `UserProfileDB` to avoid making the same few read/timestamp updates being made hundreds/thousands of times.
Note for 2. it uses cache tools which would need to be added in DIRACOS. Any objections?
I'll follow up with a WebApp PR which makes use of this.
*Framework
NEW: Add UserProfileClient.listStatesForWeb endpoint to make the Public State Manager faster
=> [v7r1] Add listStatesForWeb endpoint to make Public State Manager faster

DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py
Hi,
As discussed in the meeting this morning, we see occasional issues with files that have an FC_Files entry but no matching FC_FileInfo row. This causes the users to get "KeyError FileID" style errors when doing anything with those directories/files.
We had a look a fixing this, but there was no easy solution: Checking that all of the requested fields are there is too slow and ensuring FileID is in the dictionary gets rid of the problem in some places, but moves the crash to others keys in others.
For now we'd like to suggest this patch: It simply improves the error message that the user sees if they list a directory containing a corrupt file. It's far from perfect, but is very low risk compared to other possible fixes and still greatly improves the user experience. I'm hoping in the …
=> [v7r1] Add better error if FC DB has a missing fields

environment-py3.yml, setup.cfg
Part of https://github.com/DIRACGrid/DIRAC/pull/5159 but these files only exist in v7.2+.
=> [v7r2] Add cachetools to dependency files

src/DIRAC/Core/Security/VOMS.py
*Core
FIX: Workaround for OSError when copying vomses directory with too many extended attributes
=> [v7r2] Workaround for OSError when copying vomses directory with too many extended attributes

requirements.txt
This isn't actually used by the DIRAC CI anymore but the LHCbDIRAC CI still depends on it. Once DIRAC is Python 3 only we can get rid of all this duplication.
=> [v7r2] Add importlib_resources to requirements.txt

environment-py3.yml
I've opened issues upstream so hopefully these can be fixed rather than littering the code with disabled checks.
This is another case where `pre-commit` would be nice as it automatically pins versions of packages like `astroid`/`pylint` so we can bump the versions when it suits us rather than being randomly hit by regressions (or previously unknown bugs). Example: https://github.com/scikit-hep/uproot4/pull/373
=> [v7r2] Pin astroid to avoid linter false positives

src/DIRAC/FrameworkSystem/Client/UserProfileClient.py, src/DIRAC/FrameworkSystem/DB/UserProfileDB.py
*Framework
CHANGE: Deprecate checkTypeRe and HashTags in UserProfileClient
FIX: Python 3 compatibility in UserProfileClient
=> [v7r2] Python 3 fixes in UserProfileClient and deprecations

src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, tests/Integration/WorkloadManagementSystem/Test_PilotAgentsDB.py
This update add an Aborted_HOUR column to the pilot efficiency table needed by the WebApp. Some logging level fixes.
=> [v7r3] Multi VO RSS update 1

WorkloadManagementSystem/JobWrapper/JobWrapper.py
As part of the upgrade to v7r2 in LHCb we found jobs started crashing with:
```python
2021-06-03 06:53:27 UTC dirac-jobexec/GaudiApplication ERROR: Failure in GaudiApplication execute module
File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r1p13/LHCbDIRAC/Workflow/Modules/GaudiApplication.py", line 164, in execute
prodConfFileName = self.createProdConfFile(stepOutputTypes, histogram, runNumberGauss, firstEventNumberGauss)
File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r1p13/LHCbDIRAC/Workflow/Modules/ModuleBase.py", line 1108, in createProdConfFile
jobMaxCPUTime=86400)
File "/cvmfs/lhcb.cern.ch/lhcbdirac/v10r1p13/LHCbDIRAC/Workflow/Modules/ModulesUtilities.py", line 132, in getEventsToProduce
CPUTime = getCPUTime(CPUNormalizationFactor)
File …
```
=> [v7r1] Improve backwards compatibility for running jobs submitted with v7r2

pyproject.toml
There is an invalid tag in the history which cases the issue reported by @TaykYoku on slack when pip installing directly from a fork which pre-dates the new style versioning. This change makes the `git describe` command more robust (causing the version to default to something like `0.1.dev33206+g68d885b.d20210602` instead of erroring).
*Python 3
FIX: Improve "git describe" command used by setuptools-scm to ignore v6e7p27
=> [v7r2] Improve git describe command used by setuptools-scm

src/DIRAC/ConfigurationSystem/private/ConfigurationClient.py, src/DIRAC/Core/Utilities/ReturnValues.py
When profiling some agents I've noticed that most of the time is spent generating the `CallStack` field in `S_ERROR`. This is due the CS being heavily used and even default keys have to format a full traceback. This PR adds a new `callStack` keyword argument to `S_ERROR` to avoid this which makes `gConfig.getOption` ~13x faster. Benchmarked with:
```python
import DIRAC
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
DIRAC.gConfig.getOption("/Systems/Transformation/Production/Agents/WorkflowTaskAgent/PollingTim", 120)
%timeit DIRAC.gConfig.getOption("/Systems/Transformation/Production/Agents/WorkflowTaskAgent/PollingTim", 120)
```
Before:
```
137 µs ± 343 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
After:
```
11.3 µs ± 35.1 ns per loop (mean ± std. …
```
=> [v7r2] Add callStack argument to S_ERROR to optimise CS

src/DIRAC/Core/Utilities/ClassAd/ClassAdLight.py
This removes the quadratic dependence on the length of the JDL to make `ClassAd.asJDL` orders of magnitude faster. For example, taking a 936KB JDL that was submitted by the WorkflowTaskAgent in LHCb for simulation jobs and loading/dumping it with:
```python
from DIRAC.Core.Utilities.ClassAd.ClassAdLight import ClassAd
fn = "/tmp/tmpF1Irnl"
with open(fn) as fp:
jdl = fp.read()
job = ClassAd(jdl)
%timeit x = job.asJDL()
```
Before:
```
1.06 s ± 166 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
After:
```
9.95 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
*Core
FIX: Optimise ClassAd.asJDL to remove quadratic runtime dependence on the length of the output
=> [v7r2] Optimise ClassAd.asJDL

.github/workflows/integration.yml, docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, integration_tests.py, src/DIRAC/ConfigurationSystem/private/ConfigurationData.py, src/DIRAC/ConfigurationSystem/private/Refresher.py, src/DIRAC/ConfigurationSystem/private/RefresherBase.py
When profiling the production agents/services in LHCb I've notice that a significant amount of time is spent waiting for one of the three locks in the CS. This change can make both single and multithreaded code that heavily uses the CS significantly faster (hard to measure/define but I've seen 2x in single threaded and 4x in multithreaded when testing).
While I can see why the locks are put in place in the CS I think they're actually implemented in such a way that they're not that useful while having a big impact on the overall CS performance.
Additionally, the "dangerZone" locks have been broken for the last 12 years as the `disableDangerZones` option still decrements the thread count causing the thread count to go negative and never be respected properly (potentially fixed by …
=> [v7r2] Add environment variable to speed up the CS

src/DIRAC/FrameworkSystem/private/monitoring/ColorGenerator.py, src/DIRAC/FrameworkSystem/private/monitoring/test/Test_ColorGenerator.py
Fixes this error seen in LHCb:
```python
2021-06-14 14:06:29 UTC Framework/Monitoring ERROR: Uncaught exception when serving RPC Function plotView
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 289, in __RPCCallFunction
uReturnValue = oMethod(*args)
File "/opt/dirac/pro/DIRAC/FrameworkSystem/Service/MonitoringHandler.py", line 170, in export_plotView
return gServiceInterface.plotView(viewRequest)
File "/opt/dirac/pro/DIRAC/FrameworkSystem/private/monitoring/ServiceInterface.py", line 408, in plotView
return self.generatePlots(viewRequest['fromSecs'], viewRequest['toSecs'], viewDefinition, viewRequest['size'])
File "/opt/dirac/pro/DIRAC/FrameworkSystem/private/monitoring/ServiceInterface.py", line 330, in generatePlots
return …
```
=> [v7r2] Fix TypeError in ColorGenerator

docs/source/DeveloperGuide/CodeTesting/index.rst, src/DIRAC/Interfaces/scripts/dirac_wms_job_parameters.py, src/DIRAC/Resources/Computing/BatchSystems/TimeLeft/TimeLeft.py, src/DIRAC/Resources/Computing/BatchSystems/TimeLeft/test/Test_TimeLeft.py, src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/WorkloadManagementSystem/Client/test/Test_Client_WorkloadManagementSystem.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py, tests/Integration/WorkloadManagementSystem/pilot.cfg
This PR removes all the calls to `/LocalSite/CPUScalingFactor`, which was related to the deprecated `MJF` system removed in this commit:
https://github.com/DIRACGrid/DIRAC/commit/1d734d7b04c41bcb1fd2d9b1c80531fe1a1c269e
`TimeLeft` was still trying to use `CPUScalingFactor` and was failing because the option does not exist anymore, and thus was not able to provide a right value of the CPU work left.
*Resources 
FIX: remove CPUScalingFactor calls
FIX: remove CPUScalingFactor calls
=> [v7r2] Remove CPUScalingFactor from DIRAC

environment-py3.yml, src/DIRAC/Core/Utilities/Subprocess.py, src/DIRAC/Core/Utilities/test/Test_Subprocess.py
=> [v7r2] Fix handling Subprocess calls which produce invalid output

.github/workflows/make_release.py
There is no need for this check as the code doesn't exist in branches prior to v7r2 and without it the same code can be used to automatically deploy the WebAppDIRAC releases to PyPI.
=> Make make_release.py re-usable for WebAppDIRAC

Interfaces/API/Dirac.py
*Interfaces
NEW: Implemented a function that allows programmatic listing of directories in the DFC. Meant to replace the never fully deployed listCatalog function.
=> [v7r1] added listCatalogDir in DIRAC API

WorkloadManagementSystem/Client/SandboxStoreClient.py
CHANGE: Make error message from SandboxStoreClient clearer when the sandbox is not found
=> [v7r1] Make error message from SandboxStoreClient clearer

src/DIRAC/MonitoringSystem/Service/MonitoringHandler.py, src/DIRAC/ProductionSystem/Service/ProductionManagerHandler.py, src/DIRAC/TransformationSystem/Service/TransformationManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/MatcherHandler.py, src/DIRAC/WorkloadManagementSystem/Service/PilotManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/PilotsLoggingHandler.py, src/DIRAC/WorkloadManagementSystem/Service/SandboxStoreHandler.py, src/DIRAC/WorkloadManagementSystem/Service/WMSAdministratorHandler.py
This is solution for https://github.com/DIRACGrid/DIRAC/issues/3848 and of real issue that we are facing now in LHCb. I don't love it but I can't find quickly a better solution.
As an explanation of why this is needed: in the process of moving, one day, to tornado-based https services, the global objects (in this case the `TransformationDB` objects) used in the TransformationManagerHandler (DIRAC, and e.g. for LHCb also LHCbDIRAC) were replaced, in v7r2, by class members (see https://github.com/DIRACGrid/DIRAC/issues/4825). This would work normally fine (as python inheritance works...) but services, as coded in DISET, somehow manage to override some of the inheritance rules.
So, what's coded here should possibly be used "everywhere" (but SQLAlchemyDB-based DB modules already have a …
=> [v7r2] Handlers to discover extensions of DBs

docs/source/DeveloperGuide/TornadoServices/index.rst, src/DIRAC/Core/Tornado/scripts/tornado_start_CS.py, src/DIRAC/Core/Tornado/scripts/tornado_start_all.py, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py
Addresses https://github.com/DIRACGrid/DIRAC/issues/5223
*Core
FIX: DIRAC_USE_TORNADO_IOLOOP is set in the runsv file rather than the python starting script (#5223 )
=> [v7r2] Tornado: export DIRAC_USE_TORNADO_IOLOOP=Yes in the runsv file

src/DIRAC/Resources/Computing/SSHComputingElement.py
The path of `submitFile` (pilot wrapper) was related to the DIRAC server and was not changed before being wrapped in the parallel library script, which caused errors during the execution of the pilot wrapper.  
*Resources
FIX: fix path of the executable file when using a parallel library within SSHCE
=> [v7r2] Fix submitFile filepath when using a parallel library within SSHCE

src/DIRAC/DataManagementSystem/scripts/dirac_dms_add_file.py
*DMS
CHANGE: prints why dirac-dms-add-files failed
=> [v7r3] dirac-dms-add-file: print the error on failure

src/DIRAC/Core/Utilities/Graphs/PieGraph.py
Before:
After:
The question is do we need to display such small values?
The plot does not draw a pie for very small values, this correction will display the ratio for values much smaller than one.
*Core
FIX: show extremely small values in pie plots
=> [v7r3] show extremely small values in pie plots

src/DIRAC/Core/scripts/install_site.sh
This breaks compatibility with versions prior to v7r0 due to the addition of `--cfg` but hopefully there aren't many people still doing fresh v6r22 installations.
=> [integration] Clean ups in install_site.sh

src/DIRAC/Core/Base/ExecutorReactor.py, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/__init__.py
Nothing especially worthy of release notes. The issue in ExecutorReactor is that Python 3 is much less permissive about poorly defined comparisons like `5 > None` and `"Hello" > "world"`:
```python
[dirac@lbcertifdirac70 ~]$ python3
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> max(12, None)
File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'int'
>>>
```
```python
[dirac@lbcertifdirac70 ~]$ python2
Python 2.7.5 (default, Nov 16 2020, 22:23:17)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> max(12, None) …
```
=> [v7r3] Fixes and support for CertifOauth

src/DIRAC/Resources/Computing/ARCComputingElement.py, src/DIRAC/Resources/Computing/SingularityComputingElement.py, src/DIRAC/WorkloadManagementSystem/Client/SandboxStoreClient.py
Targetting v7r2 as I think these fixes belong there:
FIX: Bytes confusion when using SandboxStoreClient with Python 3
*Resources
FIX: Bytes confusion when using SingularityComputingElement with Python 3
=> [v7r2] Python 3 hackathon fixes

src/DIRAC/Core/Base/Client.py
This change of `importlib_resources` (https://github.com/python/importlib_resources/pull/221) introduced a change of behavior (https://github.com/python/importlib_resources/issues/230)
With `importlib_resources` >= `5.2.0`, `path` would not throw an error if the resource does not exist, but `fp.read_text` would raise `FileNotFoundError`, so i just shifted the block in the `try/except`
*Core
CHANGE: protect client doc generation against new importlib_resources
=> [v7r2]Client: protect documentation generation against py3

environment-py3.yml
It turns out installing from their git repo was an even worse idea than expected as it installs the full server package instead of the client causing https://github.com/DIRACGrid/DIRAC/issues/5250.
Luckily they now have a pre-release so we can make this slightly less hacky.
=> [v7r2] Install rucio from PyPI again

src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/TransformationSystem/Client/TransformationClient.py, src/DIRAC/TransformationSystem/DB/TransformationDB.py, src/DIRAC/TransformationSystem/DB/TransformationDB.sql, src/DIRAC/TransformationSystem/Service/TransformationManagerHandler.py
The three commits are worth viewing separately as they're three separate improvements:
* 48bdcf3: Add indices which make several queries considerably faster
* bba7880: When escaping a long list of values the database is pinged for every element by `MySQL._getConnection` making queries like `TransformationID is in (1,2,3,4,5,6,7,8,9,10)` unnecessarily slow from all the round trips to the database
* af2560a: Add `columns` argument to `TransformationClient.getTransformations` which is primarily useful for avoiding the download of hundred of megabytes of XML in the `Body` column when getting lots of transformations.
*Core
FIX: Avoid pinging the database every time MySQL.__escapeString is called
NEW: Add columns keyword argument to …
=> [v7r2] Optimisation for Transformation system queries

src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_pilot_job_info.py
```python
bash-4.2$ dirac-wms-pilot-job-info gsiftp://calc2.t1.grid.kiae.ru:2811/jobs/2v4MDmcf3LzngXGZXoMFMvcqYUz0ymWKy3zmSlHKDmABFKDmF1GXIo
File "/cvmfs/lhcb.cern.ch/lhcbdirac/versions/v10.2.3-x86_64-1623745062/bin/dirac-wms-pilot-job-info", line 8, in <module>
sys.exit(main())
File "/cvmfs/lhcb.cern.ch/lhcbdirac/versions/v10.2.3-x86_64-1623745062/lib/python3.9/site-packages/DIRAC/Core/Utilities/DIRACScript.py", line 77, in __call__
return entrypoint.load()._func()
File "/cvmfs/lhcb.cern.ch/lhcbdirac/versions/v10.2.3-x86_64-1623745062/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_pilot_job_info.py", line 76, in main
100. * params['TotalCPUTime(s)'] / params['WallClockTime(s)'])
TypeError: can't multiply sequence by non-int …
```
=> [v7r2] Fix TypeError in dirac-wms-pilot-job-info

src/DIRAC/Core/Utilities/JEncode.py, src/DIRAC/Core/Utilities/test/Test_Encode.py
In LHCbDIRAC's ProductionManagementSystem `datetime.date` objects are used quite a bit but JEncode fails to handle them.
*Core
NEW: Support datetime.date objects in JEncode
=> [v7r2] Support datetime.date objects in JEncode

tests/Jenkins/utilities.sh
The DIRACOS2 integration tests have been testing the latest release instead of the currently built binary. This should fix it 🤞
=> [v7r2] Use DIRACOS_TARBALL_PATH if specified when running Python 3 integration tests

src/DIRAC/Resources/Computing/BatchSystems/SLURM.py, src/DIRAC/Resources/Computing/ComputingElement.py, src/DIRAC/Resources/Computing/LocalComputingElement.py, src/DIRAC/Resources/Computing/SSHBatchComputingElement.py, src/DIRAC/Resources/Computing/SSHComputingElement.py, src/DIRAC/WorkloadManagementSystem/Utilities/JobParameters.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_get_wn_parameters.py
This works together (or not) from https://github.com/DIRACGrid/Pilot/pull/132 (the Pilot PR is not 100% necessary).
Note that here I used tags of type "%dGPUs" (similar to e.g. tags "%dProcessors". I have not yet added/modified the documentation, I will do after the PR review.
*Resources
NEW: SLURM can set gpus-per-task
NEW: added getGPUs method
=> [v7r2] Adding GPUs support (CEs definition)

src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_PilotStatusAgent.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.py, src/DIRAC/WorkloadManagementSystem/Service/WMSAdministratorHandler.py, tests/Integration/Resources/ProxyProvider/Test_DIRACCAProxyProvider.py, tests/Integration/WorkloadManagementSystem/Test_PilotsClient.py
Python 3 hackathon fixes.
*Core
CHANGE: modify MySQL._to_string
*WorkloadManager
FIX: decode values using _to_string method in JobDB
FIX: mock _escapeString in Test_Agent_PilotStatusAgent to pass test
FIX: escape values in PilotAgentsDB
CHANGE: remove pilots before start Test_PilotsClient test
=> [v7r3] Python 3 hackathon fixes

src/DIRAC/WorkloadManagementSystem/Client/SandboxStoreClient.py
Just a small fix: `mode="rb"` is not a valid mode according to:
https://docs.python.org/2.7/library/tarfile.html
FIX: SandboxStoreClient tarfile mode
=> [v7r2] SandboxStoreClient: fix tarfile mode

src/DIRAC/TransformationSystem/Client/TransformationClient.py, tests/Integration/TransformationSystem/Test_Client_Transformation.py
This prevents a race condition when the status known to an agent is not what is in the DB anymore.
Unfortunately, this only decreases the likelihood of the race condition. A real fix would be to change this whole method at the DB level and add the known status as a selection criteria. But that's a lot more work 
*TS
NEW: add currentStatus parameter to TransformationClient.setTransformationParameter
=> [v7r2] TS: add a status check before updating it

src/DIRAC/ConfigurationSystem/private/RefresherBase.py
`DIRAC.Core.Base.Client.Client` has no ``serviceURL`` attribute, so log print:
```
Trying to refresh from functools.partial(<bound method Client.executeRPC of <DIRAC.ConfigurationSystem.Client.ConfigurationClient.ConfigurationClient object at 0x7f9b7f147d00>>, call='serviceURL')
```
*Configuration
FIX: fix RefresherBase log
=> [v7r2] fix RefresherBase log

src/DIRAC/Core/DISET/private/MessageFactory.py
*Core
FIX:  Use isinstance when checking types in MessageFactory
=> [v7r3] Use isinstance when checking types in MessageFactory

src/DIRAC/Core/Utilities/Plotting/FileCoding.py
Encoding stub must fix base64 decoding error:
```
File "/opt/dirac/pro/DIRAC/Core/Utilities/Plotting/FileCoding.py", line 49, in extractRequestFromFileId
stub = base64.urlsafe_b64decode(stub)
File "/opt/dirac/versions/v7r3-pre15_1626334216/diracos/usr/lib64/python2.7/base64.py", line 119, in urlsafe_b64decode
return b64decode(s.translate(_urlsafe_decode_translation))
TypeError: character mapping must return integer, None or unicode
```
*Core
FIX: encode stub before base64
=> [v7r3] encode stub in FileCoding

DataManagementSystem/Service/FTS3ManagerHandler.py
Fixes this error:
```
2021-07-27 13:19:23 UTC DataManagement/FTS3Manager ERROR: Error in parameter check: isinstance() arg 2 must be a class, type, or tuple of classes and types
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 325, in __checkExpectedArgumentTypes
if not isinstance(args[iIndex], tuple(oTypesList[iIndex])):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```
*Data Management
FIX: Type error when calling FTS3ManagerHandler.getActiveJobs
=> [v7r1] Fix type checking in FTS3ManagerHandler.getActiveJobs

docs/requirements.txt
Just adding a package to build the docs on RTD.
=> [v7r1] Docs: add enum34 needed by rucio clients

src/DIRAC/FrameworkSystem/scripts/dirac_admin_update_instance.py
*Framework
FIX: fix use of --excludeHosts in dirac-admin-update-instance
=> [v7r2] dirac-admin-update-instance: fix use of --excludeHosts

src/DIRAC/Resources/Computing/BatchSystems/Host.py, src/DIRAC/Resources/Computing/SSHBatchComputingElement.py, src/DIRAC/Resources/Computing/SSHComputingElement.py
The output retrieval for pilots in a SSHBatch CE was screwed due to pilot reference not reflecting the actual execution host. This also prevented proper association of pilots and jobs steered by them. 
This PR comes together with a PR in the Pilot project https://github.com/DIRACGrid/Pilot/pull/134.
*Resources
FIX: SSHComputingElement - treat properly the case of the pilots submitted to SSHBatch CE
FIX: SSHBatchComputingElement - use special SSHBATCH execution context
FIX: Host.py - put the actual execution host name/IP into the SSH_NODE_HOST environment
=> [v7r2] SSHBatch CE pilots fixes

src/DIRAC/ConfigurationSystem/Client/PathFinder.py, src/DIRAC/ConfigurationSystem/Client/test/Test_PathFinder.py, src/DIRAC/Core/Base/private/ModuleLoader.py, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py, src/DIRAC/FrameworkSystem/DB/ComponentMonitoringDB.py
This PR adds some convenience in getting service URLs as a list. As well as the ability to obtain URLs of all services in the context of the system. Port and path validation has also been added.
Currently, mostly getServiceURL is used, which returns a list of URLs as a string, which is then converted to a list type, or processed as a single URL. Therefore, for better clarity, getServiceURLs returns a list of URLs and can randomize the list and add failover URLs.
NEW: test new PathFinder methods
NEW: add checkServiceURL that check URL port and path
NEW: add getServiceURLs that return list type result
NEW: add getSystemURLs that return all services URLs for system
FIX: getGatewayURLs pass list to randomize when serviceName is empty
CHANGE: …
=> [integration] update PathFinder

tests/Jenkins/dirac_ci.sh
Like https://github.com/DIRACGrid/DIRAC/pull/5258/files but for the server installation
=> [v7r3] Use DIRACOS_TARBALL_PATH if specified when running Python 3 integration tests

src/DIRAC/FrameworkSystem/Agent/ComponentSupervisionAgent.py, src/DIRAC/FrameworkSystem/Agent/test/Test_ComponentSupervisionAgent.py, src/DIRAC/FrameworkSystem/ConfigTemplate.cfg
*Framework
FIX: ComponentSupervisionAgent: consistently use the actual "Setup", and not the "instance" to look up options. Note: you might need to change your config from "Production" to "DIRAC-Production" depending on you config.
=> [v7r2] ComponentSupervisionAgent: look in correct CS path

src/DIRAC/TransformationSystem/Client/TaskManager.py
Fixes this crash when using Python 3:
```python
~/Development/DIRAC-dev/DIRAC/src/DIRAC/Core/Utilities/DEncode.py in encodeList(lValue, eList)
437   eList.append(b"l")
438   for uObject in lValue:
--> 439     g_dEncodeFunctions[type(uObject)](uObject, eList)
440   eList.append(b"e")
441
KeyError: <class 'dict_values'>
```
FIX: Python 3 serialisation error when calling JobMonitoringClient.getJobsStatus in WorkflowTasks.getSubmittedFileStatus
=> [v7r2] Fix call to JobMonitoringClient.getJobsStatus in WorkflowTasks

src/DIRAC/TransformationSystem/Agent/DataRecoveryAgent.py
*TS
FIX: DataRecoveryAgent: fix exception when there is exactly 1 done or failed job for a transformation
=> [v7r2] DRA: fix divide by zero if we have just 1 job

src/DIRAC/FrameworkSystem/Client/ProxyManagerClient.py
For some reason, this fix was not merged from v7r1 #4853 
*Framework
FIX: fix ProxyManagerClient docs
=> [v7r2] fix ProxyManagerClient docs (from #4853)

src/DIRAC/Resources/Storage/EchoStorage.py, src/DIRAC/Resources/Storage/GFAL2_StorageBase.py
Removals against Echo are ridiculous, but the claim is that nothing can be done.
I add here a trivial throttle mechanism.
*Resources
NEW: removal throttle for Echo
CHANGE: private methods in GFAL2_StorageBase are now protected
=> [v7r2] Mitigation of crappy Echo removal

.github/workflows/pilotWrapper.yml, README.rst, docs/docs.conf, docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/index.rst, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py, tests/Integration/WorkloadManagementSystem/Test_GenerateAndExecutePilotWrapper.py
This waits for `Pilot/devel` branch to merge to `Pilot/master` branch (after https://github.com/DIRACGrid/Pilot/pull/133)
*WMS
CHANGE: SiteDirector: do not send dirac-install if it's py3 pilot
=> [v7r3] SiteDirector: do not send dirac-install if it's py3 pilot

src/DIRAC/Resources/Computing/ParallelLibraries/Srun.py
This PR juste removed the `os.chmod(executableFile)` line from `Srun.py` that is not necessary and breaks the submission of pilots.
*Resources
FIX: Parallel Library Srun: remove chmod of executableFile
=> [v7r2] Fix Multi-node wrapper Srun

environment-py3.yml, environment.yml, requirements.txt, setup.cfg, src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py, src/DIRAC/WorkloadManagementSystem/Agent/StatesAccountingAgent.py
and a few other fixes, that don't deserve a note.
The reason for limit ES client to 7.13 can be found in https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/
=> [v7r2] Limit ES client to 7.13

tests/Integration/Framework/Test_UserProfileClient.py
Fixes a test bug when running Test_UserProfileClient in LHCb's CI: https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/merge_requests/1068
=> [v7r3] Dynamically get group and VO when testing UserProfileClient

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/Utilities/QueueUtilities.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_QueueUtilities.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_match.py
This PR moves `SiteDirector.getQueues()` in `QueuesUtilities`: the method was very similar to `QueueUtilities.getQueuesResolved()` and might be needed in the future (e.g. in the case of sites with no external connecitivities). 
- Move `getQueues()`
- Break down `getQueuesResolved()` in several smaller methods easier to test and usable by others functions such as `getQueues`
- Add unit tests
CHANGE: Move SiteDirector.getQueues in QueueUtilities module
=> [v7r3] Move SiteDirector getQueues in QueueUtilities

environment.yml, src/DIRAC/Core/DISET/ServiceReactor.py, src/DIRAC/Core/DISET/private/MessageBroker.py, src/DIRAC/Core/DISET/private/Transports/BaseTransport.py, src/DIRAC/Core/DISET/private/Transports/PlainTransport.py, src/DIRAC/Core/DISET/private/Transports/test/Test_SSLTransport.py, src/DIRAC/Core/Utilities/Subprocess.py
closes https://github.com/DIRACGrid/DIRAC/issues/5232
*Core
FIX: Use selectors(2) instead of select.select to avoid issues with file descriptors > 1024
=> [v7r2] Use selectors module

src/DIRAC/Core/Utilities/ElasticSearchDB.py
*Core
FIX: ElasticSearchDB: use ca certs file if requested
=> [v7r2] ElasticSearchDB: use ca certs file if requested

src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py
Since v7r2p5 the sandboxes from jobs in the transformation system are kept permanently as the jobs are never unassigned. This is because the sandboxes are removed when the `JobCleaningAgent` moves jobs to the `Deleted` status:
https://github.com/DIRACGrid/DIRAC/blob/31229839611bbd75fc05eb6fb183b3acedfe0ac7/src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py#L233
For jobs which are managed by the transformation system this is instead done by the `TransformationCleaningAgent`:
https://github.com/DIRACGrid/DIRAC/blob/31229839611bbd75fc05eb6fb183b3acedfe0ac7/src/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py#L645
This fixes it by moving the call to `SandboxStoreClient().unassignJobs` time that jobs are actually removed to ensure that there is no way for jobs to …
=> [v7r2] Fix bug where transformation system sandboxes are kept forever

src/DIRAC/WorkloadManagementSystem/DB/VirtualMachineDB.py, src/DIRAC/WorkloadManagementSystem/Service/VirtualMachineManagerHandler.py, tests/Integration/WorkloadManagementSystem/Test_VirtualMachineDB.py, tests/Integration/WorkloadManagementSystem/Test_VirtualMachineManagerClient.py, tests/Integration/all_integration_client_tests.sh, tests/Integration/all_integration_server_tests.sh, tests/Jenkins/utilities.sh
Hi,
Here are some tests of the basic functionality of the VMDIRAC DB + Service. It also removes a bunch of unused functions (all of the pod stuff) and fixes up a few bugs that got introduced during the merge (found thanks to the new tests :-)
The tests only really focus on the core functions, but it's a start. The main things not tested are the history functions used by the web interface: I'm not really sure if they've worked in recent times, so they probably need additional attention in conjunction with the webapp code first anyway.
(Probably) closes #5283 .
Regards,
Simon
FIX: Fix-up minor errors introduced during VMDIRAC merge
NEW: Tests for VirtualMachine DB & Service
=> [v7r3] Add VMDIRAC Tests

src/DIRAC/ConfigurationSystem/Client/PathFinder.py
Fix getSystemURLs, getOptionsFromCFG can return None
*Core
FIX: fix bug in getSystemURLs
=> [v7r3] fix getSystemURLs

src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py
*Framework
FIX: Fix using the System Administrator to install Python 3 releases of DIRAC from Python 2
=> [v7r3] Fix installing Python 3 releases of DIRAC from Python 2

src/DIRAC/Workflow/Modules/Script.py, src/DIRAC/Workflow/Modules/test/Test_Modules.py
Fixes this crash seen in some LHCb user jobs for Python 2 pilots (Python 3 works already, output is from the newly added test):
```python
self.log.verbose(stdout)
self.log.verbose(stderr)
if os.path.exists(self.applicationLog):
self.log.verbose('Removing existing %s' % self.applicationLog)
os.remove(self.applicationLog)
with open('%s/%s' % (os.getcwd(), self.applicationLog), 'w') as fopen:
>       fopen.write("<<<<<<<<<< %s Standard Output >>>>>>>>>>\n\n%s " % (self.executable, stdout))
E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 44-49: ordinal not in range(128)
failed     = False
fopen      = <closed file '/home/cburr/Development/DIRAC-dev/DIRAC/applicationLog.txt', mode 'w' at 0x7fd8d666e030>
outputDict = {'OK': True, 'Value': (0, '█████╗
', '')}
self …
```
=> [v7r2] Fix UnicodeEncodeError when application log contains non-ascii characters

src/DIRAC/Resources/Computing/SingularityComputingElement.py, src/DIRAC/WorkloadManagementSystem/Utilities/Utils.py
*Resources
FIX: Pass --cfg /tmp/pilot.cfg when reusing host DIRAC installation in SingularityComputingElement
=> [v7r2] Pass --cfg /tmp/pilot.cfg when reusing host DIRAC installation in SingularityComputingElement

src/DIRAC/ConfigurationSystem/Client/ConfigurationClient.py
```python
File "/opt/dirac/versions/v7.3.0a20-1629294914/Linux-x86_64/lib/python3.9/site-packages/DIRAC/ConfigurationSystem/Client/ConfigurationClient.py", line 54, in commitNewData
return self.executeRPC('commitNewData', b64encode(sData))
File "/opt/dirac/versions/v7.3.0a20-1629294914/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Tornado/Client/TornadoClient.py", line 65, in executeRPC
rpcCall = {'method': method, 'args': encode(args)}
File "/opt/dirac/versions/v7.3.0a20-1629294914/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Utilities/JEncode.py", line 181, in encode
return json.dumps(inData, cls=DJSONEncoder)
File "/opt/dirac/versions/v7.3.0a20-1629294914/Linux-x86_64/lib/python3.9/json/__init__.py", line 234, in dumps
return cls(
File …
```
=> [v7r3] Fix editing the CS when running with Python 3 + tornado

src/DIRAC/TransformationSystem/Agent/TransformationAgent.py
```python
2021-08-19 05:43:42 UTC Transformation/TransformationAgent/[192] .__writeCache ERROR: Could not write replica cache file /opt/dirac/work/Transformation/TransformationAgent/ReplicaCache_192.pkl
File "/opt/dirac/versions/v7.3.0a20-1629294914/Linux-x86_64/lib/python3.9/site-packages/DIRAC/TransformationSystem/Agent/TransformationAgent.py", line 656, in __writeCache
pickle.dump(self.replicaCache.get(t_id, {}), fd)
TypeError: write() argument must be str, not bytes
```
=> [v7r3] Fix reading/writing TransformationAgent cache files for Python 3

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
*WMS
FIX: Allow Platform parameter to be missing from the queue configuration
=> [v7r3] Allow Platform to be missing from the queue parameters when submitting pilots

src/DIRAC/Core/Tornado/scripts/tornado_start_all.py
@fstagni you added this [here](https://github.com/DIRACGrid/DIRAC/pull/5214/files#diff-8990c56b0602bc15b3b5b3525ca77bd304daa6d4a725f060fe00da6d90c2e3daR39-R40) but I don't understand why it would be needed? It's a problem as it causes the configuration system to fail to initialise as it's before the option to use server certificates is set.
=> [v7r3] Fix running tornado-start-all without a proxy

requirements.txt
This is used by the LHCbDIRAC CI for the current production release so it should have been included in #5334.
For v7r3 the requirements.txt file has been removed and the LHCbDIRAC Python 2 CI has been moved to use conda.
=> [v7r2 ONLY] Add selectors2 to requirements.txt

docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
Fixes the issue that caused this DIRACOS pipeline to fail: https://gitlab.cern.ch/CLICdp/iLCDirac/DIRACOS/-/jobs/15899525
=> [integration] Allow GitHub PR commentBody to be None

src/DIRAC/Resources/MessageQueue/StompMQConnector.py
I think it would be useful to return `StompMQConnector`/`put` error when an exception raised.
*Resources
FIX: return error for StompMQConnector
=> [v7r2] return error in StompMQConnector.put()

src/DIRAC/Core/DISET/private/Service.py
*Core
CHANGE: __RCSID__ is no longer access for Python 3 based installations
=> [v7r3] Don't use __RCSID__ for Python 3 based installations

src/DIRAC/Resources/Storage/test/Test_FilePlugin.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py
One of the unit tests has started failing as in Python 3.9.7+ `shutil.copy` was fixed to raise `FileNotFoundError` instead of `IsADirectoryError`, see:
* https://bugs.python.org/issue43219
* https://github.com/python/cpython/pull/27082
It's an issue with the test code itself and not DIRAC.
Old behavour:
```python
$ python --version
Python 3.9.5
$ python -c 'import shutil; shutil.copy2("/tmp/tmpajr883ky/subDir", "/tmp/tmpcu9phq73/test/subDir")'
File "<string>", line 1, in <module>
File "/home/cburr/miniconda3/envs/dirac-development/lib/python3.9/shutil.py", line 435, in copy2
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/home/cburr/miniconda3/envs/dirac-development/lib/python3.9/shutil.py", line 264, in copyfile
with open(src, 'rb') as fsrc, …
```
=> [v7r2] Adapt Test_FilePlugin.py for https://bugs.python.org/issue43219

src/DIRAC/Core/DISET/private/Service.py
This causes a few errors each hour in the LHCb setup:
```
2021-09-07 08:11:47 UTC Configuration/Server [140400182417152] ERROR: ConnectionError ConnectionError: Error while receiving arguments ([2001:1458:301:21::100:54]:51290)[lhcb_user:mneedham] Error in _read: (104, 'Connection reset by peer'
) SSLError(104, 'Connection reset by peer')
2021-09-07 08:11:47 UTC Configuration/Server [140400182417152] ERROR: Exception while executing handler action
File "/opt/dirac/pro/DIRAC/Core/DISET/private/Service.py", line 631, in _executeAction
return response["Value"][0]
KeyError: 'Value'
```
*Core
FIX: Handle S_ERROR in Service._executeAction
=> [v7r2] Handle S_ERROR in Service._executeAction

RequestManagementSystem/DB/RequestDB.py
FIX: Fix the GROUP BY syntax in the RequestSummaryWeb to be compliant with MariaDB 10.5. The fix is backward compatible with MySQL 5.7
=> [v7r1] Fix group by syntax in ReqSummaryWeb

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Utilities/ReturnValues.py, src/DIRAC/Core/Utilities/test/Test_ReturnValues.py
This is an idea that I've been using for my own code with works which DIRAC which I think would be generally useful. As my explanation became a little long I've put it in a codimd document: https://codimd.web.cern.ch/8eEaG3lnRG2SiXCUS6WhFA#
If people approve of the idea I'll add tests and documentation.
*Core
NEW: Add unwrap and convertReturnValue to simplify writing code with exceptions
=> [v7r2] Helper functions to make working with errors easier

src/DIRAC/Core/DISET/private/Service.py, src/DIRAC/Core/DISET/private/ServiceConfiguration.py
In the LHCb master CS we've had an issue that it became overloaded. This was made worse by the fact that the new connections are added the the thread pool forever until the service is unable to serve any requests. This PR makes it so that if there are more than (approximately) 100 tasks queued up the service drops new connections.
*Core
CHANGE: Requests are now dropped if the backlog is too large 
=> [v7r2] Drop requests if a service is overloaded

.github/workflows/semantic.yml, docs/source/DeveloperGuide/CodingConvention/index.rst
Because I am more than fed up to browse a history with 376 consecutive "typo" or "fix" commit messages for a single file, I propose this extra action check which enforces a specific format (inspired by https://www.conventionalcommits.org/en/v1.0.0/#summary)
Details in the PR directly 
It's nothing really new, we already do the same effort to write it in a sort of similar way for the release news. 
That's an extra step towards a better life together.
*Test
NEW: force commit format
=> [v7r2] Add semantic tests for commits

src/DIRAC/TransformationSystem/Client/Transformation.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_TransformationSystem.py
*TS
FIX: Transformation.setBody correctly checks all the operation tuples
=> [v7r2] Transformation.setBody correctly checks all the operation tuples

src/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py, src/DIRAC/Core/DISET/private/Transports/SSLTransport.py, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py
Addresses https://github.com/DIRACGrid/DIRAC/issues/5114
Running the following code
```python
from DIRAC.Core.Base import Script
from DIRAC.Core.Base.Client import Client
from DIRAC.Core.Security.X509Chain import X509Chain
Script.parseCommandLine()
#service = 'Framework/ProxyManager'
service = 'WorkloadManagement/JobMonitoring'
print("With standard proxy")
c = Client()
c.setServer(service)
res = c.whoami()
print( res['Value']['DN'] if res['OK'] else res)
print("With a stolen proxy")
proxy = X509Chain()
proxy.loadProxyFromFile('/tmp/chaen/proxy.fstagni.lhcb_user')
c = Client(proxyChain=proxy)
c.setServer(service)
res = c.whoami()
print( res['Value']['DN'] if res['OK'] else res)
```
Without the fix
```bash
With standard proxy
/DC=ch/DC=cern/OU=Organic …
```
=> [v7r2] Reintroduce proxyChain parameter

AccountingSystem/DB/AccountingDB.py
*Accounting
FIX: GROUP BY statement syntax to be compatible with more recent SQL reference (e.g. as used in MariaDB 10.5). This fix is backward compatible.
=> [v7r1] fix syntax query

src/DIRAC/Interfaces/API/Dirac.py
Discard https://github.com/DIRACGrid/DIRAC/commit/dfbb53232dba40aff4bf0f04802877c51d078ab1 that resolve error described in previous hackathon https://trello.com/c/y7TgEuF7/40-multi-vo-tests. Now after the last lot of changes, this key returns correctly, so I canceled the last adjustment.
*Interfaces
FIX: Discard https://github.com/DIRACGrid/DIRAC/commit/dfbb53232dba40aff4bf0f04802877c51d078ab1.
=> [8.0] Discard dfbb532.

src/DIRAC/Resources/Computing/BatchSystems/SLURM.py
There is a bug in the `Slurm` module that prevents to get the status of the pilots.
*Resources
FIX: Slurm getJobStatus
=> [v7r2] Fix Slurm getJobStatus "need more than 0 value to unpack"

docs/source/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.rst, src/DIRAC/Resources/Computing/ARCComputingElement.py
This PR integrates the `emies` endpoint to the ARC CE.
Here are some slides from July 2020 presenting a status of ARC: https://indico.cern.ch/event/813749/contributions/3925796/attachments/2070723/3476159/ARC-July2020-gdb.pdf.
- We currently rely on `gridftp` that is, IIUC, going to be dropped in the future (slide 9).
- `emies` allows to interact directly with Arex services that will probably replace gridftpd services.
- We need `emies` to interact with some arc instances.
*Resources
NEW: Add emies endpoint to the ARC CE
=> [v7r3] Add Emies endpoint to ARCCE

src/DIRAC/Core/Utilities/ExecutorDispatcher.py, src/DIRAC/Core/Utilities/test/Test_ExecutorDispatcher.py
Explanation by ChrisB in https://codimd.web.cern.ch/j7tlF5_aRqmndtKMh96bgA?view
FIX: Ensure invalid tasks don't get rescheduled by ExecutorDispatcher
really unsure about this.
=> [v7r2] Executors fix: do not push the task back in the queue if it's not anymore there

src/DIRAC/Core/Base/Client.py, src/DIRAC/RequestManagementSystem/Client/ReqClient.py
*RMS
FIX: ReqClient uses correct credentials to talk to ReqProxies
FIX: ReqClient uses proper WMS client insteand of RPCClient
=> [v7r2] Use proper Client and credentials in ReqProxy

src/DIRAC/DataManagementSystem/scripts/dirac_dms_protocol_matrix.py, tests/Integration/DataManagementSystem/Test_Client_DFC.py
*DMS
FIX: adapt csv use to py3
*Test
FIX: adapt csv use to py3
=> [v7r2]csv library expects bytes in py2, str in py3

src/DIRAC/Core/scripts/dirac_configure.py, src/DIRAC/Core/scripts/dirac_deploy_scripts.py, tests/Jenkins/utilities.sh
*Core
FIX: unless explicitly set, do not skip the CA checks
=> [v7r2] fix: always removing the flag for skipping the CA checks

src/DIRAC/Resources/Computing/BatchSystems/Condor.py, src/DIRAC/Resources/Computing/BatchSystems/GE.py, src/DIRAC/Resources/Computing/BatchSystems/Host.py, src/DIRAC/Resources/Computing/BatchSystems/LSF.py, src/DIRAC/Resources/Computing/BatchSystems/OAR.py, src/DIRAC/Resources/Computing/BatchSystems/SLURM.py, src/DIRAC/Resources/Computing/BatchSystems/Torque.py, src/DIRAC/Resources/Computing/BatchSystems/executeBatch.py, src/DIRAC/Resources/Computing/SSHComputingElement.py, src/DIRAC/WorkloadManagementSystem/Utilities/PilotWrapper.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py
Draft because:
- make a review already
- fixes in https://github.com/DIRACGrid/DIRAC/commit/ba83558af4d852093bab2f6eb32de9af1bf64d9a can be propagated to other batch systems, if these ones are considered OK
*WMS
NEW: add support for execution of pilot wrappers when the python executable is not set
=> [v7r2] add support for execution of pilot wrappers when the python executable is not set

src/DIRAC/Resources/Cloud/cloudinit.template
Hi,
Here is the patch to update the VMDIRAC instances to use python3.
Regards,
Simon
CHANGE: Use python3 in VMDIRAC instances.
=> [v7r3] Update VMDIRAC boot template to use python3

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Tornado/Server/TornadoService.py, src/DIRAC/FrameworkSystem/DB/ProxyDB.py
@atsareg @TaykYoku I have absolutely no idea how the Tornado change will propagate to future branches, since I don't yet understand the refactoring
*Core
CHANGE: RequestHandler/TornadoService do not propagate callstack to client
*Framework
NEW: ProxyDB returns more DErrno
=> [v7r2] Error propagation from ProxyDB and remove callstack when returning

src/DIRAC/Resources/MessageQueue/StompMQConnector.py
The reconnection mechanism was effective only for listener.
Now, I just try to reconnect once in case a message cannot be sent
*Resources
FIX: Stomp MQ: reconnect in case of lost connection
=> [WIP][v7r2] fix (Stomp): reconnect in case of MQ producer

src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py
FIX: Optimizers: fail job if ISB LFN does not start with '/'
=> [v7r2] Optimizers: fail job if ISB LFN does not start with '/'

src/DIRAC/Core/DISET/ServiceReactor.py, src/DIRAC/Core/DISET/private/Service.py
In LHCb the changes in #5394 have turned out to occasionally cause issues with operations which need to interactions with the master CS (e.g. making edits).
After discussing with @chaen we've come to the conclusion that sleeping is better than dropping requests directly. This also allows the kernel TCP backlog to be effective.
*Core
CHANGE: Sleep instead of dropping requests when services are overloaded
=> [v7r2] Sleep instead of dropping requests when services are overloaded

src/DIRAC/Core/DISET/ServiceReactor.py, src/DIRAC/Core/DISET/private/Service.py
Sweep #5461 `Sleep instead of dropping requests when services are overloaded` to `rel-v7r3`.
=> [sweep:v7r3] Sleep instead of dropping requests when services are overloaded

.github/workflows/basic.yml, .github/workflows/integration.yml
To reduce the load on the CI I think we can remove some CI jobs without reducing the effective coverage.
Any thoughts?
=> [integration] Reduce number of CI jobs

.github/workflows/deployment.yml
The deployment of v7r2p29 failed with this error which was silently ignored by the CI:
```
Run OLD_STYLE=${GITHUB_REF##*/}
OLD_STYLE=${GITHUB_REF##*/}
NEW_STYLE=$(python -c "import diraccfg; major, minor, patch, pre = diraccfg.parseVersion('${OLD_STYLE}'); print(f'{major}.{minor}.{patch}', f'a{pre}' if pre else '', sep='')")
echo "Converted ${OLD_STYLE} version to ${NEW_STYLE}"
.github/workflows/make_release.py \
--token="***" \
--version="v${NEW_STYLE}" \
--rev="$(git rev-parse HEAD)"
git fetch --all --tags
shell: /usr/bin/bash -l {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.9.7/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.7/x64/lib
Converted v7r2p29 version to 7.2.29
File "/home/runner/work/DIRAC/DIRAC/.github/workflows/make_release.py …
```
=> [v7r2] Fix deployment CI job

src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py
* JobWrapper
CHANGE: We have race conditions between the termination of jobs and the failover request. There is also a problem with RAL storage as a failed upload would remove the file recovered by failover if this is too soon. Hence delay to 45 minutes the execution of failover requests
=> [v7r2] Increased failover request delay

src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py
Already swept in #5482 
*Framework
FIX: Allow Python 3 style pre-releases to be installed if the primary extension is a pre-release
=> [v7r3] Allow pre-releases if the primary extension is a pre-release

environment-py3.yml, environment.yml
There is an incompatibility between sphynx and the new docutils release that is exhibited in LHCbDIRAC 
Details: https://sourceforge.net/p/docutils/bugs/431/
```
sphinx-build -b html -d build/doctrees  -wsphinxWarnings source build/html
Running Sphinx v4.0.0
conf.py:     INFO: LHCbDIRACVERSION is 'integration'
conf.py:     INFO: Current location '/builds/chaen/LHCbDIRAC/docs/source'
conf.py:     INFO: DiracDocTools location '/opt/conda/envs/test-env/lib/python3.9/site-packages/diracdoctools/__init__.py'
conf.py:     INFO: DiracDocTools location '/opt/conda/envs/test-env/lib/python3.9/site-packages/diracdoctools/Utilities.py'
conf.py:     INFO: DiracDocTools location '/opt/conda/envs/test-env/lib/python3.9/site-packages/diracdoctools/cmd/__init__.py'
WARNING: while setting up extension …
```
=> [v7r2] fix (docs): remove docutils from the requirements

src/DIRAC/Core/Security/m2crypto/X509CRL.py, src/DIRAC/Core/Security/m2crypto/X509Chain.py
1. `os.open` doesn't clear the file before writing causing junk data to be appended if the original file is larger than the new data:
```python
import os
!echo "0123456789" > "example.txt"
!cat example.txt
0123456789
fd = os.open("example.txt", os.O_RDWR | os.O_CREAT)
os.write(fd, b"abcdef")
os.close(fd)
!cat example.txt
abcdef6789
```
2. `X509CRL.__str__` returns `bytes` instead of `str` for Python 3
*Core
FIX: Fix overwriting files from an X509Chain object
=> [v7r2] Fixes to X509CRL and X509Chain

environment.yml
Sweep #5556 `fix (docs): remove docutils from the requirements` to `integration`.
*Docs
CHANGE: Forces docutils to 0.17 because of bug with sphynx
=> [sweep:integration] fix (docs): remove docutils from the requirements

.github/workflows/integration.yml
Integration tests are fragile and take resources and a lot of time and I don't see the need for them when changing documentation or README for example. So I think it would be wise to turn them off in these cases.
*CI
CHANGE: don't run Integration tests for documentation changes
=> [v7r3] don't run Integration tests for documentation changes

src/DIRAC/AccountingSystem/private/Plotters/NetworkPlotter.py
The request Accounting -> Network -> Packet lost rate (magnified) causes an error:
```
ERROR: Error while generating the plots Value keys 100 - IF(SUM(PacketLossRate)/SUM(entriesInBucket)*10 > 100, 100, SUM(PacketLossRate)/SUM(entriesInBucket)*10), 100 are not defined
```
This RP should provide correct pattern.
*Accounting
FIX: provide correct pattern for reportMagnifiedPacketLossRate
=> [8.0] fix selectFields pattern for Network plot (hackathon fixes)

src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/FrameworkSystem/ConfigTemplate.cfg
Based on the discussion under #5397, the use of a **proxy** is likely to be preferred by users on the beginning, even when using the `DIRAC Authorization Service`. Therefore I think it will be more logical by default to allow users to receive **proxy** certificates in case of **successful** authorization through `DIRAC AS`, and the administrator will have an opportunity to forbid it using the `downloadablePersonalProxy` option.
*Framework
CHANGE: allow DIRAC AS return proxy by default
=> [integration] allow DIRAC AS return proxy by default

src/DIRAC/Core/Utilities/DIRACScript.py
In https://github.com/DIRACGrid/DIRAC/pull/5216 I fixed `extensionsByPriority()` to return the highest priority extension first to be more consistent in the SystemAdministrator. When doing this I forgot to fix it in DIRACScript so the DIRAC versions of scripts were being preffered to the LHCbDIRAC versions.
*Core
FIX: Extension ordering in DIRACScript
=> [v7r3] fix: Extension ordering in DIRACScript

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
=> fix (WMS): Fix UnicodeDecodeErrors in JobDB.getJobParameters

src/DIRAC/ConfigurationSystem/private/ServiceInterfaceBase.py
This solves the problem of the master CS being overloaded by not keeping it in the list of CS once new slaves are added 
*Configuration
CHANGE: do not add the master CS first in the list of CS when new slaves are added
=> [v7r3] Only expose masterCS if not using replicas

src/DIRAC/Core/Utilities/StateMachine.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
Fixes jobs that get stuck in completing with requests that are failing with:
```python
jsuc.setJobStatusBulk(
552878361,
{'2021-11-16 21:06:35.884937': {'ApplicationStatus': 'Executing RunScriptStep1', 'Source': 'Job_552878361'},
'2021-11-16 22:34:19.002077': {'ApplicationStatus': 'exe-script.py successful', 'Source': 'Job_552878361'}},
False
)['Message'] ==  "getNextState: '' is not a valid state"
```
FIX: Don't run JobsStateMachine if newStat is ''
=> [v7r3] Don't run JobsStateMachine if newStat is ''

src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py
*Framework
FIX: Issue installing DIRAC and extensions on servers running Python 3
=> [v7r3] Fix installing extensions on Python 3 based servers

tests/Integration/Resources/Storage/Test_Resources_GFAL2StorageBase.py
Sweep #5576 `test: fix http/https typo in Test_Resources_GFAL2StorageBase` to `integration`.
Closes #5579
*Test
FIX: fix typo in the HTTPs Resources tests
=> [sweep:integration] test: fix http/https typo in Test_Resources_GFAL2StorageBase

src/DIRAC/FrameworkSystem/Service/SystemAdministratorHandler.py
Sweep #5600 `Fix installing extensions on Python 3 based servers` to `integration`.
Closes #5602
*Framework
FIX: Issue installing DIRAC and extensions on servers running Python 3
=> [sweep:integration] Fix installing extensions on Python 3 based servers

src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py
⚠️ I'm not certain this is the right solution but somehow we have to prevent it going further and trying to do ``WHERE (`Owner`, `OwnerGroup`) IN (  ) AND``:
```
ERROR  _query (SELECT `Status`, COUNT(*) FROM `Jobs`    WHERE (`Owner`, `OwnerGroup`) IN (  ) AND `LastUpdateTime` < "2021-11-17 13:11" GROUP BY `Status...
```
FIX: Return error if JobPolicy.getControlledUsers returns an empty list
=> [v7r3] Return error if JobPolicy.getControlledUsers returns an empty list

src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Client/WMSClient.py
⚠️ The bug fixed here has most probably created a (larg-ish) number of jobs in status "DELETED" that will stay "forever" unless a manual intervention is made. I will post a solution in a discussion linked to this PR.
FIX: fix bug in TransformationCleaningAgent, that was NOT removing jobs but only deleting them
*WMS
FIX: removing jobs instead of deleting them when bulk submission fails
=> [v7r2] Fix bug in TransformationCleaningAgent, that was NOT removing jobs but only deleting them

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
The last hackathon found many error messages that were not really errors. This PR is intended to fix messages about return response.
*Core
FIX: change tornado response messages
=> [8.0] edit response messages (Tornado Server) (hackathon fixes)

src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg, src/DIRAC/RequestManagementSystem/Service/ReqProxyHandler.py
Until now, we were sweeping 10 requests every 2 minutes, and this is hardcoded. Needless to say that when you have thousands of requests in the cache, it sucks :-)
*RMS
NEW: add SweepSize option to the ReqProxy
=> [v7r3] feat (RMS): ReqProxy takes the number of request to sweep from the CS

src/DIRAC/FrameworkSystem/DB/ComponentMonitoringDB.py
Trivial bug fix 
```
2021-11-18 09:59:19 UTC Framework/Monitoring/Framework/ComponentMonitoringDB ERROR: Not found URL for allVoBoxes service.
2021-11-18 09:59:19 UTC Framework/Monitoring ERROR: Uncaught exception when serving RPC Function getComponentsStatus
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 302, in __RPCCallFunction
uReturnValue = oMethod(*args)
File "/opt/dirac/pro/DIRAC/FrameworkSystem/Service/MonitoringHandler.py", line 248, in export_getComponentsStatus
return gServiceInterface.getComponentsStatus(condDict)
File "/opt/dirac/pro/DIRAC/FrameworkSystem/private/monitoring/ServiceInterface.py", line 639, in getComponentsStatus
return self.compmonDB.getComponentsStatus(condDict)
File …
```
=> [v7r3] getComponentsStatus bug whith empty service list

src/DIRAC/FrameworkSystem/DB/ComponentMonitoringDB.py
Sweep #5614 `getComponentsStatus bug whith empty service list` to `integration`.
*Framework
FIX: continue on empty service list in getComponentsStatus
Closes #<built-in function id>
Closes https://github.com/DIRACGrid/DIRAC/issues/5616
=> Sweep #5614 `getComponentsStatus bug whith empty service list` to `integration`

src/DIRAC/TransformationSystem/Agent/TransformationCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py
This is a fix on the (wrong) fix originally provided in #5598 (for which the warning was not justified!)
*TS
FIX: TransformationCleaningAgent 'deletes', do not 'remove' jobs
=> [v7r2] fix: TransformationCleaningAgent 'deletes', do not 'remove' jobs

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Core/Tornado/Server/TornadoServer.py
*Core
CHANGE: use DIRAC_DEBUG_M2CRYPTO to enable SSL debugging in tornado
=> [WIP] [v7r3] More debug for tornado

src/DIRAC/FrameworkSystem/Agent/MyProxyRenewalAgent.py, src/DIRAC/FrameworkSystem/ConfigTemplate.cfg, src/DIRAC/FrameworkSystem/DB/ProxyDB.py, src/DIRAC/FrameworkSystem/Service/ProxyManagerHandler.py
The email address used to send reminder emails about expired proxy was configured in the DB... 
This refactoring makes it take from the Service or Agent config, which is much more sensible. I will update the wiki accordingly once merged and released
*Framework
CHANGE: proxy expiration emails are sent from an address taken from the Service/Agent config instead of the DB
=> [v7r3] ProxyDB sender email taken from the service/agent config

.gitignore, docs/source/AdministratorGuide/Systems/Transformation/index.rst, docs/source/AdministratorGuide/Tutorials/dmsWithTs.rst, docs/source/DeveloperGuide/Systems/Transformation/bodyplugin.rst, docs/source/DeveloperGuide/Systems/Transformation/index.rst, src/DIRAC/TransformationSystem/Client/BodyPlugin/BaseBody.py, src/DIRAC/TransformationSystem/Client/BodyPlugin/DummyBody.py, src/DIRAC/TransformationSystem/Client/RequestTasks.py, src/DIRAC/TransformationSystem/Client/Transformation.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_RequestTasks.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_TransformationSystem.py
Hopefully the tests and documentation in this PR are clear enough to explain what is achieved. 
The basic aim is to be able to have a more dynamic way of creating `Requests` from a `Task`. 
The first attempt was with 2685bb53565b9b4c70ef40f75e7cc398d618022f and this worked nicely.
But then I wanted more, so I introduced Body Plugins a5823faf1e5e9ee373285b5ef1afda1499876cc6
The driving reason is the data export of LHCb. 
@andresailer this is what we talked about. Inheriting from the `Transformation` object was highly impractical for several reasons. 
*TS
NEW: Allow MultiOperation body to fetch values from the task dict
NEW: Introduce Body Plugins for DMS transformations
=> [v7r3] Transformation system more flexible

src/DIRAC/Resources/Computing/BatchSystems/Condor.py, src/DIRAC/Resources/Computing/CREAMComputingElement.py, src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py, src/DIRAC/Resources/Computing/LocalComputingElement.py, src/DIRAC/Resources/Computing/test/Test_HTCondorCEComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/Service/PilotManagerHandler.py, src/DIRAC/WorkloadManagementSystem/Service/WMSAdministratorHandler.py, src/DIRAC/WorkloadManagementSystem/Service/WMSUtilities.py
This PR aims to solve part of the issues that we have with the pilot wrappers: https://github.com/DIRACGrid/DIRAC/issues/5136
Currently, the `Site Director` lets HTCondor the responsibility of deleting the pilot wrappers after their execution because jobs would fail otherwise.
Thus, `HTCondorCE` needs to perform `find` calls to retrieve and delete all the old pilot wrappers that are not needed anymore.
In this PR, we add the `-spool` option to `condor_submit` that allows to immediately spool the required inputs data with the job during the submission. Thus, pilot wrappers can be modified/deleted just after the submission without impacting the jobs.
`-spool` is only used by the local condor_schedd because the `-remote` option, according to the documentation, performs `-spool` internally: …
=> [v7r3] Refactor WMSUtilities and better handle logs and executables in HTCondorCE

src/DIRAC/DataManagementSystem/scripts/dirac_dms_directory_sync.py
*DMS
FIX: dirac-dms-directory-sync: The script will now try all files and not end a thread if one of the files assigned to be uploaded or downloaded to a thread fails. The script will also print out all failed files, and their error at the end of a thread. A few log messages have been corrected as well.
=> [v7r2] fix (DMS): directory-sync: better failure logging, later abort

src/DIRAC/FrameworkSystem/Client/SystemAdministratorClientCLI.py
closes #5621 
*Framework
FIX: SystemAdministratorCLI: get DIRAC version from Extensions
=> [v7r3] Fix SystemAdministratorCLI

src/DIRAC/Core/Utilities/ExecutorDispatcher.py
*Core
FIX: Tasks never get removed from the ExecutorState if an UnrecoverableTaskException is raised
=> [v7r2] More executor fixes

docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst
*Monitoring
FIX: Wrong link on the docs page for the WMSHistory dashboard. Fixed the link and edited some of the text.
=> [integration] fix: Documentation on dashboards 

src/DIRAC/__init__.py
*Core
FIX: DIRAC.isPy3VersionNumber always returns True
=> [v7r3] Fix DIRAC.isPy3VersionNumber always returns True

src/DIRAC/WorkloadManagementSystem/Service/OptimizationMindHandler.py
Sweep #5639 `Fix typo in OptimizationMindHandler.exec_taskError` to `integration`.
FIX: Bad error handling in OptimizationMindHandler.exec_taskError
Closes #5640
=> [sweep:integration] Fix typo in OptimizationMindHandler.exec_taskError

docs/source/AdministratorGuide/Resources/computingelements.rst, src/DIRAC/ConfigurationSystem/Agent/Bdii2CSAgent.py, src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/ConfigurationSystem/ConfigTemplate.cfg, src/DIRAC/ConfigurationSystem/scripts/dirac_admin_add_resources.py
*CS
CHANGE: Bdii2CSAgent: add InjectSingleCoreQueue option to automatically create single core equivalents for MutliCore Queues , kind of fixes #5582
CHANGE: Bdii2CSAgent: CEs in the BannedCEs list are no longer updated by the agent, previously this list only concerned CEs that are not already in the Configuration, fixes  #5224 
CHANGE: dirac-admin-add-resources: add --onecore option to automatically create single core equivalents for MutliCore Queues
FIX: dirac-admin-add-resources: fix the query about adding new CEs, this can now be answered in the negative
=> [v7r2] Bdii2CSAgent features: bannedCEs, SingleCoreQueues

docs/source/AdministratorGuide/Resources/computingelements.rst, src/DIRAC/ConfigurationSystem/Agent/Bdii2CSAgent.py, src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/ConfigurationSystem/ConfigTemplate.cfg, src/DIRAC/ConfigurationSystem/scripts/dirac_admin_add_resources.py
from  #5660 
(cherry picked from commit 515c352bd36505642c72f56ed7d0d581c522f46f)
fixes #5679 
*CS
CHANGE: Bdii2CSAgent: add InjectSingleCoreQueue option to automatically create single core equivalents for MutliCore Queues , kind of fixes #5582
CHANGE: Bdii2CSAgent: CEs in the BannedCEs list are no longer updated by the agent, previously this list only concerned CEs that are not already in the Configuration, fixes  #5224 
CHANGE: dirac-admin-add-resources: add --onecore option to automatically create single core equivalents for MutliCore Queues
FIX: dirac-admin-add-resources: fix the query about adding new CEs, this can now be answered in the negative
=> [v7r3] sweep Bdii2CSAgent features: bannedCEs, SingleCoreQueues

src/DIRAC/ConfigurationSystem/Client/VOMS2CSSynchronizer.py
From the hackathon
*CS
FIX: fix an exception in the VOMS2CSAgent when a user joins a second VO
=> [V7r2] voms2cs agent fix when joining second VO

src/DIRAC/Core/Utilities/DEncode.py
```log
2021-12-07 13:51:41 UTC Transformation/TransformationManager ERROR: Exception while executing handler action
File "/opt/dirac/versions/v10.3.3-1638259177/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/Service.py", line 608, in _executeAction
response = handlerObj._rh_executeAction(proposalTuple)
File "/opt/dirac/versions/v10.3.3-1638259177/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/RequestHandler.py", line 156, in _rh_executeAction
result = self.__trPool.send(self.__trid, retVal)  # this will delete the value from the S_OK(value)
File "/opt/dirac/versions/v10.3.3-1638259177/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/TransportPool.py", line 113, in send
return transport.sendData(msg)
File …
```
=> [v7r2] Fix encodeDict when the dict keys have mixed types

src/DIRAC/Core/Utilities/ThreadSafe.py
When constructing documentation, the description of the methods marked by the decorator disappears.
*Core
FIX: ThreadSafe.Synchronizer: Add target method docstring to preserve docstring of decorated function
=> [integration] add target method docstring (Synchronizer decorator)

src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py
*WMS
FIX: ElasticJobParametersDB: get in output all entries
=> [v7r2] fix: ElasticJobParametersDB: get in output all entries

environment-py3.yml, environment.yml, src/DIRAC/WorkloadManagementSystem/Client/CPUNormalization.py, src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_cpu_normalization.py
This PR aims to replace the copy of the old `DB12.py` by the new db12 package.
Before merging this PR, the following PRs should be merged:
- https://github.com/DIRACGrid/DIRACOS/pull/192
- https://github.com/DIRACGrid/DIRACOS2/pull/61
CHANGE: Replace DB12.py with the db12 package
=> [v7r3] feat (wms): use db12 package to compute cpu power

src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, tests/CI/install_server.sh
Currently the integration test CI doesn't support HTTPS-only services as it adds them by running sed to change `dips://` URLs to `https://`. This change makes it so that `dirac-install-tornado-service` adds the service to the CS automatically, the same way that legacy services are done.
The reason for making this change is to support HTTPS-only services.
*HTTPS
FIX: Add URLs to CS when installing HTTPS services
=> [v7r3] Add URLs to CS when installing HTTPS services

src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py
There must have been a regression at some point during a refactoring.
The CA path was not properly passed to `requests` so CA verification was not effective
*Core
FIX: TornadoBaseClientcorrectly checks CA 
=> [v7r3] Correct check of CA location in TornadoBaseClient

.github/workflows/integration.yml, docs/source/AdministratorGuide/ExternalsSupport/index.rst, docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst, environment.yml, src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/MonitoringSystem/DB/MonitoringDB.py
The package `opensearch-dsl` is not yet available with conda-forge - a [pull request](https://github.com/conda-forge/staged-recipes/pull/17180) was opened to add the package.
Resolves #5167.
*Core
CHANGE: Replacing Elasticsearch python client with OpenSearch. 
=> [integration] Replace Elasticsearch clients with OpenSearch, remove support for ES6 - resolves #5167

src/DIRAC/ConfigurationSystem/Client/Helpers/CSGlobals.py, src/DIRAC/ConfigurationSystem/Client/Helpers/__init__.py, src/DIRAC/TransformationSystem/scripts/dirac_production_runjoblocal.py
The result of `importlib.import_module` is a bit different than `imp.find_module`, so I think that without this fix it will work differently. I have already expressed my opinion https://github.com/DIRACGrid/DIRAC/pull/5617#discussion_r758307808.
*Configuration
FIX: fix CSGlobals.Extensions class
=> [integration] remove CSGlobals.Extensions class

src/DIRAC/Resources/Computing/InProcessComputingElement.py, src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
Quick fix to convert a tuple into a list in `JobAgent`.
This should resolve one of the issue we had during the hackaton with the `InProcessCE`. 
FIX: convert inputs from tuple to list in JobAgent before submitting to a CE
=> [v7r3] hackaton fix (wms): JobAgent submitJob inputs

src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py
The LHCb optimisers failed spectacularly with:
```
11:53 AM
2021-12-16 10:53:24 UTC WorkloadManagement/Optimizers ERROR: Error while processing task 565300222
File "/opt/dirac/versions/v10.3.3-1638280653/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Base/ExecutorReactor.py", line 184, in __moduleProcess
result = modInstance._ex_processTask(taskId, taskStub)
File "/opt/dirac/versions/v10.3.3-1638280653/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/Base/ExecutorModule.py", line 146, in _ex_processTask
result = self.processTask(taskId, taskObj)
File "/opt/dirac/versions/v10.3.3-1638280653/Linux-x86_64/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/Executor/Base/OptimizerExecutor.py", line 84, in processTask
optResult = …
```
=> [v7r2] JobSanity doesn't handle input sanboxes named "LFN:"

src/DIRAC/WorkloadManagementSystem/Executor/JobSanity.py
Sweep #5742 `JobSanity doesn't handle input sanboxes named "LFN:"` to `rel-v7r3`.
FIX: JobSanity doesn't handle input sanboxes named "LFN:"
Closes #5747
=> [sweep:v7r3] JobSanity doesn't handle input sanboxes named "LFN:"

src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py
Sweep #5729 `Get Tornado's port from the CS when adding URLs` to `integration`.
*Framework
FIX: Get Tornado's port from the CS when adding URLs
Closes #5731
=> [sweep:integration] Get Tornado's port from the CS when adding URLs

dirac.cfg, docs/source/AdministratorGuide/Resources/storage.rst, src/DIRAC/Resources/Storage/GFAL2_XROOTStorage.py, src/DIRAC/Resources/Storage/StorageBase.py
There are cases when specific storage can input/output more protocols with a given plugin than other storages (e.g. some tape are SRM+HTTPs ready, some aren't, `dCache` can return `xroot` instead of `root`, `Storm` can return `file`, etc). 
This PR allows to overwrite the hardcoded default with a CS configuration. This was meant to be possible from the beginning when I introduced multi protocol, but somehow, it did not make it into the code. Now, it's here
(triggered by https://github.com/DIRACGrid/DIRAC/issues/5727)
*Resources
NEW: allow to overwrite input/output  storage plugin parameter with the CS
CHANGE: add "xroot" to the list of input protocol for the XROOT plugin
=> [v7r3] Allow to specify input protocol in the CS 

src/DIRAC/Interfaces/API/Dirac.py, src/DIRAC/WorkloadManagementSystem/Client/JobStatus.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
*Interfaces
CHANGE: DIRAC APIs check if a JobState transition is allowed
=> [v7r3] DIRAC APIs check if a JobState transition is allowed

src/DIRAC/FrameworkSystem/Agent/test/Test_ComponentSupervisionAgent.py
Currently the tests use `psutil.Error` when mocking which isn't intended to be used directly (see [here](https://github.com/giampaolo/psutil/blob/18348c9b6b66ff12abbbfeaebbe2218cdc6b5556/psutil/_common.py#L279-L310)) causing the CI to fail. Even though it's been fixed upstream I think it's better to raise one of the specialised exception classes instead.
No need for release notes.
=> [v7r2] Fix mocking of psutil

src/DIRAC/TransformationSystem/Service/TransformationManagerHandler.py
In https://github.com/DIRACGrid/DIRAC/pull/5327/ `Scheduled` was removed from `TASKS_STATE_NAMES` however this can be a valid state from the DMS.
Fix: Restore task state "Scheduled"
=> [v7r3] Restore task state "Scheduled"

src/DIRAC/WorkloadManagementSystem/Agent/PilotStatusAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/tests/Test_JobStateUpdate.py
*WMS
FIX: better use the job state machine when setting the job status, in particular when it comes from failover requests that may be inserted between 2 successful updates. 
Note: there is still a pending question about what to do if the state machine refuses the status change... Currently it basically remains unchanged, but is it the right thing?
=> [v7r3] Fix setJobStatus service

src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/FrameworkSystem/ConfigTemplate.cfg, src/DIRAC/FrameworkSystem/private/authorization/AuthServer.py, tests/Integration/Framework/Test_AuthServer.py
From discussion https://codimd.web.cern.ch/2ctS6OH5QZiMJqJLXaMivw?view.
*Framework
FIX: rename downloadablePersonalProxy value to allowProxyDownload
=> [integration] rename downloadablePersonalProxy value

src/DIRAC/WorkloadManagementSystem/Agent/PilotStatusAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, src/DIRAC/WorkloadManagementSystem/Service/tests/Test_JobStateUpdate.py
Sweep #5719 `Fix setJobStatus service` to `integration`.
Adding original author @phicharp as watcher.
*WMS
FIX: better use the job state machine when setting the job status, in particular when it comes from failover requests that may be inserted between 2 successful updates. 
Closes #5792
=> [sweep:integration] Fix setJobStatus service

.readthedocs.yaml
Howdy! :wave:
I am @readthedocs-assistant and I am sending you this pull request to upgrade the configuration of your Read the Docs project.
Your project will continue working whether or not you merge it, but I recommended you take it into consideration.
Also, in case you haven't done it already, remember that you can enable the pull request builds for your project to see the effect of these changes. To do it, [follow the instructions](https://docs.readthedocs.io/en/stable/pull-requests.html), close this pull request, and open it again.
_*Note*: This tool is in beta phase. Don't hesitate to ping @astrojuanlu and/or @humitos if you spot any problems._
The following migrators were applied:
- Migrate to `build.tools` configuration.
This uses the new base Docker image based on Ubuntu 20.04 …
=> Update Read the Docs configuration (automatic)

src/DIRAC/Interfaces/API/Dirac.py
#5752 introduced a check of the job status transition in the API. However, this check only accepts single job ID, while the methods calling it used list of job IDs. This resulted in exceptions like this one
```python
>>> dirac.deleteJob(577500249)
File "<stdin>", line 1, in <module>
File "/cvmfs/lhcb.cern.ch/lhcbdirac/versions/v10.4.6-x86_64-1641914322/lib/python3.9/site-packages/DIRAC/Interfaces/API/Dirac.py", line 1678, in deleteJob
res = JobStatus.checkJobStateTransition(jobID, JobStatus.DELETED)
File "/cvmfs/lhcb.cern.ch/lhcbdirac/versions/v10.4.6-x86_64-1641914322/lib/python3.9/site-packages/DIRAC/WorkloadManagementSystem/Client/JobStatus.py", line 114, in checkJobStateTransition
currentStatus = res["Value"][jobID]["Status"]
TypeError: unhashable …
```
=> [v7r3] fix (API): checkJobStateTransition needs a single jobID

src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_cpu_normalization.py
This PR enables logs coming from `db12` in the `dirac-wms-cpu-normalization` script.
CHANGE: enable logs from db12 in dirac-wms-cpu-normalization
=> [v7r3] feat(wms): enable logs from db12 in dirac-wms-cpu-normalization

docs/source/AdministratorGuide/ServerInstallations/InstallingDiracServer.rst
Just one very small fix related to this previous PR: https://github.com/DIRACGrid/DIRAC/pull/5823
*docs
FIX: fix indentation in the doc related to the server installation
=> [8.0] fix(docs): fix indentation

src/DIRAC/TransformationSystem/DB/TransformationDB.sql
This of course requires a manual intervention, that can be done at any time (not really depending from this release). On LHCb clone of TransformationDB it took rather long:
```
MySQL [TransformationDB]> ALTER TABLE `TransformationMetaQueries` MODIFY COLUMN `MetaDataValue` TEXT;
Query OK, 0 rows affected (0.11 sec)
Records: 0  Duplicates: 0  Warnings: 0
MySQL [TransformationDB]> ALTER TABLE `AdditionalParameters` MODIFY COLUMN `ParameterValue` LONGTEXT;
Query OK, 2353784 rows affected (3 min 39.64 sec)
Records: 2353784  Duplicates: 0  Warnings: 0
MySQL [TransformationDB]> ALTER TABLE `Transformations` MODIFY COLUMN `Body` LONGTEXT;
Query OK, 145680 rows affected (27 min 9.51 sec)
Records: 145680  Duplicates: 0  Warnings: 0
MySQL [TransformationDB]> 
MySQL [TransformationDB]> ALTER TABLE …
```
=> [8.0] TransformationDB: removing BLOB in favor of TEXT for non-binary data

src/DIRAC/TransformationSystem/Client/TaskManager.py, src/DIRAC/TransformationSystem/DB/TransformationDB.py
The fix in TaksManager fixes the original problem discovered during the hackathon, the fix in transformationDB is a followup issue.
I guess this comes from the JSON encode/decode where integer keys are no longer supported?
*TS
FIX: Convert fileID / taskID to fix issue when task status is updated in transformation treatment
=> [integration] [hackathon] fix(transformation): convert task/file ID to integer to fix type mismatch

src/DIRAC/ConfigurationSystem/Client/VOMS2CSSynchronizer.py
We had the problem that when a user  has 2 DNs from 2 CAs, the `VOMS2CS` agent will correctly set 2 DNs in the `Users` registry, but the `CA` would be oscillating at each run.
This PR makes sure that the 2 CAs are added.
Caution: an incorrect CS will not be modified, i.e. if you have that case, you have to fix it by hand. The easier is to keep in the CS only one DN with the correct CA, and run the agent. The new DN and new CA will be correctly added  
*Configuration
FIX: VOMS2CSAgent correctly takes into account multiple CAs for users with multiple DNs
=> [v7r3] VOMS2CS: update correctly CAs for users with multiple DNs

src/DIRAC/Core/Tornado/Server/TornadoREST.py, src/DIRAC/Core/scripts/dirac_info.py, src/DIRAC/FrameworkSystem/API/AuthHandler.py, src/DIRAC/FrameworkSystem/private/authorization/AuthServer.py, src/DIRAC/FrameworkSystem/private/authorization/utils/Clients.py, src/DIRAC/FrameworkSystem/scripts/dirac_login.py, src/DIRAC/Resources/IdProvider/CheckInIdProvider.py, src/DIRAC/Resources/IdProvider/IAMIdProvider.py, src/DIRAC/Resources/IdProvider/OAuth2IdProvider.py
This PR contains some fixes related to python 3 and some bug fixes found during the last OAuth 2 tests.
*Core
FIX: TorandoREST ignore arguments that not defined in the target method
FIX: dirac-info show "None found" instead of exception
*Framework
FIX: use payload keyword argument for handle_response method
CHANGE: use DIRAC CAs location to request DIRAC AS
FIX: fix message in dirac-login after authorization
*Resources
CHANGE: verify CAs when request IdP by default
=> [8.0] common oauth 2, python 3 fixes

src/DIRAC/ResourceStatusSystem/Service/PublisherHandler.py
Essence:
`getSite` can return `S_ERROR` result or just a `str`. `S_ERROR` result can be passed to `selectStatusElement` and I think its not very good.
```python
site = self.getSite(elementType, elementName)
if not site:
return S_ERROR("No site")
siteStatus = self.rsClient.selectStatusElement(
"Site", "Status", name=site, ...
```
Fix:
Force `getSite` to return `S_OK`/`S_ERROR`
*ResourceStatus
FIX: return S_OK/S_ERROR in PublisherHandler.getSite
=> [v7r2] return standard result in PublisherHandler.getSite

src/DIRAC/MonitoringSystem/Client/Types/PilotSubmissionMonitoring.py, src/DIRAC/MonitoringSystem/Client/Types/WMSHistory.py, src/DIRAC/MonitoringSystem/private/Plotters/PilotSubmissionMonitoringPlotter.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Error in pilot submission monitoring as no plots can be generated in WebApp and no monitoring fields are discovered in the indices in ES-Kibana. 
Changed name in methods for PilotSubmissionMonitoringPlotter to fix the issue of the missing plots selectors on the WebApp.
*Monitoring
FIX: Changed name of methods in PilotSubmissionMonitoringPlotter
=> [integration] Hackaton fix for Pilot Submission Monitoring

src/DIRAC/RequestManagementSystem/Client/ReqClient.py, src/DIRAC/WorkloadManagementSystem/Client/JobMinorStatus.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/Service/JobMonitoringHandler.py, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py
In order to better reflect the last sign of life of a job in the web Job Monitor page, we changed the following: the HeartBeatTime is set every time a status is changed by the job itself (i.e. from JobAgent, Job watch dog or JobWrapper), and the `LastSignOfLife` is using the `HeartBeatTime` if it is set.
*WMS
CHANGE: HeartBeatTime is set every time a status is changed by the job itself
In passing add a minor status in `JobMinorStatus.py` to avoid strings in the code
=> [v7r3] Better estimate of last sign of life of jobs in web Job Monitor

src/DIRAC/Core/DISET/RequestHandler.py, src/DIRAC/Core/Tornado/Server/TornadoService.py
Currently when services return `S_ERROR` the callstack gets stripped from the object. This is nice from a security perspective however this information can be useful when debugging.
Instead I propose we include the callstack in the service logs when showing the error's `["Message"]`.
Any thoughts?
*Core
CHANGE: Show callstack in service logs when returning S_ERROR
=> [v7r3] Show callstack in service logs before cleaning it

src/DIRAC/Core/Security/test/Test_X509Chain.py, src/DIRAC/FrameworkSystem/Client/ProxyGeneration.py, src/DIRAC/FrameworkSystem/Client/ProxyManagerClient.py, src/DIRAC/FrameworkSystem/Client/ProxyUpload.py, src/DIRAC/FrameworkSystem/Service/ProxyManagerHandler.py, src/DIRAC/FrameworkSystem/scripts/dirac_proxy_init.py, tests/Jenkins/utilities.sh
it seems that the definition of `rfc` parameter does not affect anything anymore, this PR remove it
*Framework
CHANGE: remove unused 'rfc' argument
=> [integration] remove unused 'rfc' argument

src/DIRAC/WorkloadManagementSystem/Client/JobMinorStatus.py, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.py, src/DIRAC/WorkloadManagementSystem/DB/JobDB.sql, src/DIRAC/WorkloadManagementSystem/DB/PilotAgentsDB.sql, src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py, tests/Integration/WorkloadManagementSystem/Test_Client_WMS.py, tests/Integration/WorkloadManagementSystem/Test_JobDB.py
resolves #5253 
*WMS
CHANGE: Replace BLOBs with TEXTs for JobDB and PilotAgentsDB
=> [8.0] Replace BLOBs with TEXTs for JobDB and PilotAgentsDB

src/DIRAC/Core/Tornado/Server/HandlerManager.py
No need for release notes but I think this would be useful for being able to tell if extensions are being loaded correctly.
=> [8.0] Show which handler is being loaded by tornado service

src/DIRAC/Core/Base/AgentModule.py
No need for sweeping as this is already done in the `integration` branch.
*Core
CHANGE: Use importlib.metadata rather than __RCSID__ for getting AgentModule version
=> [v7r3] Don't use __RCSID__ when running AgentModule with Python 3

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
`sLog.debug` dont'n show all useful details about raised errors from `_gatherPeerCredentials` method.
*Core
FIX: print error details/callstack in BaseRequestHandler
=> [integration] print error details/callstack in BaseRequestHandler

src/DIRAC/FrameworkSystem/scripts/dirac_login.py
The problem observed in today hackaton was due to an incorrect call to `setVOMSAttributes`.  
The `chain` given was actually the certificate, while what you want to give it is the proxy generated from the chain. But `chain.generateProxyToFile` does generate a proxy, but does not update the `chain` object (and it is not what we want). 
So the solution is to give the generated proxy location to `setVOMSAttributes`
*Framework
FIX: dirac-login uses the correct proxy to add VOMS attributes
=> [8.0] fix (dirac-login): pass the file location to setVOMSAttributes

src/DIRAC/Core/Base/AgentModule.py
This reverts commit b8fd6a580ddd6c5264f6b237bceaf801bd0a13e9.
We've seen an issue that `self.__initializeMonitor()` is now called after `self.initialize(*initArgs)` meaning that any agents with an initialize that calls `gMonitor.registerActivity` silently fail as [this condition](https://github.com/DIRACGrid/DIRAC/blob/d9dd4c772f33116aa70578d803fbf397be17d55d/src/DIRAC/FrameworkSystem/Client/MonitoringClient.py#L221-L241) isn't met.
I'll assign to @fstagni as I'm not sure why this change was made in the first place.
*Core
FIX: Revert "moved initialization of monitoring after agent initialize()"
=> [v7r3] Revert "moved initialization of monitoring after agent initialize()"

src/DIRAC/RequestManagementSystem/scripts/dirac_rms_request.py
Thanks to the idiotic PEP-515, our request names `<transformationID>_<counter>` are considered as number... 
We could envisage using a `-` instead of a `_` but that could break some scripts relying on this convention. Not much though...
*RMS
FIX: dirac-rms-request takes into account PEP-515 
=> [v7r3] Take into account pep-515 for Request names

src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
To execute jobs in parallel within a singularity container, one has to specify `LocalCEType = Pool/Singularity` in a given CE configuration.
It seems that the `InnerCESubmissionType` (`Singularity`) is not taken into account.
The `PoolComputingElement.innerCESubmissionType` is defined as `InProcess` by default.
The only way to update it is to `_reset` the CE, and the only way to reset it is to update its parameters using `setParameters()`.
FIX: update PoolCE.InnerCESubmissionType from JobAgent
=> [v7r2] fix: update PoolCE.innerCESubmissionType from JobAgent

src/DIRAC/Core/Utilities/Subprocess.py
Hi,
Here is the patch to limit the number of times the unicode error message will be printed for #5968.
Regards,
Simon
*Core
FIX: Limit reoccurrences of subprocess unicode error
=> [v7r2] fix: Limit reoccurrences of subprocess unicode error

src/DIRAC/Core/Base/AgentReactor.py, src/DIRAC/WorkloadManagementSystem/Agent/JobAgent.py
*Core
FIX: fix: allow for agents to loop every 10 seconds
*WMS
FIX: can't change the polling time of JobAgent from inside an already running agent
=> [v7r3] JobAgent polling time fix

src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py
*Subsystem
FIX: allow to run Watchdog on non x86 platforms
=> [v7r3] fix: allow to run Watchdog on non x86 platforms

.pre-commit-config.yaml
Due to https://github.com/psf/black/issues/2964
We still want an old version of black for python2 compatibility, so freeze click in the pre-commit hook
Do NOT propagate to integration, I will make another one for that
=> [v7r3] fix (CI): fix click version for black pre-commit hook

.pre-commit-config.yaml
Upgrade black version for python3, and fix click version for python2 compatible files
=> [8.0] fix (CI): upgrade black for pre-commit hook

src/DIRAC/WorkloadManagementSystem/scripts/dirac_wms_cpu_normalization.py
Sweep #5939 `dirac-wms-get-cpu-norm: support multi-core allocations` to `integration`.
CHANGE: dirac-wms-get-cpu-normalization depends on db12 multiple_dirac_benchmark
Closes #5992
=> [sweep:integration] dirac-wms-get-cpu-norm: support multi-core allocations

src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py
*WMS
FIX: StalledJobAgent can force status from Submitting to Failed
FIX: ElasticJobParametersDB: make sure the docID is less than 512 characters
=> [v7r3] fix: StalledJobAgent can force status from Submitting to Failed

src/DIRAC/WorkloadManagementSystem/Agent/StalledJobAgent.py, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py
Sweep #5979 `fix: StalledJobAgent can force status from Submitting to Failed` to `integration`.
*WMS
FIX: StalledJobAgent can force status from Submitting to Failed
FIX: ElasticJobParametersDB: make sure the docID is less than 512 characters
Closes #6003
=> [sweep:integration] fix: StalledJobAgent can force status from Submitting to Failed

dirac.cfg, docs/source/AdministratorGuide/Resources/storage.rst, src/DIRAC/DataManagementSystem/Client/FTS3Job.py
It makes sense to have a BringOnline timeout setting per SE, as this is very dependent on many settings that are site specific
*DMS
NEW: BringOnline setting for FTS transfers can be SE dependant
=> [v7r3] Take the BringOnline timeout from the SE configuration

.pre-commit-config.yaml
Backport #5997 for `rel-v7r2`.
=> [v7r2] Fix click version for black pre-commit hook

src/DIRAC/RequestManagementSystem/scripts/dirac_rms_request.py
* RMS
FIX: if the request ID is an integer the test `is digit()` throws an exception
=> [v7r3] Fix previous fix in RMS

src/DIRAC/__init__.py
No need for release notes. The current docstring was only valid for v7r2.
=> [v7r3] Correct docstring for DIRAC._computeRootPath

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/__init__.py
Sweep #6011 `Allow rootPath override` to `integration`.
Adding original author @sfayer as watcher.
*Core
FIX: Allow rootPath to be overridden with DIRAC_ROOT_PATH  environment variable
Closes #6030
=> [sweep:integration] Allow rootPath override

src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py
Fixes #5968.
FIX: utf-8 support in job output for python2
=> [v7r2] Fix utf-8 support in job output for python2

src/DIRAC/RequestManagementSystem/scripts/dirac_rms_request.py
Sweep #6020 `Fix previous fix in RMS` to `integration`.
Adding original author @phicharp as watcher.
* RMS
FIX: if the request ID is an integer the test `is digit()` throws an exception
Closes #6024
=> [sweep:integration] Fix previous fix in RMS

src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py, src/DIRAC/Resources/Computing/test/Test_HTCondorCEComputingElement.py
Previous version didn't use the proxy set by setproxy, so it always failed with an auth error.
*Resources
FIX: HTCondorCE: make sure proxy is available when running condor_rm
=> [v7r3] fix: use correct environment for condor_rm

environment-py3.yml, environment.yml, setup.cfg, src/DIRAC/Resources/Computing/CloudComputingElement.py, src/DIRAC/Resources/Computing/cloudinit.template, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
This code will enable DIRAC to (eventually) get rid of the CloudDirector. 
The goal is to use the same mechanisms for cloud as for grid resources and to deprecate the VMDIRAC components.
- relies on libcloud to minimize back ends
- uses the pilot job references to track the instance 
- uses the standard pilot wrapper
- needs a hook in SiteDirector to be able to clean up the pilots without having to have a separate agent
- See issue #5282
We'd be happy to discuss this at the next BiLD meeting.
*Resources
NEW:  add CloudComputingElement
CHANGE:  add hook for pilot cleanup
=> [v7r3] add CloudComputingElement

src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py, src/DIRAC/Resources/Computing/test/Test_HTCondorCEComputingElement.py
Sweep #6013 `fix: use correct environment for condor_rm` to `integration`.
Adding original author @marianne013 as watcher.
*Resources
FIX: HTCondorCE: make sure proxy is available when running condor_rm
Closes #6036
=> [sweep:integration] fix: use correct environment for condor_rm

dirac.cfg, docs/source/AdministratorGuide/Systems/MonitoringSystem/index.rst, src/DIRAC/ConfigurationSystem/Client/Helpers/Operations.py, src/DIRAC/Core/Base/AgentModule.py, src/DIRAC/Core/DISET/private/Service.py, src/DIRAC/Core/Tornado/Server/TornadoServer.py, src/DIRAC/MonitoringSystem/Client/DataOperationSender.py, src/DIRAC/MonitoringSystem/Client/Types/RMSMonitoring.py, src/DIRAC/RequestManagementSystem/Agent/RequestExecutingAgent.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/Agent/StatesAccountingAgent.py, src/DIRAC/WorkloadManagementSystem/ConfigTemplate.cfg
The flags used to enable monitoring are all over the place and have different names for each monitoring type, which could be confusing.
I propose reorganizing all of the flags under one unique flag `MonitoringBackends/Default`, that enables all the monitoring types without needing to activate one by one.
There would also be the possibility to override this default flag manually and decide the monitoring option for any specific type.
*Monitoring
CHANGE: Replaced the flags for monitoring with a new unified flag system
=> [integration] Reorganizing monitoring flags

src/DIRAC/WorkloadManagementSystem/Client/DIRACbenchmark.py
Will resolve the following issue (affecting python2 installations): https://github.com/DIRACGrid/DIRAC/issues/6053
FIX: DIRACBenchmark client TypeError
=> [v7r3]fix(wms): DIRACBenchmark client typeError

src/DIRAC/Resources/Computing/ComputingElement.py
Closes #6014
*Resources
FIX: use ceType instead of ceName for CE parameters
=> [v7r3]: use ceType instead of ceName for CE parameters

src/DIRAC/Workflow/Modules/Script.py
Sweep #6045 `Don't crash if systemCall fails` to `integration`.
*WMS
FIX: Don't crash if systemCall fails
Closes #6064
=> [sweep:integration] Don't crash if systemCall fails

src/DIRAC/Resources/Storage/GFAL2_SRM2Storage.py
By the time 8.0 is out, I suspect most sites will have it working. In the case of LHCb, all sites have it, and it runs fine.
As soon as it is merged, I will add a note in the wiki to describe the change
@iueda this is probably of interest to you
*Resources
NEW: add SRM+HTTPs as a default TPC protocol in SRM
=> [8.0] feat (SRM): allow SRM+HTTPs as default

src/DIRAC/Core/Utilities/ElasticSearchDB.py
Added option op_type in index API for Elasticsearch. This option can be used to make sure the document will created rather tahn updated resulting in unique document once created.
*Elasticsearch
NEW: option op_type in index API for Elasticsearch
Closes #5920
=> [v7r2] added op_type option in elasticsearch options

src/DIRAC/Core/Tornado/Server/private/BaseRequestHandler.py
The WebApp assumes Tornado will return the binary content from the sandbox store:
https://github.com/DIRACGrid/WebAppDIRAC/blob/26565c2c4d6368971971757127a0b56581fa7bbd/src/WebAppDIRAC/WebApp/handler/JobMonitorHandler.py#L473-L480
*Web
FIX: Fix downloading sandboxes from the Job Manager in the WebApp
=> [integration] Downloading job sandboxes from the web

docs/source/AdministratorGuide/Resources/index.rst, docs/source/AdministratorGuide/Resources/simpleMQ.rst, environment.yml, src/DIRAC/Resources/MessageQueue/Simple/StompInterface.py
The existing support of MQ in DIRAC was designed with the idea of abstracting as much as possible the type of queues and the protocol used. It is all very well, but at the cost of:
* extremely complex code
* very inefficient because way too many abstraction layers
* Has bugs (can't listen to an alias with multiple host behind for example)
* Was done with the idea of exposing each and every single possibility of usage
It is a very theoretical work, with no actual understanding of how you really want to use MQ. It was also design with some wrong understanding of the different roles in a MQ system. In practice, there is ALWAYS a relation between what you actually want to do  with your messages, and how you configure it. That's why so much abstraction is useless. 
This PR builds on the LHCb …
=> [8.0] Upgrade Stomp version and implement simpler interface

src/DIRAC/Resources/Computing/cloudinit.template
This is a sensible default mechanism for detecting the proxies: It's how the main CernVM works.
*Resources
FIX: autodetect cvmfs proxy in default cloudce template
=> [v7r3] fix: autodetect cvmfs proxy in default cloudce template

src/DIRAC/Core/Utilities/ElasticSearchDB.py
Sweep #6067 `added op_type option in elasticsearch options` to `integration`.
Adding original author @panta-123 as watcher.
*Elasticsearch
NEW: option op_type in index API for Elasticsearch
Closes #6093
=> [sweep:integration] added op_type option in elasticsearch options

src/DIRAC/Resources/Computing/ARCComputingElement.py, src/DIRAC/Resources/Computing/ComputingElement.py, src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py, src/DIRAC/Resources/Computing/InProcessComputingElement.py, src/DIRAC/Resources/Computing/LocalComputingElement.py, src/DIRAC/Resources/Computing/PoolComputingElement.py, src/DIRAC/Resources/Computing/SSHComputingElement.py, src/DIRAC/Resources/Computing/SudoComputingElement.py
Sweep #6079 `fix: use ceType instead of ceName for CE parameters version 2` to `integration`.
Adding original author @marianne013 as watcher.
*Resources
FIX: use ceType instead of ceName for CE parameters
Closes #6089
=> [sweep:integration] fix: use ceType instead of ceName for CE parameters version 2

src/DIRAC/Core/Utilities/ExecutorDispatcher.py
The OptimizationMind suffers from a rare race condition that causes tasks
to get lost occasionally. I thought I'd fixed this in #5667 however it's
much too difficult to fix completely it would require the internal state
to be entirely refactored. Reverting this line avoids massive amounts of
log output when this happens.
FIX: Avoid producing massive log output in OptimizationMind
=> [v7r2] Avoid producing massive log output in OptimizationMind

src/DIRAC/Resources/Computing/CloudComputingElement.py
Did the proxy dumpAllToString return type change in integration where it seems to be a str while in v7r3 it seems to be bytes ? 
*Resources
FIX: remove decode from proxy in CloudCE
=> [integration] fix: remove decode from proxy in CloudCE

src/DIRAC/Resources/Computing/CloudComputingElement.py
*Resources
FIX: use identity instead of subject of proxy in CloudCE
=> [v7r3] fix: use identity instead of subject of proxy in CloudCE

src/DIRAC/Core/Base/CLI.py
Currently the dirac-dms-filecatalog-cli displays its help along these lines:
`stats               : et the catalog statistics`
after fix:
`stats               : Get the catalog statistics`
*Core
FIX: don't truncate first character in cli doc strings
=> [v7r3] fix: don't truncate first char in cli doc strings

src/DIRAC/Core/Base/CLI.py
[v7r3] fix: don't truncate first char in cli doc strings
(cherry picked from commit f36f0e4bf78c8dbde3a34762dd49bd42fac55bc0)
This is my first attempt at fixing a sweep failure, bear with me.
*Core
FIX: don't truncate first character in cli doc strings
=> [integration] fix: Merge pull request #6118 from marianne013/patch-1

tests/Integration/WorkloadManagementSystem/Test_JobParameters_MySQLandES.py
In LHCbDIRAC CI, we observer odd failures only for this very specific test. It is not systematically reproducible, but happens very often. This test is a bit odd since it runs in the server integration tests but is actually a client test. In any case, since the diset components were restarted, I restart Tornado too
```python
LocalRepo/TestCode/DIRAC/tests/Integration/WorkloadManagementSystem/Test_JobParameters_MySQLandES.py::test_MySQLandES_jobParameters FAILED [100%]
=================================== FAILURES ===================================
________________________ test_MySQLandES_jobParameters _________________________
def test_MySQLandES_jobParameters():
"""a basic put - remove test, changing the flag in between"""
jobID = createJob()
res = …
```
=> [v8.0] test (JobParameters): restart Tornado after changing the configuration

src/DIRAC/Resources/Cloud/Utilities.py
*Resources/Cloud
FIX: userData need to be in "ascii" string format to meet the requirement of "create_node" when creating VMs from cloud resources
=> [v7r3] fix userData format for creating VMs from Cloud resources

docs/source/AdministratorGuide/Systems/WorkloadManagement/Pilots/Pilots3.rst
*docs
NEW: add info on installing non-released code from within the pilot
=> [v7r3] docs: add info on installing non-released code from within the pilot

src/DIRAC/Core/DISET/private/Service.py
`threading.activeCount` was deprecated in Python 3.10 (October 2021) and will be removed in Python 3.12 (October 2023).
Replace with `threading.active_count`, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
*Core
FIX: Replace deprecated threading.activeCount with active_count
=> [integration] Replace deprecated threading.activeCount with active_count

src/DIRAC/Core/DISET/private/Service.py
Backport https://github.com/DIRACGrid/DIRAC/pull/6151
=> [v7r3] Backport: Replace deprecated threading.activeCount with active_count

src/DIRAC/Core/DISET/private/Service.py
Backport https://github.com/DIRACGrid/DIRAC/pull/6151
=> [v7r2] Backport: Replace deprecated threading.activeCount with active_count

src/DIRAC/FrameworkSystem/scripts/dirac_login.py
*Framework
FIX: dirac_login: avoid misleading error message, fixes issue #6096
=> [8.0] fix for dirac_login: avoid misleading error message (issue #6096)

src/DIRAC/Core/scripts/dirac_configure.py
This PR aims to simplify the choice of authorization server for users, for example:
```
dirac-configure --login=dirac.egi.eu
```
*Core
NEW: add https to issuer address automatically
=> [8.0] [dirac-configure] add https to issuer address automatically

.pylintrc, src/DIRAC/TransformationSystem/Agent/test/Test_Plugins.py, src/DIRAC/TransformationSystem/Client/test/Test_Client_TransformationSystem.py, src/DIRAC/WorkloadManagementSystem/Client/test/Test_JobReport.py, src/DIRAC/WorkloadManagementSystem/Executor/test/Test_Executor.py, src/DIRAC/WorkloadManagementSystem/Utilities/test/Test_PilotWrapper.py, tests/Integration/AccountingSystem/Test_DataStoreClient.py, tests/Workflow/Regression/Test_RegressionUserJobs.py
Adding specific regex to avoid pylint invalid-name warning for test module and too long test names
=> [Integration] Feat: stop pylint invalid-name for test module and test function

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
remove the VOPolicy field from the job description, which is not used since #5184.
=> [Integration] fix: removing VOPolicy from job description

src/DIRAC/RequestManagementSystem/Agent/CleanReqDBAgent.py, src/DIRAC/RequestManagementSystem/ConfigTemplate.cfg
NEW: Add option to automatically cancel Scheduled requests after a defined time period.  Default behaviour unchanged. Relates to #6136
=> [v7r3] feat: add option to automatically cancel Scheduled requests

src/DIRAC/MonitoringSystem/Client/MonitoringReporter.py, src/DIRAC/MonitoringSystem/Client/ServerUtils.py
A simple import of MonitoringReporter which happens, for example, when importing Dirac interface class, results in an attempt to create and ping ES MonitoringDB. In CLI commands this creates unnecessary delays and confusing error printouts, e.g.:
$ dls -L /
Cannot ping ElasticsearchDB!
Can't connect to MonitoringDB RuntimeError('Can not connect to ES cluster , exiting...')
where it is normal that direct access to ES is not available in the interactive environment and the MonitoringReporter is not actually invoked. 
*Monitoring
FIX: MonitoringReporter - late binding to MonitoringDB
=> [8.0] Late binding of MonitoringReporter to the monitoringDB

src/DIRAC/Core/Utilities/Extensions.py
If an import was buggy in an Agent or Handler, we would only see an error like 
```
ERROR: Error while loading agent module Could not find <system>/<agent>
```
This PR makes the distinction between not finding the module we look for, and a missing dependency in the module we are looking for
*Core
FIX:  better report of error when importing Module
=> [v8.0] fix (Core): better report of error when importing Module

src/DIRAC/Core/scripts/dirac_agent.py, src/DIRAC/Resources/Computing/ARC6ComputingElement.py, src/DIRAC/Resources/Computing/ARCComputingElement.py
This PR aims to integrate a new method to submit ARC jobs:
- transfer the full proxies to the remote computing resources
- no need to specify the port (because it can be changed by the ARC admins)
- no need to specify the interface used (it will try to submit via the REST interface first, then EMI-ES, and finally GRIDFTP)
This can probably be a good way to transition from GRIDFTP to REST.
I tested the new method with ~45 ARC CEs from ~20 sites.
In most of the case, the Python interface was using the REST interface.
No big change in the submission duration, I did 3 submissions of 50 jobs with the new and the old method on a same CE and got the following results:
- new method: 30.5 seconds
- old method: 34.7 seconds
CHANGE: new method to submit …
=> [v7r2] feat (resources): introduce a new way to submit pilots from ARC

tests/CI/docker-compose.yml
To make a very long story short, this just sets a maximum number of open files for the dirac container in the CI. 
If not, and using a recent version of docker, you get a huge number (1073741816) as a limit ([1]), and the `rpm` version in the `cc7` image will iterate on alllllll the `fd`, which can take very long ([2]). So if you do `yum install XYZ` in such a container, it will take half a day. 
[1] https://github.com/containerd/containerd/pull/4475  
[2] https://github.com/rpm-software-management/rpm/blob/rpm-4.11.3-release/lib/rpmscript.c#L116-L122
*CI
NEW: max open files for dirac CI container to 8192
=> [v7r3] test (CI): set a max number of files for the dirac containers in docker-compose

src/DIRAC/FrameworkSystem/Service/ProxyManagerHandler.py
In the hackathon I noticed clients running 7.3 cause an exception in the proxy manager when proxies are uploaded which is then shown to the client like:
```
2022-06-23 09:28:49 UTC dirac-proxy-init [140503643989824] ERROR: Can't read certificate ( 1104 : TypeError('cannot use a string pattern on a bytes-like object'))
```
This is because the we've changed the type of X509 data from `bytes` to `str` for v8.0.
I suggest adding a workaround to the proxy manager in v8.0 and removing it in v8.1.
=> [8.0] Support receiving proxies from clients running v7.3.x

.github/labeler.yml
Hopefully fixing the issue for https://github.com/DIRACGrid/DIRAC/pull/6198, I'll test in https://github.com/DIRACGrid/DIRAC/pull/6200 and manually apply to all branches if it works.
=> [v7r3] Add workaround for labeler ignoring hidden files

src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata/MultiVODirectoryMetadata.py
FIX: Built-in metakeys were incorrectly modified in a MultiVO environment. This fix keeps them intact while modifying user-supplied metadata names by append a VO suffix, as before.
=> [v7r2] fix: address issue 6092 where built-in metakeys were modified for MultiVO

src/DIRAC/Resources/Computing/ARC6ComputingElement.py, src/DIRAC/Resources/Computing/ARCComputingElement.py
This PR solves typo issues in `ARC6`.
Also, the `writeXRSL` private method from `ARC` becomes protected to be used in `ARC6`.
*Resources
FIX: ARC6 typo issues
FIX: ARC writeXRSL becomes protected
=> [v7r2] fix: ARC6 CE issues

src/DIRAC/Resources/Computing/ARC6ComputingElement.py, src/DIRAC/Resources/Computing/ARCComputingElement.py
Sorry, I didn't spot the issue in my previous PR from this morning.
*Resources
FIX: ARCCE.getARCJob() becomes protected
=> [v7r2] fix: ARCCE.getARCJob() becomes protected

src/DIRAC/Core/Security/VOMS.py
Hi,
We have one of our 3 VOMS servers in GridPP down for maintenance this week: We are seeing "Could not set-up proxy" errors due to a timeout on some of our jobs.
On investigating this I found 2 main problems:
* The first parameter to the BaseSecurity constructor isn't timeout, so it actually uses the default (30) instead of the pre-set value for the VOMS class (initially 40).
* The voms-proxy-init2 command actually tries each server twice, so the timeout needs to be doubled.
(voms-proxy-init2 can also be a bit slow to get going with a new pilot on a busy worker node, so it can still clip into the 30 second timeout even if the theoretical timeout for a single server down is 24 seconds, so giving it more leeway in general is probably a good idea).
Regards,
Simon
*Core …
=> [v7r2] Increase VOMS command timeout

src/DIRAC/Interfaces/API/Dirac.py
Hi,
We frequently run into this infamous error when trying to replicate an LFN with dirac-dms-replicate-lfn:
```
ERROR A local file "mytestfile" with the same name as the remote file exists. Cannot proceed with replication:
Go to a different working directory
Move it different directory or use a different localCache
Delete the file yourself
```
While not a major issue, this is still a little annoying, particularly as it's most frequently encountered by users just starting to learn DIRAC (and long time sysadmins who always forget this restriction :-)  . I can't see any negative effects of creating a local tmpdir and using that instead of just CWD by default (you can always set localCache="." if you really want the old behaviour, e.g. actual caching between commands).
Regards,
Simon …
=> [v7r3] Make tmpdir for local cache instead of using CWD when replicating

src/DIRAC/FrameworkSystem/scripts/dirac_uninstall_component.py
dirac-uninstall-component called the old "System" column name of InstalledComponentDB which is now called "DIRACSystem"
=> [Integration] fix: fix dirac-uninstall-component by using the new column name

src/DIRAC/Interfaces/API/Dirac.py
Sweep #6224 `Make tmpdir for local cache instead of using CWD when replicating` to `integration`.
Adding original author @sfayer as watcher.
*Interfaces
CHANGE: Make tmpdir for local cache instead of using CWD directly when replicating
Closes #6226
=> [sweep:integration] Make tmpdir for local cache instead of using CWD when replicating

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Hi,
We've noticed that the SiteDirector crashes when CheckPlatform=True due to a KeyError, it looks like the Platform is actually contained within "ParametersDict" now.
```
File "DIRAC/Core/Base/AgentModule.py", line 359, in am_secureCall
result = functor(*args)
File "DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 332, in execute
result = self.submitPilots()
File "DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 385, in submitPilots
ce, ceDict = self._getCE(queueName)
File "DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py", line 651, in _getCE
result = self.resourcesModule.getCompatiblePlatforms(self.queueDict[queue]["Platform"])
KeyError: 'Platform'
```
Regards,
Simon
FIX: Fix Platform …
=> [v7r3] Fix Platform key error in SD when CheckPlatform=True

src/DIRAC/FrameworkSystem/private/standardLogging/Formatter/MicrosecondJsonFormatter.py, src/DIRAC/Resources/LogBackends/MessageQueueBackend.py, src/DIRAC/Resources/LogBackends/StdoutJsonBackend.py
This is useful for orchestrators like K8 which often comes with fluentd or the like
*Framework
NEW: Add StdoutJsonBackend 
=> [v7r3] feat (logging): add an stdout Backend with json formatting

src/DIRAC/FrameworkSystem/scripts/dirac_login.py
`result["Message"]` may contain special characters such as `<>`.
The `prompt_toolkit` package tries to interpret them and fail, which return an error hiding the real error.
FIX: dirac_login HTML error hiding the actual error
=> [v8.0] hackaton fix: dirac_login HTML error hiding the actual error

src/DIRAC/WorkloadManagementSystem/DB/JobDB.py
Making getJobAttributes use getJobsAttribute to avoid code duplication as suggested by a TODO comment
=> [Integration] refactor: making getJobAttributes use getJobsAttributes to avoid code duplication

src/DIRAC/Core/Tornado/Server/TornadoREST.py
Returns `TornadoREST` to being functional for HTTP GET requests.
It's good enough for the `AuthHandler` class but we should plan more before using `TornadoREST` for any other handler.
Closes https://github.com/DIRACGrid/DIRAC/issues/6245
Superceeds https://github.com/DIRACGrid/DIRAC/pull/6249
=> [8.0] Allow TornadoREST methods to be prefixed with "get_"

environment.yml, integration_tests.py, requirements.txt
The latest release of `typer` changed slightly how the `NaturalOrderGroup` in `integration_tests.py` needed to be implemented.
Also includes https://github.com/DIRACGrid/DIRAC/pull/6253.
=> [v7r2] Fix integration_tests.py for latest release of typer

src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py
Hi,
I found that running the FC changePathGroup function only works if one LFN is given: If multiple are specified only the first is updated and the rest return an error as the loop variable "res" gets overwritten.
Regards,
Simon
FIX: Fix FC change{group,owner,mode} for multiple LFNs
=> [v7r2] Fix FC chgrp on multiple LFNs

src/DIRAC/Resources/Catalog/ConditionPlugins/ProxyPlugin.py
I just realized that the ProxyPlugin of the FCCondition parser was not taking ThreadConfig into account
*Resources
FIX: Conditional FC ProxyPlugin checks the ThreadConfig
=> feat (ConditionalFC): ProxyPlugin checks also ThreadConfig

src/DIRAC/RequestManagementSystem/DB/RequestDB.py
Backport of #6114 for backward compatibility (tested)
=> [v7r3] feat: from BLOB to VARCHAR for ReqDB fields

src/DIRAC/WorkloadManagementSystem/Agent/JobCleaningAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py
*WMS
FIX: ElasticJobParametersDB: do not return parameters that are not needed
=> [8.0] fix: delete parameters that are not needed

src/DIRAC/Core/Utilities/Network.py, src/DIRAC/Core/Utilities/test/Test_Network.py
*Core
CHANGE: Use psutil.net_if_addrs for Network.discoverInterfaces
=> [8.0] Use psutil.net_if_addrs for Network.discoverInterfaces

src/DIRAC/Core/Security/m2crypto/X509Certificate.py, src/DIRAC/Core/Security/m2crypto/X509Chain.py, src/DIRAC/Core/Security/m2crypto/X509Request.py, src/DIRAC/Core/Security/m2crypto/__init__.py, src/DIRAC/Core/Security/test/Test_X509Chain.py, src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/FrameworkSystem/Client/ProxyGeneration.py, src/DIRAC/FrameworkSystem/DB/ProxyDB.py, src/DIRAC/MonitoringSystem/Client/DataOperationSender.py, src/DIRAC/Resources/ProxyProvider/DIRACCAProxyProvider.py, tests/Integration/Core/Test_ElasticsearchDB.py, tests/System/client_dms.sh
Besides the change of proxy length, this PR contains quite a few improvement of the DataOperationSender. There will most definitely be more work needed for the DataOperation monitoring, but at least something comes out of it ! 
I guess 9d7910f178bf3c02f0c0d03cd7a03c6bd06f374a may lead into more data being added to an index, or the other way around, but it is not really important
* Core
CHANGE: Default proxy length is 2048 bits
CHANGE: remove RFC argument for proxy generation
* Monitoring
FIX: ElasticSearchDB generates full index names based on UTC
FIX: DataOperationSender works on a copy of the documents
CHANGE: DataOperationSender fails if the master accounting system fails
=> [v8.0] multiple hackaton fixes

src/DIRAC/FrameworkSystem/DB/ProxyDB.py
Hi,
We're still seeing issues where users manage to upload proxies with groups occasionally: I haven't tracked that down yet, the checks in ProxyDB should prevent it happening but somehow they don't always. These proxies have either 0 or -1 days of lifetime causing the user to get a notification e-mail every day.
We've been hotpatching this extra check in for quite a while now (possibly more than a year?), so I thought I'd commit it properly.
Regards,
Simon
*Framework
FIX: Don't notify users with expired proxies
=> [v7r3] Don't notify users with expired proxies

tests/CI/docker-compose.yml, tests/Jenkins/dirac-cfg-update-server.py
The latest release of S3Mock has become stricter and now requires a valid bucket name (https://github.com/adobe/S3Mock/pull/743).
=> [v7r2] Fix testing against S3Mock

src/DIRAC/Resources/Computing/CloudComputingElement.py
Hi,
It's quite common for the CloudCE to be instantiated with missing config params as "CEType = Cloud" used to be a placeholder for all kinds of dynamic resources where the CEType isn't actually used (VMDIRAC, Vcycle, Vac) at least on GridPP instances. At the moment it just crashes with an exception on the ceParameters.get line which can make it hard to see which CE it is actually causing the problem, this patch changes it to a more useful error message.
Regards,
Simon
*Resources
FIX: Return proper error if provider value missing in CloudCE
=> [v7r3] Return proper error if provider value missing in CloudCE

src/DIRAC/Resources/Computing/SingularityComputingElement.py
Hi,
The newer version of singularity in DIRACOS2 has an extra quirk that I haven't seen before: With the --contain option it makes the rootfs of the container a small tmpfs (which is fine, as it used to be), but it doesn't touch $HOME. Generally this results in $HOME pointing into /home or /mnt (on a cloud), whatever it was outside of the container and writing to a 16MiB tmpfs. Most user jobs don't even notice this, but some use pip and other tools that write to $HOME/.cache by default and can quite quickly run out of space. This new patch just adds the option to SingularityCE to set home to be /tmp inside the container (which is the usual scratch area) so that all the space is available and things don't trip-up.
Regards,
Simon
*Resources
FIX: Set HOME in SingularityCE …
=> [v7r3] Set HOME in SingularityCE to avoid tmpfs

.readthedocs.yaml, environment.yml
I don't think it deserves release notes.
This is just to have everything needed for Readthedoc builds for extension to work out of the box
=> Install diracdoctools directly from environment.yaml

environment.yml, setup.cfg
`suds-jurko` was originally a fork since then `suds-community/suds` has taken over the `suds` name on PyPI and is the only maintained version.
This [should be a backwards compatible change](https://github.com/suds-community/suds/issues/81) and I'm inclined to suggest backporting it after I've done a few more checks.
See https://github.com/DIRACGrid/DIRAC/issues/6322 for details.
*Core
CHANGE: Replace suds-jurko with suds
=> [8.0] Replace suds-jurko with suds

.pylintrc, docs/diracdoctools/Utilities.py, environment.yml, setup.cfg, src/DIRAC/Core/Utilities/Subprocess.py, src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py, src/DIRAC/Resources/Computing/BatchSystems/Host.py, src/DIRAC/Resources/Computing/test/Test_SSHComputingElement.py
For Python 2 we started using `subprocess32` in https://github.com/DIRACGrid/DIRAC/pull/4286 as it was significantly faster for the integration tests. Now DIRAC is Python 3-only we can remove it.
=> [8.0] Replace subprocess32 with standard library module

docs/source/UserGuide/GettingStarted/UserJobs/DiracAPI/index.rst
In the documentation, the python code block was not rendered correctly due to an extra :
=> [v7r3] Fix incorrect rendering of code block

src/DIRAC/Core/Utilities/ProcessPool.py, src/DIRAC/Core/Utilities/test/ProcessesCreator.py, src/DIRAC/Core/Utilities/test/Test_Subprocess.py, src/DIRAC/Resources/Storage/test/Test_FilePlugin.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py, src/DIRAC/tests/Utilities/ProcessesCreator_withChildren.py
At the moment `pytest` fails when running on arm64 macOS with a handful of minor issues. Even if it isn't a fully supported platform I think they're worthwhile fixing to make it easier for people to develop locally.
=> [8.0] Unit test compatibility fixes

src/DIRAC/DataManagementSystem/DB/FTS3DB.py
Fixes this deprecation notice:
```python
src/DIRAC/DataManagementSystem/DB/test/Test_FTS3DB.py::test_raceCondition
/Users/cburr/Development/DIRAC-dev/DIRAC/src/DIRAC/DataManagementSystem/DB/FTS3DB.py:550: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
.filter(~FTS3Operation.operationID.in_(opIDsWithJobAssigned))
```
Please review carefully in case I've done something stupid 😄
=> [8.0] Replace deprecated Subquery coercion with explicit select

src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py
Hi,
We still have occasions where we have a misconfigured CE missing a Platform for various reasons. If CheckPlatform = True this results in a KeyError and it isn't obvious which CE triggered it, so this just adds an error message for that state.
I also noticed that there was a return missing from the other error state: It'll still continue to use result["Value"] even if result["OK"] was False. I've never seen that happen, but I've fixed it at the same time anyway.
Regards,
Simon
FIX: Log error if CE Platform is missing.
=> [v7r3] Handle missing Platform in SD

src/DIRAC/Interfaces/scripts/dirac_wms_job_parameters.py, src/DIRAC/WorkloadManagementSystem/DB/ElasticJobParametersDB.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/Watchdog.py
Closes #6332. See the issue for justification.
CHANGE: Remove CPU(MHz) from CacheSize(kB) job parameters
=> [8.0] Remove CPU(MHz) from CacheSize(kB) job parameters

src/DIRAC/Core/Base/Client.py
When using `super()` (i.e. without arguments) in `Client` classes we currently get an exception:
```
TypeError: super(type, obj): obj must be an instance or subtype of type
```
This is due to the `createClient` decorator creating a new class which is not a subclass of the user defined class and is fixed by this PR.
*Core
FIX: createClient now creates subclasses of the original class
=> [8.0] Fix setting base class in the createClient class decorator

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/Core/scripts/dirac_configure.py
In Python 3.10 the default [OpenSSL security level](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html#DEFAULT-CALLBACK-BEHAVIOUR) is increased to 2 (see https://github.com/python/cpython/issues/88164). This results in 1024-bit RSA no longer being allowed. For DISET this isn't a problem however HTTPS requests fail due to the standard library being used. This pull request just modifies TornadoBaseClient to always set the OpenSSL ciphers to get consistency across Python versions.
See also https://github.com/DIRACGrid/DIRAC/issues/6269.
*Core
CHANGE: Set OpenSSL ciphers to "DEFAULT:@SECLEVEL=1"
NEW: Experimental support for Python 3.10
NEW: Suppress InsecureRequestWarning when using dirac-configure with HTTPS servers
NEW: Support overriding ciphers …
=> [8.0] Fix using HTTPS with Python 3.10+ and suppress InsecureRequestWarning

environment.yml, pyproject.toml, setup.cfg, src/DIRAC/Core/Utilities/DErrno.py, src/DIRAC/Core/Utilities/ReturnValues.py
I originally just wanted to silent pylint for complaining about `unsubscriptable-object` when using `convertToReturnValue`. Turns out to be trickier than expected: https://github.com/PyCQA/pylint/issues/7292
Anyway, I added the type hints. Not sure whether we want to merge it already or wait for pylint to be fixed. I don't mind. 
Also, as of python 3.10, we will be able to forward the type hint through the elipse https://peps.python.org/pep-0612/
**Update from @cburr:** This now adds type hints to the entire `ReturnValues` module and can propogate the type of `retVal["Value"]` through `S_OK`/`convertToReturnValue`/`returnValueOrRaise`. We can't actually use mypy for checking this until https://github.com/python/mypy/pull/13389 is merged and releasd however I've tested locally with that …
=> [v8.0] Annotate ReturnValues.py

docs/diracdoctools/CustomizedDocs/CustomClient.py, docs/source/DeveloperGuide/AddingNewComponents/DevelopingCommands/index.rst, docs/source/UserGuide/Tutorials/UsingDIRACFromPython/index.rst, docs/source/UserGuide/Tutorials/index.rst, src/DIRAC/ConfigurationSystem/Client/LocalConfiguration.py, src/DIRAC/Core/Security/Properties.py, src/DIRAC/Core/Utilities/exceptions.py, src/DIRAC/FrameworkSystem/private/standardLogging/LogLevels.py, src/DIRAC/FrameworkSystem/private/standardLogging/Logging.py, src/DIRAC/Resources/LogBackends/AbstractBackend.py, src/DIRAC/__init__.py
In order to make `DIRAC.initialize` more useful when writing scripts it needs to have arguments to expose some of the functionality which is currently only available via the command line. This pull request adds a proposal for what I think the arguments should be along with improving the user documentation by adding a tutorial on how to use the DIRAC client.
To summarise the some of the new options:
* `require_auth`: By default `DIRAC.initialize` now raises an exception if it was unable to authenticate against the CS (hopefully with a hint about why). Setting `require_auth=False` disables this behavour.
* `log_level`: Allows the log level to be changed. As part of this I've also changed `LogLevel` to be an `enum` (the implementation of this could be improved but that's not a user-facing …
=> [8.0] Add arguments to DIRAC.initialize

src/DIRAC/Core/Base/AgentModule.py
Fixes this error I noticed:
```pylint
File "/home/dirac/ServerInstallDIR/diracos/lib/python3.9/site-packages/DIRAC/Core/Base/AgentModule.py", line 152, in __getCodeInfo
self.__codeProperties["version"] = importlib.metadata.version(
AttributeError: module 'importlib' has no attribute 'metadata'
```
Apparently pylint isn't able to notice this error as even this reproducer is okay:
```python
$ cat test.py
import importlib
importlib.metadata
$ pylint test.py
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:2:0: W0104: Statement seems to have no effect (pointless-statement)
------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, …
```
=> [integration] Explicitly import importlib.metadata instead of just importlib

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/AccountingSystem/DB/AccountingDB.py, src/DIRAC/Core/Utilities/MySQL.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DatasetManager/DatasetManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryClosure.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryLevelTree.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryManager/DirectoryTreeBase.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManager.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerBase.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerFlat.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManagerPs.py, src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerDB.py, src/DIRAC/DataManagementSystem/DB/FileCatalogDB.py, src/DIRAC/ProductionSystem/DB/ProductionDB.py, src/DIRAC/StorageManagementSystem/DB/StorageManagementDB.py, src/DIRAC/TransformationSystem/DB/TransformationDB.py
The idea was to be able to compare what the `MySQL` optimizer does in version 5.7 and 8.0 when running the Integration tests of the DFC.
This PR adds an environment variable `DIRAC_MYSQL_OPTIMIZER_TRACES_PATH` that should point to an existing directory. Every call to a method of `MySQL` (`_query`, `_update`, `executeStoredProcedure`, `executeStoredProcedureWithCursor`) will then create a json file in that directory containing the optimizer traces (https://dev.mysql.com/doc/internals/en/optimizer-tracing.html).
The logic is in ff45676376323d7b60c344f42b0aea09053a48ab
This is a very advanced optimization tool, so the decorator itself may lead in crashes, but that's by design (see code doc). If the environment variable is NOT set, the decorator is not even applied. 
<details>
<summary>Click …
=> [v8.0] Add an SQL optimizer tracer

src/DIRAC/WorkloadManagementSystem/Agent/PushJobAgent.py, src/DIRAC/WorkloadManagementSystem/Agent/test/Test_Agent_PushJobAgent.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/test/Test_JobWrapper.py, src/DIRAC/WorkloadManagementSystem/JobWrapper/test/jobDescription.xml
Fixing some issues with `PushJobAgent`.
Instead of writing CE details in the DIRAC configuration (which was not ideal at all), passing parameters to the `dirac-jobexec`.
FIX: pass CE parameters to dirac-jobexec instead of writing them in the configuration
One question:
At the end of a job execution, the `JobWrapper` submits a report to the `Accounting` service.
In this report, the `CPUTime` is field is wrong because the application was actually executed on a remote resource. (https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py#L1242)
2 solutions:
- We assume `CPUTime` plots are wrong for sites associated with the `PushJobAgent`, we don't look at this information.
- We use the …
=> [v7r3] fix (wms): additional fixes for the PushJobAgent

src/DIRAC/WorkloadManagementSystem/Client/InputDataResolution.py
When running some test jobs locally I've been wanting to use a shared local directory for downloading the input data rather than re-downloading it for every job. One option would be to keep passing the directory from `Job.runLocal` until `DownloadInputData` is initialised however this feels messy. The best idea I've had so far is to add a configuration option (`/LocalSite/InputDataDirectory`) but I'm open to others.
*WMS
NEW: The default InputDataDirectory used by DownloadInputData can be overridden by setting /LocalSite/InputDataDirectory
=> [v7r3] Allow the default InputDataDirectory to be overridden in LocalSite

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py
Backport of https://github.com/DIRACGrid/DIRAC/pull/6299.
*Core
CHANGE: Set OpenSSL ciphers to "DEFAULT:@SECLEVEL=1"
NEW: Experimental support for Python 3.10
FIX: Correct check of CA locations
=> [v7r2] Backport: Fix using HTTPS with Python 3.10+

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/Core/scripts/dirac_configure.py
Backport of https://github.com/DIRACGrid/DIRAC/pull/6299.
*Core
CHANGE: Set OpenSSL ciphers to "DEFAULT:@SECLEVEL=1"
NEW: Experimental support for Python 3.10
NEW: Suppress InsecureRequestWarning when using dirac-configure with HTTPS servers
=> [v7r3] Backport: Fix using HTTPS with Python 3.10+ and suppress InsecureRequestWarning

src/DIRAC/WorkloadManagementSystem/Agent/VirtualMachineMonitorAgent.py
The call to halt at the end of VirtualMachineMonitor was mistakenly left commented out: It should be enabled so that VMs stop in a timely manner.
FIX: Stop instance from VirtualMachineMonitor
=> [v7r3] Enable VirtualMachineMonitor halt call

src/DIRAC/Resources/Storage/GFAL2_StorageBase.py
That goes to show how well posix permissions are supported on grid storage :-) 
*Resources
FIX: new directory creation specifies the permission in octal mode
=> [v7r3] fix (gfal2): specify new directory permissions in octal

src/DIRAC/Resources/Storage/StorageElement.py
We had problems recently of negative free space. This is due to the asynchronous nature of quota enforcement of some storage (EOS in that case) and the fact that we are very close to the limit.
*Resources
CHANGE: negative free space value is transformed to 0
=> [v7r3]fix (SE): free space can be negative, so set it to 0

.github/workflows/semantic.yml, src/DIRAC/FrameworkSystem/Service/ProxyManagerHandler.py
This reverts commit ce3963dd600e6919868d8a05ddcac5d848edc504 from #6195.
Leaving as draft until we have a branch for 8.0.x releases.
=> [8.1] Revert support receiving proxies from clients running v7.3.x

.github/workflows/deployment.yml
Partly deals with https://github.com/DIRACGrid/DIRAC/issues/6362 and adds some protection against deploying releases from integration or wrong versions from `rel-v*` branches.
I've tested this as carefully as I can locally but it's still likely to be buggy 😅 
It's only for the CI so not worthy of release notes.
=> [8.0] Fix deployment of 8.0.x and add protections against deploying incorrect versions

docs/source/AdministratorGuide/ServerInstallations/environment_variable_configuration.rst, src/DIRAC/Core/Tornado/Client/private/TornadoBaseClient.py, src/DIRAC/Core/scripts/dirac_configure.py
Follow up to #6299. I've already made a note to document this in 8.1's release notes.
*Core
CHANGE: Use Python's default SSL ciphers by default
=> [8.1] Remove SECLEVEL override

integration_tests.py, src/DIRAC/ConfigurationSystem/Client/Utilities.py, src/DIRAC/Core/Base/ElasticDB.py, src/DIRAC/Core/Utilities/ElasticSearchDB.py, src/DIRAC/Core/Utilities/ServerUtils.py, src/DIRAC/MonitoringSystem/Client/ServerUtils.py, src/DIRAC/WorkloadManagementSystem/Client/ServerUtils.py, tests/CI/docker-compose.yml, tests/CI/envs/elasticsearch:7.9.1.env, tests/Integration/Core/Test_ElasticsearchDB.py, tests/Jenkins/dirac_ci.sh, tests/Jenkins/install.cfg
From the latest hackaton (16th May 2022).
Remove the warning logs related to ElasticDB initialization, appearing in every job output. 
FIX: remove warning logs when initializing ElasticDB parameters
=> [8.0] fix: remove warning messages when initializing ElasticDB parameters
